-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum AttrType
require("common");


local AbsorbAttrConfigDefault = {Weigh=100,RoleAttrLimit=5000,}
local AbsorbAttrConfig= {
  [1]={BaseID=1,AttrType=AttrType.ATTR_LIDAO,},
  [2]={BaseID=2,AttrType=AttrType.ATTR_TIZHI,},
  [3]={BaseID=3,AttrType=AttrType.ATTR_WUXING,},
  [4]={BaseID=4,AttrType=AttrType.ATTR_NEIJIN,},
  [5]={BaseID=5,AttrType=AttrType.ATTR_JINGLI,},
  [6]={BaseID=6,AttrType=AttrType.ATTR_LINGQIAO,},
  [7]={BaseID=7,AttrType=AttrType.ATTR_JIANFAJINGTONG,},
  [8]={BaseID=8,AttrType=AttrType.ATTR_QUANZHANGJINGTONG,},
  [9]={BaseID=9,AttrType=AttrType.ATTR_DAOFAJINGTONG,},
  [10]={BaseID=10,AttrType=AttrType.ATTR_TUIFAJINGTONG,},
  [11]={BaseID=11,AttrType=AttrType.ATTR_NEIGONGJINGTONG,},
  [12]={BaseID=12,AttrType=AttrType.ATTR_YISHUJINGTONG,},
  [13]={BaseID=13,AttrType=AttrType.ATTR_ANQIJINGTONG,},
  [14]={BaseID=14,AttrType=AttrType.ATTR_QIMENJINGTONG,},
  [15]={BaseID=15,AttrType=AttrType.ATTR_HITATK,Weigh=40,},
  [16]={BaseID=16,AttrType=AttrType.ATTR_CRITATK,Weigh=40,},
  [17]={BaseID=17,AttrType=AttrType.ATTR_CONTINUATK,Weigh=40,},
  [18]={BaseID=18,AttrType=AttrType.ATTR_SHANBI,Weigh=40,},
  [19]={BaseID=19,AttrType=AttrType.ATTR_KANGLIANJI,Weigh=40,},
  [20]={BaseID=20,AttrType=AttrType.ATTR_BAOJIDIKANGZHI,Weigh=40,},
  [21]={BaseID=21,AttrType=AttrType.ATTR_SUDUZHI,Weigh=20,},
  [22]={BaseID=22,AttrType=AttrType.ATTR_TIANFUZHI,Weigh=40,},
  [23]={BaseID=23,AttrType=AttrType.ATTR_POZHAOVALUE,Weigh=40,},
  [24]={BaseID=24,AttrType=AttrType.ATTR_FANTANVALUE,Weigh=40,},
  [25]={BaseID=25,AttrType=AttrType.ATTR_FANJIZHI,Weigh=40,},
  [26]={BaseID=26,AttrType=AttrType.ATTR_BAOSHANGZHI,Weigh=20,},
}
for k,v in pairs(AbsorbAttrConfig) do
    setmetatable(v, {['__index'] = AbsorbAttrConfigDefault})
end

-- export table: AbsorbAttrConfig
return AbsorbAttrConfig
