-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local AbsorbCommon= {
  [1]={BaseID=1,OpenTag=120015,MaxExp=785,MaxLayer=7,LayersExp={0,10,35,85,185,385,785,},RankAddExp={1,2,5,10,20,30,50,},LayersAbsorbAttr={300,600,900,1200,1500,1800,2100,},LayersGift={2198,2199,2200,2201,2202,2203,2204,},BagItem=901916,AdvLootItem=901915,ItemTask=7127,},
}

-- export table: AbsorbCommon
return AbsorbCommon
