-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local ActivitySign= {
  [1]={BaseID=1,StartTime="2020-11-06 00:00:00",EndTime="2020-11-12 24:00:00",HideTime="2020-11-14 24:00:00",RewardList={"1","2","3","4","5","6","7",},GiftText="门派礼包",MallList={"10080001","10080002","10080003",},TipText="新门派“六扇门”已解锁，可在新周目选择门派时拜入",Icon="ActivitySignBG/house_icon_united",TitleText="新门派预告",},
  [2]={BaseID=2,StartTime="2020-11-15 00:00:00",EndTime="2020-11-19 24:00:00",HideTime="2020-11-21 24:00:00",RewardList={"11","12","13","14","15",},GiftText="超值礼包",MallList={"10080004","10080005","10080006",},TipText="新玩法“掌门对决”已解锁，可在剧本选择界面进入",Icon="ActivitySignBG/house_icon_play",TitleText="新玩法预告",},
  [3]={BaseID=3,StartTime="2020-11-22 00:00:00",EndTime="2020-11-26 24:00:00",HideTime="2020-11-28 24:00:00",RewardList={"16","17","18","19","20",},GiftText="超值礼包",MallList={"10080009","10080010","10080011",},TipText="新角色“谢无悠”已解锁，版本更新后可在自由模式中找到她",Icon="ActivitySignBG/house_icon_role",TitleText="新角色预告",},
  [4]={BaseID=4,StartTime="2020-11-29 00:00:00",EndTime="2020-12-03 24:00:00",HideTime="2020-12-05 24:00:00",RewardList={"21","22","23","24","25",},GiftText="超值礼包",MallList={"10080012","10080013","10080014",},TipText="新角色“黑色禁药”已解锁，版本更新后可在京城中找到他",Icon="ActivitySignBG/house_icon_role",TitleText="新角色预告",},
  [5]={BaseID=5,StartTime="2021-01-03 00:00:00",EndTime="2021-01-07 24:00:00",HideTime="2021-01-09 24:00:00",RewardList={"26","27","28","29","30",},GiftText="超值礼包",MallList={"10080015","10080016","10080017",},TipText="角色“游迟迟”已解锁，版本更新后可在鸣沙山白衣教内找到她",Icon="ActivitySignBG/house_icon_role",TitleText="新队友解锁",},
  [6]={BaseID=6,StartTime="2021-01-17 00:00:00",EndTime="2021-01-21 24:00:00",HideTime="2021-01-23 24:00:00",RewardList={"31","32","33","34","35",},GiftText="超值礼包",MallList={"10080018","10080019","10080020",},TipText="新剧本“江湖濯玉录”已解锁，版本更新后可在剧本界面进入",Icon="ActivitySignBG/house_icon_story",TitleText="新剧本预告",},
  [7]={BaseID=7,StartTime="2021-01-24 00:00:00",EndTime="2021-01-28 24:00:00",HideTime="2021-01-30 24:00:00",RewardList={"36","37","38","39","40",},GiftText="超值礼包",MallList={"10080021","10080022","10080023",},TipText="角色“阿良”可加入队伍，可在剧本内雪山迷宫中找到他",Icon="ActivitySignBG/house_icon_role",TitleText="新队友解锁",},
}

-- export table: ActivitySign
return ActivitySign
