-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum AcupointTargetType
-- enum SkillEffectDescription
require("common");


local AcupointEffectDefault = {EffectTarget=AcupointTargetType.ATT_PlayerAndTeam,EffectEnum=SkillEffectDescription.SED_Jue1Se2Shu3Xing4Zen1Qiang,EffectArg2=0,EffectValueA=0,EffectValueB=0,}
local AcupointEffect= {
  [1]={BaseID=1,NameID=2910001,EffectArg1=31,EffectValueA=16,DescID=2920001,},
  [2]={BaseID=2,NameID=2910002,EffectArg1=32,EffectValueA=13,DescID=2920002,},
  [3]={BaseID=3,NameID=2910003,EffectArg1=100,EffectValueA=21,DescID=2920003,},
  [4]={BaseID=4,NameID=2910004,EffectArg1=387,EffectValueA=21,DescID=2920004,},
  [5]={BaseID=5,NameID=2910005,EffectArg1=33,EffectValueA=18,DescID=2920005,},
  [6]={BaseID=6,NameID=2910006,EffectArg1=389,EffectValueA=25,DescID=2920006,},
  [7]={BaseID=7,NameID=2910007,EffectArg1=9,EffectValueA=6,DescID=2920007,},
  [8]={BaseID=8,NameID=2910008,EffectArg1=11,EffectValueA=6,DescID=2920008,},
  [9]={BaseID=9,NameID=2910009,EffectArg1=12,EffectValueA=6,DescID=2920009,},
  [10]={BaseID=10,NameID=2910010,EffectArg1=10,EffectValueA=6,DescID=2920010,},
  [11]={BaseID=11,NameID=2910011,EffectArg1=16,EffectValueA=6,DescID=2920011,},
  [12]={BaseID=12,NameID=2910012,EffectArg1=15,EffectValueA=6,DescID=2920012,},
  [13]={BaseID=13,NameID=2910013,EffectArg1=13,EffectValueA=6,DescID=2920013,},
  [14]={BaseID=14,NameID=2910014,EffectArg1=14,EffectValueA=6,DescID=2920014,},
  [15]={BaseID=15,NameID=2910015,EffectArg1=17,EffectValueA=3240,DescID=2920015,},
  [16]={BaseID=16,NameID=2910016,EffectArg1=20,EffectValueA=64,DescID=2920016,},
  [17]={BaseID=17,NameID=2910017,EffectArg1=18,EffectValueA=1080,DescID=2920017,},
  [18]={BaseID=18,NameID=2910018,EffectArg1=65,EffectValueA=216,DescID=2920018,},
  [19]={BaseID=19,NameID=2910019,EffectArg1=54,EffectValueA=360,DescID=2920019,},
  [20]={BaseID=20,NameID=2910020,EffectEnum=SkillEffectDescription.SED_Zhi1Ding2Xi3Bei4Wu1Xue2Shu3Xing4Zen1Qiang,EffectArg1=2,EffectArg2=342,EffectValueB=100,DescID=2920020,},
  [21]={BaseID=21,NameID=2910021,EffectEnum=SkillEffectDescription.SED_Zhi1Ding2Xi3Bei4Wu1Xue2Shu3Xing4Zen1Qiang,EffectArg1=4,EffectArg2=342,EffectValueB=100,DescID=2920021,},
  [22]={BaseID=22,NameID=2910022,EffectEnum=SkillEffectDescription.SED_Zhi1Ding2Xi3Bei4Wu1Xue2Shu3Xing4Zen1Qiang,EffectArg1=5,EffectArg2=342,EffectValueB=100,DescID=2920022,},
  [23]={BaseID=23,NameID=2910023,EffectEnum=SkillEffectDescription.SED_Zhi1Ding2Xi3Bei4Wu1Xue2Shu3Xing4Zen1Qiang,EffectArg1=3,EffectArg2=342,EffectValueB=100,DescID=2920023,},
  [24]={BaseID=24,NameID=2910024,EffectEnum=SkillEffectDescription.SED_Zhi1Ding2Xi3Bei4Wu1Xue2Shu3Xing4Zen1Qiang,EffectArg1=14,EffectArg2=342,EffectValueB=100,DescID=2920024,},
  [25]={BaseID=25,NameID=2910025,EffectEnum=SkillEffectDescription.SED_Role_AddBuff,EffectArg1=4290,EffectValueB=100,DescID=2920025,},
  [26]={BaseID=26,NameID=2910026,EffectEnum=SkillEffectDescription.SED_Zhi1Ding2Xi3Bei4Wu1Xue2Shu3Xing4Zen1Qiang,EffectArg1=8,EffectArg2=342,EffectValueB=100,DescID=2920026,},
  [27]={BaseID=27,NameID=2910027,EffectEnum=SkillEffectDescription.SED_Zhi1Ding2Xi3Bei4Wu1Xue2Shu3Xing4Zen1Qiang,EffectArg1=7,EffectArg2=342,EffectValueB=100,DescID=2920027,},
  [28]={BaseID=28,NameID=2910028,EffectArg1=30,EffectValueA=32,DescID=2920028,},
  [29]={BaseID=29,NameID=2910029,EffectArg1=33,EffectValueA=18,DescID=2920029,},
  [30]={BaseID=30,NameID=2910030,EffectArg1=31,EffectValueA=16,DescID=2920030,},
  [31]={BaseID=31,NameID=2910031,EffectArg1=64,EffectValueA=27,DescID=2920031,},
  [32]={BaseID=32,NameID=2910032,EffectArg1=32,EffectValueA=13,DescID=2920032,},
  [33]={BaseID=33,NameID=2910033,EffectArg1=35,EffectValueA=21,DescID=2920033,},
  [34]={BaseID=34,NameID=2910034,EffectArg1=9,EffectValueA=6,DescID=2920034,},
  [35]={BaseID=35,NameID=2910035,EffectArg1=11,EffectValueA=6,DescID=2920035,},
  [36]={BaseID=36,NameID=2910036,EffectArg1=12,EffectValueA=6,DescID=2920036,},
  [37]={BaseID=37,NameID=2910037,EffectArg1=10,EffectValueA=6,DescID=2920037,},
  [38]={BaseID=38,NameID=2910038,EffectArg1=16,EffectValueA=6,DescID=2920038,},
  [39]={BaseID=39,NameID=2910039,EffectArg1=15,EffectValueA=6,DescID=2920039,},
  [40]={BaseID=40,NameID=2910040,EffectArg1=13,EffectValueA=6,DescID=2920040,},
  [41]={BaseID=41,NameID=2910041,EffectArg1=14,EffectValueA=6,DescID=2920041,},
  [42]={BaseID=42,NameID=2910042,EffectArg1=56,EffectValueA=10,DescID=2920042,},
  [43]={BaseID=43,NameID=2910043,EffectArg1=57,EffectValueA=10,DescID=2920043,},
  [44]={BaseID=44,NameID=2910044,EffectArg1=60,EffectValueA=10,DescID=2920044,},
  [45]={BaseID=45,NameID=2910045,EffectArg1=59,EffectValueA=10,DescID=2920045,},
  [46]={BaseID=46,NameID=2910046,EffectArg1=58,EffectValueA=10,DescID=2920046,},
  [47]={BaseID=47,NameID=2910047,EffectArg1=61,EffectValueA=10,DescID=2920047,},
  [48]={BaseID=48,NameID=2910048,EffectEnum=SkillEffectDescription.SED_Role_AddBuff,EffectArg1=623,EffectValueB=100,DescID=2920048,},
  [49]={BaseID=49,NameID=2910049,EffectEnum=SkillEffectDescription.SED_Role_AddBuff,EffectArg1=625,EffectValueB=100,DescID=2920049,},
  [50]={BaseID=50,NameID=2910050,EffectEnum=SkillEffectDescription.SED_Role_AddBuff,EffectArg1=624,EffectValueB=100,DescID=2920050,},
  [51]={BaseID=51,NameID=2910051,EffectEnum=SkillEffectDescription.SED_Role_AddBuff,EffectArg1=626,EffectValueB=100,DescID=2920051,},
  [52]={BaseID=52,NameID=2910052,EffectEnum=SkillEffectDescription.SED_Role_AddBuff,EffectArg1=4168,EffectValueB=100,DescID=2920052,},
  [53]={BaseID=53,NameID=2910053,EffectEnum=SkillEffectDescription.SED_Role_AddBuff,EffectArg1=4272,EffectValueB=100,DescID=2920053,},
  [54]={BaseID=54,NameID=2910054,EffectEnum=SkillEffectDescription.SED_Role_AddBuff,EffectArg1=629,EffectValueB=100,DescID=2920054,},
  [55]={BaseID=55,NameID=2910055,EffectEnum=SkillEffectDescription.SED_Role_AddBuff,EffectArg1=630,EffectValueB=100,DescID=2920055,},
  [56]={BaseID=56,NameID=2910056,EffectEnum=SkillEffectDescription.SED_Role_AddBuff,EffectArg1=632,EffectValueA=1,DescID=2920056,},
  [57]={BaseID=57,NameID=2910057,EffectEnum=SkillEffectDescription.SED_Role_AddBuff,EffectArg1=633,EffectValueA=1,DescID=2920057,},
  [58]={BaseID=58,NameID=2910058,EffectEnum=SkillEffectDescription.SED_Role_AddBuff,EffectArg1=634,EffectValueB=100,DescID=2920058,},
  [59]={BaseID=59,NameID=2910059,EffectEnum=SkillEffectDescription.SED_Role_AddBuff,EffectArg1=635,EffectValueB=100,DescID=2920059,},
  [60]={BaseID=60,NameID=2910060,EffectEnum=SkillEffectDescription.SED_Role_AddBuff,EffectArg1=636,EffectValueB=100,DescID=2920060,},
  [61]={BaseID=61,NameID=2910061,EffectEnum=SkillEffectDescription.SED_Role_AddBuff,EffectArg1=637,EffectValueA=1,DescID=2920061,},
  [62]={BaseID=62,NameID=2910062,EffectEnum=SkillEffectDescription.SED_Role_AddBuff,EffectArg1=638,EffectValueA=1,DescID=2920062,},
}
for k,v in pairs(AcupointEffect) do
    setmetatable(v, {['__index'] = AcupointEffectDefault})
end

-- export table: AcupointEffect
return AcupointEffect
