-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum FavorType
require("common");


local ApplePolishConfig= {
  [1]={BaseID=1,FindItemFavorList={FavorType.FT_Music,FavorType.FT_Game,FavorType.FT_Paint,FavorType.FT_Wine,FavorType.FT_Flower,FavorType.FT_LivingItem,FavorType.FT_Food,FavorType.FT_Cooking,FavorType.FT_Medicinal,FavorType.FT_Ore,FavorType.FT_Maquillage,},MessageClanList={11,8,18,10,22,16,3,17,15,5,4,2,1,19,12,},ForgeMakeList={49,72,83,53,71,94,87,113,106,109,107,52,61,75,104,47,57,111,114,77,112,85,86,56,115,58,6,44,108,54,59,50,62,45,81,65,93,69,78,60,51,73,110,68,67,48,76,105,88,46,},MessageFavorList={FavorType.FT_Food,FavorType.FT_Wine,FavorType.FT_Cooking,FavorType.FT_Cloth,FavorType.FT_Jewelry,FavorType.FT_Weapon,FavorType.FT_Ore,FavorType.FT_Flower,FavorType.FT_Medicinal,FavorType.FT_LivingItem,FavorType.FT_Paint,},},
}

-- export table: ApplePolishConfig
return ApplePolishConfig
