-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum AttrType
require("common");


local ArenaLimit= {
  [1001]={BaseID=1001,OtherMartialLevelUps=25,GoldenMartialLevelUp=25,DarkGoldenMartialLevelUp=20,BaseAttrUp=2000,JingTongAttrUp=2000,HP=0,},
  [2001]={BaseID=2001,OtherMartialLevelUps=30,GoldenMartialLevelUp=30,DarkGoldenMartialLevelUp=25,BaseAttrUp=5000,JingTongAttrUp=5000,HP=0,},
  [3001]={BaseID=3001,OtherMartialLevelUps=30,GoldenMartialLevelUp=30,DarkGoldenMartialLevelUp=30,BaseAttrUp=10000,JingTongAttrUp=10000,HP=0,},
}

-- export table: ArenaLimit
return ArenaLimit
