-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum AttrType
require("common");


local AttrTrans= {
}

-- export table: AttrTrans
return AttrTrans
