-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum AudioType
require("common");


local AudioBGMDefault = {ResourceBGM=1,type=AudioType.AudioType_Music,}
local AudioBGM= {
  [1]={BaseID=1,ResourceBGM=2003,},
  [2]={BaseID=2,ResourceBGM=2001,Clans={46,},Mazes={5,},},
  [3]={BaseID=3,ResourceBGM=2012,Clans={21,},Mazes={19,},},
  [4]={BaseID=4,ResourceBGM=2010,Clans={13,},Mazes={34,54,68,},},
  [5]={BaseID=5,ResourceBGM=2011,Clans={20,},Mazes={24,},ReplaceTag={1997,},ReplaceTagValue={1,},ReplaceBGM={2004,},},
  [6]={BaseID=6,ResourceBGM=2009,Clans={47,},Mazes={33,39,102,},},
  [7]={BaseID=7,ResourceBGM=2018,Mazes={41,21,17,40,28,},},
  [8]={BaseID=8,ResourceBGM=2018,Maps={367,653,666,794,795,796,2010,},Mazes={27,22,23,65,60,62,67,95,68,},},
  [9]={BaseID=9,ResourceBGM=2004,Maps={1395,},Mazes={16,66,},},
  [10]={BaseID=10,ResourceBGM=2005,Mazes={44,45,46,47,48,},},
  [11]={BaseID=11,ResourceBGM=2017,Mazes={7,32,61,},},
  [12]={BaseID=12,ResourceBGM=2020,Mazes={14,},},
  [13]={BaseID=13,ResourceBGM=2018,Maps={661,},Mazes={57,20,58,6,43,98,29,},},
  [14]={BaseID=14,ResourceBGM=2021,Mazes={9,},},
  [15]={BaseID=15,ResourceBGM=2017,Mazes={35,36,37,38,42,59,71,72,73,},},
  [16]={BaseID=16,ResourceBGM=2019,Mazes={8,10,11,12,13,3,4,},},
  [17]={BaseID=17,ResourceBGM=2021,Maps={1759,},},
  [18]={BaseID=18,ResourceBGM=2016,Clans={63,64,},},
  [19]={BaseID=19,ResourceBGM=2016,Clans={3,62,12,22,19,},},
  [20]={BaseID=20,ResourceBGM=2015,Clans={4,18,89,},},
  [21]={BaseID=21,ResourceBGM=2014,Clans={10,11,83,80,77,87,},},
  [22]={BaseID=22,ResourceBGM=2013,Clans={8,79,72,68,},Mazes={30,},},
  [23]={BaseID=23,ResourceBGM=2022,Clans={16,5,15,48,14,69,78,},Mazes={89,},},
  [24]={BaseID=24,ResourceBGM=2015,Clans={2,7,84,1,17,},},
  [25]={BaseID=25,ResourceBGM=2016,Clans={9,24,67,70,71,74,75,76,81,82,85,86,90,94,95,},},
  [26]={BaseID=26,Maps={367,},},
  [27]={BaseID=27,Maps={653,666,794,795,796,},},
  [28]={BaseID=28,ResourceBGM=2003,Maps={60,69,66,69,75,},ReplaceTag={822,},ReplaceTagValue={1,},ReplaceBGM={2004,},},
  [29]={BaseID=29,ResourceBGM=2005,Mazes={25,},},
  [30]={BaseID=30,Maps={1922,},},
  [31]={BaseID=31,ResourceBGM=2016,Maps={2001,96,},},
  [32]={BaseID=32,ResourceBGM=2014,Maps={1987,1988,1994,1989,1037,},},
  [33]={BaseID=33,ResourceBGM=2007,Mazes={76,},},
  [1001]={BaseID=1001,type=AudioType.AudioType_Sound,},
  [1002]={BaseID=1002,ResourceBGM=3003,type=AudioType.AudioType_Sound,Clans={46,21,13,20,47,},},
  [1003]={BaseID=1003,type=AudioType.AudioType_Sound,Maps={367,},},
  [1004]={BaseID=1004,type=AudioType.AudioType_Sound,Maps={653,666,794,795,796,},},
  [1005]={BaseID=1005,ResourceBGM=3005,type=AudioType.AudioType_Sound,Maps={60,69,66,69,75,},ReplaceTag={822,},ReplaceTagValue={1,},ReplaceBGM={3008,},},
  [1006]={BaseID=1006,ResourceBGM=3000,type=AudioType.AudioType_Sound,Mazes={14,9,},},
  [1007]={BaseID=1007,ResourceBGM=3007,type=AudioType.AudioType_Sound,Mazes={35,36,37,38,42,59,71,72,73,},},
  [1008]={BaseID=1008,ResourceBGM=3006,type=AudioType.AudioType_Sound,Mazes={8,10,11,12,13,3,4,26,},},
  [1009]={BaseID=1009,ResourceBGM=3000,type=AudioType.AudioType_Sound,Maps={1759,},},
  [1010]={BaseID=1010,ResourceBGM=3004,type=AudioType.AudioType_Sound,Mazes={16,66,44,45,46,47,48,},},
  [1011]={BaseID=1011,ResourceBGM=3008,type=AudioType.AudioType_Sound,Mazes={25,},},
  [1012]={BaseID=1012,ResourceBGM=3000,type=AudioType.AudioType_Sound,Maps={1922,},},
  [1013]={BaseID=1013,ResourceBGM=3000,type=AudioType.AudioType_Sound,Maps={2001,96,},},
  [1014]={BaseID=1014,ResourceBGM=3007,type=AudioType.AudioType_Sound,Maps={1987,1994,},},
}
for k,v in pairs(AudioBGM) do
    setmetatable(v, {['__index'] = AudioBGMDefault})
end

-- export table: AudioBGM
return AudioBGM
