-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local BabyJingTongAttrDes= {
  [1]={BaseID=1,DesID=180084,TargetValue=20,LimitMin=10,LimitMax=20,},
  [2]={BaseID=2,DesID=180085,TargetValue=80,LimitMin=15,LimitMax=40,},
  [3]={BaseID=3,DesID=180086,TargetValue=180,LimitMin=30,LimitMax=70,},
  [4]={BaseID=4,DesID=180087,TargetValue=320,LimitMin=60,LimitMax=110,},
  [5]={BaseID=5,DesID=180088,TargetValue=999999,LimitMin=100,LimitMax=160,},
  [6]={BaseID=6,DesID=180089,TargetValue=999999,LimitMin=100,LimitMax=160,},
}

-- export table: BabyJingTongAttrDes
return BabyJingTongAttrDes
