-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum RankType
require("common");


local BabyRankInfluenceDefault = {ParRankWeight1=0,ParRankWeight2=0,ParRankWeight3=0,ParRankWeight4=0,ParRankWeight7=5,ParRankWeight8=5,ParRankWeight9=5,}
local BabyRankInfluence= {
  [1]={BaseID=1,Rank=RankType.RT_White,Giftweight=40,SpGiftweight=40,MartialWeight=5,ParRankWeight1=5,ParRankWeight2=5,ParRankWeight3=5,ParRankWeight4=5,ParRankWeight5=5,ParRankWeight6=5,ParRankTime=3000,MartialBookAttrInfluence=10,},
  [2]={BaseID=2,Rank=RankType.RT_Green,Giftweight=35,SpGiftweight=35,MartialWeight=10,ParRankWeight2=5,ParRankWeight3=5,ParRankWeight4=5,ParRankWeight5=5,ParRankWeight6=5,ParRankTime=3000,MartialBookAttrInfluence=12,},
  [3]={BaseID=3,Rank=RankType.RT_Blue,Giftweight=30,SpGiftweight=30,MartialWeight=15,ParRankWeight3=10,ParRankWeight4=10,ParRankWeight5=10,ParRankWeight6=10,ParRankWeight7=10,ParRankWeight8=10,ParRankWeight9=10,ParRankTime=6000,MartialBookAttrInfluence=14,},
  [4]={BaseID=4,Rank=RankType.RT_Purple,Giftweight=25,SpGiftweight=25,MartialWeight=15,ParRankWeight4=15,ParRankWeight5=15,ParRankWeight6=15,ParRankWeight7=15,ParRankWeight8=15,ParRankWeight9=15,ParRankTime=6000,MartialBookAttrInfluence=16,},
  [5]={BaseID=5,Rank=RankType.RT_Orange,Giftweight=20,SpGiftweight=20,MartialWeight=15,ParRankWeight5=10,ParRankWeight6=10,ParRankWeight7=10,ParRankWeight8=10,ParRankWeight9=10,ParRankTime=9000,MartialBookAttrInfluence=18,},
  [6]={BaseID=6,Rank=RankType.RT_Golden,Giftweight=15,SpGiftweight=15,MartialWeight=10,ParRankWeight5=0,ParRankWeight6=10,ParRankWeight7=10,ParRankWeight8=10,ParRankWeight9=10,ParRankTime=12000,MartialBookAttrInfluence=20,},
  [7]={BaseID=7,Rank=RankType.RT_DarkGolden,Giftweight=10,SpGiftweight=10,MartialWeight=5,ParRankWeight5=0,ParRankWeight6=0,ParRankTime=15000,MartialBookAttrInfluence=25,},
  [8]={BaseID=8,Rank=RankType.RT_MultiColor,Giftweight=10,SpGiftweight=10,MartialWeight=5,ParRankWeight5=0,ParRankWeight6=0,ParRankTime=15000,MartialBookAttrInfluence=25,},
  [9]={BaseID=9,Rank=RankType.RT_ThirdGearDarkGolden,Giftweight=10,SpGiftweight=10,MartialWeight=5,ParRankWeight5=0,ParRankWeight6=0,ParRankTime=15000,MartialBookAttrInfluence=25,},
}
for k,v in pairs(BabyRankInfluence) do
    setmetatable(v, {['__index'] = BabyRankInfluenceDefault})
end

-- export table: BabyRankInfluence
return BabyRankInfluence
