-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local BackgroundConfig= {
  [1]={BaseID=1,ResourcePath="path1",Desc="desc1",},
  [2]={BaseID=2,ResourcePath="path2",Desc="desc2",},
  [3]={BaseID=3,ResourcePath="path3",Desc="desc3",},
  [4]={BaseID=4,ResourcePath="path4",Desc="desc4",},
  [5]={BaseID=5,ResourcePath="path5",Desc="desc5",},
}

-- export table: BackgroundConfig
return BackgroundConfig
