-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum BattleAIActionType
-- enum BattleAIActionClass
-- enum BattleAIMartionType
-- enum DepartEnumType
require("common");


local BattleAIActionDefault = {Hide=False,DepartEnum=DepartEnumType.DET_DepartEnumTypeNull,}
local BattleAIAction= {
  [1]={BaseID=1,Type=BattleAIActionType.BAAT_AOYI,ClassType=BattleAIActionClass.BAAC_AOYI,Filter=BattleAIMartionType.BAMT_AOYI,},
  [2]={BaseID=2,Type=BattleAIActionType.BAAT_MARTIAL,ClassType=BattleAIActionClass.BAAC_MARTIAL,Filter=BattleAIMartionType.BAMT_NORMAL,},
  [3]={BaseID=3,Type=BattleAIActionType.BAAT_COMBO,ClassType=BattleAIActionClass.BAAC_COMBO,Filter=BattleAIMartionType.BAMT_COMBO,},
  [4]={BaseID=4,Type=BattleAIActionType.BAAT_ENEMY_CLOSE,ClassType=BattleAIActionClass.BAAC_OTHER,Filter=BattleAIMartionType.BAMT_NULL,},
  [5]={BaseID=5,Type=BattleAIActionType.BAAT_ENEMY_AWAY,ClassType=BattleAIActionClass.BAAC_OTHER,Filter=BattleAIMartionType.BAMT_NULL,},
  [6]={BaseID=6,Type=BattleAIActionType.BAAT_SKIP_ROUND,ClassType=BattleAIActionClass.BAAC_OTHER,Filter=BattleAIMartionType.BAMT_NULL,},
  [7]={BaseID=7,Type=BattleAIActionType.BAAT_MARTIAL,ClassType=BattleAIActionClass.BAAC_MARTIAL,Filter=BattleAIMartionType.BAMT_NORMAL,DepartEnum=DepartEnumType.DET_MedicalSkill,},
}
for k,v in pairs(BattleAIAction) do
    setmetatable(v, {['__index'] = BattleAIActionDefault})
end

-- export table: BattleAIAction
return BattleAIAction
