-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local BattleAITemplate= {
  [1]={BaseID=1,NameID=410001,StrategyListTarget={2,2,2,},StrategyListAction={1,2,4,},StrategyListParam={0,0,0,},StrategyNameID=410051,},
  [2]={BaseID=2,NameID=410002,StrategyListTarget={28,2,2,2,},StrategyListAction={7,1,2,4,},StrategyListParam={0,0,0,0,},StrategyNameID=410052,},
}

-- export table: BattleAITemplate
return BattleAITemplate
