-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum BattleFunctionType
require("common");


local BattleFuncTypeEnum= {
  [1]={BaseID=1,FuncTypeName=BattleFunctionType.BFT_Battle_ChangeRoleAttr,EventArg1Type="int[]",EventArg1Name="1显示名称",EventArg2Type="RoleClass",EventArg2Name="2门派模版",EventArg3Type="int",EventArg3Name="3等级",EventArg4Type="SexType[]",EventArg4Name="4性别",EventArg5Type="RoleTypeTemplate[]",EventArg5Name="5类型",EventArg6Type="RankType[]",EventArg6Name="6品质",EventArg7Type="",EventArg7Name="",EventArg8Type="",EventArg8Name="",EventArg9Type="",EventArg9Name="",EventArg10Type="",EventArg10Name="",EventArg11Type="",EventArg11Name="",EventArg12Type="",EventArg12Name="",EventArg13Type="",EventArg13Name="",},
  [2]={BaseID=2,FuncTypeName=BattleFunctionType.BFT_Maze_ChangeRoleAttr,EventArg1Type="RoleClass[]",EventArg1Name="1门派模版",EventArg2Type="int",EventArg2Name="2等级下限",EventArg3Type="int",EventArg3Name="3等级上限",EventArg4Type="SexType[]",EventArg4Name="4性别",EventArg5Type="RoleTypeTemplate[]",EventArg5Name="5类型",EventArg6Type="RankType[]",EventArg6Name="6品质",EventArg7Type="int",EventArg7Name="7显示名称",EventArg8Type="",EventArg8Name="",EventArg9Type="",EventArg9Name="",EventArg10Type="",EventArg10Name="",EventArg11Type="",EventArg11Name="",EventArg12Type="",EventArg12Name="",EventArg13Type="",EventArg13Name="",},
  [3]={BaseID=3,FuncTypeName=BattleFunctionType.BFT_Clan_ChangeAttr,EventArg1Type="RoleTypeTemplate[]",EventArg1Name="1类型",EventArg2Type="",EventArg2Name="",EventArg3Type="",EventArg3Name="",EventArg4Type="",EventArg4Name="",EventArg5Type="",EventArg5Name="",EventArg6Type="",EventArg6Name="",EventArg7Type="",EventArg7Name="",EventArg8Type="",EventArg8Name="",EventArg9Type="",EventArg9Name="",EventArg10Type="",EventArg10Name="",EventArg11Type="",EventArg11Name="",EventArg12Type="",EventArg12Name="",EventArg13Type="",EventArg13Name="",},
}

-- export table: BattleFuncTypeEnum
return BattleFuncTypeEnum
