-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum EffectDescription
require("common");


local BattleConditionDefault = {Name=EffectDescription.EDD_JudgeMark,EventArg5=0,EventArg6=0,EventArg7=0,EventArg8=0,EventArg9=0,EventArg10=0,EventArg11=0,EventArg12=0,EventArg13=0,ArgCount=4,}
local BattleCondition= {
  [706515]={BaseID=706515,EventArg1={52,0,},EventArg3={10000,0,},EventArg4={1,0,},},
  [706516]={BaseID=706516,EventArg1={37,0,},EventArg3={10000,0,},EventArg4={1,0,},EventArg11=-4,},
  [706517]={BaseID=706517,EventArg1={80001,0,},EventArg3={10000,0,},EventArg4={0,0,},},
  [706518]={BaseID=706518,EventArg1={80001,0,},EventArg3={0,0,},EventArg4={1,0,},},
  [706519]={BaseID=706519,EventArg1={80001,0,},EventArg3={10000,0,},EventArg4={0,0,},},
  [706520]={BaseID=706520,EventArg1={80002,0,},EventArg3={10000,0,},EventArg4={1,0,},},
  [706521]={BaseID=706521,EventArg1={471,0,},EventArg3={10000,0,},EventArg4={1,0,},},
  [706522]={BaseID=706522,EventArg1={780,0,},EventArg3={10000,0,},EventArg4={1,0,},},
  [706523]={BaseID=706523,EventArg1={954,0,},EventArg3={10000,0,},EventArg4={1,0,},},
  [706524]={BaseID=706524,EventArg1={954,0,},EventArg3={10000,0,},EventArg4={1,0,},},
  [706525]={BaseID=706525,EventArg1={914,0,},EventArg3={10000,0,},EventArg4={1,0,},},
  [706526]={BaseID=706526,EventArg1={914,0,},EventArg3={10000,0,},EventArg4={1,0,},},
  [706527]={BaseID=706527,EventArg1={80003,0,},EventArg3={10000,0,},EventArg4={1,0,},},
  [706528]={BaseID=706528,EventArg1={110,0,},EventArg3={10000,0,},EventArg4={1,0,},},
  [706529]={BaseID=706529,EventArg1={1041,0,},EventArg3={10000,0,},EventArg4={1,0,},},
  [706530]={BaseID=706530,EventArg1={80004,0,},EventArg3={10000,0,},EventArg4={1,0,},},
  [706531]={BaseID=706531,EventArg1={80004,0,},EventArg3={10000,0,},EventArg4={1,0,},},
  [3111363]={BaseID=3111363,Name=EffectDescription.EDD_PlotTask_VariableCompare,EventArg1={641,0,},EventArg3={1,0,},EventArg4={10000,0,},},
}
for k,v in pairs(BattleCondition) do
    setmetatable(v, {['__index'] = BattleConditionDefault})
end

-- export table: BattleCondition
return BattleCondition
