-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local BondLevel= {
  [1]={BaseID=1,Level=1,GrowScale=10000,ConsumeScale=10000,},
  [2]={BaseID=2,Level=2,GrowScale=10000,ConsumeScale=12000,},
  [3]={BaseID=3,Level=3,GrowScale=10000,ConsumeScale=15000,},
  [4]={BaseID=4,Level=4,GrowScale=10000,ConsumeScale=18000,},
  [5]={BaseID=5,Level=5,GrowScale=10000,ConsumeScale=20000,},
  [6]={BaseID=6,Level=6,GrowScale=10000,ConsumeScale=25000,},
  [7]={BaseID=7,Level=7,GrowScale=10000,ConsumeScale=30000,},
  [8]={BaseID=8,Level=8,GrowScale=10000,ConsumeScale=40000,},
  [9]={BaseID=9,Level=9,GrowScale=10000,ConsumeScale=55000,},
  [10]={BaseID=10,Level=10,GrowScale=10000,ConsumeScale=80000,},
}

-- export table: BondLevel
return BondLevel
