-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local ClanChallengeConfig= {
  [1]={BaseID=1,BaseTask=5047,RankFactorList={70,75,80,90,100,130,180,},},
}

-- export table: ClanChallengeConfig
return ClanChallengeConfig
