-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum ClanType
require("common");


local ClanEliminateConfig= {
  [1]={BaseID=1,SmallClanTag=1641,SmallClanBuffPower=10,BigClanTag=1650,BigClanBuffPowerList={20,50,80,120,160,260,440,600,900,1200,1600,2200,3000,4000,5200,6500,},ClanTypeList={ClanType.CLT_WuLin,ClanType.CLT_BaDao,},ClanTypeTagList={1651,1825,},ClanTypeBuffPowerList={5,11,18,26,35,},ClanEliminateTaskID=5477,TiGuanLingItemID=801007,},
}

-- export table: ClanEliminateConfig
return ClanEliminateConfig
