-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local ClanPrestige= {
  [1]={BaseID=1,PrestigeLevel=0,ZhengFuReward=10,WageReward=1,LevelValue=5,RewardRate=10,},
  [2]={BaseID=2,PrestigeLevel=1,ZhengFuReward=10,WageReward=1,LevelValue=5,RewardRate=10,},
  [3]={BaseID=3,PrestigeLevel=2,ZhengFuReward=20,WageReward=2,LevelValue=25,RewardRate=20,},
  [4]={BaseID=4,PrestigeLevel=3,ZhengFuReward=50,WageReward=5,LevelValue=60,RewardRate=30,},
  [5]={BaseID=5,PrestigeLevel=4,ZhengFuReward=100,WageReward=10,LevelValue=100,RewardRate=40,},
  [6]={BaseID=6,PrestigeLevel=5,ZhengFuReward=200,WageReward=20,LevelValue=200,RewardRate=50,},
}

-- export table: ClanPrestige
return ClanPrestige
