-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local ClanLetter= {
  [1]={BaseID=1,ClanLetterID=63,},
  [2]={BaseID=2,ClanLetterID=22,},
  [3]={BaseID=3,ClanLetterID=19,},
  [4]={BaseID=4,ClanLetterID=3,},
  [5]={BaseID=5,ClanLetterID=12,},
  [6]={BaseID=6,ClanLetterID=2,},
  [7]={BaseID=7,ClanLetterID=10,},
  [8]={BaseID=8,ClanLetterID=11,},
  [9]={BaseID=9,ClanLetterID=95,},
  [10]={BaseID=10,ClanLetterID=49,},
  [11]={BaseID=11,ClanLetterID=4,},
  [12]={BaseID=12,ClanLetterID=17,},
  [13]={BaseID=13,ClanLetterID=8,},
  [14]={BaseID=14,ClanLetterID=1,},
  [15]={BaseID=15,ClanLetterID=16,},
  [16]={BaseID=16,ClanLetterID=18,},
}

-- export table: ClanLetter
return ClanLetter
