-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local ClanChallengeDefault = {Count=10,Buff=0,ChallengeCD=0,}
local ClanChallenge= {
  [1]={BaseID=1,Map=542,Role=1040113002,BuffLayers={90,80,70,60,50,40,30,20,10,0,},Task=5048,},
  [2]={BaseID=2,Map=544,Role=1040301002,BuffLayers={90,80,70,60,50,40,30,20,10,0,},Task=4334,},
  [3]={BaseID=3,Map=542,Role=1040301003,BuffLayers={90,80,70,60,50,40,30,20,10,0,},Task=4335,},
  [4]={BaseID=4,Map=603,Role=1120113001,BuffLayers={90,80,70,60,50,40,30,20,10,0,},Task=4009,},
  [5]={BaseID=5,Map=610,Role=1120301003,BuffLayers={90,80,70,60,50,40,30,20,10,0,},Task=4011,},
  [6]={BaseID=6,Map=603,Role=1120301005,BuffLayers={90,80,70,60,50,40,30,20,10,0,},Task=4012,},
  [7]={BaseID=7,Map=681,Role=1230301001,BuffLayers={90,80,70,60,50,40,30,20,10,0,},Task=4016,},
  [8]={BaseID=8,Map=7,Role=1030114001,BuffLayers={90,80,70,60,50,40,30,20,10,0,},Task=4017,},
  [9]={BaseID=9,Map=1757,Role=1050301003,BuffLayers={90,80,70,60,50,40,30,20,10,0,},Task=4018,},
  [10]={BaseID=10,Map=2,Role=1060114001,BuffLayers={90,80,70,60,50,40,30,20,10,0,},Task=4021,},
  [11]={BaseID=11,Map=791,Role=1000001149,BuffLayers={90,80,70,60,50,40,30,20,10,0,},Task=4022,},
  [12]={BaseID=12,Map=791,Role=1000001149,BuffLayers={90,80,70,60,50,40,30,20,10,0,},Task=4023,},
  [13]={BaseID=13,Map=786,Role=1170301003,BuffLayers={90,80,70,60,50,40,30,20,10,0,},Task=4347,},
  [14]={BaseID=14,Map=786,Role=1170301003,BuffLayers={90,80,70,60,50,40,30,20,10,0,},Task=4346,},
  [15]={BaseID=15,Map=790,Role=1170301002,BuffLayers={90,80,70,60,50,40,30,20,10,0,},Task=4348,},
  [16]={BaseID=16,Map=790,Role=1170301002,BuffLayers={90,80,70,60,50,40,30,20,10,0,},Task=4349,},
  [17]={BaseID=17,Map=808,Role=1210301002,BuffLayers={90,80,70,60,50,40,30,20,10,0,},Task=5154,},
  [18]={BaseID=18,Map=814,Role=1210301005,BuffLayers={90,80,70,60,50,40,30,20,10,0,},Task=5155,},
  [19]={BaseID=19,Map=873,Role=1080301006,BuffLayers={90,80,70,60,50,40,30,20,10,0,},Task=5157,},
  [20]={BaseID=20,Map=873,Role=1080301004,BuffLayers={90,80,70,60,50,40,30,20,10,0,},Task=5156,},
  [21]={BaseID=21,Map=1876,Role=1250113018,BuffLayers={90,80,70,60,50,40,30,20,10,0,},Task=5543,},
  [22]={BaseID=22,Map=1876,Role=1090314001,BuffLayers={90,80,70,60,50,40,30,20,10,0,},Task=5567,},
  [23]={BaseID=23,Map=962,Role=1250113017,BuffLayers={90,80,70,60,50,40,30,20,10,0,},Task=5568,},
}
for k,v in pairs(ClanChallenge) do
    setmetatable(v, {['__index'] = ClanChallengeDefault})
end

-- export table: ClanChallenge
return ClanChallenge
