-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local ClanTaskHaoGan= {
  [1]={BaseID=1,HaoGanMin=-100000,HaoGanMax=10,Hard={1,},HardWeight={100,},HaoGan={10,},},
  [2]={BaseID=2,HaoGanMin=10,HaoGanMax=20,Hard={1,2,},HardWeight={50,50,},HaoGan={10,10,},},
  [3]={BaseID=3,HaoGanMin=20,HaoGanMax=30,Hard={1,2,},HardWeight={50,50,},HaoGan={6,10,},},
  [4]={BaseID=4,HaoGanMin=30,HaoGanMax=40,Hard={1,2,3,},HardWeight={10,60,30,},HaoGan={4,6,10,},},
  [5]={BaseID=5,HaoGanMin=40,HaoGanMax=50,Hard={2,3,4,},HardWeight={10,60,30,},HaoGan={4,6,10,},},
  [6]={BaseID=6,HaoGanMin=50,HaoGanMax=60,Hard={3,4,5,},HardWeight={10,60,30,},HaoGan={3,5,8,},},
  [7]={BaseID=7,HaoGanMin=60,HaoGanMax=70,Hard={4,5,6,},HardWeight={10,60,30,},HaoGan={3,5,8,},},
  [8]={BaseID=8,HaoGanMin=70,HaoGanMax=80,Hard={5,6,7,},HardWeight={10,60,30,},HaoGan={2,4,6,},},
  [9]={BaseID=9,HaoGanMin=80,HaoGanMax=90,Hard={6,7,8,},HardWeight={10,60,30,},HaoGan={2,4,6,},},
  [10]={BaseID=10,HaoGanMin=90,HaoGanMax=99,Hard={7,8,9,},HardWeight={10,60,30,},HaoGan={1,2,3,},},
  [11]={BaseID=11,HaoGanMin=99,HaoGanMax=10000,Hard={7,8,9,},HardWeight={10,60,30,},HaoGan={1,2,3,},},
}

-- export table: ClanTaskHaoGan
return ClanTaskHaoGan
