-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum AttrType
require("common");


local CommonConfig= {
  [1]={BaseID=1,DefaultMartialMaxLevel=10,MartialMaxLevelExtra=10,MartialMaxLevelFinal=30,MaxStrengthenLevel=20,MaxSilverStrengthenTimes=50,VipExtraStrengthenTimes=450,MaxSilverRecastTimes=50,VipExtraRecastTimes=450,MartialUnlockAttrSelf=2400,MartialUnlockAttrDepart=1000,MartialUnlockAppointed=2000,MartialUnlockClan=1200,BackpackPayPrice=0,BackpackPaySize=0,BackpackBaseSize=600,BackpackSizePerDiff=100,BackpackPayTime=0,AllMateLeaveTeamTalkList={140023,140024,140025,},MartialUnlockAll=140,Iron2SilverPrice=50,Wmf2SilverPrice=30,InnerDemonBattleID=1023,ClanDelegationOpenTag=120006,CityDelegationOpenTag=120007,PrisonMap=661,PrisonTask=4584,PrisonNPCTask=0,MainCitys={25,26,27,21,28,},CommonAddMainCityDispositionLimit=5,ForgetInitialMartialTask=4689,LowLuckyValueMin=0,LowLuckyValueMax=0,MidLuckyValueMin=0,MidLuckyValueMax=0,HighLuckyValueMin=1,HighLuckyValueMax=999,InteractGiveTaskItems={80602,450504,},DuelDontEnterPrisonTag=120008,FreedomInitalTeammateBeginID=1880028000,FreedomInitalTeammateEndID=1880028079,CloseSwornAndMarryTag=120012,TreasureBookVIPBringInUP=6,OpenUnlcokInteractTag=120014,StrideRank=0,GoodEvilGift={449,869,705,870,1017,1018,},GoodEvilvalue={2,10,-2,-10,-5,5,},NormalTeammateLimit=50,VIPTeammateLimit=100,GraduateTag=1655,CurInteractRoleTagKey=130024,BabyNameUITagKey=130025,LimitNumMultiple=100,AccountInitItem={1303,1202,70603,70601,1601,},AccountInitItemNum={1,1,1,1,10,},TreasureMazeList={59,38,72,37,71,35,36,42,73,},EvilRouteTag=1748,EvilEliminateGifts={1680,1681,1682,1683,1684,},ScriptEndStoryTag=130036,EvoluteStrategyTag=130037,CurMainShowPet=102,ForgetMartialCostSilver=15,ForgetMartialFreeLv=0,MakeSecretCostSilver=500,OpenMartialStrongLevel=10,YWHighTowerMapID=652,YWHighTowerMapNameTag=130039,EvoluteOpenTag=110001,WeekEndRecycleMeridiansMax=40000,RoleMaxLevel=50,AutoUnlockDiff=2,timePerTile=5,RefreshGiftCost=2,InteractRefreshCost=1,CityTransferCost=200,},
}

-- export table: CommonConfig
return CommonConfig
