-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local CompareReward= {
  [1]={BaseID=1,MeridianLevelMin=1,MeridianLevelMax=60,WeightNull=200,WeightItem=800,ItemDropid=8250,WeightGiftPack=0,GiftPackID=250601726,FloorsItems={30941,30951,},FloorsItemNums={10,20,},},
  [2]={BaseID=2,MeridianLevelMin=61,MeridianLevelMax=140,WeightNull=200,WeightItem=700,ItemDropid=8251,WeightGiftPack=100,GiftPackID=250601726,FloorsItems={30941,30952,},FloorsItemNums={10,21,},},
  [3]={BaseID=3,MeridianLevelMin=141,MeridianLevelMax=270,WeightNull=180,WeightItem=710,ItemDropid=8252,WeightGiftPack=110,GiftPackID=250601727,FloorsItems={30941,30953,},FloorsItemNums={10,22,},},
  [4]={BaseID=4,MeridianLevelMin=271,MeridianLevelMax=550,WeightNull=160,WeightItem=720,ItemDropid=8253,WeightGiftPack=120,GiftPackID=250601728,FloorsItems={30941,30954,},FloorsItemNums={10,23,},},
  [5]={BaseID=5,MeridianLevelMin=551,MeridianLevelMax=810,WeightNull=140,WeightItem=730,ItemDropid=8254,WeightGiftPack=130,GiftPackID=250601729,FloorsItems={30941,30955,},FloorsItemNums={10,24,},},
  [6]={BaseID=6,MeridianLevelMin=811,MeridianLevelMax=1650,WeightNull=120,WeightItem=740,ItemDropid=8255,WeightGiftPack=140,GiftPackID=250601730,FloorsItems={30941,30956,},FloorsItemNums={10,25,},},
  [7]={BaseID=7,MeridianLevelMin=1651,MeridianLevelMax=3300,WeightNull=100,WeightItem=750,ItemDropid=8256,WeightGiftPack=150,GiftPackID=250601731,FloorsItems={30941,30957,},FloorsItemNums={10,26,},},
  [8]={BaseID=8,MeridianLevelMin=3301,MeridianLevelMax=999999,WeightNull=80,WeightItem=760,ItemDropid=8257,WeightGiftPack=160,GiftPackID=250601732,FloorsItems={30941,30958,},FloorsItemNums={10,27,},},
}

-- export table: CompareReward
return CompareReward
