-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local DailyReward= {
  [1]={BaseID=1,WaiterID=10090001,MeridiansLvlMin=0,MeridiansLvlMax=139,FreeRewards={1005,1105,8123,},FreeRewardsNum={1,1,1,},ChallengeRewards={1005,1105,8123,250601508,},ChallengeRewardsNum={4,4,4,1,},},
  [2]={BaseID=2,WaiterID=10090001,MeridiansLvlMin=140,MeridiansLvlMax=549,FreeRewards={1005,1105,8123,},FreeRewardsNum={1,1,1,},ChallengeRewards={1005,1105,8123,250601623,},ChallengeRewardsNum={4,4,4,1,},},
  [3]={BaseID=3,WaiterID=10090001,MeridiansLvlMin=550,MeridiansLvlMax=5500,FreeRewards={1005,1105,8123,},FreeRewardsNum={1,1,1,},ChallengeRewards={1005,1105,8123,250601624,},ChallengeRewardsNum={4,4,4,1,},},
  [4]={BaseID=4,WaiterID=10090002,MeridiansLvlMin=0,MeridiansLvlMax=139,FreeRewards={1005,1105,30951,},FreeRewardsNum={1,1,1,},ChallengeRewards={1005,1105,30951,1204,},ChallengeRewardsNum={4,4,4,1,},},
  [5]={BaseID=5,WaiterID=10090002,MeridiansLvlMin=140,MeridiansLvlMax=549,FreeRewards={1005,1105,30951,},FreeRewardsNum={1,1,1,},ChallengeRewards={1005,1105,30951,1202,},ChallengeRewardsNum={4,4,4,1,},},
  [6]={BaseID=6,WaiterID=10090002,MeridiansLvlMin=550,MeridiansLvlMax=5500,FreeRewards={1005,1105,30951,},FreeRewardsNum={1,1,1,},ChallengeRewards={1005,1105,30951,1201,},ChallengeRewardsNum={4,4,4,1,},},
}

-- export table: DailyReward
return DailyReward
