-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum RackItemMoneyType
require("common");


local Day3SignIn= {
  [1]={BaseID=1,StartDate={Year=2020,Month=10,Day=28,},EndDate={Year=2030,Month=12,Day=31,},TargetRole=1210313001,AdImg="CharacterCG/major/major_linghudage",FirstDayItems={30441,9301,30951,1303,1308,},FDINums={5,2,2,1,1,},FDIAppearTime={600,1800,3600,7200,10800,},NextDayItems={440406,412607,510707,},NDINums={1,1,1,},RoleCardItem=335002,MoneyType=RackItemMoneyType.RIMT_GOLD,Cost=1,MailTitle="风冲到达",MailContent="风冲到达活动超时未领取的物品和角色卡，请查收附件。",},
}

-- export table: Day3SignIn
return Day3SignIn
