-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum RankType
-- enum ClanMemberType
require("common");


local DelegationTaskPublishConfig= {
  [1]={BaseID=1,ClanRank=RankType.RT_White,PublisherDispositionConfigList={{MinDisposition=-100,MaxDisposition=10,ClanMember=ClanMemberType.CMET_DOORKEEPER,},{MinDisposition=-100,MaxDisposition=100,ClanMember=ClanMemberType.CMET_TEMP_MASTER,},},},
  [2]={BaseID=2,ClanRank=RankType.RT_Green,PublisherDispositionConfigList={{MinDisposition=-100,MaxDisposition=10,ClanMember=ClanMemberType.CMET_DOORKEEPER,},{MinDisposition=-100,MaxDisposition=100,ClanMember=ClanMemberType.CMET_TEMP_MASTER,},},},
  [3]={BaseID=3,ClanRank=RankType.RT_Blue,PublisherDispositionConfigList={{MinDisposition=-100,MaxDisposition=10,ClanMember=ClanMemberType.CMET_DOORKEEPER,},{MinDisposition=-100,MaxDisposition=100,ClanMember=ClanMemberType.CMET_TEMP_MASTER,},},},
  [4]={BaseID=4,ClanRank=RankType.RT_Purple,PublisherDispositionConfigList={{MinDisposition=-100,MaxDisposition=10,ClanMember=ClanMemberType.CMET_DOORKEEPER,},{MinDisposition=-100,MaxDisposition=100,ClanMember=ClanMemberType.CMET_TEMP_MASTER,},},},
  [5]={BaseID=5,ClanRank=RankType.RT_Orange,PublisherDispositionConfigList={{MinDisposition=-100,MaxDisposition=10,ClanMember=ClanMemberType.CMET_DOORKEEPER,},{MinDisposition=-100,MaxDisposition=100,ClanMember=ClanMemberType.CMET_TEMP_MASTER,},},},
  [6]={BaseID=6,ClanRank=RankType.RT_Golden,PublisherDispositionConfigList={{MinDisposition=-100,MaxDisposition=20,ClanMember=ClanMemberType.CMET_DOORKEEPER,},{MinDisposition=-100,MaxDisposition=100,ClanMember=ClanMemberType.CMET_TEMP_MASTER,},},},
  [7]={BaseID=7,ClanRank=RankType.RT_DarkGolden,PublisherDispositionConfigList={{MinDisposition=-100,MaxDisposition=20,ClanMember=ClanMemberType.CMET_DOORKEEPER,},{MinDisposition=-100,MaxDisposition=100,ClanMember=ClanMemberType.CMET_TEMP_MASTER,},},},
}

-- export table: DelegationTaskPublishConfig
return DelegationTaskPublishConfig
