-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local DelegationTaskSetting= {
  [1]={BaseID=1,DispositionRange={MinValue=-100,MaxValue=10,},TaskParamsSettingList={{TaskDifficulty=1,Weight=100,ClanDispositionReward=10,},},},
  [2]={BaseID=2,DispositionRange={MinValue=10,MaxValue=20,},TaskParamsSettingList={{TaskDifficulty=1,Weight=50,ClanDispositionReward=10,},{TaskDifficulty=2,Weight=50,ClanDispositionReward=10,},},},
  [3]={BaseID=3,DispositionRange={MinValue=20,MaxValue=30,},TaskParamsSettingList={{TaskDifficulty=1,Weight=50,ClanDispositionReward=6,},{TaskDifficulty=2,Weight=50,ClanDispositionReward=10,},},},
  [4]={BaseID=4,DispositionRange={MinValue=30,MaxValue=40,},TaskParamsSettingList={{TaskDifficulty=3,Weight=30,ClanDispositionReward=4,},{TaskDifficulty=4,Weight=50,ClanDispositionReward=6,},{TaskDifficulty=5,Weight=30,ClanDispositionReward=10,},},},
  [5]={BaseID=5,DispositionRange={MinValue=40,MaxValue=50,},TaskParamsSettingList={{TaskDifficulty=4,Weight=50,ClanDispositionReward=6,},{TaskDifficulty=5,Weight=50,ClanDispositionReward=10,},},},
  [6]={BaseID=6,DispositionRange={MinValue=50,MaxValue=60,},TaskParamsSettingList={{TaskDifficulty=4,Weight=50,ClanDispositionReward=5,},{TaskDifficulty=5,Weight=30,ClanDispositionReward=8,},},},
  [7]={BaseID=7,DispositionRange={MinValue=60,MaxValue=70,},TaskParamsSettingList={{TaskDifficulty=4,Weight=30,ClanDispositionReward=3,},{TaskDifficulty=5,Weight=40,ClanDispositionReward=5,},{TaskDifficulty=6,Weight=30,ClanDispositionReward=8,},},},
  [8]={BaseID=8,DispositionRange={MinValue=70,MaxValue=80,},TaskParamsSettingList={{TaskDifficulty=5,Weight=30,ClanDispositionReward=2,},{TaskDifficulty=6,Weight=40,ClanDispositionReward=4,},{TaskDifficulty=7,Weight=30,ClanDispositionReward=6,},},},
  [9]={BaseID=9,DispositionRange={MinValue=80,MaxValue=90,},TaskParamsSettingList={{TaskDifficulty=6,Weight=30,ClanDispositionReward=2,},{TaskDifficulty=7,Weight=40,ClanDispositionReward=4,},{TaskDifficulty=8,Weight=30,ClanDispositionReward=6,},},},
  [10]={BaseID=10,DispositionRange={MinValue=90,MaxValue=100,},TaskParamsSettingList={{TaskDifficulty=7,Weight=30,ClanDispositionReward=1,},{TaskDifficulty=8,Weight=40,ClanDispositionReward=2,},{TaskDifficulty=9,Weight=30,ClanDispositionReward=3,},},},
}

-- export table: DelegationTaskSetting
return DelegationTaskSetting
