-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local DifficultyDefault = {MartialUp=10,FKangXingBase=10,EKangXingBase=30,}
local Difficulty= {
  [1]={BaseID=1,DiffLevel=1,NumUp=100,HPUp=4000000,BaseAttrUp=60000,JingTongUp=20000,DmgUp=1700000,DefUp=210000,GiftUp=200000,MartialLevelUp=40,MartialUp=0,InheritUp=4,LevelUp=30,CostUp=0,OfficialUp=2000,},
  [2]={BaseID=2,DiffLevel=2,NumUp=120,HPUp=4800000,BaseAttrUp=72000,JingTongUp=24000,DmgUp=2000000,DefUp=250000,GiftUp=240000,MartialLevelUp=40,MartialUp=1,InheritUp=5,LevelUp=31,CostUp=100,OfficialUp=3000,},
  [3]={BaseID=3,DiffLevel=3,NumUp=150,HPUp=5800000,BaseAttrUp=86000,JingTongUp=29000,DmgUp=2400000,DefUp=300000,GiftUp=290000,MartialLevelUp=41,MartialUp=2,InheritUp=6,LevelUp=32,CostUp=200,OfficialUp=4000,},
  [4]={BaseID=4,DiffLevel=4,NumUp=180,HPUp=7000000,BaseAttrUp=100000,JingTongUp=35000,DmgUp=2900000,DefUp=360000,GiftUp=350000,MartialLevelUp=41,MartialUp=3,InheritUp=7,LevelUp=33,CostUp=300,OfficialUp=5000,},
  [5]={BaseID=5,DiffLevel=5,NumUp=250,HPUp=8400000,BaseAttrUp=120000,JingTongUp=42000,DmgUp=3500000,DefUp=430000,GiftUp=420000,MartialLevelUp=42,MartialUp=4,InheritUp=8,LevelUp=34,CostUp=400,OfficialUp=6000,},
  [6]={BaseID=6,DiffLevel=6,NumUp=330,HPUp=10000000,BaseAttrUp=140000,JingTongUp=50000,DmgUp=4200000,DefUp=520000,GiftUp=500000,MartialLevelUp=42,MartialUp=5,InheritUp=9,LevelUp=35,CostUp=500,OfficialUp=7000,},
  [7]={BaseID=7,DiffLevel=7,NumUp=430,HPUp=12000000,BaseAttrUp=170000,JingTongUp=60000,DmgUp=5000000,DefUp=620000,GiftUp=600000,MartialLevelUp=43,MartialUp=6,InheritUp=10,LevelUp=36,CostUp=600,OfficialUp=8000,},
  [8]={BaseID=8,DiffLevel=8,NumUp=560,HPUp=14000000,BaseAttrUp=200000,JingTongUp=72000,DmgUp=6000000,DefUp=740000,GiftUp=720000,MartialLevelUp=43,MartialUp=7,InheritUp=11,LevelUp=37,CostUp=700,OfficialUp=9000,},
  [9]={BaseID=9,DiffLevel=9,NumUp=730,HPUp=17000000,BaseAttrUp=240000,JingTongUp=86000,DmgUp=7200000,DefUp=890000,GiftUp=860000,MartialLevelUp=44,MartialUp=8,InheritUp=12,LevelUp=38,CostUp=800,OfficialUp=10000,},
  [10]={BaseID=10,DiffLevel=10,NumUp=1100,HPUp=20000000,BaseAttrUp=290000,JingTongUp=100000,DmgUp=8600000,DefUp=1100000,GiftUp=1000000,MartialLevelUp=44,MartialUp=9,InheritUp=13,LevelUp=39,CostUp=900,OfficialUp=11000,},
  [11]={BaseID=11,DiffLevel=11,NumUp=1700,HPUp=24000000,BaseAttrUp=350000,JingTongUp=120000,DmgUp=10000000,DefUp=1300000,GiftUp=1200000,MartialLevelUp=45,InheritUp=14,LevelUp=40,CostUp=1000,OfficialUp=12000,},
  [12]={BaseID=12,DiffLevel=12,NumUp=2600,HPUp=29000000,BaseAttrUp=420000,JingTongUp=140000,DmgUp=12000000,DefUp=1600000,GiftUp=1400000,MartialLevelUp=45,InheritUp=15,LevelUp=41,CostUp=1100,OfficialUp=13000,},
  [13]={BaseID=13,DiffLevel=13,NumUp=3900,HPUp=35000000,BaseAttrUp=500000,JingTongUp=170000,DmgUp=14000000,DefUp=1900000,GiftUp=1700000,MartialLevelUp=46,InheritUp=16,LevelUp=42,CostUp=1200,OfficialUp=14000,},
  [14]={BaseID=14,DiffLevel=14,NumUp=5900,HPUp=42000000,BaseAttrUp=600000,JingTongUp=200000,DmgUp=17000000,DefUp=2300000,GiftUp=2000000,MartialLevelUp=47,InheritUp=17,LevelUp=43,CostUp=1300,OfficialUp=15000,},
  [15]={BaseID=15,DiffLevel=15,NumUp=11800,HPUp=50000000,BaseAttrUp=720000,JingTongUp=240000,DmgUp=20000000,DefUp=2800000,GiftUp=2400000,MartialLevelUp=48,InheritUp=18,LevelUp=44,CostUp=1400,OfficialUp=16000,},
  [16]={BaseID=16,DiffLevel=16,NumUp=23600,HPUp=60000000,BaseAttrUp=860000,JingTongUp=290000,DmgUp=24000000,DefUp=3400000,GiftUp=2900000,MartialLevelUp=49,InheritUp=19,LevelUp=45,CostUp=1500,OfficialUp=17000,},
  [17]={BaseID=17,DiffLevel=17,NumUp=47200,HPUp=72000000,BaseAttrUp=1000000,JingTongUp=350000,DmgUp=29000000,DefUp=4100000,GiftUp=3500000,MartialLevelUp=50,InheritUp=20,LevelUp=46,CostUp=1600,OfficialUp=18000,},
  [18]={BaseID=18,DiffLevel=18,NumUp=94400,HPUp=86000000,BaseAttrUp=1200000,JingTongUp=420000,DmgUp=35000000,DefUp=4900000,GiftUp=4200000,MartialLevelUp=51,InheritUp=21,LevelUp=47,CostUp=1700,OfficialUp=19000,},
  [19]={BaseID=19,DiffLevel=19,NumUp=188800,HPUp=100000000,BaseAttrUp=1400000,JingTongUp=500000,DmgUp=42000000,DefUp=5900000,GiftUp=5000000,MartialLevelUp=52,InheritUp=22,LevelUp=48,CostUp=1800,OfficialUp=20000,},
  [20]={BaseID=20,DiffLevel=20,NumUp=377600,HPUp=120000000,BaseAttrUp=1700000,JingTongUp=600000,DmgUp=50000000,DefUp=7100000,GiftUp=6000000,MartialLevelUp=53,InheritUp=23,LevelUp=49,CostUp=1900,OfficialUp=21000,},
}
for k,v in pairs(Difficulty) do
    setmetatable(v, {['__index'] = DifficultyDefault})
end

-- export table: Difficulty
return Difficulty
