-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local DispositionConfig= {
  [1]={BaseID=1,LowDispositionUpValue=-1,RoleRevengeUpValue=-50,RoleRevengeTaskID=5655,PassClanCityRevengeUpValue=-90,EnterClanCityRevengeUpValue=-50,PassClanCityRevengeTaskID=5554,EnterClanCityRevengeTaskID=5497,},
}

-- export table: DispositionConfig
return DispositionConfig
