-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum RankType
require("common");


local EquipGenRule= {
  [1]={BaseID=1,Rank=RankType.RT_White,GenNum=5,},
  [2]={BaseID=2,Rank=RankType.RT_Green,GenNum=5,},
  [3]={BaseID=3,Rank=RankType.RT_Blue,GenNum=5,},
  [4]={BaseID=4,Rank=RankType.RT_Purple,GenNum=10,},
  [5]={BaseID=5,Rank=RankType.RT_Orange,GenNum=20,},
  [6]={BaseID=6,Rank=RankType.RT_Golden,GenNum=50,},
  [7]={BaseID=7,Rank=RankType.RT_DarkGolden,GenNum=50,},
  [8]={BaseID=8,Rank=RankType.RT_MultiColor,GenNum=50,},
  [9]={BaseID=9,Rank=RankType.RT_ThirdGearDarkGolden,GenNum=50,},
}

-- export table: EquipGenRule
return EquipGenRule
