-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum Event
-- enum TBoolean
require("common");


local EventConfig= {
  [1]={BaseID=1,EventType=Event.Event_RoleSelect,OnlyProcOneTask=TBoolean.BOOL_YES,},
}

-- export table: EventConfig
return EventConfig
