-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local EvoluteBigMapEventTask= {
  [1]={BaseID=1,StageIDs={1,},TaskCondition=0,TaskID=3576,Weight=10,},
  [2]={BaseID=2,StageIDs={2,3,4,5,6,},TaskCondition=0,TaskID=3584,Weight=15,},
  [3]={BaseID=3,StageIDs={2,3,4,5,6,},TaskCondition=0,TaskID=3585,Weight=15,},
  [4]={BaseID=4,StageIDs={3,4,5,6,},TaskCondition=0,TaskID=3588,Weight=20,},
  [6]={BaseID=6,StageIDs={3,4,5,6,},TaskCondition=0,TaskID=3589,Weight=20,},
  [7]={BaseID=7,StageIDs={4,5,6,},TaskCondition=121001,TaskID=3587,Weight=0,},
}

-- export table: EvoluteBigMapEventTask
return EvoluteBigMapEventTask
