-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum SexType
-- enum FavorType
require("common");


local FavorPool= {
  [1]={BaseID=1,Sex=SexType.ST_Male,favor={FavorType.FT_Game,FavorType.FT_Paint,FavorType.FT_Wine,FavorType.FT_Food,FavorType.FT_Weapon,FavorType.FT_Martial,FavorType.FT_Ore,},},
  [2]={BaseID=2,Sex=SexType.ST_Female,favor={FavorType.FT_Music,FavorType.FT_Flower,FavorType.FT_Food,FavorType.FT_Jewelry,FavorType.FT_Cloth,FavorType.FT_Medicinal,FavorType.FT_Maquillage,},},
}

-- export table: FavorPool
return FavorPool
