-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local FinalBattleConfig= {
  [1]={BaseID=1,RoundCount=10,FriendBaseHP=100,EnemyBaseHP=100,FriendLowDMG=5,FriendHighDMG=13,EnemyLowDMG=21,EnemyHighDMG=24,StageTask=5120,EasyModeTag=120005,EvilStageTask=5319,EvilModeTag=1746,VictoryAddBuff=4295,VictoryAddBuffLayerList={0,5,10,15,},CurVictoryNumTag=130035,},
}

-- export table: FinalBattleConfig
return FinalBattleConfig
