-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum TBoolean
require("common");


local FinalBattleCity= {
  [1]={BaseID=1,NameID=3710001,PosX=386,PosY=274,EnemyTeams={101,102,103,104,},FriendTeams={101,102,103,104,105,106,107,},Maze=44,Drops={50480002,},EasyModeDrops={50480012,},City=27,Evil=TBoolean.BOOL_NO,VictoryRecordTag=130029,},
  [2]={BaseID=2,NameID=3710002,PosX=-407,PosY=186,EnemyTeams={201,202,203,204,},FriendTeams={201,202,203,204,205,},Maze=45,Drops={50480001,},EasyModeDrops={50480011,},City=21,Evil=TBoolean.BOOL_NO,VictoryRecordTag=130030,},
  [3]={BaseID=3,NameID=3710003,PosX=63,PosY=54,EnemyTeams={301,302,303,304,},FriendTeams={301,302,303,304,305,306,},Maze=46,Drops={50480003,},EasyModeDrops={50480013,},City=25,Evil=TBoolean.BOOL_NO,VictoryRecordTag=130031,},
  [4]={BaseID=4,NameID=3710004,PosX=-220,PosY=-154,EnemyTeams={401,402,403,404,},FriendTeams={401,402,403,404,405,406,},Maze=47,Drops={50480005,},EasyModeDrops={50480015,},City=28,Evil=TBoolean.BOOL_NO,VictoryRecordTag=130032,},
  [5]={BaseID=5,NameID=3710005,PosX=396,PosY=-160,EnemyTeams={501,502,503,504,},FriendTeams={501,502,503,504,505,},Maze=48,Drops={50480004,},EasyModeDrops={50480014,},City=26,Evil=TBoolean.BOOL_NO,VictoryRecordTag=130033,},
  [6]={BaseID=6,NameID=3710001,PosX=386,PosY=274,EnemyTeams={111,112,113,114,},FriendTeams={111,112,113,114,},Maze=93,Drops={50480002,},EasyModeDrops={50480012,},City=27,Evil=TBoolean.BOOL_YES,VictoryRecordTag=1759,},
  [7]={BaseID=7,NameID=3710002,PosX=-407,PosY=186,EnemyTeams={211,212,213,214,},FriendTeams={211,212,213,214,},Maze=94,Drops={50480001,},EasyModeDrops={50480011,},City=21,Evil=TBoolean.BOOL_YES,VictoryRecordTag=1760,},
  [8]={BaseID=8,NameID=3710003,PosX=63,PosY=54,EnemyTeams={311,312,313,314,},FriendTeams={311,312,313,314,},Maze=92,Drops={50480003,},EasyModeDrops={50480013,},City=25,Evil=TBoolean.BOOL_YES,VictoryRecordTag=1761,},
  [9]={BaseID=9,NameID=3710004,PosX=-220,PosY=-154,EnemyTeams={411,412,413,414,},FriendTeams={411,412,413,414,},Maze=90,Drops={50480005,},EasyModeDrops={50480015,},City=28,Evil=TBoolean.BOOL_YES,VictoryRecordTag=1762,},
  [10]={BaseID=10,NameID=3710005,PosX=396,PosY=-160,EnemyTeams={511,512,513,514,},FriendTeams={511,512,513,514,},Maze=91,Drops={50480004,},EasyModeDrops={50480014,},City=26,Evil=TBoolean.BOOL_YES,VictoryRecordTag=1763,},
}

-- export table: FinalBattleCity
return FinalBattleCity
