-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum FavorType
require("common");


local FindItemTaskConfig= {
  [1]={BaseID=1,FindItemTaskStartTaskID=5068,FindItemTaskItemFavorTypeList={FavorType.FT_Music,FavorType.FT_Game,FavorType.FT_Paint,FavorType.FT_Wine,FavorType.FT_Flower,FavorType.FT_LivingItem,FavorType.FT_Food,FavorType.FT_Cooking,FavorType.FT_Medicinal,FavorType.FT_Ore,FavorType.FT_Maquillage,},},
}

-- export table: FindItemTaskConfig
return FindItemTaskConfig
