-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local ForgeMakeTaskConfig= {
  [1]={BaseID=1,ForgeMakeTaskStartTaskID=4354,ForgeMakeIDList={56,62,61,60,59,58,57,46,47,48,49,50,51,52,53,54,44,45,6,93,94,86,87,88,85,81,83,76,77,78,75,71,72,73,67,68,69,65,104,105,106,107,108,109,110,111,112,113,114,115,},},
}

-- export table: ForgeMakeTaskConfig
return ForgeMakeTaskConfig
