-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local ForgeRecastPowder= {
  [1]={BaseID=1,Name=1,RankBase={0,5,10,10,10,10,20,30,30,30,},},
  [2]={BaseID=2,Name=2,RankBase={0,5,10,10,10,20,30,50,50,50,},},
  [3]={BaseID=3,Name=3,RankBase={0,5,10,10,20,30,50,80,80,80,},},
  [4]={BaseID=4,Name=4,RankBase={0,5,10,20,20,40,60,100,100,100,},},
  [5]={BaseID=5,Name=5,RankBase={0,5,10,20,30,50,80,130,130,130,},},
  [6]={BaseID=6,Name=6,RankBase={0,5,20,20,30,60,90,150,150,150,},},
  [7]={BaseID=7,Name=7,RankBase={0,5,20,30,40,70,110,180,180,180,},},
  [8]={BaseID=8,Name=8,RankBase={0,5,20,30,40,80,120,200,200,200,},},
}

-- export table: ForgeRecastPowder
return ForgeRecastPowder
