-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local GrabTitleReward= {
  [1]={BaseID=1,EffectScriptID={2,7,},DailyMailMax=3,MailItems={1401,},MailItemsNum={50,},MailTitle="NPC冠名奖励",MailContent="你的角色已经乱入到其他玩家的世界中，称号是%s你在江湖中的知名度提高了。",},
}

-- export table: GrabTitleReward
return GrabTitleReward
