-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local GrabTitle_ReplaceRate= {
  [1]={BaseID=1,ReplaceRate=0,},
  [2]={BaseID=2,ReplaceRate=0,},
  [3]={BaseID=3,ReplaceRate=0,},
  [4]={BaseID=4,ReplaceRate=0,},
  [5]={BaseID=5,ReplaceRate=5,},
  [6]={BaseID=6,ReplaceRate=5,},
  [7]={BaseID=7,ReplaceRate=10,},
  [8]={BaseID=8,ReplaceRate=10,},
  [9]={BaseID=9,ReplaceRate=15,},
  [10]={BaseID=10,ReplaceRate=15,},
  [11]={BaseID=11,ReplaceRate=20,},
  [12]={BaseID=12,ReplaceRate=20,},
  [13]={BaseID=13,ReplaceRate=20,},
  [14]={BaseID=14,ReplaceRate=30,},
  [15]={BaseID=15,ReplaceRate=30,},
  [16]={BaseID=16,ReplaceRate=30,},
  [17]={BaseID=17,ReplaceRate=40,},
  [18]={BaseID=18,ReplaceRate=40,},
  [19]={BaseID=19,ReplaceRate=40,},
  [20]={BaseID=20,ReplaceRate=50,},
}

-- export table: GrabTitle_ReplaceRate
return GrabTitle_ReplaceRate
