-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local HighTowerConfig= {
  [1]={BaseID=1,ModelRole=1010001033,BackMap=1447,MainTask=5187,NormalTask=0,NormalBuilding=1450,NormalMap=828,NormalRoleBuilding=829,NormalMaxStage=1000,NormalMapDesc=3910001,BloodTask=0,BloodBuilding=1451,BloodMap=1455,BloodRoleBuilding=1456,BloodMaxStage=1000,BloodMapLockDesc=3910002,BloodMapDesc=3910003,UnlockBloodStage=0,RegimentTask=0,RegimentBuilding=1448,RegimentMap=1453,RegimentRoleBuilding=1454,RegimentMaxStage=100,RegimentMapLockDesc=3910004,RegimentMapDesc=3910005,UnlockRegimentStage=0,WeekLimit=50,},
}

-- export table: HighTowerConfig
return HighTowerConfig
