-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum HoodleLotteryPoolType
require("common");


local HoodleTutor= {
  [1]={BaseID=1,CountMin=0,CountMax=20,NailExtraPR=3500,ExtraDrop=HoodleLotteryPoolType.SHLPT_WELFARE1,},
  [2]={BaseID=2,CountMin=21,CountMax=50,NailExtraPR=1000,ExtraDrop=HoodleLotteryPoolType.SHLPT_WELFARE1,},
  [3]={BaseID=3,CountMin=51,CountMax=200,NailExtraPR=0,ExtraDrop=HoodleLotteryPoolType.SHLPT_WELFARE2,},
  [4]={BaseID=4,CountMin=201,CountMax=500,NailExtraPR=0,ExtraDrop=HoodleLotteryPoolType.SHLPT_WELFARE3,},
}

-- export table: HoodleTutor
return HoodleTutor
