-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local HoodlePrivacy= {
  [1]={BaseID=1,BeginDate="2021-01-14 12:00:00",EndDate="2021-02-06 11:59:59",Senior1Item=250601749,Senior2Item=337005,Senior3Item=367041,Senior4Item=367041,Senior5Item=367040,BossItem=367042,CallProb=10000,LowerNum=60,LowerHP=6,Senior1HP=18,Senior2HP=18,Senior3HP=18,Senior4HP=18,Senior5HP=18,BossHP=48,LowerDrop=130011,BG="PinballServerAD/pinball_ad_009",},
  [2]={BaseID=2,BeginDate="2021-02-06 12:00:00",EndDate="2021-02-20 11:59:59",Senior1Item=250601749,Senior2Item=367040,Senior3Item=250601746,Senior4Item=367039,Senior5Item=250601750,BossItem=337008,CallProb=10000,LowerNum=60,LowerHP=6,Senior1HP=18,Senior2HP=18,Senior3HP=18,Senior4HP=18,Senior5HP=18,BossHP=48,LowerDrop=130011,BG="PinballServerAD/pinball_ad_009",},
  [3]={BaseID=3,BeginDate="2021-02-20 12:00:00",EndDate="2021-03-06 11:59:59",Senior1Item=250601749,Senior2Item=367040,Senior3Item=250601746,Senior4Item=367039,Senior5Item=250601750,BossItem=337007,CallProb=10000,LowerNum=60,LowerHP=6,Senior1HP=18,Senior2HP=18,Senior3HP=18,Senior4HP=18,Senior5HP=18,BossHP=48,LowerDrop=130011,BG="PinballServerAD/pinball_ad_009",},
  [4]={BaseID=4,BeginDate="2021-03-06 12:00:00",EndDate="2021-03-20 11:59:59",Senior1Item=250601749,Senior2Item=367040,Senior3Item=250601746,Senior4Item=367039,Senior5Item=250601750,BossItem=250601752,CallProb=10000,LowerNum=60,LowerHP=6,Senior1HP=18,Senior2HP=18,Senior3HP=18,Senior4HP=18,Senior5HP=18,BossHP=48,LowerDrop=130011,BG="PinballServerAD/pinball_ad_009",},
}

-- export table: HoodlePrivacy
return HoodlePrivacy
