-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local HoodleHPColorDefault = {R=85,G=155,B=102,}
local HoodleHPColor= {
  [1]={ID=1,},
  [2]={ID=2,R=233,G=157,B=48,},
  [3]={ID=3,R=198,G=32,B=32,},
  [4]={ID=4,},
  [5]={ID=5,R=233,G=157,B=48,},
  [6]={ID=6,R=198,G=32,B=32,},
  [7]={ID=7,},
  [8]={ID=8,R=233,G=157,B=48,},
  [9]={ID=9,R=198,G=32,B=32,},
  [10]={ID=10,},
  [11]={ID=11,R=233,G=157,B=48,},
  [12]={ID=12,R=198,G=32,B=32,},
  [13]={ID=13,},
  [14]={ID=14,R=233,G=157,B=48,},
  [15]={ID=15,R=198,G=32,B=32,},
}
for k,v in pairs(HoodleHPColor) do
    setmetatable(v, {['__index'] = HoodleHPColorDefault})
end

-- export table: HoodleHPColor
return HoodleHPColor
