-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum HoodleLotteryPoolType
-- enum CDropType
-- enum TBoolean
require("common");


local HoodleDefault = {HoodleItem=1601,NailTimes=6,BurstTimes=6,IsAddTenShootMode=TBoolean.BOOL_YES,IsUseTenShootMode=TBoolean.BOOL_YES,}
local Hoodle= {
  [1]={BaseID=1,PoolType=HoodleLotteryPoolType.SHLPT_NORMAL,Name=631001,},
  [2]={BaseID=2,PoolType=HoodleLotteryPoolType.SHLPT_WELFARE1,Name=631001,BeginDate={Year=2019,Month=8,Day=23,},EndDate={Year=2019,Month=9,Day=23,},},
  [3]={BaseID=3,PoolType=HoodleLotteryPoolType.SHLPT_WELFARE2,Name=631001,BeginDate={Year=2019,Month=8,Day=23,},EndDate={Year=2019,Month=9,Day=23,},},
  [4]={BaseID=4,PoolType=HoodleLotteryPoolType.SHLPT_WELFARE3,Name=631001,BeginDate={Year=2019,Month=8,Day=23,},EndDate={Year=2019,Month=9,Day=23,},},
  [5]={BaseID=5,PoolType=HoodleLotteryPoolType.SHLPT_GEREN,Name=631003,},
}
for k,v in pairs(Hoodle) do
    setmetatable(v, {['__index'] = HoodleDefault})
end

-- export table: Hoodle
return Hoodle
