-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local HoodleScene= {
  [1]={ID=1,Key="bg_pinball_scene",Normal="PinballPools/public_001/bg_pinball_scene",Bai="PinballPools/personal_001/bg_pinball_scene",},
  [2]={ID=2,Key="pinball_img_obstacles1",Normal="PinballPools/public_001/pinball_img_obstacles1",Bai="PinballPools/personal_001/pinball_img_obstacles1",},
  [3]={ID=3,Key="pinball_img_obstacles2",Normal="PinballPools/public_001/pinball_img_obstacles2",Bai="PinballPools/personal_001/pinball_img_obstacles2",},
  [4]={ID=4,Key="pinball_img_obstacles2_1",Normal="PinballPools/public_001/pinball_img_obstacles2_1",Bai="PinballPools/personal_001/pinball_img_obstacles2_1",},
  [5]={ID=5,Key="pinball_img_obstacles3",Normal="PinballPools/public_001/pinball_img_obstacles3",Bai="PinballPools/personal_001/pinball_img_obstacles3",},
  [6]={ID=6,Key="pinball_img_obstacles4",Normal="PinballPools/public_001/pinball_img_obstacles4",Bai="PinballPools/personal_001/pinball_img_obstacles4",},
  [7]={ID=7,Key="pinball_img_obstacles5",Normal="PinballPools/public_001/pinball_img_obstacles5",Bai="PinballPools/personal_001/pinball_img_obstacles5",},
  [8]={ID=8,Key="pinball_img_obstacles5_1",Normal="PinballPools/public_001/pinball_img_obstacles5_1",Bai="PinballPools/personal_001/pinball_img_obstacles5_1",},
  [9]={ID=9,Key="pinball_img_stone1",Normal="PinballPools/public_001/pinball_img_stone1",Bai="PinballPools/personal_001/pinball_img_stone1",},
  [10]={ID=10,Key="pinball_img_stone2",Normal="PinballPools/public_001/pinball_img_stone2",Bai="PinballPools/personal_001/pinball_img_stone2",},
  [11]={ID=11,Key="pinball_img_stone3",Normal="PinballPools/public_001/pinball_img_stone3",Bai="PinballPools/personal_001/pinball_img_stone2",},
  [12]={ID=12,Key="pinball_img_stone4",Normal="PinballPools/public_001/pinball_img_stone4",Bai="PinballPools/personal_001/pinball_img_stone2",},
  [13]={ID=13,Key="pinball_img_stone5",Normal="PinballPools/public_001/pinball_img_stone5",Bai="PinballPools/personal_001/pinball_img_stone2",},
  [14]={ID=14,Key="pinball_img_stone6",Normal="PinballPools/public_001/pinball_img_stone6",Bai="PinballPools/personal_001/pinball_img_stone2",},
  [15]={ID=15,Key="pinball_img_stone7",Normal="PinballPools/public_001/pinball_img_stone7",Bai="PinballPools/personal_001/pinball_img_stone2",},
  [16]={ID=16,Key="pinball_img_stone8",Normal="PinballPools/public_001/pinball_img_stone8",Bai="PinballPools/personal_001/pinball_img_stone2",},
  [17]={ID=17,Key="pinball_img_stone9",Normal="PinballPools/public_001/pinball_img_stone9",Bai="PinballPools/personal_001/pinball_img_stone2",},
}

-- export table: HoodleScene
return HoodleScene
