-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local HoodleRole= {
  [1]={PoolID=1,RoleType=0,IdlePath="Effect/Ui_eff/ef_danzhu/img_people1",HitPath="Effect/Ui_eff/ef_danzhu/img_people2",DiePath="Effect/Ui_eff/ef_danzhu/img_people3",},
  [5]={PoolID=5,RoleType=0,IdlePath="Effect/Ui_eff/ef_danzhu/role_personal_pool_001/img_002_normal",HitPath="Effect/Ui_eff/ef_danzhu/role_personal_pool_001/img_002_hit",DiePath="Effect/Ui_eff/ef_danzhu/role_personal_pool_001/img_002_death",},
  [65541]={PoolID=5,RoleType=1,IdlePath="Effect/Ui_eff/ef_danzhu/role_personal_pool_001/img_002_normal",HitPath="Effect/Ui_eff/ef_danzhu/role_personal_pool_001/img_002_hit",DiePath="Effect/Ui_eff/ef_danzhu/role_personal_pool_001/img_002_death",},
  [131077]={PoolID=5,RoleType=2,IdlePath="Effect/Ui_eff/ef_danzhu/role_personal_pool_001/img_003_normal",HitPath="Effect/Ui_eff/ef_danzhu/role_personal_pool_001/img_003_hit",DiePath="Effect/Ui_eff/ef_danzhu/role_personal_pool_001/img_003_death",},
  [196613]={PoolID=5,RoleType=3,IdlePath="Effect/Ui_eff/ef_danzhu/role_personal_pool_001/img_007_normal",HitPath="Effect/Ui_eff/ef_danzhu/role_personal_pool_001/img_007_hit",DiePath="Effect/Ui_eff/ef_danzhu/role_personal_pool_001/img_007_death",},
  [262149]={PoolID=5,RoleType=4,IdlePath="Effect/Ui_eff/ef_danzhu/role_personal_pool_001/img_006_normal",HitPath="Effect/Ui_eff/ef_danzhu/role_personal_pool_001/img_006_hit",DiePath="Effect/Ui_eff/ef_danzhu/role_personal_pool_001/img_006_death",},
  [327685]={PoolID=5,RoleType=5,IdlePath="Effect/Ui_eff/ef_danzhu/role_personal_pool_001/img_004_normal",HitPath="Effect/Ui_eff/ef_danzhu/role_personal_pool_001/img_004_hit",DiePath="Effect/Ui_eff/ef_danzhu/role_personal_pool_001/img_004_death",},
  [393221]={PoolID=5,RoleType=6,IdlePath="Effect/Ui_eff/ef_danzhu/role_personal_pool_001/img_005_normal",HitPath="Effect/Ui_eff/ef_danzhu/role_personal_pool_001/img_005_hit",DiePath="Effect/Ui_eff/ef_danzhu/role_personal_pool_001/img_005_death",},
  [458757]={PoolID=5,RoleType=7,IdlePath="Effect/Ui_eff/ef_danzhu/role_personal_pool_001/img_009_normal",HitPath="Effect/Ui_eff/ef_danzhu/role_personal_pool_001/img_009_hit",DiePath="Effect/Ui_eff/ef_danzhu/role_personal_pool_001/img_009_death",},
  [65536001]={PoolID=1,RoleType=1000,IdlePath="Effect/Ui_eff/ef_danzhu/img_woman",HitPath="Effect/Ui_eff/ef_danzhu/img_woman2",DiePath="",},
  [65536005]={PoolID=5,RoleType=1000,IdlePath="Effect/Ui_eff/ef_danzhu/role_personal_pool_001/img_010_normal",HitPath="Effect/Ui_eff/ef_danzhu/role_personal_pool_001/img_010_hit",DiePath="",},
}

-- export table: HoodleRole
return HoodleRole
