-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local HoodlePrivacyWeightDefault = {LowerWeight=45,Senior1Weight=10,Senior2Weight=10,Senior3Weight=10,Senior4Weight=10,Senior5Weight=10,BossWeight=5,}
local HoodlePrivacyWeight= {
  [1]={BaseID=1,CountMin=0,CountMax=5,LowerWeight=90,Senior1Weight=2,Senior2Weight=2,Senior3Weight=2,Senior4Weight=2,Senior5Weight=2,BossWeight=0,},
  [2]={BaseID=2,CountMin=6,CountMax=10,LowerWeight=84,Senior1Weight=3,Senior2Weight=3,Senior3Weight=3,Senior4Weight=3,Senior5Weight=3,BossWeight=1,},
  [3]={BaseID=3,CountMin=11,CountMax=15,LowerWeight=78,Senior1Weight=4,Senior2Weight=4,Senior3Weight=4,Senior4Weight=4,Senior5Weight=4,BossWeight=2,},
  [4]={BaseID=4,CountMin=16,CountMax=20,LowerWeight=72,Senior1Weight=5,Senior2Weight=5,Senior3Weight=5,Senior4Weight=5,Senior5Weight=5,BossWeight=3,},
  [5]={BaseID=5,CountMin=21,CountMax=25,LowerWeight=66,Senior1Weight=6,Senior2Weight=6,Senior3Weight=6,Senior4Weight=6,Senior5Weight=6,BossWeight=4,},
  [6]={BaseID=6,CountMin=26,CountMax=30,LowerWeight=60,Senior1Weight=7,Senior2Weight=7,Senior3Weight=7,Senior4Weight=7,Senior5Weight=7,},
  [7]={BaseID=7,CountMin=31,CountMax=35,LowerWeight=55,Senior1Weight=8,Senior2Weight=8,Senior3Weight=8,Senior4Weight=8,Senior5Weight=8,},
  [8]={BaseID=8,CountMin=36,CountMax=40,LowerWeight=50,Senior1Weight=9,Senior2Weight=9,Senior3Weight=9,Senior4Weight=9,Senior5Weight=9,},
  [9]={BaseID=9,CountMin=41,CountMax=45,},
  [10]={BaseID=10,CountMin=46,CountMax=50,},
  [11]={BaseID=11,CountMin=51,CountMax=55,},
  [12]={BaseID=12,CountMin=56,CountMax=60,},
  [13]={BaseID=13,CountMin=61,CountMax=65,},
}
for k,v in pairs(HoodlePrivacyWeight) do
    setmetatable(v, {['__index'] = HoodlePrivacyWeightDefault})
end

-- export table: HoodlePrivacyWeight
return HoodlePrivacyWeight
