-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum HouseChatBubbleType
require("common");


local HouseChatBubble= {
  [1]={BaseID=1,DialogueType=HouseChatBubbleType.HCBT_Login,ChatID=670001,AudioID=10000,},
  [2]={BaseID=2,DialogueType=HouseChatBubbleType.HCBT_Login,ChatID=670002,AudioID=10001,},
  [3]={BaseID=3,DialogueType=HouseChatBubbleType.HCBT_Login,ChatID=670003,AudioID=10002,},
  [4]={BaseID=4,DialogueType=HouseChatBubbleType.HCBT_Login,ChatID=670004,AudioID=10003,},
  [5]={BaseID=5,DialogueType=HouseChatBubbleType.HCBT_Back,ChatID=670008,AudioID=10007,},
  [6]={BaseID=6,DialogueType=HouseChatBubbleType.HCBT_Back,ChatID=670009,AudioID=10008,},
  [7]={BaseID=7,DialogueType=HouseChatBubbleType.HCBT_Back,ChatID=670010,AudioID=10009,},
}

-- export table: HouseChatBubble
return HouseChatBubble
