-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local InnerDemonMartialAddDefault = {White=3,Green=3,Blue=3,Purple=5,}
local InnerDemonMartialAdd= {
  [0]={BaseID=0,Orange=8,Golden=11,DarkGolden=13,},
  [1]={BaseID=1,Orange=8,Golden=11,DarkGolden=13,},
  [2]={BaseID=2,Orange=8,Golden=11,DarkGolden=13,},
  [3]={BaseID=3,Orange=8,Golden=11,DarkGolden=13,},
  [4]={BaseID=4,Orange=10,Golden=13,DarkGolden=15,},
  [5]={BaseID=5,White=4,Green=4,Blue=4,Purple=6,Orange=10,Golden=13,DarkGolden=15,},
  [6]={BaseID=6,White=4,Green=4,Blue=4,Purple=6,Orange=11,Golden=14,DarkGolden=16,},
  [7]={BaseID=7,White=5,Green=5,Blue=5,Purple=7,Orange=11,Golden=14,DarkGolden=16,},
  [8]={BaseID=8,White=5,Green=5,Blue=5,Purple=7,Orange=12,Golden=15,DarkGolden=17,},
  [9]={BaseID=9,White=6,Green=6,Blue=6,Purple=8,Orange=14,Golden=17,DarkGolden=19,},
  [10]={BaseID=10,White=6,Green=6,Blue=6,Purple=8,Orange=15,Golden=18,DarkGolden=20,},
}
for k,v in pairs(InnerDemonMartialAdd) do
    setmetatable(v, {['__index'] = InnerDemonMartialAddDefault})
end

-- export table: InnerDemonMartialAdd
return InnerDemonMartialAdd
