-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local InnerDemonEnhanceItem= {
  [0]={BaseID=0,EnhanceItem=0,},
  [1]={BaseID=1,EnhanceItem=1,},
  [2]={BaseID=2,EnhanceItem=3,},
  [3]={BaseID=3,EnhanceItem=5,},
  [4]={BaseID=4,EnhanceItem=7,},
  [5]={BaseID=5,EnhanceItem=10,},
  [6]={BaseID=6,EnhanceItem=12,},
  [7]={BaseID=7,EnhanceItem=14,},
  [8]={BaseID=8,EnhanceItem=16,},
  [9]={BaseID=9,EnhanceItem=19,},
  [10]={BaseID=10,EnhanceItem=20,},
}

-- export table: InnerDemonEnhanceItem
return InnerDemonEnhanceItem
