-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local InnerDemonGenerateLevel= {
  [0]={BaseID=0,White=20,Green=22,Blue=24,Purple=27,Orange=30,Golden=32,DarkGolden=36,},
  [1]={BaseID=1,White=21,Green=23,Blue=25,Purple=28,Orange=31,Golden=33,DarkGolden=37,},
  [2]={BaseID=2,White=21,Green=23,Blue=25,Purple=28,Orange=32,Golden=34,DarkGolden=38,},
  [3]={BaseID=3,White=22,Green=24,Blue=26,Purple=29,Orange=33,Golden=35,DarkGolden=39,},
  [4]={BaseID=4,White=22,Green=24,Blue=26,Purple=29,Orange=34,Golden=36,DarkGolden=40,},
  [5]={BaseID=5,White=25,Green=27,Blue=29,Purple=32,Orange=35,Golden=37,DarkGolden=41,},
  [6]={BaseID=6,White=26,Green=28,Blue=30,Purple=33,Orange=36,Golden=38,DarkGolden=42,},
  [7]={BaseID=7,White=26,Green=28,Blue=30,Purple=33,Orange=37,Golden=39,DarkGolden=43,},
  [8]={BaseID=8,White=27,Green=29,Blue=31,Purple=34,Orange=38,Golden=40,DarkGolden=44,},
  [9]={BaseID=9,White=28,Green=30,Blue=32,Purple=35,Orange=39,Golden=41,DarkGolden=45,},
  [10]={BaseID=10,White=32,Green=34,Blue=36,Purple=39,Orange=40,Golden=42,DarkGolden=46,},
}

-- export table: InnerDemonGenerateLevel
return InnerDemonGenerateLevel
