-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum RankType
require("common");


local InnerDemonMartialBase= {
  [1]={MartialRank=RankType.RT_White,MartialBase=13,},
  [2]={MartialRank=RankType.RT_Green,MartialBase=12,},
  [3]={MartialRank=RankType.RT_Blue,MartialBase=11,},
  [4]={MartialRank=RankType.RT_Purple,MartialBase=10,},
  [5]={MartialRank=RankType.RT_Orange,MartialBase=10,},
  [6]={MartialRank=RankType.RT_Golden,MartialBase=10,},
  [7]={MartialRank=RankType.RT_DarkGolden,MartialBase=10,},
  [8]={MartialRank=RankType.RT_MultiColor,MartialBase=10,},
}

-- export table: InnerDemonMartialBase
return InnerDemonMartialBase
