-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local InquiryGift= {
  [1]={BaseID=1,GiftID=1781,ReviseNull=2500,ReviseDoubt=-2500,ReviseGuilt=2500,},
  [2]={BaseID=2,GiftID=1782,ReviseNull=2000,ReviseDoubt=-2000,ReviseGuilt=3000,},
  [3]={BaseID=3,GiftID=1783,ReviseNull=3000,ReviseDoubt=-3000,ReviseGuilt=2000,},
  [4]={BaseID=4,GiftID=1784,ReviseNull=4000,ReviseDoubt=-4000,ReviseGuilt=1000,},
}

-- export table: InquiryGift
return InquiryGift
