-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum RankType
-- enum FavorType
require("common");


local InquiryCommon= {
  [1]={BaseID=1,TaskID=3992,DialogueRandomPool={"180095","180096","180097",},RoleIDs={1040301007,1040201001,},GoodEvilLimitPool={"180099",},GoodEvil={30,-30,},LevelLimitPool={"180098",},LevelLimit={5,2,},Rank={RankType.RT_White,RankType.RT_Green,RankType.RT_Blue,RankType.RT_Purple,RankType.RT_Orange,RankType.RT_Golden,RankType.RT_DarkGolden,},Random={80,60,25,15,10,5,1,},AdventureGiftHerbs={474,476,480,511,512,},PresentHerbs=FavorType.FT_Medicinal,AdventureGiftRock={513,514,515,516,517,},PresentRock=FavorType.FT_Ore,AdventureGiftFood={521,533,532,531,525,},PresentFood=FavorType.FT_Cooking,PresentFinal={1002,1102,},},
}

-- export table: InquiryCommon
return InquiryCommon
