-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum ItemTypeDetail
-- enum RankType
require("common");


local ItemResolve= {
  [1]={BaseID=1,ItemType=ItemTypeDetail.ItemType_RolePieces,Rank=RankType.RT_White,PlatformCoin=10,},
  [2]={BaseID=2,ItemType=ItemTypeDetail.ItemType_RolePieces,Rank=RankType.RT_Green,PlatformCoin=20,},
  [3]={BaseID=3,ItemType=ItemTypeDetail.ItemType_RolePieces,Rank=RankType.RT_Blue,PlatformCoin=40,},
  [4]={BaseID=4,ItemType=ItemTypeDetail.ItemType_RolePieces,Rank=RankType.RT_Purple,PlatformCoin=60,},
  [5]={BaseID=5,ItemType=ItemTypeDetail.ItemType_RolePieces,Rank=RankType.RT_Orange,PlatformCoin=100,},
  [6]={BaseID=6,ItemType=ItemTypeDetail.ItemType_RolePieces,Rank=RankType.RT_Golden,PlatformCoin=300,},
  [7]={BaseID=7,ItemType=ItemTypeDetail.ItemType_RolePieces,Rank=RankType.RT_DarkGolden,PlatformCoin=1000,},
  [8]={BaseID=8,ItemType=ItemTypeDetail.ItemType_RolePieces,Rank=RankType.RT_MultiColor,PlatformCoin=1000,},
  [9]={BaseID=9,ItemType=ItemTypeDetail.ItemType_RolePieces,Rank=RankType.RT_ThirdGearDarkGolden,PlatformCoin=1000,},
  [10]={BaseID=10,ItemType=ItemTypeDetail.ItemType_PetPieces,Rank=RankType.RT_White,PlatformCoin=12,},
  [11]={BaseID=11,ItemType=ItemTypeDetail.ItemType_PetPieces,Rank=RankType.RT_Green,PlatformCoin=24,},
  [12]={BaseID=12,ItemType=ItemTypeDetail.ItemType_PetPieces,Rank=RankType.RT_Blue,PlatformCoin=60,},
  [13]={BaseID=13,ItemType=ItemTypeDetail.ItemType_PetPieces,Rank=RankType.RT_Purple,PlatformCoin=100,},
  [14]={BaseID=14,ItemType=ItemTypeDetail.ItemType_PetPieces,Rank=RankType.RT_Orange,PlatformCoin=160,},
  [15]={BaseID=15,ItemType=ItemTypeDetail.ItemType_PetPieces,Rank=RankType.RT_Golden,PlatformCoin=240,},
  [16]={BaseID=16,ItemType=ItemTypeDetail.ItemType_PetPieces,Rank=RankType.RT_DarkGolden,PlatformCoin=400,},
  [17]={BaseID=17,ItemType=ItemTypeDetail.ItemType_PetPieces,Rank=RankType.RT_MultiColor,PlatformCoin=400,},
  [18]={BaseID=18,ItemType=ItemTypeDetail.ItemType_PetPieces,Rank=RankType.RT_ThirdGearDarkGolden,PlatformCoin=400,},
}

-- export table: ItemResolve
return ItemResolve
