-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum ItemTypeDetail
-- enum RankType
require("common");


local ItemRecycleExp= {
  [1]={BaseID=1,RecycleType=ItemTypeDetail.ItemType_Equipment,ItemRank={RankType.RT_White,RankType.RT_Green,RankType.RT_Blue,RankType.RT_Purple,RankType.RT_Orange,RankType.RT_Golden,RankType.RT_DarkGolden,RankType.RT_MultiColor,RankType.RT_ThirdGearDarkGolden,},RecycleExp={6,8,12,18,30,50,100,100,100,},},
  [2]={BaseID=2,RecycleType=ItemTypeDetail.ItemType_Consume,ItemRank={RankType.RT_White,RankType.RT_Green,RankType.RT_Blue,RankType.RT_Purple,RankType.RT_Orange,RankType.RT_Golden,RankType.RT_DarkGolden,RankType.RT_MultiColor,RankType.RT_ThirdGearDarkGolden,},RecycleExp={4,6,8,12,18,30,50,50,50,},},
  [3]={BaseID=3,RecycleType=ItemTypeDetail.ItemType_Material,ItemRank={RankType.RT_White,RankType.RT_Green,RankType.RT_Blue,RankType.RT_Purple,RankType.RT_Orange,RankType.RT_Golden,RankType.RT_DarkGolden,RankType.RT_MultiColor,RankType.RT_ThirdGearDarkGolden,},RecycleExp={4,6,8,12,18,30,50,50,50,},},
  [4]={BaseID=4,RecycleType=ItemTypeDetail.ItemType_Book,ItemRank={RankType.RT_White,RankType.RT_Green,RankType.RT_Blue,RankType.RT_Purple,RankType.RT_Orange,RankType.RT_Golden,RankType.RT_DarkGolden,RankType.RT_MultiColor,RankType.RT_ThirdGearDarkGolden,},RecycleExp={10,12,16,24,40,70,140,140,140,},},
}

-- export table: ItemRecycleExp
return ItemRecycleExp
