-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [1005623001]="大地图据点-{目标地图(Int)}",
  [1005623002]="{ID数值1}",
  [1005623003]="{ID数值1}",
  [1005623004]="{ID数值1}",
}

-- export table: Language
return Language
