-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [1107060001]="前方就是花圃的出口，我应该……",
  [1107060002]="离开迷宫",
  [1107060003]="绕道而行",
}

-- export table: Language
return Language
