-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [1103860001]="【无】门派-长生门炼药炉",
  [1103861001]="【无】门派-通用门派玩法",
  [1103862001]="【无】门派-五毒教炼制毒药",
  [1103862002]="【五毒教】炼制毒药",
}

-- export table: Language
return Language
