-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [1005779001]="宝箱放置动态任务-{所在建筑(Int)}-{所在建筑(Language)[Map.NameID]}",
}

-- export table: Language
return Language
