-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [1003930001]="师傅教导我前往世界各地寻找画的真谛，但是我该从哪里开始寻找呢？如果这时候有个队友能帮助我一下就好了……",
  [1003930002]="我要回忆哪段剧情呢？",
  [1003930003]="前往开封回忆故事",
  [1003930004]="前往杭州回忆故事",
  [1003930005]="前往逍遥仙宫回忆故事",
}

-- export table: Language
return Language
