-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [1103533001]="【无】大决战-邪线-三层退出监听",
  [1103533002]="眼下攻占此处主城，是否要继续前进挑战4层的大将？\n<color=#dd0f0f>一旦退出将直接攻占该主城，无法再进入</color>",
  [1103533003]="离开此地",
  [1103533004]="离开此地",
  [1103539001]="【无】天阴教-天阴教任务监听",
}

-- export table: Language
return Language
