-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [710001]="擂台系统已部分开启，周一至周五开启少年赛、大众赛。暂不开启大师赛、门派赛、华山论剑。\r\n    装备强化等级限制：<color=red>10</color>\r\n    武学等级上限：<color=red>25</color>\r\n    角色修行上限：<color=red>5</color>\r\n    宠物修行上限：<color=red>5</color>",
  [710002]="擂台系统已部分开启，周一至周五开启少年赛、大众赛，周六大师赛。下周将开启门派赛、华山论剑。\r\n    装备强化等级限制：<color=red>10</color>\r\n    武学等级上限：<color=red>25</color>\r\n    角色修行上限：<color=red>5</color>\r\n    宠物修行上限：<color=red>5</color>",
  [710003]="擂台系统已全部开启，周一至周五少年赛、大众赛，周六大师赛，周日门派赛，每隔三周的周日华山论剑。\r\n    装备强化等级限制：<color=red>15</color>\r\n    武学等级上限：<color=red>28</color>\r\n    角色修行上限：<color=red>8</color>\r\n    宠物修行上限：<color=red>8</color>",
  [710004]="擂台系统已全部开启，周一至周五少年赛、大众赛，周六大师赛，周日门派赛，每隔三周的周日华山论剑。\r\n    装备强化等级限制：<color=red>20</color>\r\n    武学等级上限：<color=red>30</color>\r\n    角色修行上限：<color=red>10</color>\r\n    宠物修行上限：<color=red>10</color>",
}

-- export table: Language
return Language
