-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [1107127001]="当前融合吸能属性：{ID数值1(AttrType)}+{int数值1(Int)}\n是否替换为：{ID数值2(AttrType)}+{int数值2(Int)}",
  [1107127002]="是",
  [1107127003]="否",
  [1107127004]="当前融合吸能属性：无\n是否替换为：{ID数值2(AttrType)}+{int数值2(Int)}",
  [1107127005]="修为已消散",
  [1107127006]="修为已消散",
}

-- export table: Language
return Language
