-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [1105260001]="漫画收藏《角色扮演5》已解锁",
  [1105261001]="漫画收藏《角色扮演6》已解锁",
  [1105262001]="漫画收藏《角色扮演7》已解锁",
  [1105263001]="漫画收藏《角色扮演8》已解锁",
}

-- export table: Language
return Language
