-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [1005463001]="你跟着段康在这三天一直忙前忙后，部署人手安插在大理居民区，同时查找线索想要揪出这些隐藏在市井之中的匪徒。",
}

-- export table: Language
return Language
