-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [300001]="平凡易容",
  [300002]="武锋",
  [300003]="广州邪线",
  [300004]="丐帮弟子",
  [300005]="欧阳七",
  [300006]="韦大宝",
  [300007]="平凡",
  [300008]="淑芬",
  [300009]="秦忠贤",
  [300010]="真人阿月",
  [300011]="真人哈斯娜",
}

-- export table: Language
return Language
