-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [1005916001]="与你誓约后，阿月换上了新娘装扮",
  [1005918001]="沿着这条道路可以前往洞穴深处，一旦前进便无法回头——",
  [1005918002]="前往洞穴深处",
  [1005918003]="绕道而行",
  [1005918004]="离开",
  [1005918005]="挖宝洞穴迷宫楼梯",
}

-- export table: Language
return Language
