-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [1103954001]="【无】任务通用功能-周目结局",
  [1103958001]="【无】玄机门_奇门遁甲",
  [1103958002]="我要干什么？",
  [1103958003]="查看石碑上的字",
  [1103958004]="从这里进入下一层",
  [1103959001]="【无】玄机门_开启奇门遁甲",
}

-- export table: Language
return Language
