-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [290001]="外功",
  [290002]="拳掌",
  [290003]="剑法",
  [290004]="刀法",
  [290005]="腿法",
  [290006]="暗器",
  [290007]="奇门",
  [290008]="内功",
  [290009]="轻功",
  [290010]="医术",
  [290011]="所有",
  [290012]="阵法",
  [290013]="登场技",
}

-- export table: Language
return Language
