-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [1004299001]="<IF-门派-SHOW-【{门派(Language)[Clan.NameID]}】><IF-委托城市-SHOW-【{委托城市(Language)[City.NameID]}】>{发布角色(Language)[Role.NameID]}托你去寻找{目标物品(Language)[Item.ItemName]}或对应的原料",
  [1004299002]="你帮助{发布角色(Language)[Role.NameID]}找到了{目标物品(Language)[Item.ItemName]}，得到了他的感激",
  [1004299004]="你帮助{发布角色(Language)[Role.NameID]}找到了配方所需的原料，得到了他的感激",
}

-- export table: Language
return Language
