-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [1005260001]="使用效果-角色扮演5",
  [1005261001]="使用效果-角色扮演6",
  [1005262001]="使用效果-角色扮演7",
  [1005263001]="使用效果-角色扮演8",
}

-- export table: Language
return Language
