-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [1103937001]="【无】仁义值系统_黑市商人",
  [1103937002]="黑市商人",
  [1103937003]="绕道而行",
  [1103938001]="【无】任务_主线_迷宫_宇文庄密室_楼梯1",
  [1103938002]="木质的地板上有个无法绕过的破洞，穿过破洞可以前往密室更深处。",
  [1103938003]="前往密室{目标楼层(Int)}层",
  [1103938004]="离开",
}

-- export table: Language
return Language
