-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [3610001]="天龙寺",
  [3610002]="清凉寺",
  [3610003]="灵隐寺",
  [3610004]="南华寺",
  [3610005]="少林寺",
}

-- export table: Language
return Language
