-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [2320001]="<color=#080a0c>提高全属性30点</color>",
  [2320002]="<color=#080a0c>提高全精通30点</color>",
}

-- export table: Language
return Language
