-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [1005032001]="誓约结束",
  [1005032002]="在进行誓约结义后，你的誓约、结义对象将会进入你的替补列表。在布阵界面可以更换当前的战斗替补。",
  [1005032003]="设置替补后，在战斗中退场时，替补角色将会代替你继续出战。此功能一场战斗只能触发一次。",
}

-- export table: Language
return Language
