-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [1103749001]="【无】长生门-闲聊及功能",
  [1103749002]="学习长生门武学",
  [1103749003]="关于长生门的过去",
  [1103749004]="关于长生门剑法",
  [1103749005]="关于医术",
  [1103749006]="关于丹药",
}

-- export table: Language
return Language
