-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [1005082001]="你选择为了自己的野心加入白衣教，接下来便是你大展宏图的时间！",
  [1005088001]="时间已到，但是你未能完成流浪军师秃鹰的任务，返回无量山看看情况吧。",
}

-- export table: Language
return Language
