-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [1104240001]="【{征服门派[Clan.NameID]}】废墟监听",
  [1104240002]="此处已是一片废墟。",
  [1104241001]="【无】任务占位1309！去表格占了再用",
}

-- export table: Language
return Language
