-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [120001]="天命之人",
  [120002]="不羁之人",
  [120003]="降龙勇士",
  [120004]="素心玉女",
  [120005]="#N/A",
  [120006]="#N/A",
  [120007]="云鬓销魂",
  [120008]="#N/A",
  [120009]="武媚之人",
  [120010]="如意之人",
  [120011]="何亭云",
  [120012]="徒弟",
  [120013]="徒弟",
}

-- export table: Language
return Language
