-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [1004332002]="<IF-门派-SHOW-【{门派(Language)[Clan.NameID]}】><IF-委托城市-SHOW-【{委托城市(Language)[City.NameID]}】>{发布角色(Language)[Role.NameID]}托你去给特定人物送信",
  [1004332003]="你帮助{发布角色(Language)[Role.NameID]}送了信，完美的完成了任务",
  [1004333001]="你帮助{发布角色(Language)[Role.NameID]}在迷宫中找到了他渴求的物品，成功的完成了任务",
  [1004333002]="<IF-门派-SHOW-【{门派(Language)[Clan.NameID]}】><IF-委托城市-SHOW-【{委托城市(Language)[City.NameID]}】>{发布角色(Language)[Role.NameID]}希望与你前往迷宫寻找物品",
}

-- export table: Language
return Language
