-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [1005065001]="逼迫退隐",
  [1005065002]="对方无法退隐",
  [1005065003]="未掌握决斗",
  [1005065004]="逼迫退隐",
  [1005065005]="这东西给你，你饶了我吧……",
}

-- export table: Language
return Language
