-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [1003860001]="你是何人？不许随便用我长生门的炼丹炉！",
  [1003860002]="至少要将长生门的好感度提升到<color=#dd0f0f>20</color>才能来这炼制丹药吗……",
  [1003862001]="元奇峰瞟了你一眼后就不再搭理你了。",
  [1003862002]="至少要将五毒教的好感度提升到40才能来这炼制毒药吗……",
}

-- export table: Language
return Language
