-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [1005188001]="在庄园深处有一个不显眼密道，不知通往何处——",
  [1005188003]="绕道而行",
  [1005188004]="离开",
  [1005188005]="进入密道(推进剧情)",
}

-- export table: Language
return Language
