-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [1104708001]="薛蔓闲聊任务",
  [1104708002]="可以和薛蔓聊聊",
  [1104708003]="闲聊",
}

-- export table: Language
return Language
