-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [1104158001]="【无】任务占位1226！去表格占了再用",
  [1104159001]="【无】任务占位1227！去表格占了再用",
}

-- export table: Language
return Language
