-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local LetterTaskConfig= {
  [1]={BaseID=1,LetterTaskStartTaskID=4404,},
}

-- export table: LetterTaskConfig
return LetterTaskConfig
