-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local MapEffectDefault = {Material="",UIName="",}
local MapEffect= {
  [1]={BaseID=1,Prefab="UI/UIPrefabs/EffectUI/MapEffect_Fire",BackgroundPrefab="UI/UIPrefabs/EffectUI/MapEffect_FireBG",},
  [2]={BaseID=2,Prefab="",UIName="MemoriesUI",BackgroundPrefab="",},
  [3]={BaseID=3,Prefab="",BackgroundPrefab="",},
  [4]={BaseID=4,Prefab="weather/Packer/windPacker",BackgroundPrefab="weather/Packer/wind_hPacker",},
  [5]={BaseID=5,Prefab="weather/Packer/mistyPacker",BackgroundPrefab="weather/Packer/misty_hPacker",},
  [6]={BaseID=6,Prefab="weather/Packer/rainPacker",BackgroundPrefab="weather/Packer/rain—mistyPacker",},
  [7]={BaseID=7,Prefab="weather/Packer/thunderRainPacker",BackgroundPrefab="weather/Packer/thunderPacker",},
  [8]={BaseID=8,Prefab="weather/Packer/snowPacker",BackgroundPrefab="weather/Packer/white-mistyPacker",},
}
for k,v in pairs(MapEffect) do
    setmetatable(v, {['__index'] = MapEffectDefault})
end

-- export table: MapEffect
return MapEffect
