-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local MapPoem= {
  [169]={BaseID=169,MapID=169,TitleID=385,Poem1ID=386,Poem2ID=387,},
  [209]={BaseID=209,MapID=209,TitleID=394,Poem1ID=395,Poem2ID=396,},
  [995]={BaseID=995,MapID=995,TitleID=388,Poem1ID=389,Poem2ID=390,},
  [1096]={BaseID=1096,MapID=1096,TitleID=397,Poem1ID=398,Poem2ID=399,},
  [1334]={BaseID=1334,MapID=1334,TitleID=391,Poem1ID=392,Poem2ID=393,},
}

-- export table: MapPoem
return MapPoem
