-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum RankType
-- enum MartialRemainsRank
require("common");


local MartialRemainsConvertConfig= {
  [1]={BaseID=1,InCompleteBookRank=RankType.RT_White,RemainsQuality=MartialRemainsRank.MRR_LOW,ConvertNum=1,},
  [2]={BaseID=2,InCompleteBookRank=RankType.RT_Green,RemainsQuality=MartialRemainsRank.MRR_LOW,ConvertNum=5,},
  [3]={BaseID=3,InCompleteBookRank=RankType.RT_Blue,RemainsQuality=MartialRemainsRank.MRR_LOW,ConvertNum=10,},
  [4]={BaseID=4,InCompleteBookRank=RankType.RT_Purple,RemainsQuality=MartialRemainsRank.MRR_LOW,ConvertNum=15,},
  [5]={BaseID=5,InCompleteBookRank=RankType.RT_Orange,RemainsQuality=MartialRemainsRank.MRR_LOW,ConvertNum=25,},
  [6]={BaseID=6,InCompleteBookRank=RankType.RT_Golden,RemainsQuality=MartialRemainsRank.MRR_LOW,ConvertNum=35,},
  [7]={BaseID=7,InCompleteBookRank=RankType.RT_DarkGolden,RemainsQuality=MartialRemainsRank.MRR_LOW,ConvertNum=50,},
}

-- export table: MartialRemainsConvertConfig
return MartialRemainsConvertConfig
