-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum DepartEnumType
-- enum AttrType
require("common");


local MartialExtExpRelation= {
  [1]={BaseID=1,DepartEnum=DepartEnumType.DET_Boxing,AttrTypeArr={AttrType.ATTR_LIDAO,AttrType.ATTR_QUANZHANGJINGTONG,},},
  [2]={BaseID=2,DepartEnum=DepartEnumType.DET_SwordMethod,AttrTypeArr={AttrType.ATTR_LINGQIAO,AttrType.ATTR_JIANFAJINGTONG,},},
  [3]={BaseID=3,DepartEnum=DepartEnumType.DET_KnifeMethod,AttrTypeArr={AttrType.ATTR_LIDAO,AttrType.ATTR_DAOFAJINGTONG,},},
  [4]={BaseID=4,DepartEnum=DepartEnumType.DET_LegMethod,AttrTypeArr={AttrType.ATTR_LINGQIAO,AttrType.ATTR_TUIFAJINGTONG,},},
  [5]={BaseID=5,DepartEnum=DepartEnumType.DET_QiMen,AttrTypeArr={AttrType.ATTR_NEIJIN,AttrType.ATTR_QIMENJINGTONG,},},
  [6]={BaseID=6,DepartEnum=DepartEnumType.DET_HiddenWeapon,AttrTypeArr={AttrType.ATTR_NEIJIN,AttrType.ATTR_ANQIJINGTONG,},},
  [7]={BaseID=7,DepartEnum=DepartEnumType.DET_Soul,AttrTypeArr={AttrType.ATTR_NEIJIN,AttrType.ATTR_NEIGONGJINGTONG,},},
  [8]={BaseID=8,DepartEnum=DepartEnumType.DET_MedicalSkill,AttrTypeArr={AttrType.ATTR_NEIJIN,AttrType.ATTR_YISHUJINGTONG,},},
  [9]={BaseID=9,DepartEnum=DepartEnumType.DET_Fly,AttrTypeArr={AttrType.ATTR_SUDUZHI,},},
  [10]={BaseID=10,DepartEnum=DepartEnumType.DET_ZhenFa,AttrTypeArr={AttrType.ATTR_JINGLI,},},
}

-- export table: MartialExtExpRelation
return MartialExtExpRelation
