-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum DepartEnumType
require("common");


local MartialUnlockAttr= {
  [1]={BaseID=1,DepartEnum=DepartEnumType.DET_Boxing,Factor=10000,},
  [2]={BaseID=2,DepartEnum=DepartEnumType.DET_SwordMethod,Factor=10000,},
  [3]={BaseID=3,DepartEnum=DepartEnumType.DET_KnifeMethod,Factor=10000,},
  [4]={BaseID=4,DepartEnum=DepartEnumType.DET_LegMethod,Factor=10000,},
  [5]={BaseID=5,DepartEnum=DepartEnumType.DET_QiMen,Factor=10000,},
  [6]={BaseID=6,DepartEnum=DepartEnumType.DET_HiddenWeapon,Factor=10000,},
  [7]={BaseID=7,DepartEnum=DepartEnumType.DET_Soul,Factor=10000,},
  [8]={BaseID=8,DepartEnum=DepartEnumType.DET_MedicalSkill,Factor=10000,},
  [9]={BaseID=9,DepartEnum=DepartEnumType.DET_MedicalAllSkill,Factor=10000,},
  [10]={BaseID=10,DepartEnum=DepartEnumType.DET_ExternalWork,Factor=10000,},
  [11]={BaseID=11,DepartEnum=DepartEnumType.DET_DuXi,Factor=10000,},
  [12]={BaseID=12,DepartEnum=DepartEnumType.DET_All,Factor=10000,},
}

-- export table: MartialUnlockAttr
return MartialUnlockAttr
