-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum DepartEnumType
-- enum AttrType
-- enum RankType
require("common");


local MartialBookCondition= {
  [1]={BaseID=1,MartialDepartment=DepartEnumType.DET_Boxing,Attributes=AttrType.ATTR_QUANZHANGJINGTONG,Rank={RankType.RT_White,RankType.RT_Green,RankType.RT_Blue,RankType.RT_Purple,RankType.RT_Orange,RankType.RT_Golden,RankType.RT_DarkGolden,RankType.RT_MultiColor,},Proficient={1,5,10,15,20,40,80,120,},},
  [2]={BaseID=2,MartialDepartment=DepartEnumType.DET_KnifeMethod,Attributes=AttrType.ATTR_DAOFAJINGTONG,Rank={RankType.RT_White,RankType.RT_Green,RankType.RT_Blue,RankType.RT_Purple,RankType.RT_Orange,RankType.RT_Golden,RankType.RT_DarkGolden,RankType.RT_MultiColor,},Proficient={1,5,10,15,20,40,80,121,},},
  [3]={BaseID=3,MartialDepartment=DepartEnumType.DET_LegMethod,Attributes=AttrType.ATTR_TUIFAJINGTONG,Rank={RankType.RT_White,RankType.RT_Green,RankType.RT_Blue,RankType.RT_Purple,RankType.RT_Orange,RankType.RT_Golden,RankType.RT_DarkGolden,RankType.RT_MultiColor,},Proficient={1,5,10,15,20,40,80,122,},},
  [4]={BaseID=4,MartialDepartment=DepartEnumType.DET_SwordMethod,Attributes=AttrType.ATTR_JIANFAJINGTONG,Rank={RankType.RT_White,RankType.RT_Green,RankType.RT_Blue,RankType.RT_Purple,RankType.RT_Orange,RankType.RT_Golden,RankType.RT_DarkGolden,RankType.RT_MultiColor,},Proficient={1,5,10,15,20,40,80,123,},},
  [5]={BaseID=5,MartialDepartment=DepartEnumType.DET_Soul,Attributes=AttrType.ATTR_NEIGONGJINGTONG,Rank={RankType.RT_White,RankType.RT_Green,RankType.RT_Blue,RankType.RT_Purple,RankType.RT_Orange,RankType.RT_Golden,RankType.RT_DarkGolden,RankType.RT_MultiColor,},Proficient={1,5,10,15,20,40,80,124,},},
  [6]={BaseID=6,MartialDepartment=DepartEnumType.DET_MedicalSkill,Attributes=AttrType.ATTR_YISHUJINGTONG,Rank={RankType.RT_White,RankType.RT_Green,RankType.RT_Blue,RankType.RT_Purple,RankType.RT_Orange,RankType.RT_Golden,RankType.RT_DarkGolden,RankType.RT_MultiColor,},Proficient={1,5,10,15,20,40,80,125,},},
  [7]={BaseID=7,MartialDepartment=DepartEnumType.DET_QiMen,Attributes=AttrType.ATTR_QIMENJINGTONG,Rank={RankType.RT_White,RankType.RT_Green,RankType.RT_Blue,RankType.RT_Purple,RankType.RT_Orange,RankType.RT_Golden,RankType.RT_DarkGolden,RankType.RT_MultiColor,},Proficient={1,5,10,15,20,40,80,126,},},
  [8]={BaseID=8,MartialDepartment=DepartEnumType.DET_HiddenWeapon,Attributes=AttrType.ATTR_ANQIJINGTONG,Rank={RankType.RT_White,RankType.RT_Green,RankType.RT_Blue,RankType.RT_Purple,RankType.RT_Orange,RankType.RT_Golden,RankType.RT_DarkGolden,RankType.RT_MultiColor,},Proficient={1,5,10,15,20,40,80,127,},},
  [9]={BaseID=9,MartialDepartment=DepartEnumType.DET_Fly,Attributes=AttrType.ATTR_SUDUZHI,Rank={RankType.RT_White,RankType.RT_Green,RankType.RT_Blue,RankType.RT_Purple,RankType.RT_Orange,RankType.RT_Golden,RankType.RT_DarkGolden,RankType.RT_MultiColor,},Speed={30,60,80,100,150,200,250,400,},},
}

-- export table: MartialBookCondition
return MartialBookCondition
