-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum RankType
-- enum TBoolean
require("common");


local MartialCD= {
  [1]={BaseID=1,MartialRank=RankType.RT_White,CDRound=0,IsCDInBattleRound=TBoolean.BOOL_YES,},
  [2]={BaseID=2,MartialRank=RankType.RT_Green,CDRound=0,IsCDInBattleRound=TBoolean.BOOL_YES,},
  [3]={BaseID=3,MartialRank=RankType.RT_Blue,CDRound=1,IsCDInBattleRound=TBoolean.BOOL_YES,},
  [4]={BaseID=4,MartialRank=RankType.RT_Purple,CDRound=2,IsCDInBattleRound=TBoolean.BOOL_YES,},
  [5]={BaseID=5,MartialRank=RankType.RT_Orange,CDRound=3,IsCDInBattleRound=TBoolean.BOOL_YES,},
  [6]={BaseID=6,MartialRank=RankType.RT_Golden,CDRound=4,IsCDInBattleRound=TBoolean.BOOL_YES,},
  [7]={BaseID=7,MartialRank=RankType.RT_DarkGolden,CDRound=5,IsCDInBattleRound=TBoolean.BOOL_YES,},
  [8]={BaseID=8,MartialRank=RankType.RT_MultiColor,CDRound=5,IsCDInBattleRound=TBoolean.BOOL_YES,},
  [9]={BaseID=9,MartialRank=RankType.RT_ThirdGearDarkGolden,CDRound=5,IsCDInBattleRound=TBoolean.BOOL_YES,},
}

-- export table: MartialCD
return MartialCD
