-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum RankType
-- enum MartialRemainsRank
require("common");


local MartialBreakRemainsConfig= {
  [1]={BaseID=1,MartialRank=RankType.RT_White,RemainsQuality=MartialRemainsRank.MRR_LOW,MartialLevel={21,22,23,24,25,26,27,28,29,30,},ConsumeNum={1,2,4,6,8,10,12,15,18,20,},},
  [2]={BaseID=2,MartialRank=RankType.RT_Green,RemainsQuality=MartialRemainsRank.MRR_LOW,MartialLevel={21,22,23,24,25,26,27,28,29,30,},ConsumeNum={5,10,20,30,40,50,60,75,90,100,},},
  [3]={BaseID=3,MartialRank=RankType.RT_Blue,RemainsQuality=MartialRemainsRank.MRR_LOW,MartialLevel={21,22,23,24,25,26,27,28,29,30,},ConsumeNum={10,20,40,60,80,100,120,150,180,200,},},
  [4]={BaseID=4,MartialRank=RankType.RT_Purple,RemainsQuality=MartialRemainsRank.MRR_LOW,MartialLevel={21,22,23,24,25,26,27,28,29,30,},ConsumeNum={15,30,60,90,120,150,180,225,270,300,},},
  [5]={BaseID=5,MartialRank=RankType.RT_Orange,RemainsQuality=MartialRemainsRank.MRR_LOW,MartialLevel={21,22,23,24,25,26,27,28,29,30,},ConsumeNum={25,50,100,150,200,250,300,375,450,500,},},
  [6]={BaseID=6,MartialRank=RankType.RT_Golden,RemainsQuality=MartialRemainsRank.MRR_LOW,MartialLevel={21,22,23,24,25,26,27,28,29,30,},ConsumeNum={35,70,140,210,280,350,420,525,630,700,},},
  [7]={BaseID=7,MartialRank=RankType.RT_DarkGolden,RemainsQuality=MartialRemainsRank.MRR_LOW,MartialLevel={21,22,23,24,25,26,27,28,29,30,},ConsumeNum={50,100,200,300,400,500,600,750,900,1000,},},
}

-- export table: MartialBreakRemainsConfig
return MartialBreakRemainsConfig
