-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum RankType
require("common");


local MartialLimitUpExp= {
  [1]={BaseID=1,KungfuRank=RankType.RT_White,LevelLimit={21,22,23,24,25,},ExpCost={50,100,150,200,250,},Exp=5,},
  [2]={BaseID=2,KungfuRank=RankType.RT_Green,LevelLimit={21,22,23,24,25,},ExpCost={100,200,300,400,500,},Exp=10,},
  [3]={BaseID=3,KungfuRank=RankType.RT_Blue,LevelLimit={21,22,23,24,25,},ExpCost={200,400,600,800,1000,},Exp=20,},
  [4]={BaseID=4,KungfuRank=RankType.RT_Purple,LevelLimit={21,22,23,24,25,},ExpCost={500,1000,1500,2000,2500,},Exp=50,},
  [5]={BaseID=5,KungfuRank=RankType.RT_Orange,LevelLimit={21,22,23,24,25,},ExpCost={1000,2000,3000,4000,5000,},Exp=100,},
  [6]={BaseID=6,KungfuRank=RankType.RT_Golden,LevelLimit={21,22,23,24,25,},ExpCost={2000,4000,6000,8000,10000,},Exp=150,},
  [7]={BaseID=7,KungfuRank=RankType.RT_DarkGolden,LevelLimit={21,22,23,24,25,},ExpCost={5000,10000,15000,20000,25000,},Exp=200,},
}

-- export table: MartialLimitUpExp
return MartialLimitUpExp
