-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum DepartEnumType
require("common");


local MatGrowUPAttrDepart= {
  [1]={BaseID=1,DepartEnum=DepartEnumType.DET_Boxing,Factor=10000,},
  [2]={BaseID=2,DepartEnum=DepartEnumType.DET_SwordMethod,Factor=7000,},
  [3]={BaseID=3,DepartEnum=DepartEnumType.DET_KnifeMethod,Factor=6000,},
  [4]={BaseID=4,DepartEnum=DepartEnumType.DET_LegMethod,Factor=6000,},
  [5]={BaseID=5,DepartEnum=DepartEnumType.DET_QiMen,Factor=6000,},
  [6]={BaseID=6,DepartEnum=DepartEnumType.DET_HiddenWeapon,Factor=7000,},
  [7]={BaseID=7,DepartEnum=DepartEnumType.DET_Soul,Factor=10000,},
  [8]={BaseID=8,DepartEnum=DepartEnumType.DET_MedicalSkill,Factor=10000,},
}

-- export table: MatGrowUPAttrDepart
return MatGrowUPAttrDepart
