-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum AdventureType
require("common");


local MazeUnlockGiftConfigDefault = {ModelBehindPosX=0,ModelBehindPosY=0,ModelBehindScale=0,}
local MazeUnlockGiftConfig= {
  [1]={BaseID=1,UnlockGiftType=AdventureType.AT_SuiYan,TipText=2590001,UnlockDialogueList={2590002,2590003,2590004,2590005,},UnlockResultText=2590006,UnlockChoiceText=2590007,},
  [2]={BaseID=2,UnlockGiftType=AdventureType.AT_TenKong,TipText=2590008,UnlockDialogueList={2590009,2590010,2590011,2590012,},UnlockResultText=2590013,UnlockChoiceText=2590014,},
  [3]={BaseID=3,UnlockGiftType=AdventureType.AT_BiQi,TipText=2590015,UnlockDialogueList={2590016,2590017,2590018,2590019,},UnlockResultText=2590020,UnlockChoiceText=2590021,},
  [4]={BaseID=4,UnlockGiftType=AdventureType.AT_BiDu,TipText=2590022,UnlockDialogueList={2590023,2590024,2590025,2590026,},UnlockResultText=2590027,UnlockChoiceText=2590028,},
  [5]={BaseID=5,UnlockGiftType=AdventureType.AT_JiGuan,TipText=2590029,UnlockDialogueList={2590030,2590031,2590032,2590033,},UnlockResultText=2590034,UnlockChoiceText=2590035,},
}
for k,v in pairs(MazeUnlockGiftConfig) do
    setmetatable(v, {['__index'] = MazeUnlockGiftConfigDefault})
end

-- export table: MazeUnlockGiftConfig
return MazeUnlockGiftConfig
