-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local MazeTaskConfig= {
  [1]={BaseID=1,MazeTaskStartTaskID=4338,MazeTaskRequireItemList={412302,413301,415301,411301,416301,414301,417301,420301,430301,440302,1004,1104,411501,412501,413501,414501,415501,416501,417501,420501,430503,440504,31052,31061,31451,31461,31072,31478,},},
}

-- export table: MazeTaskConfig
return MazeTaskConfig
