-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local MazeDes= {
  [3]={Maze=3,DesID=180064,},
  [4]={Maze=4,DesID=180066,},
  [8]={Maze=8,DesID=180065,},
  [9]={Maze=9,DesID=180062,},
  [10]={Maze=10,DesID=180067,},
  [11]={Maze=11,DesID=180061,},
  [12]={Maze=12,DesID=180068,},
  [13]={Maze=13,DesID=180063,},
  [14]={Maze=14,DesID=180060,},
  [17]={Maze=17,DesID=180072,},
  [21]={Maze=21,DesID=180071,},
  [28]={Maze=28,DesID=180073,},
  [40]={Maze=40,DesID=180070,},
  [41]={Maze=41,DesID=180069,},
}

-- export table: MazeDes
return MazeDes
