-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local MeridiansBreak= {
  [1]={BaseID=1,ItemCost=10,},
  [2]={BaseID=2,ItemCost=20,},
  [3]={BaseID=3,ItemCost=30,},
  [4]={BaseID=4,ItemCost=40,},
  [5]={BaseID=5,ItemCost=50,},
  [6]={BaseID=6,ItemCost=60,},
  [7]={BaseID=7,ItemCost=70,},
  [8]={BaseID=8,ItemCost=80,},
  [9]={BaseID=9,ItemCost=90,},
  [10]={BaseID=10,ItemCost=100,},
  [11]={BaseID=11,ItemCost=110,},
  [12]={BaseID=12,ItemCost=120,},
  [13]={BaseID=13,ItemCost=130,},
  [14]={BaseID=14,ItemCost=140,},
  [15]={BaseID=15,ItemCost=150,},
  [16]={BaseID=16,ItemCost=160,},
  [17]={BaseID=17,ItemCost=170,},
  [18]={BaseID=18,ItemCost=180,},
  [19]={BaseID=19,ItemCost=190,},
  [20]={BaseID=20,ItemCost=200,},
  [21]={BaseID=21,ItemCost=210,},
  [22]={BaseID=22,ItemCost=220,},
  [23]={BaseID=23,ItemCost=230,},
  [24]={BaseID=24,ItemCost=240,},
  [25]={BaseID=25,ItemCost=250,},
  [26]={BaseID=26,ItemCost=260,},
  [27]={BaseID=27,ItemCost=270,},
  [28]={BaseID=28,ItemCost=280,},
  [29]={BaseID=29,ItemCost=290,},
  [30]={BaseID=30,ItemCost=300,},
  [31]={BaseID=31,ItemCost=310,},
  [32]={BaseID=32,ItemCost=320,},
}

-- export table: MeridiansBreak
return MeridiansBreak
