-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Meridians= {
  [1]={BaseID=1,NameID=220001,DescID=220002,ShowArray=0,AcupointID={1,2,3,4,5,6,},Background="MeridianBG/meridian_img_person01",Stage={1,},BreakConsume={1,},BreakAddID=220048,BreakValue={1000,},UnlockDescID={0,220003,220004,220005,},},
  [2]={BaseID=2,NameID=220042,DescID=220043,ShowArray=1,AcupointID={11,12,13,14,15,16,17,18,},Background="MeridianBG/meridian_img_person02",Stage={2,},BreakConsume={1,},BreakAddID=220055,BreakValue={1000,},UnlockDescID={220044,220045,220046,220047,},},
  [3]={BaseID=3,NameID=220006,DescID=220007,ShowArray=2,AcupointID={21,22,23,24,25,},Background="MeridianBG/meridian_img_person03",Stage={3,},BreakConsume={1,},BreakAddID=220049,BreakValue={1000,},UnlockDescID={220008,220009,220010,220011,},},
  [5]={BaseID=5,NameID=220036,DescID=220037,ShowArray=3,AcupointID={41,42,43,44,45,46,47,48,},Background="MeridianBG/meridian_img_person04",Stage={3,},BreakConsume={1,},BreakAddID=220054,BreakValue={1000,},UnlockDescID={220038,220039,220040,220041,},},
  [6]={BaseID=6,NameID=220030,DescID=220031,ShowArray=4,AcupointID={51,52,53,54,55,56,},Background="MeridianBG/meridian_img_person05",Stage={4,},BreakConsume={1,},BreakAddID=220053,BreakValue={1000,},UnlockDescID={220032,220033,220034,220035,},},
  [7]={BaseID=7,NameID=220024,DescID=220025,ShowArray=5,AcupointID={61,62,63,64,65,66,67,68,},Background="MeridianBG/meridian_img_person06",Stage={4,},BreakConsume={1,},BreakAddID=220052,BreakValue={1000,},UnlockDescID={220026,220027,220028,220029,},},
  [8]={BaseID=8,NameID=220018,DescID=220019,ShowArray=6,AcupointID={71,72,73,74,75,76,},Background="MeridianBG/meridian_img_person07",Stage={5,},BreakConsume={1,},BreakAddID=220051,BreakValue={1000,},UnlockDescID={220020,220021,220022,220023,},},
  [9]={BaseID=9,NameID=220012,DescID=220013,ShowArray=7,AcupointID={81,82,83,84,85,86,87,88,},Background="MeridianBG/meridian_img_person08",Stage={5,},BreakConsume={1,},BreakAddID=220050,BreakValue={1000,},UnlockDescID={220014,220015,220016,220017,},},
}

-- export table: Meridians
return Meridians
