-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local NewRound= {
  [1]={BaseID=1,PicID="GalleryCG/result_img_picture1",TipsID=520,},
  [2]={BaseID=2,PicID="GalleryCG/result_img_picture2",TipsID=521,},
  [3]={BaseID=3,PicID="GalleryCG/result_img_picture3",TipsID=522,},
  [4]={BaseID=4,PicID="GalleryCG/result_img_picture4",TipsID=523,},
  [5]={BaseID=5,PicID="GalleryCG/result_img_picture5",TipsID=524,},
  [6]={BaseID=6,PicID="GalleryCG/result_img_picture6",TipsID=525,},
}

-- export table: NewRound
return NewRound
