-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local NineSwordNum= {
  [1]={BaseID=1,Master=0,NumUp=3,SixVeinNumUp=6,SixVeinDamageAttenuation=0,},
  [2]={BaseID=2,Master=100,NumUp=4,SixVeinNumUp=9,SixVeinDamageAttenuation=5000,},
  [3]={BaseID=3,Master=200,NumUp=5,SixVeinNumUp=10,SixVeinDamageAttenuation=7500,},
  [4]={BaseID=4,Master=300,NumUp=6,SixVeinNumUp=11,SixVeinDamageAttenuation=8750,},
  [5]={BaseID=5,Master=400,NumUp=7,SixVeinNumUp=12,SixVeinDamageAttenuation=9000,},
  [6]={BaseID=6,Master=500,NumUp=8,SixVeinNumUp=13,SixVeinDamageAttenuation=9000,},
  [7]={BaseID=7,Master=600,NumUp=9,SixVeinNumUp=14,SixVeinDamageAttenuation=9000,},
  [8]={BaseID=8,Master=1000,NumUp=10,SixVeinNumUp=15,SixVeinDamageAttenuation=9000,},
  [9]={BaseID=9,Master=2000,NumUp=11,SixVeinNumUp=16,SixVeinDamageAttenuation=9000,},
  [10]={BaseID=10,Master=50000,NumUp=12,SixVeinNumUp=17,SixVeinDamageAttenuation=9000,},
  [11]={BaseID=11,Master=100000,NumUp=13,SixVeinNumUp=18,SixVeinDamageAttenuation=9000,},
  [12]={BaseID=12,Master=200000,NumUp=14,SixVeinNumUp=19,SixVeinDamageAttenuation=9000,},
  [13]={BaseID=13,Master=300000,NumUp=15,SixVeinNumUp=20,SixVeinDamageAttenuation=9000,},
  [14]={BaseID=14,Master=9999999,NumUp=16,SixVeinNumUp=21,SixVeinDamageAttenuation=9000,},
}

-- export table: NineSwordNum
return NineSwordNum
