-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local PetLevel= {
  [1]={level=1,Fragment=1,Fragment2=0,},
  [2]={level=2,Fragment=2,Fragment2=0,},
  [3]={level=3,Fragment=4,Fragment2=0,},
  [4]={level=4,Fragment=6,Fragment2=0,},
  [5]={level=5,Fragment=8,Fragment2=0,},
  [6]={level=6,Fragment=12,Fragment2=1,},
  [7]={level=7,Fragment=16,Fragment2=2,},
  [8]={level=8,Fragment=24,Fragment2=4,},
  [9]={level=9,Fragment=32,Fragment2=6,},
  [10]={level=10,Fragment=50,Fragment2=8,},
}

-- export table: PetLevel
return PetLevel
