-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local PKClanDefault = {BuffID=0,SkillTimes=0,RoleLevel=1,}
local PKClan= {
  [2]={ClanID=2,ClanMasterID=1040101001,DialogList={820021,820048,},SkillNameID=820030,SkillIcon="PKUI/img_pk_1",SkillDesID=820031,SkillProcess={0,},Weight=1200,EffectRoleList={4,15,52,14,65,111,121,133,134,100,150,148,149,191,},WeightProList={10,10,10,10,10,10,10,10,10,10,10,10,10,10,},RoleID=100,},
  [3]={ClanID=3,ClanMasterID=1140314003,DialogList={820022,},SkillNameID=820032,SkillIcon="PKUI/img_pk_8",SkillDesID=820033,BuffID=4376,SkillProcess={0,},Weight=1200,EffectRoleList={5,16,67,17,18,19,66,80,162,101,135,160,161,},WeightProList={10,10,10,10,10,10,10,10,10,10,10,10,10,},RoleID=135,},
  [4]={ClanID=4,ClanMasterID=1120301004,DialogList={820023,820049,},SkillNameID=820034,SkillIcon="PKUI/img_pk_4",SkillDesID=820035,SkillTimes=1,SkillProcess={0,1,0,},Weight=1000,EffectRoleList={6,20,21,22,23,24,25,73,50,60,76,81,98,122,159,158,157,187,},WeightProList={10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,},RoleID=158,},
  [8]={ClanID=8,ClanMasterID=1230301003,DialogList={820024,820050,},SkillNameID=820036,SkillIcon="PKUI/img_pk_5",SkillDesID=820037,SkillProcess={0,},Weight=1000,EffectRoleList={7,26,27,28,90,131,173,174,175,},WeightProList={10,10,10,10,10,10,10,10,10,},RoleID=173,RoleLevel=2,},
  [10]={ClanID=10,ClanMasterID=1150301016,DialogList={820025,},SkillNameID=820038,SkillIcon="PKUI/img_pk_6",SkillDesID=820039,SkillProcess={0,},Weight=1200,EffectRoleList={8,2,29,30,31,38,126,59,97,112,117,166,136,165,163,164,193,},WeightProList={10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,},RoleID=136,},
  [11]={ClanID=11,ClanMasterID=1170301005,DialogList={820026,820051,},SkillNameID=820040,SkillIcon="PKUI/img_pk_9",SkillDesID=820041,BuffID=4381,SkillProcess={0,},Weight=1000,EffectRoleList={9,32,33,34,49,128,48,62,70,96,137,167,168,170,186,},WeightProList={10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,},RoleID=137,},
  [12]={ClanID=12,ClanMasterID=1210314002,DialogList={820027,820052,},SkillNameID=820042,SkillIcon="PKUI/img_pk_3",SkillDesID=820043,BuffID=4380,SkillProcess={0,},Weight=800,EffectRoleList={11,41,64,39,40,74,84,141,140,142,172,118,171,169,184,},WeightProList={10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,},RoleID=142,},
  [15]={ClanID=15,ClanMasterID=1080314001,DialogList={820028,820053,},SkillNameID=820044,SkillIcon="PKUI/img_pk_7",SkillDesID=820045,BuffID=4378,SkillProcess={0,},Weight=800,EffectRoleList={13,12,1,43,44,45,42,143,144,145,146,147,154,155,156,188,},WeightProList={10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,},RoleID=147,},
  [63]={ClanID=63,ClanMasterID=1040301007,DialogList={820029,820054,},SkillNameID=820046,SkillIcon="PKUI/img_pk_2",SkillDesID=820047,SkillTimes=1,SkillProcess={1,1,1,},Weight=800,EffectRoleList={10,35,36,61,124,116,138,139,151,152,153,},WeightProList={10,10,10,10,10,10,10,10,10,10,10,},RoleID=139,},
}
for k,v in pairs(PKClan) do
    setmetatable(v, {['__index'] = PKClanDefault})
end

-- export table: PKClan
return PKClan
