-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum TBoolean
require("common");


local PKConfig= {
  [1]={BaseID=1,OpenTime={12,1,},NPCID=1000012015,NPCDesID=820004,RuleTitleID=820005,RuleDesID={820001,820002,820003,},UpdateTitleID=820006,UpdateDesID={820004,},PoolNum=32,TotalNum=64,PlayerNum=8,SelectRoleNum=4,SelectEquipNum=4,RefreshTimes=50,FreeTickets=3,TicketCost=1500,BegRate={2500,2500,2500,2500,},BuyPrice={1,2,3,5,8,12,20,},DialogRate=50,DialogMaxNum=3,JibanID=9681,JibanNum=10,JibanPrice=5,ForbidTicket=TBoolean.BOOL_NO,MinUnlockNum=30,ForbidSelectLock=TBoolean.BOOL_NO,ForbidMinUnlockNum=10,PreSelect=TBoolean.BOOL_YES,},
}

-- export table: PKConfig
return PKConfig
