-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local PKProcessDefault = {Time=90,Gold=0,RefreshTimes=10,}
local PKProcess= {
  [1]={BaseID=1,RoundID=1,NameID=820011,RefreshTimes=20,RateDescID=820061,},
  [2]={BaseID=2,RoundID=2,NameID=820012,Gold=5,RateDescID=820062,},
  [3]={BaseID=3,RoundID=3,NameID=820013,RateDescID=820063,},
  [4]={BaseID=4,RoundID=4,NameID=820014,Gold=5,RateDescID=820064,},
  [5]={BaseID=5,RoundID=5,NameID=820015,RateDescID=820065,},
  [6]={BaseID=6,RoundID=6,NameID=820016,Gold=5,RateDescID=820066,},
  [7]={BaseID=7,RoundID=7,NameID=820017,RateDescID=820067,},
  [8]={BaseID=8,RoundID=8,NameID=820018,RateDescID=820068,},
  [9]={BaseID=9,RoundID=9,NameID=820019,RateDescID=820069,},
  [10]={BaseID=10,RoundID=10,NameID=820020,RefreshTimes=0,RateDescID=0,},
}
for k,v in pairs(PKProcess) do
    setmetatable(v, {['__index'] = PKProcessDefault})
end

-- export table: PKProcess
return PKProcess
