-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local PKRole= {
  [1]={BaseID=1,RoleID=1080221003,DialogID=0,Weight32=1000,RoleNum32=6,Weight={1000,1000,1000,1000,1000,1000,1000,1000,1000,},Gift1=0,Gift2=0,Gift3=0,Gift4=0,Gift5=0,Gift6=0,Gift7=0,Gift8=0,Gift9=0,Gift10=0,Gift11=0,Gift12=0,},
}

-- export table: PKRole
return PKRole
