-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local PKRoleMainDefault = {BaseID=1,Weight=100,}
local PKRoleMain= {
  [65537]={MixLevel=1,RoleID=1320000001,Grade=0,TrueMixLevel=7,},
  [131073]={MixLevel=2,RoleID=1320000002,Grade=1,TrueMixLevel=8,},
  [196609]={MixLevel=3,RoleID=1320000003,Grade=2,TrueMixLevel=9,},
  [262145]={MixLevel=4,RoleID=1320000004,Grade=3,TrueMixLevel=10,},
  [327681]={MixLevel=5,RoleID=1320000005,Grade=4,TrueMixLevel=11,},
  [393217]={MixLevel=6,RoleID=1320000006,Grade=5,TrueMixLevel=12,},
}
for k,v in pairs(PKRoleMain) do
    setmetatable(v, {['__index'] = PKRoleMainDefault})
end

-- export table: PKRoleMain
return PKRoleMain
