-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum RankType
require("common");


local PKRoleColor= {
  [1]={BaseID=1,Rank=RankType.RT_DarkGolden,NumList={0,1,2,},WeightList={500,1000,500,},},
  [2]={BaseID=2,Rank=RankType.RT_Golden,NumList={0,1,2,},WeightList={500,1000,500,},},
  [3]={BaseID=3,Rank=RankType.RT_Orange,NumList={6,7,8,},WeightList={500,1000,500,},},
  [4]={BaseID=4,Rank=RankType.RT_Purple,NumList={6,7,8,},WeightList={500,1000,500,},},
  [5]={BaseID=5,Rank=RankType.RT_Blue,NumList={5,6,7,},WeightList={500,1000,500,},},
  [6]={BaseID=6,Rank=RankType.RT_Green,NumList={5,6,7,},WeightList={500,1000,500,},},
}

-- export table: PKRoleColor
return PKRoleColor
