-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum PlatBuffType
require("common");


local PlatBuff= {
  [1001]={BaseID=1001,BufType=PlatBuffType.PlatBuffType_BattleExp,Value1=500,Value2=0,Value3=0,Value4=0,Value5=0,},
  [1002]={BaseID=1002,BufType=PlatBuffType.PlatBuffType_BattleExp,Value1=500,Value2=0,Value3=0,Value4=0,Value5=0,},
}

-- export table: PlatBuff
return PlatBuff
