-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local PlayerAssetDefault = {AssetType=1,PagingID="asset",Window="",WindowPage=0,CommonFunctionID=0,}
local PlayerAsset= {
  [1]={BaseID=1,AssetID=1,AssetName="精铁",ItemID=30951,AssetKey="playerRefinedIron",CommonFunctionID=38,},
  [2]={BaseID=2,AssetID=2,AssetName="完美粉",ItemID=30941,AssetKey="playerPerfectPowder",CommonFunctionID=39,},
  [3]={BaseID=3,AssetID=3,AssetName="忘忧草",ItemID=9626,AssetKey="playerWangyoucao",CommonFunctionID=40,},
  [4]={BaseID=4,AssetID=4,AssetName="百宝书残页",ItemID=9660,AssetType=2,AssetKey="",},
  [5]={BaseID=5,AssetID=5,AssetName="活动积分",ItemID=9619,AssetKey="playerActiveScore",},
  [6]={BaseID=6,AssetID=6,AssetName="资源值",ItemID=9618,AssetKey="playerPlatScore",},
  [7]={BaseID=7,AssetID=7,AssetName="擂台币",ItemID=1302,AssetKey="playerDrinkMoney",},
  [8]={BaseID=8,AssetID=8,AssetName="大金币",ItemID=1701,AssetKey="playerSecondGold",},
  [9]={BaseID=9,AssetID=9,AssetName="小侠客",ItemID=1601,AssetType=3,AssetKey="",CommonFunctionID=41,},
  [10]={BaseID=10,AssetID=10,AssetName="经脉经验",ItemID=9616,AssetType=4,AssetKey="curTotalExp",},
  [11]={BaseID=11,AssetID=11,AssetName="经脉冲破丹",ItemID=9620,AssetType=4,AssetKey="curTotalBreak",},
  [12]={BaseID=12,AssetID=12,AssetName="低级武学残文",ItemID=1311,AssetKey="lowInCompleteTextNum",CommonFunctionID=33,},
  [13]={BaseID=13,AssetID=13,AssetName="中级武学残文",ItemID=1312,AssetKey="midInCompleteTextNum",CommonFunctionID=34,},
  [14]={BaseID=14,AssetID=14,AssetName="高级武学残文",ItemID=1313,AssetKey="highInCompleteTextNum",CommonFunctionID=35,},
  [15]={BaseID=15,AssetID=15,AssetName="刷新球",ItemID=9698,AssetKey="playerRefreshBall",CommonFunctionID=43,},
  [38]={BaseID=38,AssetID=38,AssetName="羁绊丹",ItemID=9681,AssetKey="iBondPellet",CommonFunctionID=201,},
  [39]={BaseID=39,AssetID=39,AssetName="空白秘籍",ItemID=9682,AssetKey="martialSecretBook",CommonFunctionID=45,},
  [42]={BaseID=42,AssetID=42,AssetName="天工锤",ItemID=30971,AssetKey="playerHeavenHammer",CommonFunctionID=37,},
  [43]={BaseID=43,AssetID=43,AssetName="金刚玉",ItemID=30953,AssetKey="playerTongLingYu",CommonFunctionID=238,},
}
for k,v in pairs(PlayerAsset) do
    setmetatable(v, {['__index'] = PlayerAssetDefault})
end

-- export table: PlayerAsset
return PlayerAsset
