-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum PlotType
require("common");


local PlotEnumDefault = {Param1Type="int",Param2Type="",Param2Name="",Param3Type="",Param3Name="",Param4Type="",Param4Name="",Param5Type="",Param5Name="",Param6Type="",Param6Name="",Param7Type="",Param7Name="",Param8Type="",Param8Name="",Param9Type="",Param9Name="",Param10Type="",Param10Name="",LangID=0,}
local PlotEnum= {
  [1]={BaseID=1,PlotTypeName=PlotType.PT_DIALOGUE,Param1Type="RoleTemplate",Param1Name="0角色",Param2Type="Language",Param2Name="1对话",Param3Type="StoryAction",Param3Name="2动画",Param4Type="StoryEffect",Param4Name="3效果",Param5Type="StoryMood",Param5Name="4表情",Param6Type="int",Param6Name="5语音",Param7Type="TBoolean",Param7Name="6隐藏模糊背景",Param8Type="int",Param8Name="7玩家ID",},
  [2]={BaseID=2,PlotTypeName=PlotType.PT_LINSHI_JUESE_DUIHUA,Param1Type="RoleTemplateModel",Param1Name="0模型",Param2Type="Language",Param2Name="1角色名",Param3Type="StoryAction",Param3Name="2动画",Param4Type="StoryEffect",Param4Name="3效果",Param5Type="StoryMood",Param5Name="4表情",Param6Type="int",Param6Name="5语音",Param7Type="TBoolean",Param7Name="6隐藏模糊背景",Param10Type="Language",Param10Name="2对话",},
  [3]={BaseID=3,PlotTypeName=PlotType.PT_SHOW_BLACK_BACKGROUND,Param1Name="0淡出时间",Param2Type="TBoolean",Param2Name="1等待淡出结束",},
  [4]={BaseID=4,PlotTypeName=PlotType.PT_HIDE_BLACK_BACKGROUND,Param1Name="0淡入时间",Param2Type="TBoolean",Param2Name="1等待淡入结束",},
  [5]={BaseID=5,PlotTypeName=PlotType.PT_WAIT,Param1Name="0等待时间",},
  [6]={BaseID=6,PlotTypeName=PlotType.PT_SHOW_IMG,Param1Name="0图片编号",Param2Type="ResourceCG",Param2Name="1图片文件",Param3Type="int",Param3Name="2X坐标",Param4Type="int",Param4Name="3Y坐标",Param5Type="int",Param5Name="4透明度",Param6Type="int",Param6Name="5缩放类型",},
  [7]={BaseID=7,PlotTypeName=PlotType.PT_MOVE_IMG,Param1Name="0图片编号",Param2Type="int",Param2Name="1X坐标",Param3Type="int",Param3Name="2Y坐标",Param4Type="int",Param4Name="3透明度",Param5Type="int",Param5Name="4移动时间",Param6Type="TBoolean",Param6Name="5等待移动结束",},
  [8]={BaseID=8,PlotTypeName=PlotType.PT_REMOVE_IMG,Param1Name="0图片编号",},
  [9]={BaseID=9,PlotTypeName=PlotType.PT_zhixing_yindao,Param1Type="String",Param1Name="0引导",Param2Type="TBoolean",Param2Name="1强制执行",},
  [10]={BaseID=10,PlotTypeName=PlotType.PT_TOAST,Param1Type="Language",Param1Name="1内容",Param2Type="TBoolean",Param2Name="记录到聊天框",},
  [11]={BaseID=11,PlotTypeName=PlotType.PT_SHOW_LOG,Param1Type="String",Param1Name="1内容",},
  [12]={BaseID=12,PlotTypeName=PlotType.PT_ADD_DANMU,Param1Type="Language",Param1Name="内容",},
  [13]={BaseID=13,PlotTypeName=PlotType.PT_SHOW_BUBBLE,Param1Type="RoleTemplate",Param1Name="角色ID",Param2Type="String",Param2Name="内容",Param3Type="int",Param3Name="显示时间",},
  [14]={BaseID=14,PlotTypeName=PlotType.PT_OPEN_CLANMARTIAL,Param1Type="Clan",Param1Name="0门派",},
  [15]={BaseID=15,PlotTypeName=PlotType.PT_SHOW_ROLE_INTERACT_UI,Param1Type="RoleTemplate",Param1Name="0角色",Param2Type="Map",Param2Name="1地图",},
  [16]={BaseID=16,PlotTypeName=PlotType.PT_BATTLE_INSERT_ROUND_INFO,Param1Type="Language",Param1Name="内容",Param2Type="BattleRoundInfoType",Param2Name="显示类型",},
  [17]={BaseID=17,PlotTypeName=PlotType.PT_OPEN_INTERACT_LEARN,Param1Type="PlayerBehaviorType",Param1Name="0 类型",},
  [18]={BaseID=18,PlotTypeName=PlotType.PT_SHOW_CLAN_INFO,Param1Type="Clan",Param1Name="0门派",},
  [19]={BaseID=19,PlotTypeName=PlotType.PT_PLAY_SOUND,Param1Type="ResourceBGM",Param1Name="音效ID",},
  [20]={BaseID=20,PlotTypeName=PlotType.PT_MAZE_SHOW_BUBBLE,Param1Type="Language",Param1Name="0文本",Param2Type="RoleTemplate",Param2Name="1角色",},
  [21]={BaseID=21,PlotTypeName=PlotType.PT_OPEN_FINALBATTLE_EMBATTLE,Param1Type="TBoolean",Param1Name="1是否在据点中",Param2Type="FinalBattleCity",Param2Name="2据点ID",Param3Type="TBoolean",Param3Name="0魔君前布阵",},
  [22]={BaseID=22,PlotTypeName=PlotType.PT_CHANGE_SCRIPT,Param1Name="目标剧本ID",},
  [23]={BaseID=23,PlotTypeName=PlotType.PT_SET_TEMP_BACKGROUND,Param1Type="TBoolean",Param1Name="0大地图背景",Param2Type="Map",Param2Name="1地图背景",Param3Type="Maze",Param3Name="2迷宫背景",},
  [24]={BaseID=24,PlotTypeName=PlotType.PT_REMOVE_TEMP_BACKGROUND,Param1Type="",Param1Name="",},
  [25]={BaseID=25,PlotTypeName=PlotType.PLOT_BIGMAPMOVE_ENTERCITY,Param1Type="City",Param1Name="0起始据点",Param2Type="City",Param2Name="1目标据点",},
  [26]={BaseID=26,PlotTypeName=PlotType.PT_PLAY_AUDIO,Param1Name="0音乐ID",Param2Type="AudioType",Param2Name="1音乐类型",},
  [27]={BaseID=27,PlotTypeName=PlotType.PT_LUNJIAN,Param1Type="",Param1Name="",},
  [28]={BaseID=28,PlotTypeName=PlotType.PT_PLAY_MAP_ROLE_ANIM,Param1Type="Map",Param1Name="0地图建筑ID",Param2Type="RoleTemplate",Param2Name="1角色",Param3Type="SpineAnimType",Param3Name="2动画类型",},
  [29]={BaseID=29,PlotTypeName=PlotType.PT_PLAY_VOCAL,Param1Type="ResourceBGM",Param1Name="音效ID",},
  [30]={BaseID=30,PlotTypeName=PlotType.PT_CAMERA_ANIM,Param1Name="0座标X",Param2Type="int",Param2Name="1座标Y",Param3Type="int",Param3Name="2移动时间",Param4Type="int",Param4Name="3模式",},
}
for k,v in pairs(PlotEnum) do
    setmetatable(v, {['__index'] = PlotEnumDefault})
end

-- export table: PlotEnum
return PlotEnum
