-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum RankType
-- enum PlayerBehaviorType
require("common");


local ProbabilityDefault = {PlayerBehavior=PlayerBehaviorType.PBT_QingJiao,HaoGanLimit=0,IsLoverSuccPer=0,SuccHaoGanChange=0,FailHaoGanChange=0,SuccClanHaoGanChange=0,FailClanHaoGanChange=0,SuccShanEChange=0,FailShanEChange=0,}
local Probability= {
  [1]={BaseID=1,TargetRank=RankType.RT_White,HaoGanLimit=10,NotLoverSuccPer=10000,IsLoverSuccPer=10000,},
  [2]={BaseID=2,TargetRank=RankType.RT_Green,HaoGanLimit=20,NotLoverSuccPer=9000,IsLoverSuccPer=10000,},
  [3]={BaseID=3,TargetRank=RankType.RT_Blue,HaoGanLimit=40,NotLoverSuccPer=8000,IsLoverSuccPer=10000,},
  [4]={BaseID=4,TargetRank=RankType.RT_Purple,HaoGanLimit=60,NotLoverSuccPer=6000,IsLoverSuccPer=9000,},
  [5]={BaseID=5,TargetRank=RankType.RT_Orange,HaoGanLimit=80,NotLoverSuccPer=5000,IsLoverSuccPer=7000,},
  [6]={BaseID=6,TargetRank=RankType.RT_Golden,HaoGanLimit=90,NotLoverSuccPer=3500,IsLoverSuccPer=5000,},
  [7]={BaseID=7,TargetRank=RankType.RT_DarkGolden,HaoGanLimit=100,NotLoverSuccPer=2000,IsLoverSuccPer=3000,},
  [8]={BaseID=8,TargetRank=RankType.RT_MultiColor,HaoGanLimit=100,NotLoverSuccPer=2000,IsLoverSuccPer=3000,},
  [9]={BaseID=9,TargetRank=RankType.RT_ThirdGearDarkGolden,HaoGanLimit=100,NotLoverSuccPer=2000,IsLoverSuccPer=3000,},
  [10]={BaseID=10,TargetRank=RankType.RT_White,PlayerBehavior=PlayerBehaviorType.PBT_TouXue,NotLoverSuccPer=10000,SuccHaoGanChange=-5,FailHaoGanChange=-1,SuccClanHaoGanChange=-5,SuccShanEChange=-1,},
  [11]={BaseID=11,TargetRank=RankType.RT_Green,PlayerBehavior=PlayerBehaviorType.PBT_TouXue,NotLoverSuccPer=10000,SuccHaoGanChange=-8,FailHaoGanChange=-2,SuccClanHaoGanChange=-8,SuccShanEChange=-2,},
  [12]={BaseID=12,TargetRank=RankType.RT_Blue,PlayerBehavior=PlayerBehaviorType.PBT_TouXue,NotLoverSuccPer=8500,SuccHaoGanChange=-10,FailHaoGanChange=-3,SuccClanHaoGanChange=-10,SuccShanEChange=-4,},
  [13]={BaseID=13,TargetRank=RankType.RT_Purple,PlayerBehavior=PlayerBehaviorType.PBT_TouXue,NotLoverSuccPer=7000,SuccHaoGanChange=-20,FailHaoGanChange=-4,SuccClanHaoGanChange=-20,SuccShanEChange=-6,},
  [14]={BaseID=14,TargetRank=RankType.RT_Orange,PlayerBehavior=PlayerBehaviorType.PBT_TouXue,NotLoverSuccPer=6000,SuccHaoGanChange=-40,FailHaoGanChange=-5,SuccClanHaoGanChange=-40,SuccShanEChange=-8,},
  [15]={BaseID=15,TargetRank=RankType.RT_Golden,PlayerBehavior=PlayerBehaviorType.PBT_TouXue,NotLoverSuccPer=5000,SuccHaoGanChange=-60,FailHaoGanChange=-6,SuccClanHaoGanChange=-80,SuccShanEChange=-12,},
  [16]={BaseID=16,TargetRank=RankType.RT_DarkGolden,PlayerBehavior=PlayerBehaviorType.PBT_TouXue,NotLoverSuccPer=3000,SuccHaoGanChange=-90,FailHaoGanChange=-8,SuccClanHaoGanChange=-150,SuccShanEChange=-20,},
  [17]={BaseID=17,TargetRank=RankType.RT_MultiColor,PlayerBehavior=PlayerBehaviorType.PBT_TouXue,NotLoverSuccPer=3000,SuccHaoGanChange=-90,FailHaoGanChange=-8,SuccClanHaoGanChange=-150,SuccShanEChange=-20,},
  [18]={BaseID=18,TargetRank=RankType.RT_ThirdGearDarkGolden,PlayerBehavior=PlayerBehaviorType.PBT_TouXue,NotLoverSuccPer=3000,SuccHaoGanChange=-90,FailHaoGanChange=-8,SuccClanHaoGanChange=-150,SuccShanEChange=-20,},
}
for k,v in pairs(Probability) do
    setmetatable(v, {['__index'] = ProbabilityDefault})
end

-- export table: Probability
return Probability
