-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum RankType
-- enum DepartEnumType
require("common");


local RankSecretBookIconDefault = {Rank=RankType.RT_White,Kftype=DepartEnumType.DET_Boxing,}
local RankSecretBookIcon= {
  [1]={BaseID=1,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_0003",},
  [2]={BaseID=2,Kftype=DepartEnumType.DET_SwordMethod,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_0002",},
  [3]={BaseID=3,Kftype=DepartEnumType.DET_KnifeMethod,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_0001",},
  [4]={BaseID=4,Kftype=DepartEnumType.DET_LegMethod,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_0004",},
  [5]={BaseID=5,Kftype=DepartEnumType.DET_HiddenWeapon,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_0006",},
  [6]={BaseID=6,Kftype=DepartEnumType.DET_QiMen,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_0005",},
  [7]={BaseID=7,Kftype=DepartEnumType.DET_Soul,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_002c",},
  [8]={BaseID=8,Kftype=DepartEnumType.DET_Fly,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_0033",},
  [9]={BaseID=9,Kftype=DepartEnumType.DET_MedicalSkill,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_003a",},
  [10]={BaseID=10,Kftype=DepartEnumType.DET_ZhenFa,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_0040",},
  [11]={BaseID=11,Rank=RankType.RT_Green,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_0009",},
  [12]={BaseID=12,Rank=RankType.RT_Green,Kftype=DepartEnumType.DET_SwordMethod,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_0008",},
  [13]={BaseID=13,Rank=RankType.RT_Green,Kftype=DepartEnumType.DET_KnifeMethod,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_0007",},
  [14]={BaseID=14,Rank=RankType.RT_Green,Kftype=DepartEnumType.DET_LegMethod,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_000a",},
  [15]={BaseID=15,Rank=RankType.RT_Green,Kftype=DepartEnumType.DET_HiddenWeapon,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_000c",},
  [16]={BaseID=16,Rank=RankType.RT_Green,Kftype=DepartEnumType.DET_QiMen,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_000b",},
  [17]={BaseID=17,Rank=RankType.RT_Green,Kftype=DepartEnumType.DET_Soul,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_002d",},
  [18]={BaseID=18,Rank=RankType.RT_Green,Kftype=DepartEnumType.DET_Fly,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_0034",},
  [19]={BaseID=19,Rank=RankType.RT_Green,Kftype=DepartEnumType.DET_MedicalSkill,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_003b",},
  [20]={BaseID=20,Rank=RankType.RT_Green,Kftype=DepartEnumType.DET_ZhenFa,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_0041",},
  [21]={BaseID=21,Rank=RankType.RT_Blue,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_000f",},
  [22]={BaseID=22,Rank=RankType.RT_Blue,Kftype=DepartEnumType.DET_SwordMethod,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_000e",},
  [23]={BaseID=23,Rank=RankType.RT_Blue,Kftype=DepartEnumType.DET_KnifeMethod,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_000d",},
  [24]={BaseID=24,Rank=RankType.RT_Blue,Kftype=DepartEnumType.DET_LegMethod,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_0010",},
  [25]={BaseID=25,Rank=RankType.RT_Blue,Kftype=DepartEnumType.DET_HiddenWeapon,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_0012",},
  [26]={BaseID=26,Rank=RankType.RT_Blue,Kftype=DepartEnumType.DET_QiMen,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_0011",},
  [27]={BaseID=27,Rank=RankType.RT_Blue,Kftype=DepartEnumType.DET_Soul,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_002e",},
  [28]={BaseID=28,Rank=RankType.RT_Blue,Kftype=DepartEnumType.DET_Fly,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_0035",},
  [29]={BaseID=29,Rank=RankType.RT_Blue,Kftype=DepartEnumType.DET_MedicalSkill,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_003c",},
  [30]={BaseID=30,Rank=RankType.RT_Blue,Kftype=DepartEnumType.DET_ZhenFa,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_0042",},
  [31]={BaseID=31,Rank=RankType.RT_Purple,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_002b",},
  [32]={BaseID=32,Rank=RankType.RT_Purple,Kftype=DepartEnumType.DET_SwordMethod,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_0014",},
  [33]={BaseID=33,Rank=RankType.RT_Purple,Kftype=DepartEnumType.DET_KnifeMethod,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_0013",},
  [34]={BaseID=34,Rank=RankType.RT_Purple,Kftype=DepartEnumType.DET_LegMethod,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_0015",},
  [35]={BaseID=35,Rank=RankType.RT_Purple,Kftype=DepartEnumType.DET_HiddenWeapon,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_0017",},
  [36]={BaseID=36,Rank=RankType.RT_Purple,Kftype=DepartEnumType.DET_QiMen,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_0016",},
  [37]={BaseID=37,Rank=RankType.RT_Purple,Kftype=DepartEnumType.DET_Soul,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_002f",},
  [38]={BaseID=38,Rank=RankType.RT_Purple,Kftype=DepartEnumType.DET_Fly,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_0036",},
  [39]={BaseID=39,Rank=RankType.RT_Purple,Kftype=DepartEnumType.DET_MedicalSkill,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_003d",},
  [40]={BaseID=40,Rank=RankType.RT_Purple,Kftype=DepartEnumType.DET_ZhenFa,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_0043",},
  [41]={BaseID=41,Rank=RankType.RT_Orange,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_001a",},
  [42]={BaseID=42,Rank=RankType.RT_Orange,Kftype=DepartEnumType.DET_SwordMethod,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_0019",},
  [43]={BaseID=43,Rank=RankType.RT_Orange,Kftype=DepartEnumType.DET_KnifeMethod,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_0018",},
  [44]={BaseID=44,Rank=RankType.RT_Orange,Kftype=DepartEnumType.DET_LegMethod,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_001b",},
  [45]={BaseID=45,Rank=RankType.RT_Orange,Kftype=DepartEnumType.DET_HiddenWeapon,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_001d",},
  [46]={BaseID=46,Rank=RankType.RT_Orange,Kftype=DepartEnumType.DET_QiMen,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_001c",},
  [47]={BaseID=47,Rank=RankType.RT_Orange,Kftype=DepartEnumType.DET_Soul,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_0030",},
  [48]={BaseID=48,Rank=RankType.RT_Orange,Kftype=DepartEnumType.DET_Fly,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_0037",},
  [49]={BaseID=49,Rank=RankType.RT_Orange,Kftype=DepartEnumType.DET_MedicalSkill,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_0018",},
  [50]={BaseID=50,Rank=RankType.RT_Orange,Kftype=DepartEnumType.DET_ZhenFa,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_0044",},
  [51]={BaseID=51,Rank=RankType.RT_Golden,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_0020",},
  [52]={BaseID=52,Rank=RankType.RT_Golden,Kftype=DepartEnumType.DET_SwordMethod,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_001f",},
  [53]={BaseID=53,Rank=RankType.RT_Golden,Kftype=DepartEnumType.DET_KnifeMethod,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_001e",},
  [54]={BaseID=54,Rank=RankType.RT_Golden,Kftype=DepartEnumType.DET_LegMethod,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_0021",},
  [55]={BaseID=55,Rank=RankType.RT_Golden,Kftype=DepartEnumType.DET_HiddenWeapon,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_0023",},
  [56]={BaseID=56,Rank=RankType.RT_Golden,Kftype=DepartEnumType.DET_QiMen,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_0022",},
  [57]={BaseID=57,Rank=RankType.RT_Golden,Kftype=DepartEnumType.DET_Soul,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_0031",},
  [58]={BaseID=58,Rank=RankType.RT_Golden,Kftype=DepartEnumType.DET_Fly,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_0038",},
  [59]={BaseID=59,Rank=RankType.RT_Golden,Kftype=DepartEnumType.DET_MedicalSkill,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_003f",},
  [60]={BaseID=60,Rank=RankType.RT_Golden,Kftype=DepartEnumType.DET_ZhenFa,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_0045",},
  [61]={BaseID=61,Rank=RankType.RT_DarkGolden,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_0026",},
  [62]={BaseID=62,Rank=RankType.RT_DarkGolden,Kftype=DepartEnumType.DET_SwordMethod,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_0025",},
  [63]={BaseID=63,Rank=RankType.RT_DarkGolden,Kftype=DepartEnumType.DET_KnifeMethod,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_0024",},
  [64]={BaseID=64,Rank=RankType.RT_DarkGolden,Kftype=DepartEnumType.DET_LegMethod,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_0027",},
  [65]={BaseID=65,Rank=RankType.RT_DarkGolden,Kftype=DepartEnumType.DET_HiddenWeapon,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_0029",},
  [66]={BaseID=66,Rank=RankType.RT_DarkGolden,Kftype=DepartEnumType.DET_QiMen,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_0028",},
  [67]={BaseID=67,Rank=RankType.RT_DarkGolden,Kftype=DepartEnumType.DET_Soul,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_0032",},
  [68]={BaseID=68,Rank=RankType.RT_DarkGolden,Kftype=DepartEnumType.DET_Fly,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_0039",},
  [69]={BaseID=69,Rank=RankType.RT_DarkGolden,Kftype=DepartEnumType.DET_MedicalSkill,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_002a",},
  [70]={BaseID=70,Rank=RankType.RT_DarkGolden,Kftype=DepartEnumType.DET_ZhenFa,SecretBookIcon="ItemIcon/miji/icon_eauip_miji_0046",},
}
for k,v in pairs(RankSecretBookIcon) do
    setmetatable(v, {['__index'] = RankSecretBookIconDefault})
end

-- export table: RankSecretBookIcon
return RankSecretBookIcon
