-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local RankChangeRule= {
  [1]={BaseID=1,IsLike=3,IsGarbage=-20,IsSameClan=1,IsNormalPeople=1,IsDestroyClan=-2,},
}

-- export table: RankChangeRule
return RankChangeRule
