-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum RedPacketType
require("common");


local RedConfig= {
  [1001]={BaseID=1001,PacketType=RedPacketType.RPT_Money,MoneyNum=1000,MeridianExpNum=50000,PacketGroupID={1,2,3,4,5,},CostItemID=9649,},
  [1002]={BaseID=1002,PacketType=RedPacketType.RPT_Money,MoneyNum=5000,MeridianExpNum=250000,PacketGroupID={6,7,8,9,10,},CostItemID=9649,},
  [1003]={BaseID=1003,PacketType=RedPacketType.RPT_Money,MoneyNum=10000,MeridianExpNum=500000,PacketGroupID={11,12,13,14,15,},CostItemID=9649,},
  [2001]={BaseID=2001,PacketType=RedPacketType.RPT_Item,MoneyNum=1000,MeridianExpNum=50000,PacketGroupID={16,17,18,19,20,},CostItemID=9650,},
  [2002]={BaseID=2002,PacketType=RedPacketType.RPT_Item,MoneyNum=5000,MeridianExpNum=250000,PacketGroupID={21,22,23,24,25,},CostItemID=9650,},
  [2003]={BaseID=2003,PacketType=RedPacketType.RPT_Item,MoneyNum=10000,MeridianExpNum=500000,PacketGroupID={26,27,28,29,30,},CostItemID=9650,},
}

-- export table: RedConfig
return RedConfig
