-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local RedKnifeUpgrade= {
  [413103]={ItemID=413103,Cuilian=0,NextItemID=413203,},
  [413203]={ItemID=413203,Cuilian=5,NextItemID=413303,},
  [413303]={ItemID=413303,Cuilian=25,NextItemID=413403,},
  [413403]={ItemID=413403,Cuilian=100,NextItemID=413502,},
  [413502]={ItemID=413502,Cuilian=500,NextItemID=413605,},
  [413605]={ItemID=413605,Cuilian=1000,NextItemID=0,},
  [414405]={ItemID=414405,Cuilian=0,NextItemID=413203,},
}

-- export table: RedKnifeUpgrade
return RedKnifeUpgrade
