-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum ResDropActivityType
-- enum TBoolean
require("common");


local ResDropActivityDefault = {ActivityType=ResDropActivityType.RDAT_Collect,IsOpen=TBoolean.BOOL_YES,}
local ResDropActivity= {
  [10001]={BaseID=10001,NameID=751001,DescID=752001,StartDate={Year=2020,Month=10,Day=10,},Duration=604800,ActivityImg="ActivityWordCollection/img_ad_banner_001",DropConfig=10001,ExtraInfoGroup={101,102,103,104,105,106,107,108,109,110,0,},EnableScripts={2,6,},},
  [10002]={BaseID=10002,NameID=751002,DescID=752002,StartDate={Year=2020,Month=11,Day=6,},Duration=604800,ActivityImg="ActivityWordCollection/img_ad_banner_002",DropConfig=10002,ExtraInfoGroup={201,202,203,204,205,206,207,208,209,210,211,0,},EnableScripts={2,6,7,},},
  [10003]={BaseID=10003,NameID=751003,DescID=752003,StartDate={Year=2020,Month=11,Day=21,},Duration=604800,ActivityImg="ActivityWordCollection/img_ad_banner_003",DropConfig=10003,ExtraInfoGroup={301,302,303,304,305,306,307,308,309,310,0,},EnableScripts={2,6,7,},},
  [10004]={BaseID=10004,NameID=751004,DescID=752004,StartDate={Year=2020,Month=12,Day=11,},Duration=604740,ActivityImg="ActivityWordCollection/img_ad_banner_006",DropConfig=10004,ExtraInfoGroup={401,402,403,404,405,406,407,408,409,410,411,},EnableScripts={2,6,7,},},
  [10005]={BaseID=10005,NameID=751005,DescID=752005,StartDate={Year=2021,Month=1,Day=4,},Duration=604740,ActivityImg="ActivityWordCollection/img_ad_banner_008",DropConfig=10005,ExtraInfoGroup={501,502,503,504,505,506,507,508,509,510,511,},EnableScripts={2,6,7,},},
  [10006]={BaseID=10006,NameID=751006,DescID=752006,StartDate={Year=2021,Month=1,Day=21,},Duration=604740,ActivityImg="ActivityWordCollection/img_ad_banner_010",DropConfig=10006,ExtraInfoGroup={601,602,603,604,605,606,607,608,609,610,611,},EnableScripts={2,6,7,10,},},
  [20001]={BaseID=20001,ActivityType=ResDropActivityType.RDAT_MultDrop,NameID=1011951,DescID=1011951,StartDate={Year=2030,Month=12,Day=31,},Duration=108000,ActivityImg="CharacterCG/major/major_linghudage",DropConfig=20001,EnableScripts={2,6,7,},},
}
for k,v in pairs(ResDropActivity) do
    setmetatable(v, {['__index'] = ResDropActivityDefault})
end

-- export table: ResDropActivity
return ResDropActivity
