-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local ResourceVideo= {
  [1]={BaseID=1,Path="Video/Martials/TestMartialVD",},
  [2]={BaseID=2,Path="Video/Martials/10104",},
  [3]={BaseID=3,Path="Video/Martials/10110",},
  [4]={BaseID=4,Path="Video/Martials/10124",},
  [5]={BaseID=5,Path="Video/Martials/10306",},
  [6]={BaseID=6,Path="Video/Martials/10309",},
  [7]={BaseID=7,Path="Video/Martials/10325",},
  [8]={BaseID=8,Path="Video/Martials/10404",},
  [9]={BaseID=9,Path="Video/Martials/10419",},
  [10]={BaseID=10,Path="Video/Martials/10506",},
  [11]={BaseID=11,Path="Video/Martials/10510",},
  [12]={BaseID=12,Path="Video/Martials/10518",},
  [13]={BaseID=13,Path="Video/Martials/10603",},
  [14]={BaseID=14,Path="Video/Martials/10606",},
  [15]={BaseID=15,Path="Video/Martials/10611",},
  [16]={BaseID=16,Path="Video/Martials/10707",},
  [17]={BaseID=17,Path="Video/Martials/10710",},
  [18]={BaseID=18,Path="Video/Martials/11104",},
  [19]={BaseID=19,Path="Video/Martials/11106",},
  [20]={BaseID=20,Path="Video/Martials/11202",},
  [21]={BaseID=21,Path="Video/Martials/11203",},
  [22]={BaseID=22,Path="Video/Martials/11207",},
  [23]={BaseID=23,Path="Video/Martials/11909",},
  [24]={BaseID=24,Path="Video/Martials/11921",},
  [25]={BaseID=25,Path="Video/Martials/10426",},
  [26]={BaseID=26,Path="Video/Martials/11314",},
  [27]={BaseID=27,Path="Video/Martials/11311",},
  [28]={BaseID=28,Path="Video/Martials/11319",},
  [29]={BaseID=29,Path="Video/Martials/11615",},
  [30]={BaseID=30,Path="Video/Martials/11605",},
  [31]={BaseID=31,Path="Video/Martials/11614",},
  [32]={BaseID=32,Path="Video/Martials/11618",},
}

-- export table: ResourceVideo
return ResourceVideo
