-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local RiskGiftParam= {
  [1]={BaseID=1,FoodGiftPer=2000,CoinGiftMin=20,CoinGiftMax=30,GatherHerbsItem={0,31321,30221,30222,},GatherHerbsWeight={50,50,20,20,},MiningItem={0,30521,},MiningWeight={50,50,},},
  [2]={BaseID=2,FoodGiftPer=4000,CoinGiftMin=40,CoinGiftMax=60,GatherHerbsItem={0,31332,31321,30231,30232,},GatherHerbsWeight={30,30,40,15,15,},MiningItem={0,30531,30521,},MiningWeight={30,30,40,},},
  [3]={BaseID=3,FoodGiftPer=6000,CoinGiftMin=60,CoinGiftMax=90,GatherHerbsItem={0,31332,31321,31341,30241,30242,},GatherHerbsWeight={25,25,25,25,10,10,},MiningItem={0,30531,30521,30541,},MiningWeight={25,25,25,25,},},
  [4]={BaseID=4,FoodGiftPer=8000,CoinGiftMin=80,CoinGiftMax=120,GatherHerbsItem={0,31332,31341,31351,30241,30242,30251,},GatherHerbsWeight={25,25,25,25,10,10,10,},MiningItem={0,30531,30541,30551,},MiningWeight={25,25,25,25,},},
  [5]={BaseID=5,FoodGiftPer=10000,CoinGiftMin=100,CoinGiftMax=150,GatherHerbsItem={31332,31341,31351,30241,30242,30251,},GatherHerbsWeight={25,25,50,10,10,10,},MiningItem={30531,30541,30551,},MiningWeight={25,25,50,},},
}

-- export table: RiskGiftParam
return RiskGiftParam
