-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local RoleExtraGiftDefault = {White=2,Green=3,Blue=4,Purple=5,Orange=6,Golden=6,DarkGolden=7,JingliangDarkGolden=7,YouxiuDarkGolden=7,}
local RoleExtraGift= {
  [1]={BaseID=1,White=0,Green=0,Blue=0,Purple=1,Orange=1,Golden=1,DarkGolden=2,JingliangDarkGolden=2,YouxiuDarkGolden=2,},
  [2]={BaseID=2,White=0,Green=0,Blue=0,Purple=1,Orange=1,Golden=1,DarkGolden=2,JingliangDarkGolden=2,YouxiuDarkGolden=2,},
  [3]={BaseID=3,White=0,Green=0,Blue=0,Purple=1,Orange=1,Golden=1,DarkGolden=2,JingliangDarkGolden=2,YouxiuDarkGolden=2,},
  [4]={BaseID=4,White=0,Green=0,Blue=0,Purple=1,Orange=1,Golden=1,DarkGolden=2,JingliangDarkGolden=2,YouxiuDarkGolden=2,},
  [5]={BaseID=5,White=0,Green=0,Blue=0,Purple=1,Orange=1,Golden=1,DarkGolden=2,JingliangDarkGolden=2,YouxiuDarkGolden=2,},
  [6]={BaseID=6,White=0,Green=0,Blue=0,Purple=1,Orange=1,Golden=1,DarkGolden=2,JingliangDarkGolden=2,YouxiuDarkGolden=2,},
  [7]={BaseID=7,White=0,Green=0,Blue=0,Purple=1,Orange=1,Golden=1,DarkGolden=2,JingliangDarkGolden=2,YouxiuDarkGolden=2,},
  [8]={BaseID=8,White=0,Green=0,Blue=0,Purple=1,Orange=1,Golden=1,DarkGolden=2,JingliangDarkGolden=2,YouxiuDarkGolden=2,},
  [9]={BaseID=9,White=0,Green=0,Blue=0,Purple=1,Orange=1,Golden=1,DarkGolden=2,JingliangDarkGolden=2,YouxiuDarkGolden=2,},
  [10]={BaseID=10,White=0,Green=0,Blue=0,Purple=1,Orange=1,Golden=1,DarkGolden=2,JingliangDarkGolden=2,YouxiuDarkGolden=2,},
  [11]={BaseID=11,White=1,Green=1,Blue=2,Purple=2,Orange=2,Golden=3,DarkGolden=4,JingliangDarkGolden=4,YouxiuDarkGolden=4,},
  [12]={BaseID=12,White=1,Green=1,Blue=2,Purple=2,Orange=2,Golden=3,DarkGolden=4,JingliangDarkGolden=4,YouxiuDarkGolden=4,},
  [13]={BaseID=13,White=1,Green=1,Blue=2,Purple=2,Orange=2,Golden=3,DarkGolden=4,JingliangDarkGolden=4,YouxiuDarkGolden=4,},
  [14]={BaseID=14,White=1,Green=1,Blue=2,Purple=2,Orange=2,Golden=3,DarkGolden=4,JingliangDarkGolden=4,YouxiuDarkGolden=4,},
  [15]={BaseID=15,White=1,Green=1,Blue=2,Purple=2,Orange=2,Golden=3,DarkGolden=4,JingliangDarkGolden=4,YouxiuDarkGolden=4,},
  [16]={BaseID=16,White=1,Green=1,Blue=2,Purple=2,Orange=2,Golden=3,DarkGolden=4,JingliangDarkGolden=4,YouxiuDarkGolden=4,},
  [17]={BaseID=17,White=1,Green=1,Blue=2,Purple=2,Orange=2,Golden=3,DarkGolden=4,JingliangDarkGolden=4,YouxiuDarkGolden=4,},
  [18]={BaseID=18,White=1,Green=1,Blue=2,Purple=2,Orange=2,Golden=3,DarkGolden=4,JingliangDarkGolden=4,YouxiuDarkGolden=4,},
  [19]={BaseID=19,White=1,Green=1,Blue=2,Purple=2,Orange=2,Golden=3,DarkGolden=4,JingliangDarkGolden=4,YouxiuDarkGolden=4,},
  [20]={BaseID=20,White=1,Green=1,Blue=2,Purple=2,Orange=2,Golden=3,DarkGolden=4,JingliangDarkGolden=4,YouxiuDarkGolden=4,},
  [21]={BaseID=21,},
  [22]={BaseID=22,},
  [23]={BaseID=23,},
  [24]={BaseID=24,},
  [25]={BaseID=25,},
  [26]={BaseID=26,},
  [27]={BaseID=27,},
  [28]={BaseID=28,},
  [29]={BaseID=29,},
  [30]={BaseID=30,},
  [31]={BaseID=31,},
  [32]={BaseID=32,},
  [33]={BaseID=33,},
  [34]={BaseID=34,},
  [35]={BaseID=35,},
  [36]={BaseID=36,},
  [37]={BaseID=37,},
  [38]={BaseID=38,},
  [39]={BaseID=39,},
  [40]={BaseID=40,},
  [41]={BaseID=41,},
  [42]={BaseID=42,},
  [43]={BaseID=43,},
  [44]={BaseID=44,},
  [45]={BaseID=45,},
  [46]={BaseID=46,},
  [47]={BaseID=47,},
  [48]={BaseID=48,},
  [49]={BaseID=49,},
  [50]={BaseID=50,},
}
for k,v in pairs(RoleExtraGift) do
    setmetatable(v, {['__index'] = RoleExtraGiftDefault})
end

-- export table: RoleExtraGift
return RoleExtraGift
