-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum CreateFacePositionType
-- enum SexType
require("common");


local RoleFaceDefault= {
  [2]={BaseID=1,PositionType=CreateFacePositionType.CFPT_HAT,RoleFaceBaseID=1,SexLimit=SexType.ST_Male,},
  [1003]={BaseID=2,PositionType=CreateFacePositionType.CFPT_HAT,RoleFaceBaseID=1001,SexLimit=SexType.ST_Female,},
  [2006]={BaseID=3,PositionType=CreateFacePositionType.CFPT_HAIRFRONT,RoleFaceBaseID=2003,SexLimit=SexType.ST_Male,},
  [3012]={BaseID=4,PositionType=CreateFacePositionType.CFPT_HAIRFRONT,RoleFaceBaseID=3008,SexLimit=SexType.ST_Female,},
  [4006]={BaseID=5,PositionType=CreateFacePositionType.CFPT_HAIRBACK,RoleFaceBaseID=4001,SexLimit=SexType.ST_Male,},
  [5007]={BaseID=6,PositionType=CreateFacePositionType.CFPT_HAIRBACK,RoleFaceBaseID=5001,SexLimit=SexType.ST_Female,},
  [6010]={BaseID=9,PositionType=CreateFacePositionType.CFPT_FOREHEADADORNMENT,RoleFaceBaseID=6001,SexLimit=SexType.ST_Male,},
  [7011]={BaseID=10,PositionType=CreateFacePositionType.CFPT_FOREHEADADORNMENT,RoleFaceBaseID=7001,SexLimit=SexType.ST_Female,},
  [8012]={BaseID=11,PositionType=CreateFacePositionType.CFPT_FACIALADORNMENT,RoleFaceBaseID=8001,SexLimit=SexType.ST_Male,},
  [9013]={BaseID=12,PositionType=CreateFacePositionType.CFPT_FACIALADORNMENT,RoleFaceBaseID=9001,SexLimit=SexType.ST_Female,},
  [10016]={BaseID=15,PositionType=CreateFacePositionType.CFPT_BACK,RoleFaceBaseID=10001,SexLimit=SexType.ST_Male,},
  [11017]={BaseID=16,PositionType=CreateFacePositionType.CFPT_BACK,RoleFaceBaseID=11001,SexLimit=SexType.ST_Female,},
  [12018]={BaseID=13,PositionType=CreateFacePositionType.CFPT_BODY,RoleFaceBaseID=12005,SexLimit=SexType.ST_Male,},
  [15016]={BaseID=14,PositionType=CreateFacePositionType.CFPT_BODY,RoleFaceBaseID=15002,SexLimit=SexType.ST_Female,},
  [18018]={BaseID=7,PositionType=CreateFacePositionType.CFPT_FACE,RoleFaceBaseID=18011,SexLimit=SexType.ST_Male,},
  [18119]={BaseID=8,PositionType=CreateFacePositionType.CFPT_FACE,RoleFaceBaseID=18111,SexLimit=SexType.ST_Female,},
  [18219]={BaseID=17,PositionType=CreateFacePositionType.CFPT_EYEBROW,RoleFaceBaseID=18202,SexLimit=SexType.ST_Male,},
  [18320]={BaseID=18,PositionType=CreateFacePositionType.CFPT_EYEBROW,RoleFaceBaseID=18302,SexLimit=SexType.ST_Female,},
  [18424]={BaseID=19,PositionType=CreateFacePositionType.CFPT_EYE,RoleFaceBaseID=18405,SexLimit=SexType.ST_Male,},
  [18522]={BaseID=20,PositionType=CreateFacePositionType.CFPT_EYE,RoleFaceBaseID=18502,SexLimit=SexType.ST_Female,},
  [18625]={BaseID=21,PositionType=CreateFacePositionType.CFPT_MOUTH,RoleFaceBaseID=18604,SexLimit=SexType.ST_Male,},
  [18727]={BaseID=22,PositionType=CreateFacePositionType.CFPT_MOUTH,RoleFaceBaseID=18705,SexLimit=SexType.ST_Female,},
  [18825]={BaseID=23,PositionType=CreateFacePositionType.CFPT_NOSE,RoleFaceBaseID=18802,SexLimit=SexType.ST_Male,},
  [18926]={BaseID=24,PositionType=CreateFacePositionType.CFPT_NOSE,RoleFaceBaseID=18902,SexLimit=SexType.ST_Female,},
}

-- export table: RoleFaceDefault
return RoleFaceDefault
