-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum RankType
require("common");


local RoleWishAchieve= {
  [1]={BaseID=1,Rank=RankType.RT_White,WishAmount=1,WishNameID={1910147,},},
  [2]={BaseID=2,Rank=RankType.RT_Green,WishAmount=1,WishNameID={1910147,},},
  [3]={BaseID=3,Rank=RankType.RT_Blue,WishAmount=3,WishNameID={1910148,1910147,1910149,},},
  [4]={BaseID=4,Rank=RankType.RT_Purple,WishAmount=3,WishNameID={1910148,1910147,1910149,},},
  [5]={BaseID=5,Rank=RankType.RT_Orange,WishAmount=5,WishNameID={1910150,1910151,1910152,1910147,1910149,},},
  [6]={BaseID=6,Rank=RankType.RT_Golden,WishAmount=5,WishNameID={1910150,1910151,1910152,1910147,1910149,},},
  [7]={BaseID=7,Rank=RankType.RT_DarkGolden,WishAmount=8,WishNameID={1910153,1910154,1910155,1910156,1910157,1910158,1910159,1910149,},},
}

-- export table: RoleWishAchieve
return RoleWishAchieve
