-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum RankType
require("common");


local RoleQuality= {
  [1]={BaseID=1,Rank=RankType.RT_White,Rate=7000,},
  [2]={BaseID=2,Rank=RankType.RT_Green,Rate=7500,},
  [3]={BaseID=3,Rank=RankType.RT_Blue,Rate=8000,},
  [4]={BaseID=4,Rank=RankType.RT_Purple,Rate=9000,},
  [5]={BaseID=5,Rank=RankType.RT_Orange,Rate=10000,},
  [6]={BaseID=6,Rank=RankType.RT_Golden,Rate=13000,},
  [7]={BaseID=7,Rank=RankType.RT_DarkGolden,Rate=18000,},
  [8]={BaseID=8,Rank=RankType.RT_MultiColor,Rate=19000,},
  [9]={BaseID=9,Rank=RankType.RT_ThirdGearDarkGolden,Rate=20000,},
}

-- export table: RoleQuality
return RoleQuality
