-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum TextType
-- enum SexType
require("common");


local RoleName= {
  [1]={BaseID=1,RoleNameType=TextType.RNT_FamilyName,Sex=SexType.ST_SexNull,MinTextID=110001,MaxTextID=110477,},
  [2]={BaseID=2,RoleNameType=TextType.RNT_FristName,Sex=SexType.ST_Male,MinTextID=110478,MaxTextID=110954,},
  [3]={BaseID=3,RoleNameType=TextType.RNT_FristName,Sex=SexType.ST_Female,MinTextID=110955,MaxTextID=111429,},
  [4]={BaseID=4,RoleNameType=TextType.RNT_FullName,Sex=SexType.ST_SexNull,MinTextID=110478,MaxTextID=110954,},
  [5]={BaseID=5,RoleNameType=TextType.RNT_FristName,Sex=SexType.ST_Eunuch,MinTextID=110478,MaxTextID=110954,},
  [6]={BaseID=6,RoleNameType=TextType.RNT_FristName,Sex=SexType.ST_SexNull,MinTextID=2170001,MaxTextID=2170086,},
}

-- export table: RoleName
return RoleName
