-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum AttrType
require("common");


local RoleCardBond= {
}

-- export table: RoleCardBond
return RoleCardBond
