-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local RoleWishConfig_QingBoZhiTu= {
  [1]={BaseID=1,ClanList={11,14,16,},},
}

-- export table: RoleWishConfig_QingBoZhiTu
return RoleWishConfig_QingBoZhiTu
