-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local RoleWishConfig_ClanBadGay= {
  [1]={BaseID=1,ClanListMale={4,10,12,},ClanListNotMale={4,12,},ClanDefault=8,AnqiList={2834,2812,2852,2851,2823,2822,2821,},CityList={4,5,7,10,13,32,},},
}

-- export table: RoleWishConfig_ClanBadGay
return RoleWishConfig_ClanBadGay
