-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum WeekEndDataEnum
require("common");


local ScriptItemDefault = {ScriptOwner=2,Score1=0,Percent1=0,Score2=0,Percent2=1,MaxValue=10000,}
local ScriptItem= {
  [1]={BaseID=1,ItemEnum=WeekEndDataEnum.WE_Cong1Men2Pai3Chu4Shi,Description="从门派出师",Score2=200,Order=1,MaxValue=200,},
  [2]={BaseID=2,ItemEnum=WeekEndDataEnum.WE_Zhui1Ji2Wang3Yi,Description="追击开封的王翼",Score2=1500,Order=2,MaxValue=1500,},
  [3]={BaseID=3,ItemEnum=WeekEndDataEnum.WE_Zhui1Ji2You3Chi4Chi,Description="追击京城的游迟迟",Score2=1500,Order=3,MaxValue=1500,},
  [4]={BaseID=4,ItemEnum=WeekEndDataEnum.WE_Zhui1Ji2Qui3Bu4Jun,Description="追击杭州的仇不均",Score2=1500,Order=4,MaxValue=1500,},
  [5]={BaseID=5,ItemEnum=WeekEndDataEnum.WE_Zhui1Ji2Wu3Feng,Description="追击广州的武锋",Score2=1500,Order=5,MaxValue=1500,},
  [6]={BaseID=6,ItemEnum=WeekEndDataEnum.WE_Zhui1Ji2Xin3An4Yang,Description="追击大理的邢安阳",Score2=1500,Order=6,MaxValue=1500,},
  [7]={BaseID=7,ItemEnum=WeekEndDataEnum.WE_Yu1Bai2Yi3Jiao4Jue1Lie,Description="与白衣教决裂",Score2=1000,Order=7,MaxValue=1000,},
  [8]={BaseID=8,ItemEnum=WeekEndDataEnum.WE_Jia1Ru2Bai3Yi4Jiao,Description="加入白衣教",Score2=2000,Order=8,MaxValue=2000,},
  [9]={BaseID=9,ItemEnum=WeekEndDataEnum.WE_Ji1Tui2Dan3Wei,Description="击退单位数",Score1=20000,Percent1=10000,Percent2=0,Order=9,MaxValue=50000,},
  [10]={BaseID=10,ItemEnum=WeekEndDataEnum.WE_Chi1You2Tong3Bi,Description="持有铜币数",Score1=20,Percent1=10000,Percent2=0,Order=10,MaxValue=20000,},
  [11]={BaseID=11,ItemEnum=WeekEndDataEnum.WE_Zao1Cheng2Shang3Hai,Description="造成伤害量",Score1=2,Percent1=10000,Percent2=0,Order=11,},
  [12]={BaseID=12,ItemEnum=WeekEndDataEnum.WE_Zao1Cheng2Zhi3Liao,Description="造成治疗量",Score1=2,Percent1=10000,Percent2=0,Order=12,},
  [13]={BaseID=13,ItemEnum=WeekEndDataEnum.WE_Dui1You,Description="队友数量",Score1=1000000,Percent1=10000,Percent2=0,Order=13,},
  [14]={BaseID=14,ItemEnum=WeekEndDataEnum.WE_Mi1You,Description="密友数量",Score1=50000000,Percent1=10000,Percent2=0,Order=14,MaxValue=50000,},
  [15]={BaseID=15,ItemEnum=WeekEndDataEnum.WE_Qi1Tao,Description="乞讨次数",Score1=200000,Percent1=10000,Percent2=0,Order=15,},
  [16]={BaseID=16,ItemEnum=WeekEndDataEnum.WE_Qie1Cuo,Description="切磋次数",Score1=200000,Percent1=10000,Percent2=0,Order=16,},
  [17]={BaseID=17,ItemEnum=WeekEndDataEnum.WE_Jue1Dou,Description="决斗次数",Score1=500000,Percent1=10000,Percent2=0,Order=17,MaxValue=50000,},
  [18]={BaseID=18,ItemEnum=WeekEndDataEnum.WE_Zhen1Fu2Men3Pai,Description="征服门派次数",Score1=2000000,Percent1=10000,Percent2=0,Order=18,},
  [101]={BaseID=101,ScriptOwner=1,ItemEnum=WeekEndDataEnum.WE_YuWenZhuang1,Description="成功从杭州行至大理",Score2=500,Order=19,MaxValue=500,},
  [102]={BaseID=102,ScriptOwner=1,ItemEnum=WeekEndDataEnum.WE_YuWenZhuang2,Description="用七彩骆驼与扫地小二达成交易",Score2=1000,Order=20,MaxValue=1000,},
  [103]={BaseID=103,ScriptOwner=1,ItemEnum=WeekEndDataEnum.WE_YuWenZhuang3,Description="在无量山玉像磕头祈祷",Score2=1000,Order=21,MaxValue=1000,},
  [104]={BaseID=104,ScriptOwner=1,ItemEnum=WeekEndDataEnum.WE_YuWenZhuang4,Description="痛饮云水阁里的美酒",Score2=1000,Order=22,MaxValue=1000,},
  [105]={BaseID=105,ScriptOwner=1,ItemEnum=WeekEndDataEnum.WE_YuWenZhuang5,Description="获得扫地小二的传家宝",Score2=1000,Order=23,MaxValue=1000,},
  [106]={BaseID=106,ScriptOwner=1,ItemEnum=WeekEndDataEnum.WE_YuWenZhuang7,Description="探听山庄密道中的对话",Score2=1000,Order=24,MaxValue=1000,},
  [107]={BaseID=107,ScriptOwner=1,ItemEnum=WeekEndDataEnum.WE_YuWenZhuang6,Description="最终战胜秦中居士一行",Score2=2500,Order=25,MaxValue=2500,},
  [108]={BaseID=108,ScriptOwner=1,ItemEnum=WeekEndDataEnum.WE_Dui1You,Description="队友数量",Score1=1000000,Percent1=10000,Percent2=0,Order=26,},
  [109]={BaseID=109,ScriptOwner=1,ItemEnum=WeekEndDataEnum.WE_Qi1Tao,Description="乞讨次数",Score1=200000,Percent1=10000,Percent2=0,Order=27,},
  [110]={BaseID=110,ScriptOwner=1,ItemEnum=WeekEndDataEnum.WE_Qie1Cuo,Description="切磋次数",Score1=200000,Percent1=10000,Percent2=0,Order=28,},
  [111]={BaseID=111,ScriptOwner=1,ItemEnum=WeekEndDataEnum.WE_Jue1Dou,Description="决斗次数",Score1=500000,Percent1=10000,Percent2=0,Order=29,MaxValue=50000,},
  [112]={BaseID=112,ScriptOwner=1,ItemEnum=WeekEndDataEnum.WE_Ji1Tui2Dan3Wei,Description="击退单位数",Score1=20000,Percent1=10000,Percent2=0,Order=30,MaxValue=50000,},
  [113]={BaseID=113,ScriptOwner=1,ItemEnum=WeekEndDataEnum.WE_Zao1Cheng2Shang3Hai,Description="造成伤害量",Score1=2,Percent1=10000,Percent2=0,Order=31,},
  [114]={BaseID=114,ScriptOwner=1,ItemEnum=WeekEndDataEnum.WE_Zao1Cheng2Zhi3Liao,Description="造成治疗量",Score1=2,Percent1=10000,Percent2=0,Order=32,},
  [201]={BaseID=201,ScriptOwner=4,ItemEnum=WeekEndDataEnum.WE_HuiTianMieDi1,Description="破天逆命传剧本胜利20场",Score2=1500,Order=2,MaxValue=1500,},
  [202]={BaseID=202,ScriptOwner=4,ItemEnum=WeekEndDataEnum.WE_HuiTianMieDi2,Description="破天逆命传剧本胜利40场",Score2=1500,Order=3,MaxValue=1500,},
  [203]={BaseID=203,ScriptOwner=4,ItemEnum=WeekEndDataEnum.WE_HuiTianMieDi3,Description="破天逆命传剧本胜利60场",Score2=1500,Order=4,MaxValue=1500,},
  [204]={BaseID=204,ScriptOwner=4,ItemEnum=WeekEndDataEnum.WE_HuiTianMieDi4,Description="破天逆命传剧本胜利80场",Score2=1500,Order=5,MaxValue=1500,},
  [205]={BaseID=205,ScriptOwner=4,ItemEnum=WeekEndDataEnum.WE_NULL,Description="破天逆命传剧本胜利100场",Score2=1500,Order=6,MaxValue=1500,},
}
for k,v in pairs(ScriptItem) do
    setmetatable(v, {['__index'] = ScriptItemDefault})
end

-- export table: ScriptItem
return ScriptItem
