-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local SecretShopPos= {
  [1]={BaseID=1,RoleID=1000114001,EvolutePercent=50,EvoluteMaps={1348,1120,1018,581,1027,},EvoluteCitys={21,28,25,27,26,},EvoluteRecordIDs={233,233,233,233,233,},},
  [2]={BaseID=2,RoleID=1000114002,EvolutePercent=50,EvoluteMaps={1348,1120,1018,581,1027,},EvoluteCitys={21,28,25,27,26,},EvoluteRecordIDs={227,231,229,230,228,},},
}

-- export table: SecretShopPos
return SecretShopPos
