-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum BuildingType
require("common");


local SectBuildingUnlock= {
  [1]={BaseID=1,HallLevel=1,BuildingType=BuildingType.DiscipleHouse,},
  [2]={BaseID=2,HallLevel=1,BuildingType=BuildingType.WS_Pharmacy,},
  [3]={BaseID=3,HallLevel=1,BuildingType=BuildingType.Storehouse,},
  [4]={BaseID=4,HallLevel=2,BuildingType=BuildingType.Passway,},
  [5]={BaseID=5,HallLevel=2,BuildingType=BuildingType.Storehouse,},
  [6]={BaseID=6,HallLevel=2,BuildingType=BuildingType.WS_Sweet,},
  [7]={BaseID=7,HallLevel=2,BuildingType=BuildingType.TR_Sword,},
  [8]={BaseID=8,HallLevel=3,BuildingType=BuildingType.Passway,},
  [9]={BaseID=9,HallLevel=3,BuildingType=BuildingType.Storehouse,},
  [10]={BaseID=10,HallLevel=3,BuildingType=BuildingType.WS_Tavern,},
  [11]={BaseID=11,HallLevel=3,BuildingType=BuildingType.WS_FlowerBed,},
  [12]={BaseID=12,HallLevel=3,BuildingType=BuildingType.TR_Knife,},
  [13]={BaseID=13,HallLevel=3,BuildingType=BuildingType.TR_Boxing,},
  [14]={BaseID=14,HallLevel=4,BuildingType=BuildingType.Passway,},
  [15]={BaseID=15,HallLevel=4,BuildingType=BuildingType.Storehouse,},
  [16]={BaseID=16,HallLevel=4,BuildingType=BuildingType.WS_Studio,},
  [17]={BaseID=17,HallLevel=4,BuildingType=BuildingType.TR_Medical,},
}

-- export table: SectBuildingUnlock
return SectBuildingUnlock
