-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum BuildingType
require("common");


local SectBuildingBackground= {
  [1]={BaseID=1,BuildingType=BuildingType.Hall,BuildingLevel=1,BackgroundID=1,},
  [2]={BaseID=2,BuildingType=BuildingType.Hall,BuildingLevel=3,BackgroundID=2,},
  [3]={BaseID=3,BuildingType=BuildingType.Storehouse,BuildingLevel=1,BackgroundID=1,},
  [4]={BaseID=4,BuildingType=BuildingType.Storehouse,BuildingLevel=2,BackgroundID=2,},
  [5]={BaseID=5,BuildingType=BuildingType.TR_Sword,BuildingLevel=1,BackgroundID=3,},
  [6]={BaseID=6,BuildingType=BuildingType.WS_FlowerBed,BuildingLevel=1,BackgroundID=4,},
}

-- export table: SectBuildingBackground
return SectBuildingBackground
