-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local ServerZoneName= {
  [1]={BaseID=1,ServerID="10001",ZoneName="微信1区",},
}

-- export table: ServerZoneName
return ServerZoneName
