-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum ConfigType
require("common");


local SingleFieldConfig= {
  [1]={BaseID=1,ConfigType=ConfigType.CFG_NPC_BIGMAP_TASK_ID,ConfigValue=5642,},
  [2]={BaseID=2,ConfigType=ConfigType.CFG_UNLOAD_ROLETREASURE_FAVOR_NEED,ConfigValue=99,},
  [3]={BaseID=3,ConfigType=ConfigType.CFG_UNLOAD_ROLETREASURE_FAVORSUB,ConfigValue=100,},
  [4]={BaseID=4,ConfigType=ConfigType.CFG_TONGLINGYU_SILVER_PRICE,ConfigValue=10,},
  [5]={BaseID=5,ConfigType=ConfigType.CFG_CREATE_ROLE_JIAN_FA_SHOW_MAX_VALUE,ConfigValue=100,},
  [6]={BaseID=6,ConfigType=ConfigType.CFG_CREATE_ROLE_DAO_FA_SHOW_MAX_VALUE,ConfigValue=100,},
  [7]={BaseID=7,ConfigType=ConfigType.CFG_CREATE_ROLE_QUAN_ZHANG_SHOW_MAX_VALUE,ConfigValue=100,},
  [8]={BaseID=8,ConfigType=ConfigType.CFG_CREATE_ROLE_TUI_FA_SHOW_MAX_VALUE,ConfigValue=100,},
  [9]={BaseID=9,ConfigType=ConfigType.CFG_CREATE_ROLE_QI_MEN_SHOW_MAX_VALUE,ConfigValue=100,},
  [10]={BaseID=10,ConfigType=ConfigType.CFG_CREATE_ROLE_AN_QI_SHOW_MAX_VALUE,ConfigValue=100,},
  [11]={BaseID=11,ConfigType=ConfigType.CFG_CREATE_ROLE_YI_SHU_SHOW_MAX_VALUE,ConfigValue=100,},
  [12]={BaseID=12,ConfigType=ConfigType.CFG_CREATE_ROLE_NEI_GONG_SHOW_MAX_VALUE,ConfigValue=100,},
  [13]={BaseID=13,ConfigType=ConfigType.CFG_CREATE_ROLE_MAX_HP_SHOW_MAX_VALUE,ConfigValue=2500,},
  [14]={BaseID=14,ConfigType=ConfigType.CFG_CREATE_ROLE_MAX_MP_SHOW_MAX_VALUE,ConfigValue=2500,},
  [15]={BaseID=15,ConfigType=ConfigType.CFG_CREATE_ROLE_DEF_SHOW_MAX_VALUE,ConfigValue=100,},
  [16]={BaseID=16,ConfigType=ConfigType.CFG_CREATE_ROLE_MARTIAL_ATK_SHOW_MAX_VALUE,ConfigValue=80,},
}

-- export table: SingleFieldConfig
return SingleFieldConfig
