-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum SkillType
require("common");


local SkillDepartPowerEft= {
  [1]={BaseID=1,Type=SkillType.SkillType_lianzhao,LianZhao=1,Factor=10000,},
  [2]={BaseID=2,Type=SkillType.SkillType_lianzhao,LianZhao=2,Factor=12500,},
  [3]={BaseID=3,Type=SkillType.SkillType_lianzhao,LianZhao=3,Factor=15000,},
  [4]={BaseID=4,Type=SkillType.SkillType_juezhao,LianZhao=0,Factor=15000,},
}

-- export table: SkillDepartPowerEft
return SkillDepartPowerEft
