-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local SpecialCityShowName= {
  [1]={BaseID=1,City=2,ShowNameID=1410024,Tag=999999,},
}

-- export table: SpecialCityShowName
return SpecialCityShowName
