-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum StoryName
-- enum TBoolean
-- enum StoryUnlockType
require("common");


local Story= {
  [1]={BaseID=1,NameID=2010002,StoryName=StoryName.SNN_YUWENZHUANGQIAN,SortIndex=3,DescID=2020002,TimeID=2030002,IsPublic=TBoolean.BOOL_YES,UnlockType=StoryUnlockType.SUT_UNLOCKED,UnlockCost=0,UnlockID=0,CG="StoryCG/cg_story_yu3wen2zhuangqi2an4",TeamOut=TBoolean.BOOL_NO,StartStoryTaskID=0,StartTask={4085,},LuckeyCost=0,IsForbidShowCityRoleList=TBoolean.BOOL_NO,bInitStart=TBoolean.BOOL_NO,bAllowStorageIn=TBoolean.BOOL_NO,bAllowShareTreasureMap=TBoolean.BOOL_NO,IsDreamStory=TBoolean.BOOL_NO,DreamStoryRole=0,OpenMartialStrong=TBoolean.BOOL_NO,OpenMakeSecret=TBoolean.BOOL_NO,WeekTakeOutLimit=0,SpecialCreateRole=0,DifficultMin=1,DifficultMax=1,DifficultUnlock=1,},
  [2]={BaseID=2,NameID=2010001,StoryName=StoryName.SNN_MOJUNLUANJIANGHU,SortIndex=2,DescID=2020001,TimeID=2030001,IsPublic=TBoolean.BOOL_YES,UnlockType=StoryUnlockType.SUT_UNLOCKED,UnlockCost=0,UnlockID=0,CG="StoryCG/cg_story_mo2jun1luan4jiang1hu2",TeamOut=TBoolean.BOOL_YES,StartStoryTaskID=0,StoryRewardShow={9691,9692,9693,},StartTask={3812,},LuckeyCost=0,IsForbidShowCityRoleList=TBoolean.BOOL_NO,bInitStart=TBoolean.BOOL_YES,bAllowStorageIn=TBoolean.BOOL_YES,bAllowShareTreasureMap=TBoolean.BOOL_NO,IsDreamStory=TBoolean.BOOL_NO,DreamStoryRole=0,OpenMartialStrong=TBoolean.BOOL_NO,OpenMakeSecret=TBoolean.BOOL_NO,WeekTakeOutLimit=0,SpecialCreateRole=0,DifficultMin=1,DifficultMax=3,DifficultUnlock=1,},
  [4]={BaseID=4,NameID=2010003,StoryName=StoryName.SNN_Null,SortIndex=4,DescID=2020003,TimeID=2030003,IsPublic=TBoolean.BOOL_YES,UnlockType=StoryUnlockType.SUT_UNLOCKED,UnlockCost=0,UnlockID=0,CG="GalleryCG/baowang",TeamOut=TBoolean.BOOL_NO,StartStoryTaskID=0,StartTask={5495,},LuckeyCost=0,IsForbidShowCityRoleList=TBoolean.BOOL_NO,bInitStart=TBoolean.BOOL_NO,bAllowStorageIn=TBoolean.BOOL_NO,bAllowShareTreasureMap=TBoolean.BOOL_NO,IsDreamStory=TBoolean.BOOL_NO,DreamStoryRole=0,OpenMartialStrong=TBoolean.BOOL_NO,OpenMakeSecret=TBoolean.BOOL_NO,WeekTakeOutLimit=0,SpecialCreateRole=0,DifficultMin=1,DifficultMax=5,DifficultUnlock=1,},
  [6]={BaseID=6,NameID=2010004,StoryName=StoryName.SNN_CESHIRUKOU,SortIndex=6,DescID=2020004,TimeID=2030004,IsPublic=TBoolean.BOOL_NO,UnlockType=StoryUnlockType.SUT_UNLOCKED,UnlockCost=0,UnlockID=0,CG="StoryCG/cg_story_ce4shi4ru4kou3",TeamOut=TBoolean.BOOL_YES,StartStoryTaskID=0,StartTask={4498,},LuckeyCost=0,IsForbidShowCityRoleList=TBoolean.BOOL_NO,bInitStart=TBoolean.BOOL_NO,bAllowStorageIn=TBoolean.BOOL_YES,bAllowShareTreasureMap=TBoolean.BOOL_NO,IsDreamStory=TBoolean.BOOL_NO,DreamStoryRole=0,OpenMartialStrong=TBoolean.BOOL_NO,OpenMakeSecret=TBoolean.BOOL_NO,WeekTakeOutLimit=0,SpecialCreateRole=0,DifficultMin=1,DifficultMax=5,DifficultUnlock=1,},
}

-- export table: Story
return Story
