-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum AttrType
require("common");


local StoryZhuazhou= {
  [1]={BaseID=1,BackCG=10001,RoleID=1000001391,QuestionID=3810001,AudioResID=10014,Answer={{LangID=3820001,RewardItems={70108,},RewardItemValues={1,},RewardRenyi=0,RandomRewardDesc=0,RandomRewardID=0,},{LangID=3820002,RewardItems={801065,},RewardItemValues={1,},RewardRenyi=0,RandomRewardDesc=0,RandomRewardID=0,},{LangID=3820003,RewardAttrs={AttrType.ATTR_ANQIJINGTONG,AttrType.ATTR_YISHUJINGTONG,},RewardAttrValues={65,65,},RewardItems={1301,},RewardItemValues={5000,},RewardRenyi=0,RandomRewardDesc=0,RandomRewardID=0,},{LangID=3820004,RewardAttrs={AttrType.ATTR_QUANZHANGJINGTONG,AttrType.ATTR_TUIFAJINGTONG,},RewardAttrValues={65,65,},RewardRenyi=0,RandomRewardDesc=0,RandomRewardID=0,},{LangID=3820005,RewardAttrs={AttrType.ATTR_QIMENJINGTONG,},RewardAttrValues={85,},RewardRenyi=0,RandomRewardDesc=0,RandomRewardID=0,},},},
  [2]={BaseID=2,BackCG=10002,RoleID=1000001393,QuestionID=3810002,AudioResID=10015,Answer={{LangID=3820006,RewardItems={70109,},RewardItemValues={1,},RewardRenyi=0,RandomRewardDesc=0,RandomRewardID=0,},{LangID=3820007,RewardItems={801066,},RewardItemValues={1,},RewardRenyi=0,RandomRewardDesc=0,RandomRewardID=0,},{LangID=3820008,RewardAttrs={AttrType.ATTR_SUDUZHI,},RewardAttrValues={30,},RewardRenyi=0,RandomRewardDesc=0,RandomRewardID=0,},{LangID=3820009,RewardRenyi=0,RandomRewardDesc=3830001,RandomRewardID=1000900,},},},
  [3]={BaseID=3,BackCG=10003,RoleID=1000001395,QuestionID=3810003,AudioResID=10016,Answer={{LangID=3820010,RewardAttrs={AttrType.ATTR_JIANFAJINGTONG,},RewardAttrValues={65,},RewardRenyi=40,RandomRewardDesc=0,RandomRewardID=0,},{LangID=3820011,RewardAttrs={AttrType.ATTR_SHANBI,},RewardAttrValues={80,},RewardRenyi=0,RandomRewardDesc=0,RandomRewardID=0,},{LangID=3820012,RewardAttrs={AttrType.ATTR_DAOFAJINGTONG,},RewardAttrValues={65,},RewardRenyi=-40,RandomRewardDesc=0,RandomRewardID=0,},},},
  [4]={BaseID=4,BackCG=10004,RoleID=1000001394,QuestionID=3810004,AudioResID=10017,Answer={{LangID=3820013,RewardAttrs={AttrType.ATTR_DEF,},RewardAttrValues={130,},RewardRenyi=0,RandomRewardDesc=0,RandomRewardID=0,},{LangID=3820014,RewardAttrs={AttrType.ATTR_ROUNDMP,},RewardAttrValues={100,},RewardRenyi=0,RandomRewardDesc=0,RandomRewardID=0,},{LangID=3820015,RewardAttrs={AttrType.ATTR_MARTIAL_ATK,},RewardAttrValues={400,},RewardRenyi=0,RandomRewardDesc=0,RandomRewardID=0,},},},
  [5]={BaseID=5,BackCG=10005,RoleID=1000001392,QuestionID=3810005,AudioResID=10018,Answer={{LangID=3820016,RewardAttrs={AttrType.ATTR_MAXMP,},RewardAttrValues={2200,},RewardRenyi=0,RandomRewardDesc=0,RandomRewardID=0,},{LangID=3820017,RewardAttrs={AttrType.ATTR_MAXHP,},RewardAttrValues={4000,},RewardRenyi=0,RandomRewardDesc=0,RandomRewardID=0,},{LangID=3820018,RewardItems={1301,},RewardItemValues={10000,},RewardRenyi=0,RandomRewardDesc=0,RandomRewardID=0,},{LangID=3820019,RewardItems={1106,},RewardItemValues={5,},RewardRenyi=0,RandomRewardDesc=0,RandomRewardID=0,},},},
}

-- export table: StoryZhuazhou
return StoryZhuazhou
