-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum TaskDescProgressType
require("common");


local TaskDescProgressEnumDefault = {arg1Type="string",arg2Type="int",arg3Type="",arg3Name="",}
local TaskDescProgressEnum= {
  [1]={BaseID=1,ProgressType=TaskDescProgressType.TaskDescProgressType_NULL,arg1Type="",arg1Name="",arg2Type="",arg2Name="",},
  [2]={BaseID=2,ProgressType=TaskDescProgressType.TDPT_wupin,arg1Type="Item",arg1Name="物品",arg2Name="目标数量",},
  [3]={BaseID=3,ProgressType=TaskDescProgressType.TDPT_wupinleixing,arg1Name="物品类型",arg2Name="目标数量",},
  [4]={BaseID=4,ProgressType=TaskDescProgressType.TDPT_zhujueshuxing,arg1Name="属性",arg2Name="目标值",},
  [5]={BaseID=5,ProgressType=TaskDescProgressType.TDPT_youxishuxing,arg1Name="属性",arg2Name="目标值",},
  [6]={BaseID=6,ProgressType=TaskDescProgressType.TDPT_jishiqi,arg1Name="计时器",arg2Type="",arg2Name="",},
  [7]={BaseID=7,ProgressType=TaskDescProgressType.TDPT_biaoji,arg1Type="TaskTag",arg1Name="标记",arg2Name="目标值",},
  [8]={BaseID=8,ProgressType=TaskDescProgressType.TDPT_shadi,arg1Type="",arg1Name="",arg2Type="",arg2Name="",},
  [9]={BaseID=9,ProgressType=TaskDescProgressType.TDPT_hanshu,arg1Type="",arg1Name="",arg2Type="",arg2Name="",},
  [10]={BaseID=10,ProgressType=TaskDescProgressType.TDPT_haogandu,arg1Type="RoleTemplate",arg1Name="角色",arg2Name="要求好感",},
  [11]={BaseID=11,ProgressType=TaskDescProgressType.TDPT_wuxuedengji,arg1Type="Martial",arg1Name="武学",arg2Name="要求等级",},
  [12]={BaseID=12,ProgressType=TaskDescProgressType.TDPT_menpaihaogan,arg1Type="Clan",arg1Name="门派",arg2Name="要求好感",},
  [13]={BaseID=13,ProgressType=TaskDescProgressType.TDPT_maoxiantianfudengji,arg1Name="冒险天赋",arg2Name="要求等级",},
  [14]={BaseID=14,ProgressType=TaskDescProgressType.TDPT_VALUE,arg1Name="动态值",arg2Name="目标值",},
}
for k,v in pairs(TaskDescProgressEnum) do
    setmetatable(v, {['__index'] = TaskDescProgressEnumDefault})
end

-- export table: TaskDescProgressEnum
return TaskDescProgressEnum
