-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local TimeLimitGiftActivity= {
  [1]={BaseID=1,NameID=810001,BeginDate={Year=2019,Month=7,Day=1,},EndDate={Year=2019,Month=7,Day=31,},BuyNum=3,GiveNum=2,},
  [2]={BaseID=2,NameID=810002,BeginDate={Year=2019,Month=8,Day=1,},EndDate={Year=2019,Month=8,Day=31,},BuyNum=5,GiveNum=5,},
  [3]={BaseID=3,NameID=810003,BeginDate={Year=2019,Month=9,Day=1,},EndDate={Year=2019,Month=9,Day=30,},BuyNum=10,GiveNum=11,},
}

-- export table: TimeLimitGiftActivity
return TimeLimitGiftActivity
