-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local TimeLimitGuessCoinV2= {
  [257]={GameType=1,GameLevel=1,CoinType=8,CoinCostNum=1,LeftCoin=2,MidCoin=3,RightCoin=2,MoveTime=5,MoveNum=5,},
  [258]={GameType=2,GameLevel=1,CoinType=1,CoinCostNum=100,LeftCoin=80,MidCoin=150,RightCoin=110,MoveTime=5,MoveNum=8,},
  [513]={GameType=1,GameLevel=2,CoinType=8,CoinCostNum=2,LeftCoin=3,MidCoin=4,RightCoin=3,MoveTime=6,MoveNum=9,},
  [769]={GameType=1,GameLevel=3,CoinType=8,CoinCostNum=6,LeftCoin=8,MidCoin=10,RightCoin=9,MoveTime=7,MoveNum=14,},
}

-- export table: TimeLimitGuessCoinV2
return TimeLimitGuessCoinV2
