-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local TreasureBookGlobalDefault = {HeroID2=0,HeroNum2=0,RichID1=9660,RichID3=0,RichNum3=0,RichID4=0,RichNum4=0,}
local TreasureBookGlobal= {
  [1]={BaseID=1,NeedNum=1000,HeroID1=9610,HeroNum1=240,RichNum1=10,RichID2=30951,RichNum2=10,},
  [2]={BaseID=2,NeedNum=5000,HeroID1=9610,HeroNum1=260,RichNum1=15,RichID2=30951,RichNum2=20,},
  [3]={BaseID=3,NeedNum=10000,HeroID1=9610,HeroNum1=280,RichNum1=20,RichID2=250601503,RichNum2=2,},
  [4]={BaseID=4,NeedNum=20000,HeroID1=9610,HeroNum1=300,RichNum1=25,RichID2=250601714,RichNum2=2,},
  [5]={BaseID=5,NeedNum=30000,HeroID1=341100,HeroNum1=5,RichNum1=30,RichID2=250601710,RichNum2=2,},
}
for k,v in pairs(TreasureBookGlobal) do
    setmetatable(v, {['__index'] = TreasureBookGlobalDefault})
end

-- export table: TreasureBookGlobal
return TreasureBookGlobal
