-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local TreasureBookGlobalRule= {
  [1]={BaseID=1,DayMin=2,DayMax=2,RewardNumMin=1000,RewardNumMax=1200,},
  [2]={BaseID=2,DayMin=4,DayMax=5,RewardNumMin=5000,RewardNumMax=5300,},
  [3]={BaseID=3,DayMin=8,DayMax=10,RewardNumMin=10000,RewardNumMax=10500,},
  [4]={BaseID=4,DayMin=14,DayMax=17,RewardNumMin=20000,RewardNumMax=22000,},
  [5]={BaseID=5,DayMin=21,DayMax=28,RewardNumMin=30000,RewardNumMax=33000,},
}

-- export table: TreasureBookGlobalRule
return TreasureBookGlobalRule
