-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local TreasureBox= {
  [1]={BaseID=1,Model="Treasure_box1",Texture="Actor/obj_Treasure box/Treasure_box1/Treasure_box1",ModelID=316,},
  [2]={BaseID=2,Model="Treasure_box3",Texture="Actor/obj_Treasure box/Treasure_box3/Treasure_box3",ModelID=318,},
  [3]={BaseID=3,Model="Treasure_box4",Texture="Actor/obj_Treasure box/Treasure_box4/Treasure_box4",ModelID=289,},
}

-- export table: TreasureBox
return TreasureBox
