-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum UpgradeAttrType
-- enum UpgradeBuffType
require("common");


local UpgradeGiftConfigDefault = {UpgradeBuffType=UpgradeBuffType.UBT_NeiShang,InfluenceBuff=140,}
local UpgradeGiftConfig= {
  [1]={BaseID=1,UpgradeAttrType=UpgradeAttrType.UAT_NeiShangHuiXue,AddPercent={10000,15000,20000,25000,40000,60000,},},
  [2]={BaseID=2,UpgradeAttrType=UpgradeAttrType.UAT_NeiShangHuiZhenQi,AddPercent={10000,15000,20000,25000,40000,60000,},},
  [3]={BaseID=3,UpgradeAttrType=UpgradeAttrType.UAT_NeiShangXiXue,AddPercent={10000,15000,20000,25000,40000,60000,},},
  [4]={BaseID=4,UpgradeAttrType=UpgradeAttrType.UAT_NeiShangBeiZhiLiao,AddPercent={10000,15000,20000,25000,40000,60000,},},
  [5]={BaseID=5,UpgradeAttrType=UpgradeAttrType.UAT_NeiShangXiZhenQi,AddPercent={10000,15000,20000,25000,40000,60000,},},
  [6]={BaseID=6,UpgradeAttrType=UpgradeAttrType.UAT_PoJia,UpgradeBuffType=UpgradeBuffType.UBT_PoJia,AddPercent={20000,60000,100000,160000,240000,400000,},InfluenceBuff=137,},
  [7]={BaseID=7,UpgradeAttrType=UpgradeAttrType.UAT_JianSu,UpgradeBuffType=UpgradeBuffType.UBT_JianSu,AddPercent={20000,-30000,-400000,-500000,-800000,-12000000,},InfluenceBuff=139,},
  [8]={BaseID=8,UpgradeAttrType=UpgradeAttrType.UAT_CanFei,UpgradeBuffType=UpgradeBuffType.UBT_CanFei,AddPercent={500000,1500000,7500000,5000000,10000000,75000000,},InfluenceBuff=141,},
  [9]={BaseID=9,UpgradeAttrType=UpgradeAttrType.UAT_LiuXue,UpgradeBuffType=UpgradeBuffType.UBT_LiuXue,AddPercent={500000,1000000,2000000,4000000,10000000,25000000,},InfluenceBuff=136,},
  [10]={BaseID=10,UpgradeAttrType=UpgradeAttrType.UAT_ZhongDu,UpgradeBuffType=UpgradeBuffType.UBT_ZhongDu,AddPercent={100000,200000,400000,800000,2000000,5000000,},InfluenceBuff=138,},
  [11]={BaseID=11,UpgradeAttrType=UpgradeAttrType.UAT_ChuanTou,UpgradeBuffType=UpgradeBuffType.UBT_ChuanTou,AddPercent={300000,400000,500000,600000,700000,800000,},InfluenceBuff=0,},
  [12]={BaseID=12,UpgradeAttrType=UpgradeAttrType.UAT_TanShe,UpgradeBuffType=UpgradeBuffType.UBT_TanShei,AddPercent={700000,800000,900000,1000000,1100000,12000000,},InfluenceBuff=0,},
  [13]={BaseID=13,UpgradeAttrType=UpgradeAttrType.UAT_ChangBeiBuXie,UpgradeBuffType=UpgradeBuffType.UBT_ChangBeiBuXie,AddPercent={4000,6000,8000,10000,12000,15000,},InfluenceBuff=0,},
  [14]={BaseID=14,UpgradeAttrType=UpgradeAttrType.UAT_ZHONGDULIUXUE,UpgradeBuffType=UpgradeBuffType.UBT_ZhongDu,AddPercent={300000,600000,1200000,2400000,6000000,15000000,},InfluenceBuff=138,},
}
for k,v in pairs(UpgradeGiftConfig) do
    setmetatable(v, {['__index'] = UpgradeGiftConfigDefault})
end

-- export table: UpgradeGiftConfig
return UpgradeGiftConfig
