-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum TBoolean
require("common");


local Weather= {
  [1]={BaseID=1,NameID=2710001,EvoDescID=0,EffectDescID=0,Background=0,IconAnim="",BuffID=0,IsRain=TBoolean.BOOL_NO,IsTips=TBoolean.BOOL_NO,},
  [2]={BaseID=2,NameID=2710002,EvoDescID=2720001,EffectDescID=2730001,Background=3,IconAnim="sun",BuffID=540,IsRain=TBoolean.BOOL_NO,IsTips=TBoolean.BOOL_YES,},
  [3]={BaseID=3,NameID=2710003,EvoDescID=2720002,EffectDescID=2730002,Background=4,IconAnim="wind",BuffID=541,IsRain=TBoolean.BOOL_NO,IsTips=TBoolean.BOOL_YES,},
  [4]={BaseID=4,NameID=2710004,EvoDescID=2720003,EffectDescID=2730003,Background=5,IconAnim="fog",BuffID=542,IsRain=TBoolean.BOOL_NO,IsTips=TBoolean.BOOL_YES,},
  [5]={BaseID=5,NameID=2710005,EvoDescID=2720004,EffectDescID=0,Background=6,IconAnim="rain",BuffID=0,IsRain=TBoolean.BOOL_YES,IsTips=TBoolean.BOOL_YES,},
  [6]={BaseID=6,NameID=2710006,EvoDescID=2720005,EffectDescID=2730004,Background=7,IconAnim="thunderstorm",BuffID=539,IsRain=TBoolean.BOOL_YES,IsTips=TBoolean.BOOL_YES,},
  [7]={BaseID=7,NameID=2710007,EvoDescID=2720006,EffectDescID=2730005,Background=8,IconAnim="snow",BuffID=543,IsRain=TBoolean.BOOL_YES,IsTips=TBoolean.BOOL_YES,},
}

-- export table: Weather
return Weather
