-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local WeekEndMeridians= {
  [1]={BaseID=1,Down=0,Up=1999999999,Percent=0,},
}

-- export table: WeekEndMeridians
return WeekEndMeridians
