-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum RankType
require("common");


local AchievePoint= {
  [1]={BaseID=1,Rank=RankType.RT_White,Point=2,},
  [2]={BaseID=2,Rank=RankType.RT_Green,Point=5,},
  [3]={BaseID=3,Rank=RankType.RT_Blue,Point=10,},
  [4]={BaseID=4,Rank=RankType.RT_Purple,Point=20,},
  [5]={BaseID=5,Rank=RankType.RT_Orange,Point=40,},
  [6]={BaseID=6,Rank=RankType.RT_Golden,Point=80,},
  [7]={BaseID=7,Rank=RankType.RT_DarkGolden,Point=200,},
}

-- export table: AchievePoint
return AchievePoint
