-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local ActivitySignRewardDefault = {PreIcon="",PreDesText="新人礼包",ShowRoleID=0,ShowIcon="",ShowName="",ShowDesText="",ItemID=1401,ItemNum=1,ClanID=0,AchieveID=0,}
local ActivitySignReward= {
  [1]={BaseID=1,PreDesText="门派名字",ShowIcon="ChainClan/united_4",ShowName="六扇门",ShowDesText="六扇门直属朝廷，下至维护治安，上至保家卫国，皆乃六扇门中人职责所在。与此同时，制衡武林诸势力，同样是六扇门事务重中之重。",ItemNum=100,PreBG="ActivitySignBG/1_LiuShanMen/img_picture1",ShowBG="ActivitySignBG/1_LiuShanMen/img_picture1",},
  [2]={BaseID=2,PreDesText="门派特色",ShowIcon="ActivitySignClanSkill/Clan_skill_5",ShowName="盘查",ShowDesText="盘查可疑角色，发现有罪之人，可将角色关入监牢",ItemID=339138,PreBG="ActivitySignBG/1_LiuShanMen/img_picture2",ShowBG="ActivitySignBG/1_LiuShanMen/img_picture2",},
  [3]={BaseID=3,PreDesText="门派传家宝",ShowItemList={"413708",},ItemID=501908,PreBG="ActivitySignBG/1_LiuShanMen/img_picture3",ShowBG="ActivitySignBG/1_LiuShanMen/img_picture3",},
  [4]={BaseID=4,PreDesText="小师妹",ShowRoleID=1030301004,ItemID=339139,PreBG="ActivitySignBG/1_LiuShanMen/img_picture4",ShowBG="ActivitySignBG/1_LiuShanMen/img_picture4",},
  [5]={BaseID=5,PreDesText="顶级武学",ShowItemList={"511926","511921",},ItemID=511927,PreBG="ActivitySignBG/1_LiuShanMen/img_picture5",ShowBG="ActivitySignBG/1_LiuShanMen/img_picture5",},
  [6]={BaseID=6,PreDesText="门派掌门",ShowRoleID=1040301007,ItemID=501927,PreBG="ActivitySignBG/1_LiuShanMen/img_picture6",ShowBG="ActivitySignBG/1_LiuShanMen/img_picture6",},
  [7]={BaseID=7,ShowItemList={"8101",},ItemID=511905,PreBG="ActivitySignBG/1_LiuShanMen/img_picture7",ShowBG="ActivitySignBG/1_LiuShanMen/img_picture7",ClanID=63,AchieveID=345,},
  [11]={BaseID=11,PreDesText="玩法简介",ShowIcon="ActivitySignClanSkill/Clan_icon_duel_001",ShowName="掌门对决",ShowDesText="1、掌门对决是一个不需要练级即可体验顶级角色的玩法；\n2、体验角色快速成长到暗金+5、45级的顶级能力；\n3、与真人玩家匹配，实时在线对战，单轮淘汰赛制；\n4、单局只需10分钟，奖励最高可得暗金角色卡。\n欲知详细玩法规则，请明天再来揭晓。",ItemID=8311,PreBG="ActivitySignBG/2_ZhangMenDuiJue/img_picture1",ShowBG="ActivitySignBG/2_ZhangMenDuiJue/img_picture1",},
  [12]={BaseID=12,PreDesText="玩法规则",ShowIcon="ActivitySignClanSkill/Clan_icon_duel_001",ShowName="玩法规则",ShowDesText="1、与64名真实玩家匹配，玩家不足时可能会加入机器人；\n2、随机抽取32名游戏中侠客，成为本局游戏的角色池；\n3、自选掌门，获得门派特技，以及该门派所有角色获得概率提升；\n4、自选队友，重复队友可合成升级，最高可升到暗金+5、45级；\n5、与其他玩家或BOSS对战，自动进行战斗，两两对决，单轮淘汰；\n6、战斗获胜后，可继续获得队友、神器，并抢夺失败者的队友，晋级下一轮；\n7、战斗若失败，则根据名次进入领奖结算。\n欲知最终奖励规则，请明天再来揭晓",ItemNum=200,PreBG="ActivitySignBG/2_ZhangMenDuiJue/img_picture2",ShowBG="ActivitySignBG/2_ZhangMenDuiJue/img_picture2",},
  [13]={BaseID=13,PreDesText="玩法奖励",ShowIcon="ActivitySignClanSkill/Clan_icon_duel_001",ShowName="奖励角色卡",ShowDesText="1、每赢一轮，都可以抢夺对方的掌门币。晋级轮次越多，掌门币越多；\n2、在结算奖励商店中，以掌门币可兑换角色卡。商店中的角色卡，就是自己比赛结束时队伍中的角色。所以队友越多，可选范围越广。参加轮次越久，高品质角色卡越多。\n欲知玩法参与条件，请明天再来揭晓。",ItemID=8312,PreBG="ActivitySignBG/2_ZhangMenDuiJue/img_picture3",ShowBG="ActivitySignBG/2_ZhangMenDuiJue/img_picture3",},
  [14]={BaseID=14,PreDesText="玩法限制",ShowIcon="ActivitySignClanSkill/Clan_icon_duel_001",ShowName="进入限制",ShowDesText="1、每日免费赠送3次入场机会，超过3次后每次进入需要消耗门票；\n2、门票购买价格暂定为1500银锭，本次限量测试为期两周，期间暂不售卖门票。\n等不及参加《掌门对决》了吗？明天版本更新后就开启，一定要来哦。",ItemID=9655,PreBG="ActivitySignBG/2_ZhangMenDuiJue/img_picture4",ShowBG="ActivitySignBG/2_ZhangMenDuiJue/img_picture4",},
  [15]={BaseID=15,ShowIcon="ActivitySignClanSkill/Clan_icon_duel_002",ShowName="活动开启",ShowDesText="《掌门对决》玩法今日版本更新后正式开启！\n从老板娘-剧本选择入口进入，与其他玩家一较高下，赢取暗金角色卡！",ItemID=9655,ItemNum=2,PreBG="ActivitySignBG/2_ZhangMenDuiJue/img_picture5",ShowBG="ActivitySignBG/2_ZhangMenDuiJue/img_picture5",},
  [16]={BaseID=16,PreDesText="人物简介",ShowIcon="ActivitySignClanSkill/Clan_icon_role_001",ShowName="人物简介",ShowDesText="自幼与父亲相依为命，在其父前往无间秘境挑战却长久未归时，毅然踏上了寻找父亲的旅程",ItemID=8311,PreBG="ActivitySignBG/3_MiJingShouHuZhe/img_picture1",ShowBG="ActivitySignBG/3_MiJingShouHuZhe/img_picture1",},
  [17]={BaseID=17,PreDesText="专属天赋",ShowIcon="ActivitySignClanSkill/Clan_icon_role_002",ShowName="专属天赋",ShowDesText="专属天赋一：提升在无间秘境中造成的伤害\n专属天赋二：降低在无间秘境中受到的伤害\n专属天赋三：可以在无间秘境的战斗中复活，一场战斗仅触发一次",ItemID=365002,PreBG="ActivitySignBG/3_MiJingShouHuZhe/img_picture2",ShowBG="ActivitySignBG/3_MiJingShouHuZhe/img_picture2",},
  [18]={BaseID=18,PreDesText="传家宝",ShowItemList={"416510","420720",},ItemNum=300,PreBG="ActivitySignBG/3_MiJingShouHuZhe/img_picture3",ShowBG="ActivitySignBG/3_MiJingShouHuZhe/img_picture3",},
  [19]={BaseID=19,PreDesText="小铃铛",ShowRoleID=1030214010,ItemID=250601601,PreBG="ActivitySignBG/3_MiJingShouHuZhe/img_picture4",ShowBG="ActivitySignBG/3_MiJingShouHuZhe/img_picture4",},
  [20]={BaseID=20,ShowIcon="ActivitySignClanSkill/Clan_icon_duel_002",ShowName="人物解锁",ShowDesText="邀请方式：等待版本更新后，去自由模式无间秘境中找她吧",ItemID=250601304,PreBG="ActivitySignBG/3_MiJingShouHuZhe/img_picture5",ShowBG="ActivitySignBG/3_MiJingShouHuZhe/img_picture5",},
  [21]={BaseID=21,PreDesText="人物简介",ShowIcon="ChainClan/united_19",ShowName="人物简介",ShowDesText="容貌俊秀、神情孤傲的男子，气质与常人迥然不同，拒人千里之外却又有着致命的吸引力。",ItemID=364002,PreBG="ActivitySignBG/4_HeiSeJinYao/img_picture1",ShowBG="ActivitySignBG/4_HeiSeJinYao/img_picture1",},
  [22]={BaseID=22,PreDesText="专属天赋",ShowIcon="ActivitySignClanSkill/Clan_icon_role_002",ShowName="专属天赋",ShowDesText="专属天赋一：使用暗器类武学时，暴击值提升\n专属天赋二：吸血率提升\n专属天赋三：攻击中毒目标时，伤害提升",ItemID=365003,PreBG="ActivitySignBG/4_HeiSeJinYao/img_picture2",ShowBG="ActivitySignBG/4_HeiSeJinYao/img_picture2",},
  [23]={BaseID=23,PreDesText="传家宝",ShowItemList={"416511",},ItemID=35009,PreBG="ActivitySignBG/4_HeiSeJinYao/img_picture3",ShowBG="ActivitySignBG/4_HeiSeJinYao/img_picture3",},
  [24]={BaseID=24,PreDesText="诡魅药师",ShowRoleID=1040113003,ItemNum=300,PreBG="ActivitySignBG/4_HeiSeJinYao/img_picture4",ShowBG="ActivitySignBG/4_HeiSeJinYao/img_picture4",},
  [25]={BaseID=25,ShowIcon="ActivitySignClanSkill/Clan_icon_duel_002",ShowName="人物解锁",ShowDesText="邀请方式：等待版本更新后，去魔君乱江湖或自由模式剧本中找他吧",ItemID=8313,PreBG="ActivitySignBG/4_HeiSeJinYao/img_picture5",ShowBG="ActivitySignBG/4_HeiSeJinYao/img_picture5",},
  [26]={BaseID=26,PreDesText="人物简介",ShowIcon="ChainClan/united_7",ShowName="人物简介",ShowDesText="原名杨轻云。二十余年前拜入长生门，因偷学禁地武学被长生门驱逐。后来凭借在长生门学到的医术研制出各类奇特丹药，吸引到江南道赏识。不知出于何种原因，追随江南道，为白衣教效力。",ItemID=364002,PreBG="ActivitySignBG/5_YouChiChi/img_picture1",ShowBG="ActivitySignBG/5_YouChiChi/img_picture1",},
  [27]={BaseID=27,PreDesText="专属武学/天赋",ShowIcon="ActivitySignClanSkill/Clan_icon_role_002",ShowName="专属武学/天赋",ShowDesText="专属武学：为所有召唤单位随机添加各种增益状态\n\n专属天赋一：降低受到来自男性角色的伤害\n专属天赋二：释放自己的专属武学时，同时为召唤单位添加一个造成伤害提升的状态",ItemID=8311,PreBG="ActivitySignBG/5_YouChiChi/img_picture2",ShowBG="ActivitySignBG/5_YouChiChi/img_picture2",},
  [28]={BaseID=28,PreDesText="传家宝",ShowItemList={"440603",},ItemID=250601601,PreBG="ActivitySignBG/5_YouChiChi/img_picture3",ShowBG="ActivitySignBG/5_YouChiChi/img_picture3",},
  [29]={BaseID=29,PreDesText="云鬓销魂",ShowRoleID=1000012021,ItemNum=300,PreBG="ActivitySignBG/5_YouChiChi/img_picture4",ShowBG="ActivitySignBG/5_YouChiChi/img_picture4",},
  [30]={BaseID=30,ShowIcon="ActivitySignClanSkill/Clan_icon_duel_002",ShowName="人物解锁",ShowDesText="邀请方式：等待版本更新后，去魔君乱江湖或自由模式剧本中找他吧",ItemID=35002,PreBG="ActivitySignBG/5_YouChiChi/img_picture5",ShowBG="ActivitySignBG/5_YouChiChi/img_picture5",},
  [31]={BaseID=31,PreDesText="新剧本",ShowIcon="ActivitySignClanSkill/Clan_icon_story_001",ShowName="江湖濯玉录",ShowDesText="江头未是风波恶，别有人间行路难。\n\n一场旷世阴谋即将浮出水面……",ItemID=364002,PreBG="ActivitySignBG/6_YuWenKe/img_picture1",ShowBG="ActivitySignBG/6_YuWenKe/img_picture1",},
  [32]={BaseID=32,PreDesText="新角色",ShowIcon="ChainClan/united_11",ShowName="新角色",ShowDesText="宇文珂——宝剑锋从磨砺出，梅花香自苦寒来。\n\n石沉水——散香漫漫蕲簟滑，沉水悠悠越瓶寒。\n\n凌乌衣——莫听穿林打叶声，何妨吟啸且徐行。",ItemID=8311,PreBG="ActivitySignBG/6_YuWenKe/img_picture2",ShowBG="ActivitySignBG/6_YuWenKe/img_picture2",},
  [33]={BaseID=33,PreDesText="新玩法",ShowIcon="ActivitySignClanSkill/Clan_skill_6",ShowName="吸能切磋",ShowDesText="融合无誉无咎两大内功，通过切磋，将部分对方的属性吸为己用",ItemID=250601601,PreBG="ActivitySignBG/6_YuWenKe/img_picture3",ShowBG="ActivitySignBG/6_YuWenKe/img_picture3",},
  [34]={BaseID=34,PreDesText="新门派",ShowIcon="ChainClan/united_16",ShowName="新门派",ShowDesText="宇文山庄：\n宇文山庄乃是曾经武林中名声显赫的门派，曾被誉为天下第一庄。门中弟子擅腿法与拳法，战斗中能为自身附加增益状态，江湖中无人不惧。\n\n如意宫：\n如意宫是沈炎三弟子石如意所创，他以《无咎神功》延伸出一套邪法，能对敌人造成持续伤害，并且自身残血时会变得更强，令江湖中人闻风丧胆。",ItemNum=300,PreBG="ActivitySignBG/6_YuWenKe/img_picture4",ShowBG="ActivitySignBG/6_YuWenKe/img_picture4",},
  [35]={BaseID=35,ShowIcon="ActivitySignClanSkill/Clan_icon_duel_002",ShowName="剧本解锁",ShowDesText="剧本解锁：等待版本更新后，就去剧本选择界面进行游玩吧",ItemID=250601509,PreBG="ActivitySignBG/6_YuWenKe/img_picture5",ShowBG="ActivitySignBG/6_YuWenKe/img_picture5",},
  [36]={BaseID=36,PreDesText="人物简介",ShowIcon="ChainClan/united_5",ShowName="人物简介",ShowDesText="刀亲王的子嗣，全真教的绝顶高手，为报家仇血恨一路帮助宇文珂克服重重阻碍。",ItemID=364002,PreBG="ActivitySignBG/7_ALiang/img_picture1",ShowBG="ActivitySignBG/7_ALiang/img_picture1",},
  [37]={BaseID=37,PreDesText="不传秘闻",ShowIcon="ActivitySignClanSkill/Clan_icon_role_002",ShowName="不传秘闻",ShowDesText="十六年前秦忠贤挑起全真教与五毒教的矛盾，阿良为了抓住秦忠贤冒险加入全真教寻找线索。",ItemID=8311,PreBG="ActivitySignBG/7_ALiang/img_picture2",ShowBG="ActivitySignBG/7_ALiang/img_picture2",},
  [38]={BaseID=38,PreDesText="蛟龙斩",ShowRoleID=1230221006,ItemID=250601601,PreBG="ActivitySignBG/7_ALiang/img_picture3",ShowBG="ActivitySignBG/7_ALiang/img_picture3",},
  [39]={BaseID=39,PreDesText="传家宝",ShowItemList={"450719",},ItemNum=300,PreBG="ActivitySignBG/7_ALiang/img_picture4",ShowBG="ActivitySignBG/7_ALiang/img_picture4",},
  [40]={BaseID=40,ShowIcon="ActivitySignClanSkill/Clan_icon_duel_002",ShowName="队友解锁",ShowDesText="邀请方式：可以在魔君、自由剧本中的雪山迷宫中找到他",ItemID=250601509,PreBG="ActivitySignBG/7_ALiang/img_picture5",ShowBG="ActivitySignBG/7_ALiang/img_picture5",},
}
for k,v in pairs(ActivitySignReward) do
    setmetatable(v, {['__index'] = ActivitySignRewardDefault})
end

-- export table: ActivitySignReward
return ActivitySignReward
