-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local AdvLootTypeTable= {
  [1]={BaseID=1,BaseEnum="药材",Icon="icon_frame_migongshiquwu_0006",},
  [2]={BaseID=2,BaseEnum="花卉",Icon="icon_frame_migongshiquwu_0006",},
  [3]={BaseID=3,BaseEnum="矿石",Icon="icon_frame_migongshiquwu_000a",},
  [4]={BaseID=4,BaseEnum="肉食",Icon="icon_frame_migongshiquwu_0010",},
  [5]={BaseID=5,BaseEnum="蔬菜",Icon="icon_frame_migongshiquwu_000e",},
  [6]={BaseID=6,BaseEnum="化妆品",Icon="icon_frame_migongshiquwu_0016",},
  [7]={BaseID=7,BaseEnum="酒",Icon="icon_frame_migongshiquwu_0012",},
  [8]={BaseID=8,BaseEnum="铜币",Icon="icon_frame_migongshiquwu_0015",},
  [9]={BaseID=9,BaseEnum="生活道具",Icon="icon_frame_migongshiquwu_0016",},
  [10]={BaseID=10,BaseEnum="音律",Icon="icon_frame_migongshiquwu_0016",},
  [11]={BaseID=11,BaseEnum="游戏",Icon="icon_frame_migongshiquwu_0016",},
  [12]={BaseID=12,BaseEnum="书画",Icon="icon_frame_migongshiquwu_0014",},
  [13]={BaseID=13,BaseEnum="海鲜",Icon="icon_frame_migongshiquwu_0013",},
  [14]={BaseID=14,BaseEnum="银锭",Icon="icon_frame_migongshiquwu_0001",},
  [15]={BaseID=15,BaseEnum="藏宝图",Icon="icon_frame_migongshiquwu_0004",},
  [16]={BaseID=16,BaseEnum="残章",Icon="icon_frame_migongshiquwu_0005",},
  [17]={BaseID=17,BaseEnum="武学",Icon="icon_frame_migongshiquwu_000d",},
  [18]={BaseID=18,BaseEnum="武器",Icon="icon_frame_migongshiquwu_0017",},
  [19]={BaseID=19,BaseEnum="饰品",Icon="icon_frame_migongshiquwu_0011",},
  [20]={BaseID=20,BaseEnum="服装",Icon="icon_frame_migongshiquwu_0019",},
  [21]={BaseID=21,BaseEnum="任务用品",Icon="icon_frame_migongshiquwu_000f",},
  [22]={BaseID=22,BaseEnum="烹饪材料",Icon="icon_frame_migongshiquwu_0016",},
  [23]={BaseID=23,BaseEnum="装备",Icon="icon_frame_migongshiquwu_0011",},
  [24]={BaseID=24,BaseEnum="杂物",Icon="icon_frame_migongshiquwu_0016",},
  [25]={BaseID=25,BaseEnum="吸能",Icon="icon_frame_migongshiquwu_0020",},
}

-- export table: AdvLootTypeTable
return AdvLootTypeTable
