-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local AITemplate= {
  [1]={BaseID=1,NameID=0,StrategyList=0,},
  [2]={BaseID=2,NameID=0,StrategyList=0,},
  [3]={BaseID=3,NameID=0,StrategyList=0,},
}

-- export table: AITemplate
return AITemplate
