-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local AllowEditRolePictureConfig= {
  [1]={BaseID=1,ResourcePictureID=514,},
  [2]={BaseID=2,ResourcePictureID=515,},
  [3]={BaseID=3,ResourcePictureID=516,},
  [4]={BaseID=4,ResourcePictureID=517,},
  [5]={BaseID=5,ResourcePictureID=518,},
  [6]={BaseID=6,ResourcePictureID=519,},
  [7]={BaseID=7,ResourcePictureID=520,},
  [8]={BaseID=8,ResourcePictureID=521,},
  [9]={BaseID=9,ResourcePictureID=526,},
  [10]={BaseID=10,ResourcePictureID=527,},
  [11]={BaseID=11,ResourcePictureID=528,},
  [12]={BaseID=12,ResourcePictureID=529,},
  [13]={BaseID=13,ResourcePictureID=530,},
  [14]={BaseID=14,ResourcePictureID=531,},
}

-- export table: AllowEditRolePictureConfig
return AllowEditRolePictureConfig
