-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local AllowEditRoleConfig= {
  [1]={BaseID=1,RoleID=1020101001,},
  [2]={BaseID=2,RoleID=1020101002,},
  [3]={BaseID=3,RoleID=1020101003,},
  [4]={BaseID=4,RoleID=1020101004,},
}

-- export table: AllowEditRoleConfig
return AllowEditRoleConfig
