-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local AllowEditRoleModelConfig= {
  [1]={BaseID=1,ResourceModelID=1071,},
  [2]={BaseID=2,ResourceModelID=1072,},
  [3]={BaseID=3,ResourceModelID=1073,},
  [4]={BaseID=4,ResourceModelID=1074,},
  [5]={BaseID=5,ResourceModelID=1075,},
  [6]={BaseID=6,ResourceModelID=1076,},
  [7]={BaseID=7,ResourceModelID=1077,},
  [8]={BaseID=8,ResourceModelID=1078,},
  [9]={BaseID=9,ResourceModelID=1079,},
  [10]={BaseID=10,ResourceModelID=1080,},
  [11]={BaseID=11,ResourceModelID=1081,},
  [12]={BaseID=12,ResourceModelID=1082,},
  [13]={BaseID=13,ResourceModelID=1083,},
  [14]={BaseID=14,ResourceModelID=1084,},
  [15]={BaseID=15,ResourceModelID=1085,},
  [16]={BaseID=16,ResourceModelID=1086,},
  [17]={BaseID=17,ResourceModelID=1087,},
  [18]={BaseID=18,ResourceModelID=1088,},
  [19]={BaseID=19,ResourceModelID=1089,},
  [20]={BaseID=20,ResourceModelID=1090,},
}

-- export table: AllowEditRoleModelConfig
return AllowEditRoleModelConfig
