-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local AllowEditItemConfig= {
  [1]={BaseID=1,ItemTypeID=9,},
  [2]={BaseID=2,ItemTypeID=10,},
  [3]={BaseID=3,ItemTypeID=11,},
  [4]={BaseID=4,ItemTypeID=12,},
  [5]={BaseID=5,ItemTypeID=13,},
  [6]={BaseID=6,ItemTypeID=27,},
  [7]={BaseID=7,ItemTypeID=28,},
  [8]={BaseID=8,ItemTypeID=29,},
  [9]={BaseID=9,ItemTypeID=3,},
  [10]={BaseID=10,ItemTypeID=4,},
  [11]={BaseID=11,ItemTypeID=5,},
  [12]={BaseID=12,ItemTypeID=47,},
  [13]={BaseID=13,ItemTypeID=46,},
  [14]={BaseID=14,ItemTypeID=21,},
  [15]={BaseID=15,ItemTypeID=42,},
}

-- export table: AllowEditItemConfig
return AllowEditItemConfig
