-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum ShopBuyLimitResetType
-- enum ShopItemBuyLimitType
require("common");


local ArenaShop= {
  [1]={BaseID=1,ItemID=7901,ItemName="普通茗茶",OriginValue=10,MaxBuyNumsPeriod=ShopBuyLimitResetType.SBLRT_WEEKLY,MaxBuyNums=20,UnlockType=ShopItemBuyLimitType.SIBLT_Null,UnlockID=0,},
  [2]={BaseID=2,ItemID=7902,ItemName="精良茗茶",OriginValue=100,MaxBuyNumsPeriod=ShopBuyLimitResetType.SBLRT_WEEKLY,MaxBuyNums=5,UnlockType=ShopItemBuyLimitType.SIBLT_ARENA_PUBLIC,UnlockID=8,},
  [3]={BaseID=3,ItemID=7903,ItemName="优秀茗茶",OriginValue=500,MaxBuyNumsPeriod=ShopBuyLimitResetType.SBLRT_WEEKLY,MaxBuyNums=2,UnlockType=ShopItemBuyLimitType.SIBLT_ARENA_PUBLIC,UnlockID=2,},
  [4]={BaseID=4,ItemID=7904,ItemName="上乘茗茶",OriginValue=1000,MaxBuyNumsPeriod=ShopBuyLimitResetType.SBLRT_WEEKLY,MaxBuyNums=2,UnlockType=ShopItemBuyLimitType.SIBLT_ARENA_MASTER,UnlockID=8,},
  [5]={BaseID=5,ItemID=7905,ItemName="极品茗茶",OriginValue=5000,MaxBuyNumsPeriod=ShopBuyLimitResetType.SBLRT_WEEKLY,MaxBuyNums=1,UnlockType=ShopItemBuyLimitType.SIBLT_ARENA_MASTER,UnlockID=2,},
  [6]={BaseID=6,ItemID=7905,ItemName="珍稀茗茶",OriginValue=10000,MaxBuyNumsPeriod=ShopBuyLimitResetType.SBLRT_WEEKLY,MaxBuyNums=1,UnlockType=ShopItemBuyLimitType.SIBLT_ARENA_CLAN,UnlockID=8,},
  [7]={BaseID=7,ItemID=1602,ItemName="侠客行经脉丹",OriginValue=248,MaxBuyNumsPeriod=ShopBuyLimitResetType.SBLRT_NULL,MaxBuyNums=0,UnlockType=ShopItemBuyLimitType.SIBLT_Null,UnlockID=0,},
  [8]={BaseID=8,ItemID=250601608,ItemName="诗词礼包",OriginValue=1000,MaxBuyNumsPeriod=ShopBuyLimitResetType.SBLRT_NULL,MaxBuyNums=0,UnlockType=ShopItemBuyLimitType.SIBLT_Null,UnlockID=0,},
}

-- export table: ArenaShop
return ArenaShop
