-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum AttrType
-- enum TBoolean
require("common");


local AttrIsPercentDefault = {PerMyriad=TBoolean.BOOL_YES,ShowAsPercent=TBoolean.BOOL_YES,}
local AttrIsPercent= {
  [36]={BaseID=AttrType.ATTR_HITATKPER,},
  [37]={BaseID=AttrType.ATTR_CRITATKPER,},
  [38]={BaseID=AttrType.ATTR_CONTINUATKPER,},
  [39]={BaseID=AttrType.ATTR_HEJILV,},
  [40]={BaseID=AttrType.ATTR_LIANZHAOLV,},
  [41]={BaseID=AttrType.ATTR_IGNOREDEFPER,},
  [42]={BaseID=AttrType.ATTR_SHANBILV,},
  [43]={BaseID=AttrType.ATTR_BAOJIDIKANGLV,},
  [44]={BaseID=AttrType.ATTR_KANGLIANJILV,},
  [45]={BaseID=AttrType.ATTR_POZHAOLV,},
  [46]={BaseID=AttrType.ATTR_FANJILV,},
  [47]={BaseID=AttrType.ATTR_SUCKHP,},
  [48]={BaseID=AttrType.ATTR_FANTANLV,},
  [49]={BaseID=AttrType.ATTR_CRITATKTIME,},
  [50]={BaseID=AttrType.ATTR_FANTANBEISHU,},
  [51]={BaseID=AttrType.ATTR_NEILIYANGXING,PerMyriad=TBoolean.BOOL_NO,ShowAsPercent=TBoolean.BOOL_NO,},
  [52]={BaseID=AttrType.ATTR_NEILIYINXING,PerMyriad=TBoolean.BOOL_NO,ShowAsPercent=TBoolean.BOOL_NO,},
  [70]={BaseID=AttrType.ATTR_JUEZHAOLV,},
  [71]={BaseID=AttrType.ATTR_YUANHULV,},
  [95]={BaseID=AttrType.ATTR_ZUIZHONGZHILIAOBAIFENBI,},
  [125]={BaseID=AttrType.ATTR_ROLE_AOYI_PERCENT,},
  [133]={BaseID=AttrType.ATTR_WEILIXISHUDUGU,},
  [302]={BaseID=AttrType.MP_ZUIZHONGSHANGHAIXIUZHENGBAIFENBI,},
  [304]={BaseID=AttrType.MP_WEILI,},
  [318]={BaseID=AttrType.MP_LIANZHAOWEILI,},
  [319]={BaseID=AttrType.MP_JUEZHAOWEILI,},
  [320]={BaseID=AttrType.MP_AOYIWEILI,},
  [321]={BaseID=AttrType.MP_DUODUANGONGJIZHUCIWEILI,},
  [322]={BaseID=AttrType.MP_DUODUANGONGJIWEILI,},
  [325]={BaseID=AttrType.MP_WUXUEJINGYANJIACHENG,},
  [336]={BaseID=AttrType.MP_CHUANTOUWEILI,},
  [338]={BaseID=AttrType.MP_TANSHEWEILIDIJIAN,},
  [341]={BaseID=AttrType.MP_SUDUBIANDONG,},
  [342]={BaseID=AttrType.MP_ZUIZHONGSHANGHAIFUJIABAIFENBI,},
  [343]={BaseID=AttrType.MP_ZUIZHONGSHANGHAIJIANMIANBAIFENBI,},
  [347]={BaseID=AttrType.MP_WEILIJIXIAN,},
  [349]={BaseID=AttrType.MP_ZhenQiXiaoHaoBeiShu,},
  [350]={BaseID=AttrType.MP_FANJIGAILV,},
  [355]={BaseID=AttrType.MP_BASE_WEILI,},
  [356]={BaseID=AttrType.MP_BASE_WEILI_MAX,},
  [358]={BaseID=AttrType.MP_WEILI_CHENGZHANG_MAX,},
  [359]={BaseID=AttrType.MP_WEILIXISHU,ShowAsPercent=TBoolean.BOOL_NO,},
  [382]={BaseID=AttrType.ATTR_WEILIBAIFENBI,},
  [384]={BaseID=AttrType.ATTR_DUODUANGONGJIZUCIWEILIBAIFENBI,},
  [385]={BaseID=AttrType.ATTR_FANGYUTISHENGLV,},
}
for k,v in pairs(AttrIsPercent) do
    setmetatable(v, {['__index'] = AttrIsPercentDefault})
end

-- export table: AttrIsPercent
return AttrIsPercent
