-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local AttrmaxDifficutyDefault = {HitRate=26000,MissRate=6500,CritTimes=44000,PoZhaoRate=13000,BloodSuckRate=26000,Rebound=44000,AidRate=10000,UniqueSkillRate=6500,}
local AttrmaxDifficuty= {
  [1]={name=1,HitRate=24000,MissRate=6000,CritRate=10000,CritDefenseRate=10000,CritTimes=40000,RepeatRate=20000,LianZhaoRate=20000,JointAttackRate=10000,PenetrateDefenseRate=20000,AntiHitRate=20000,PoZhaoRate=12000,CounterAttackRate=20000,BloodSuckRate=24000,ReboundRate=20000,Rebound=40000,UniqueSkillRate=6000,},
  [2]={name=2,HitRate=24000,MissRate=6000,CritRate=10000,CritDefenseRate=10000,CritTimes=40000,RepeatRate=20000,LianZhaoRate=20000,JointAttackRate=10000,PenetrateDefenseRate=20000,AntiHitRate=20000,PoZhaoRate=12000,CounterAttackRate=20000,BloodSuckRate=24000,ReboundRate=20000,Rebound=40000,UniqueSkillRate=6000,},
  [3]={name=3,HitRate=24000,MissRate=6000,CritRate=10000,CritDefenseRate=10000,CritTimes=40000,RepeatRate=20000,LianZhaoRate=20000,JointAttackRate=10000,PenetrateDefenseRate=20000,AntiHitRate=20000,PoZhaoRate=12000,CounterAttackRate=20000,BloodSuckRate=24000,ReboundRate=20000,Rebound=40000,UniqueSkillRate=6000,},
  [4]={name=4,HitRate=24000,MissRate=6000,CritRate=10000,CritDefenseRate=10000,CritTimes=40000,RepeatRate=20000,LianZhaoRate=20000,JointAttackRate=10000,PenetrateDefenseRate=20000,AntiHitRate=20000,PoZhaoRate=12000,CounterAttackRate=20000,BloodSuckRate=24000,ReboundRate=20000,Rebound=40000,UniqueSkillRate=6000,},
  [5]={name=5,CritRate=12000,CritDefenseRate=12000,RepeatRate=24000,LianZhaoRate=24000,JointAttackRate=12000,PenetrateDefenseRate=24000,AntiHitRate=24000,CounterAttackRate=24000,ReboundRate=24000,},
  [6]={name=6,CritRate=12000,CritDefenseRate=12000,RepeatRate=24000,LianZhaoRate=24000,JointAttackRate=12000,PenetrateDefenseRate=24000,AntiHitRate=24000,CounterAttackRate=24000,ReboundRate=24000,},
  [7]={name=7,CritRate=12000,CritDefenseRate=12000,RepeatRate=24000,LianZhaoRate=24000,JointAttackRate=12000,PenetrateDefenseRate=24000,AntiHitRate=24000,CounterAttackRate=24000,ReboundRate=24000,},
  [8]={name=8,CritRate=12000,CritDefenseRate=12000,RepeatRate=24000,LianZhaoRate=24000,JointAttackRate=12000,PenetrateDefenseRate=24000,AntiHitRate=24000,CounterAttackRate=24000,ReboundRate=24000,},
  [9]={name=9,CritRate=14000,CritDefenseRate=14000,RepeatRate=28000,LianZhaoRate=28000,JointAttackRate=14000,PenetrateDefenseRate=28000,AntiHitRate=28000,CounterAttackRate=28000,ReboundRate=28000,},
  [10]={name=10,HitRate=28000,MissRate=7000,CritRate=14000,CritDefenseRate=14000,CritTimes=48000,RepeatRate=28000,LianZhaoRate=28000,JointAttackRate=14000,PenetrateDefenseRate=28000,AntiHitRate=28000,PoZhaoRate=14000,CounterAttackRate=28000,BloodSuckRate=28000,ReboundRate=28000,Rebound=48000,UniqueSkillRate=7000,},
}
for k,v in pairs(AttrmaxDifficuty) do
    setmetatable(v, {['__index'] = AttrmaxDifficutyDefault})
end

-- export table: AttrmaxDifficuty
return AttrmaxDifficuty
