-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local AudioUI= {
  [1]={BaseID=1,ButtonDefault=4000,ButtonClose=4001,ButtonCancel=4002,ButtonFold=4004,EventBattle=4010,EventBoss=4005,EventCity=4011,EventRoll=4012,EventRollTreasure=4015,EventGold=4032,EventBigMap=4026,EventQuestion1=2002076,EventQuestion2=2002077,EventQuestion3=2002079,EventQuestionPage=4043,EventBattleWin=4040,EventBattleLose=4041,EventQuestDone=4047,EventFavorUp=4016,EventTalentGet=4017,EventAttrUp=4025,EventLevelUp=4051,EventMaze1=4018,EventMaze2=4034,EventTreasure1=4023,EventTreasure2=4022,EventTreasure3=4021,VoiceHurtMale=7000,VoiceHurtFemale=7001,VoiceDieMale=7002,VoiceDieFemale=7003,},
}

-- export table: AudioUI
return AudioUI
