-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local BabyBaseAttr= {
  [1]={BaseID=1,BaseHP=26870,BaseMP=7900,BaseDefense=475,MartialAttack=2680,QuanZhangJingTong=250,JianFaJingTong=250,DaoFaJingTong=250,TuiFaJingTong=250,QiMenJingTong=250,AnQiJingTong=250,YiShuJingTong=250,NeiGongJingTong=250,},
}

-- export table: BabyBaseAttr
return BabyBaseAttr
