-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum BabyUpgradeType
require("common");


local BabyUpgradeTask= {
  [1]={BabyUpgradeType=BabyUpgradeType.BUT_Story,TaskID=4547,Weight=1,},
  [2]={BabyUpgradeType=BabyUpgradeType.BUT_BeRole,TaskID=4548,Weight=1,},
  [3]={BabyUpgradeType=BabyUpgradeType.BUT_Item,TaskID=4555,Weight=1,},
  [4]={BabyUpgradeType=BabyUpgradeType.BUT_Hero,TaskID=4549,Weight=1,},
  [5]={BabyUpgradeType=BabyUpgradeType.BUT_Advise,TaskID=4551,Weight=1,},
  [6]={BabyUpgradeType=BabyUpgradeType.BUT_Prop,TaskID=4552,Weight=1,},
  [7]={BabyUpgradeType=BabyUpgradeType.BUT_Clan,TaskID=4550,Weight=1,},
  [8]={BabyUpgradeType=BabyUpgradeType.BUT_Wenpon,TaskID=4553,Weight=1,},
  [9]={BabyUpgradeType=BabyUpgradeType.BUT_Beauty,TaskID=4554,Weight=1,},
  [10]={BabyUpgradeType=BabyUpgradeType.BUT_Food,TaskID=4556,Weight=3,},
  [11]={BabyUpgradeType=BabyUpgradeType.BUT_Kongfun,TaskID=4557,Weight=3,},
}

-- export table: BabyUpgradeTask
return BabyUpgradeTask
