-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local BabyBassAttrDes= {
  [1]={BaseID=1,DesID=180084,HpStandardVal=26490,MpStandardVal=12285,DefenseStandardVal=730,MartialAttackStandardVal=4180,HpLimitMin=1500,HpLimitMax=1950,MpLimitMin=1200,MpLimitMax=1500,DefenseLimitMin=72,DefenseLimitMax=90,MartialAttackLimitMin=400,MartialAttackLimitMax=510,},
  [2]={BaseID=2,DesID=180085,HpStandardVal=71670,MpStandardVal=27350,DefenseStandardVal=1640,MartialAttackStandardVal=9300,HpLimitMin=1951,HpLimitMax=3330,MpLimitMin=1501,MpLimitMax=1850,DefenseLimitMin=91,DefenseLimitMax=115,MartialAttackLimitMin=511,MartialAttackLimitMax=630,},
  [3]={BaseID=3,DesID=180086,HpStandardVal=160510,MpStandardVal=56650,DefenseStandardVal=3400,MartialAttackStandardVal=19370,HpLimitMin=3331,HpLimitMax=5790,MpLimitMin=1851,MpLimitMax=2490,DefenseLimitMin=116,DefenseLimitMax=150,MartialAttackLimitMin=631,MartialAttackLimitMax=850,},
  [4]={BaseID=4,DesID=180087,HpStandardVal=335300,MpStandardVal=115230,DefenseStandardVal=6920,MartialAttackStandardVal=39180,HpLimitMin=5791,HpLimitMax=9940,MpLimitMin=2491,MpLimitMax=3500,DefenseLimitMin=151,DefenseLimitMax=210,MartialAttackLimitMin=851,MartialAttackLimitMax=1200,},
  [5]={BaseID=5,DesID=180088,HpStandardVal=99999999,MpStandardVal=99999999,DefenseStandardVal=99999999,MartialAttackStandardVal=99999999,HpLimitMin=9941,HpLimitMax=17000,MpLimitMin=3501,MpLimitMax=5400,DefenseLimitMin=211,DefenseLimitMax=320,MartialAttackLimitMin=1201,MartialAttackLimitMax=1840,},
  [6]={BaseID=6,DesID=180089,HpStandardVal=99999999,MpStandardVal=99999999,DefenseStandardVal=99999999,MartialAttackStandardVal=99999999,HpLimitMin=9941,HpLimitMax=17000,MpLimitMin=3501,MpLimitMax=5400,DefenseLimitMin=211,DefenseLimitMax=320,MartialAttackLimitMin=1201,MartialAttackLimitMax=1840,},
}

-- export table: BabyBassAttrDes
return BabyBassAttrDes
