-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum BattleFactorType
require("common");


local BattleFactorRelate= {
  [1]={BaseID=BattleFactorType.BFACT_speedUpPanel,Value=1,},
  [2]={BaseID=BattleFactorType.BFACT_speedDownPanel,Value=0,},
  [3]={BaseID=BattleFactorType.BFACT_speedChangeFactor,Value=0.5,},
  [4]={BaseID=BattleFactorType.BFACT_speedMinFactor,Value=1.33,},
  [5]={BaseID=BattleFactorType.BFACT_speedNorm,Value=2,},
  [6]={BaseID=BattleFactorType.BFACT_speedDown,Value=0.4,},
  [7]={BaseID=BattleFactorType.BFACT_speedUp,Value=2,},
  [8]={BaseID=BattleFactorType.BFACT_DodgeMax,Value=0.3,},
  [9]={BaseID=BattleFactorType.BFACT_DodgeUpPanel,Value=0.3,},
  [10]={BaseID=BattleFactorType.BFACT_DodgeDown,Value=0,},
  [11]={BaseID=BattleFactorType.BFACT_CritMax,Value=0.8,},
  [12]={BaseID=BattleFactorType.BFACT_CritDownPanel,Value=0.05,},
  [13]={BaseID=BattleFactorType.BFACT_CritUpPanel,Value=0.6,},
  [14]={BaseID=BattleFactorType.BFACT_CritDgeBase,Value=1,},
  [15]={BaseID=BattleFactorType.BFACT_CritDgeMax,Value=0.5,},
  [16]={BaseID=BattleFactorType.BFACT_CritDgeDownPanel,Value=0,},
  [17]={BaseID=BattleFactorType.BFACT_CritDgeUpPanel,Value=0.5,},
  [18]={BaseID=BattleFactorType.BFACT_CritDgeDown,Value=1.1,},
  [19]={BaseID=BattleFactorType.BFACT_seeThroughMax,Value=0.3,},
  [20]={BaseID=BattleFactorType.BFACT_CritDgeUp,Value=3,},
  [21]={BaseID=BattleFactorType.BFACT_seeThroughUpPanel,Value=0.15,},
  [22]={BaseID=BattleFactorType.BFACT_seeThroughDownPanel,Value=0,},
  [23]={BaseID=BattleFactorType.BFACT_seeThroughDown,Value=0.01,},
  [24]={BaseID=BattleFactorType.BFACT_seeThroughUp,Value=1,},
  [25]={BaseID=BattleFactorType.BFACT_seeThroughDge,Value=0.5,},
  [28]={BaseID=BattleFactorType.BFACT_reboundMax,Value=0.4,},
  [29]={BaseID=BattleFactorType.BFACT_reboundDown,Value=0,},
  [30]={BaseID=BattleFactorType.BFACT_reboundUpPanel,Value=0.4,},
  [31]={BaseID=BattleFactorType.BFACT_reboundDownPanel,Value=0,},
  [32]={BaseID=BattleFactorType.BFACT_reboundUp,Value=1,},
  [33]={BaseID=BattleFactorType.BFACT_counterMax,Value=0.4,},
  [34]={BaseID=BattleFactorType.BFACT_counterDown,Value=0,},
  [35]={BaseID=BattleFactorType.BFACT_counterUpPanel,Value=0.4,},
  [36]={BaseID=BattleFactorType.BFACT_counterDownPanel,Value=0,},
  [37]={BaseID=BattleFactorType.BFACT_counterUp,Value=1.5,},
  [38]={BaseID=BattleFactorType.BFACT_ComboMax,Value=0.6,},
  [39]={BaseID=BattleFactorType.BFACT_ComboDownPanel,Value=0.05,},
  [40]={BaseID=BattleFactorType.BFACT_ComboUpPanel,Value=0.5,},
}

-- export table: BattleFactorRelate
return BattleFactorRelate
