-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local BattleFactorDefault = {crit_m=0,critDge_m=-600,dodge_m=0,speed_n=207,seeThrough_m=-400,rebound_m=0,Combo_m=0,counter_m=-600,}
local BattleFactor= {
  [1]={BaseID=1,physique_hp=50,crit_n=5348,critDge_n=605,dodge_n=190,speed_m=-72,seeThrough_n=1344,rebound_n=1248,Combo_n=3744,AntiCombo=0,def_m=120,def_n=319,counter_n=768,},
  [2]={BaseID=2,physique_hp=50,crit_n=5081,critDge_n=640,dodge_n=211,speed_m=-85,seeThrough_n=1425,rebound_n=1244,Combo_n=3732,AntiCombo=10,def_m=142,def_n=376,counter_n=814,},
  [3]={BaseID=3,physique_hp=50,crit_n=4974,critDge_n=736,dodge_n=236,speed_m=-88,seeThrough_n=1639,rebound_n=1211,Combo_n=3632,AntiCombo=20,def_m=169,def_n=450,counter_n=936,},
  [4]={BaseID=4,physique_hp=50,crit_n=4653,critDge_n=837,dodge_n=260,speed_m=-91,seeThrough_n=1863,rebound_n=1161,Combo_n=3482,AntiCombo=40,def_m=197,def_n=523,counter_n=1065,},
  [5]={BaseID=5,physique_hp=51,crit_n=5081,critDge_n=1493,dodge_n=454,speed_m=-95,seeThrough_n=3322,rebound_n=1473,Combo_n=4418,AntiCombo=80,def_m=391,def_n=1040,counter_n=1898,},
  [6]={BaseID=6,physique_hp=52,crit_n=4867,critDge_n=1604,dodge_n=485,speed_m=-97,seeThrough_n=3569,rebound_n=1448,Combo_n=4343,AntiCombo=160,def_m=421,def_n=1119,counter_n=2039,},
  [7]={BaseID=7,physique_hp=53,crit_n=4439,critDge_n=1716,dodge_n=515,speed_m=-101,seeThrough_m=-408,seeThrough_n=3816,rebound_n=1323,Combo_n=3969,AntiCombo=360,def_m=454,def_n=1205,counter_n=2181,},
  [8]={BaseID=8,physique_hp=54,crit_n=4386,critDge_n=2053,dodge_n=610,speed_m=-104,seeThrough_m=-488,seeThrough_n=4568,rebound_n=1385,Combo_n=4156,AntiCombo=560,def_m=556,def_n=1476,counter_n=2610,},
  [9]={BaseID=9,physique_hp=55,crit_n=3904,critDge_m=-623,critDge_n=2185,dodge_n=644,speed_m=-107,seeThrough_m=-519,seeThrough_n=4860,rebound_n=1236,Combo_n=3707,AntiCombo=760,def_m=592,def_n=1572,counter_n=2777,},
  [10]={BaseID=10,physique_hp=56,crit_n=3744,critDge_m=-665,critDge_n=2331,dodge_n=754,speed_m=-111,seeThrough_m=-554,seeThrough_n=5185,rebound_n=1248,Combo_n=3744,AntiCombo=960,def_m=704,def_n=1872,counter_n=2963,},
  [11]={BaseID=11,physique_hp=57,crit_n=3477,critDge_m=-709,critDge_n=2487,dodge_n=800,speed_m=-113,seeThrough_m=-591,seeThrough_n=5533,rebound_n=1161,Combo_n=3482,AntiCombo=1160,def_m=751,def_n=1996,counter_n=3162,},
  [12]={BaseID=12,physique_hp=58,crit_n=3477,critDge_m=-934,critDge_n=3275,dodge_n=1036,speed_m=-117,seeThrough_m=-778,seeThrough_n=7284,rebound_n=1236,Combo_n=3707,AntiCombo=1360,def_m=994,def_n=2640,counter_n=4162,},
  [13]={BaseID=13,physique_hp=59,crit_n=3049,critDge_m=-987,critDge_n=3461,dodge_n=1094,speed_m=-121,seeThrough_m=-823,seeThrough_n=7699,rebound_n=1111,Combo_n=3332,AntiCombo=1560,def_m=1057,def_n=2809,counter_n=4400,},
  [14]={BaseID=14,physique_hp=61,crit_n=2888,critDge_m=-1039,critDge_n=3643,dodge_n=1146,speed_m=-123,seeThrough_m=-866,seeThrough_n=8103,rebound_n=1061,Combo_n=3182,AntiCombo=1760,def_m=1116,def_n=2966,counter_n=4630,},
  [15]={BaseID=15,physique_hp=62,crit_n=3102,critDge_m=-1101,critDge_n=3860,dodge_n=1284,speed_m=-127,speed_n=248,seeThrough_m=-918,seeThrough_n=8586,rebound_n=1161,Combo_n=3482,AntiCombo=1960,def_m=1260,def_n=3348,counter_n=4906,},
  [16]={BaseID=16,physique_hp=63,crit_n=3583,critDge_m=-1726,critDge_n=6050,dodge_n=1934,speed_m=-130,speed_n=322,seeThrough_m=-1438,seeThrough_n=13457,rebound_n=1485,Combo_n=4455,AntiCombo=2160,def_m=1928,def_n=5125,counter_n=7690,},
  [17]={BaseID=17,physique_hp=64,crit_n=3690,critDge_m=-1778,critDge_n=6232,dodge_n=1989,speed_m=-133,speed_n=396,seeThrough_m=-1482,seeThrough_n=13861,rebound_n=1523,Combo_n=4568,AntiCombo=2360,def_m=1993,def_n=5297,counter_n=7921,},
  [18]={BaseID=18,physique_hp=66,crit_n=3797,critDge_m=-1837,critDge_n=6438,dodge_n=2065,speed_m=-137,speed_n=929,seeThrough_m=-1531,seeThrough_n=14321,rebound_n=1585,Combo_n=4755,AntiCombo=2560,def_m=2076,def_n=5517,counter_n=8183,},
  [19]={BaseID=19,physique_hp=67,crit_n=3904,critDge_m=-1893,critDge_n=6636,dodge_n=2124,speed_m=-140,speed_n=888,seeThrough_m=-1578,seeThrough_n=14759,rebound_n=1610,Combo_n=4830,AntiCombo=2760,def_m=2154,def_n=5724,counter_n=8434,},
  [20]={BaseID=20,physique_hp=69,crit_n=4546,critDge_m=-2385,critDge_n=8361,dodge_n=2660,speed_m=-143,speed_n=961,seeThrough_m=-1988,seeThrough_n=18597,rebound_n=1972,Combo_n=5916,AntiCombo=2960,def_m=2707,def_n=7194,counter_n=10627,},
  [21]={BaseID=21,physique_hp=70,crit_n=4653,critDge_m=-2449,critDge_n=8583,dodge_n=2730,speed_m=-146,speed_n=920,seeThrough_m=-2041,seeThrough_n=19091,rebound_n=2022,Combo_n=6065,AntiCombo=3160,def_m=2778,def_n=7382,counter_n=10909,},
  [22]={BaseID=22,physique_hp=72,crit_n=4760,critDge_m=-2514,critDge_n=8810,dodge_n=2801,speed_m=-149,speed_n=994,seeThrough_m=-2095,seeThrough_n=19596,rebound_n=2072,Combo_n=6215,AntiCombo=3360,def_m=2850,def_n=7574,counter_n=11198,},
  [23]={BaseID=23,physique_hp=73,crit_n=5562,critDge_m=-3136,critDge_n=10990,dodge_n=3469,speed_m=-153,speed_n=952,seeThrough_m=-2613,seeThrough_n=24445,rebound_n=2521,Combo_n=7563,AntiCombo=3560,def_m=3524,def_n=9366,counter_n=13968,},
  [24]={BaseID=24,physique_hp=75,crit_n=5669,critDge_m=-3206,critDge_n=11237,dodge_n=3555,speed_m=-156,speed_n=1026,seeThrough_m=-2672,seeThrough_n=24995,rebound_n=2583,Combo_n=7750,AntiCombo=3760,def_m=3607,def_n=9586,counter_n=14283,},
  [25]={BaseID=25,physique_hp=77,crit_n=5883,critDge_m=-3304,critDge_n=11581,dodge_n=3696,speed_m=-159,speed_n=984,seeThrough_m=-2754,seeThrough_n=25758,rebound_n=2683,Combo_n=8050,AntiCombo=3960,def_m=3745,def_n=9953,counter_n=14719,},
  [26]={BaseID=26,physique_hp=78,crit_n=6846,critDge_m=-4047,critDge_n=14184,dodge_n=4475,speed_m=-162,speed_n=1058,seeThrough_m=-3373,seeThrough_n=31549,rebound_n=3195,Combo_n=9585,AntiCombo=4160,def_m=4537,def_n=12057,counter_n=18028,},
  [27]={BaseID=27,physique_hp=80,crit_n=7007,critDge_m=-4131,critDge_n=14478,dodge_n=4581,speed_m=-166,speed_n=1017,seeThrough_m=-3442,seeThrough_n=32200,rebound_n=3270,Combo_n=9809,AntiCombo=4360,def_m=4639,def_n=12328,counter_n=18400,},
  [28]={BaseID=28,physique_hp=82,crit_n=7220,critDge_m=-4236,critDge_n=14845,dodge_n=4725,speed_m=-169,speed_n=1090,seeThrough_m=-3530,seeThrough_n=33019,rebound_n=3370,Combo_n=10109,AntiCombo=4560,def_m=4783,def_n=12711,counter_n=18868,},
  [29]={BaseID=29,physique_hp=84,crit_n=7381,critDge_m=-4328,critDge_n=15168,dodge_n=4839,speed_m=-172,speed_n=1049,seeThrough_m=-3607,seeThrough_n=33737,rebound_n=3444,Combo_n=10333,AntiCombo=4760,def_m=4900,def_n=13020,counter_n=19279,},
  [30]={BaseID=30,physique_hp=86,crit_n=9788,critDge_m=-5250,critDge_n=18398,dodge_n=6380,speed_m=-176,speed_n=1007,seeThrough_m=-4375,seeThrough_n=40920,rebound_n=4580,Combo_n=13740,AntiCombo=4960,def_m=6410,def_n=17035,counter_n=23383,},
  [31]={BaseID=31,physique_hp=88,crit_n=10269,critDge_m=-5355,critDge_n=18767,dodge_n=6635,speed_m=-178,speed_n=1081,seeThrough_m=-4462,seeThrough_n=41740,rebound_n=4780,Combo_n=14340,AntiCombo=5160,def_m=6660,def_n=17698,counter_n=23851,},
  [32]={BaseID=32,physique_hp=90,crit_n=10804,critDge_m=-5461,critDge_n=19140,dodge_n=6914,speed_m=-182,speed_n=1040,seeThrough_m=-4551,seeThrough_n=42570,rebound_n=4980,Combo_n=14939,AntiCombo=5360,def_m=6934,def_n=18425,counter_n=24326,},
  [33]={BaseID=33,physique_hp=92,crit_n=11339,critDge_m=-5575,critDge_n=19538,dodge_n=7230,speed_m=-185,speed_n=1113,seeThrough_m=-4646,seeThrough_n=43457,rebound_n=5229,Combo_n=15687,AntiCombo=5560,def_m=7243,def_n=19248,counter_n=24833,},
  [34]={BaseID=34,physique_hp=94,crit_n=11981,critDge_m=-5696,critDge_n=19962,dodge_n=7575,speed_m=-188,speed_n=1187,seeThrough_m=-4747,seeThrough_n=44400,rebound_n=5479,Combo_n=16436,AntiCombo=5760,def_m=7582,def_n=20147,counter_n=25371,},
  [35]={BaseID=35,physique_hp=96,crit_n=13104,critDge_m=-5918,critDge_n=20740,dodge_n=8244,speed_m=-192,speed_n=1260,seeThrough_m=-4932,seeThrough_n=46128,rebound_n=5990,Combo_n=17971,AntiCombo=5960,def_m=8226,def_n=21860,counter_n=26359,},
  [36]={BaseID=36,physique_hp=99,crit_n=13746,critDge_m=-5980,critDge_n=20957,dodge_n=8615,speed_m=-194,speed_n=1334,seeThrough_m=-4983,seeThrough_n=46611,rebound_n=6277,Combo_n=18832,AntiCombo=6160,def_m=8588,def_n=22823,counter_n=26635,},
  [37]={BaseID=37,physique_hp=101,crit_n=14441,critDge_m=-6046,critDge_n=21189,dodge_n=9035,speed_m=-198,speed_n=1408,seeThrough_m=-5038,seeThrough_n=47127,rebound_n=6589,Combo_n=19768,AntiCombo=6360,def_m=8999,def_n=23913,counter_n=26930,},
  [38]={BaseID=38,physique_hp=104,crit_n=15243,critDge_m=-6115,critDge_n=21431,dodge_n=9510,speed_m=-202,speed_n=1481,seeThrough_m=-5096,seeThrough_n=47666,rebound_n=6939,Combo_n=20817,AntiCombo=6560,def_m=9463,def_n=25148,counter_n=27238,},
  [39]={BaseID=39,physique_hp=106,crit_n=16099,critDge_m=-6190,critDge_n=21694,dodge_n=10055,speed_m=-204,speed_n=1555,seeThrough_m=-5158,seeThrough_n=48249,rebound_n=7351,Combo_n=22052,AntiCombo=6760,def_m=9997,def_n=26567,counter_n=27571,},
  [40]={BaseID=40,physique_hp=109,crit_n=17062,critDge_m=-6266,critDge_n=21961,dodge_n=10674,speed_m=-208,speed_n=1628,seeThrough_m=-5222,seeThrough_n=48844,rebound_n=7812,Combo_n=23437,AntiCombo=6960,def_m=10606,def_n=28183,counter_n=27911,},
  [41]={BaseID=41,physique_hp=111,crit_n=18185,critDge_m=-6348,critDge_n=22249,dodge_n=11385,speed_m=-211,speed_n=1702,seeThrough_m=-5290,seeThrough_n=49484,rebound_n=8324,Combo_n=24972,AntiCombo=7160,def_m=11304,def_n=30039,counter_n=28277,},
  [42]={BaseID=42,physique_hp=114,crit_n=19415,critDge_m=-6436,critDge_n=22557,dodge_n=12194,speed_m=-214,speed_n=1776,seeThrough_m=-5364,seeThrough_n=50169,rebound_n=8923,Combo_n=26770,AntiCombo=7360,def_m=12103,def_n=32163,counter_n=28668,},
  [43]={BaseID=43,physique_hp=117,crit_n=20859,critDge_m=-6528,critDge_n=22880,dodge_n=13140,speed_m=-218,speed_n=1840,seeThrough_m=-5440,seeThrough_n=50887,rebound_n=9622,Combo_n=28866,AntiCombo=7560,def_m=13031,def_n=34628,counter_n=29078,},
  [44]={BaseID=44,physique_hp=120,crit_n=22571,critDge_m=-6626,critDge_n=23222,dodge_n=14229,speed_m=-221,speed_n=1840,seeThrough_m=-5522,seeThrough_n=51650,rebound_n=10433,Combo_n=31300,AntiCombo=7760,def_m=14104,def_n=37479,counter_n=29514,},
  [45]={BaseID=45,physique_hp=123,crit_n=24496,critDge_m=-6732,critDge_n=23591,dodge_n=15506,speed_m=-224,speed_n=1840,seeThrough_m=-5610,seeThrough_n=52469,rebound_n=11369,Combo_n=34108,AntiCombo=7960,def_m=15358,def_n=40811,counter_n=29982,},
  [46]={BaseID=46,physique_hp=126,crit_n=26742,critDge_m=-6841,critDge_n=23974,dodge_n=16999,speed_m=-227,speed_n=1840,seeThrough_m=-5701,seeThrough_n=53322,rebound_n=12468,Combo_n=37403,AntiCombo=8160,def_m=16831,def_n=44727,counter_n=30470,},
  [47]={BaseID=47,physique_hp=129,crit_n=29417,critDge_m=-6957,critDge_n=24383,dodge_n=18789,speed_m=-230,speed_n=1840,seeThrough_m=-5798,seeThrough_n=54231,rebound_n=13790,Combo_n=41371,AntiCombo=8360,def_m=18592,def_n=49405,counter_n=30989,},
  [48]={BaseID=48,physique_hp=133,crit_n=32733,critDge_m=-7083,critDge_n=24822,dodge_n=20965,speed_m=-234,speed_n=1840,seeThrough_m=-5902,seeThrough_n=55208,rebound_n=15413,Combo_n=46238,AntiCombo=8560,def_m=20723,def_n=55069,counter_n=31547,},
  [49]={BaseID=49,physique_hp=136,crit_n=36798,critDge_m=-7215,critDge_n=25286,dodge_n=23665,speed_m=-237,speed_n=1840,seeThrough_m=-6013,seeThrough_n=56240,rebound_n=17435,Combo_n=52304,AntiCombo=8760,def_m=23362,def_n=62081,counter_n=32137,},
  [50]={BaseID=50,physique_hp=140,crit_n=42093,critDge_m=-7356,critDge_n=25781,dodge_n=27100,speed_m=-240,speed_n=1840,seeThrough_m=-6130,seeThrough_n=57340,rebound_n=20043,Combo_n=60129,AntiCombo=8960,def_m=26713,def_n=70988,counter_n=32766,},
}
for k,v in pairs(BattleFactor) do
    setmetatable(v, {['__index'] = BattleFactorDefault})
end

-- export table: BattleFactor
return BattleFactor
