-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local BreakLimitMaster= {
  [1]={BaseID=1,Master=1270301001,Map=525,},
  [2]={BaseID=2,Master=1030101017,Map=543,},
  [3]={BaseID=3,Master=1140314003,Map=567,},
  [4]={BaseID=4,Master=1120301004,Map=597,},
  [5]={BaseID=5,Master=1230301003,Map=676,},
  [6]={BaseID=6,Master=1150301016,Map=705,},
  [7]={BaseID=7,Master=1170301005,Map=785,},
  [8]={BaseID=8,Master=1210314002,Map=801,},
  [9]={BaseID=9,Master=1080314001,Map=867,},
  [10]={BaseID=10,Master=1160301004,Map=885,},
  [11]={BaseID=11,Master=1100301001,Map=901,},
  [12]={BaseID=12,Master=1250301002,Map=928,},
  [13]={BaseID=13,Master=1150301022,Map=946,},
  [14]={BaseID=14,Master=1090325010,Map=963,},
  [15]={BaseID=15,Master=1290301002,Map=1858,},
  [16]={BaseID=16,Master=1040301007,Map=1752,},
}

-- export table: BreakLimitMaster
return BreakLimitMaster
