-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local BreakLimitMaze= {
  [3]={Maze=3,},
  [4]={Maze=4,},
  [8]={Maze=8,},
  [9]={Maze=9,},
  [10]={Maze=10,},
  [11]={Maze=11,},
  [12]={Maze=12,},
  [13]={Maze=13,},
  [14]={Maze=14,},
}

-- export table: BreakLimitMaze
return BreakLimitMaze
