local t = {
	[0x2713] = {
		["id"] = 0x2713,
		["effect"] = {
			{
				["type"] = 0x0,
				["prefabPath"] = "Effect/Eff/com/ef_buff_chiyou_n",
				["prefabAnim"] = nil,
				["mountName"] = "ref_origin",
				["scale"] = 3.000000,
				["layer"] = 0x0,
				["noFlipX"] = true,
			},
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x127d] = {
		["id"] = 0x127d,
		["effect"] = {
			{
				["type"] = 0x0,
				["prefabPath"] = nil,
				["prefabAnim"] = nil,
				["mountName"] = "ref_head",
				["scale"] = 3.000000,
				["layer"] = 0x0,
				["noFlipX"] = true,
			},
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x1272] = {
		["id"] = 0x1272,
		["effect"] = {
			{
				["type"] = 0x0,
				["prefabPath"] = nil,
				["prefabAnim"] = nil,
				["mountName"] = "ref_origin",
				["scale"] = 2.500000,
				["layer"] = 0x0,
				["noFlipX"] = true,
			},
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x1271] = {
		["id"] = 0x1271,
		["effect"] = {
			{
				["type"] = 0x0,
				["prefabPath"] = nil,
				["prefabAnim"] = nil,
				["mountName"] = "ref_origin",
				["scale"] = 2.500000,
				["layer"] = 0x0,
				["noFlipX"] = true,
			},
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x1270] = {
		["id"] = 0x1270,
		["effect"] = {
			{
				["type"] = 0x0,
				["prefabPath"] = nil,
				["prefabAnim"] = nil,
				["mountName"] = "ref_origin",
				["scale"] = 2.500000,
				["layer"] = 0x0,
				["noFlipX"] = true,
			},
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x126f] = {
		["id"] = 0x126f,
		["effect"] = {
			{
				["type"] = 0x0,
				["prefabPath"] = nil,
				["prefabAnim"] = nil,
				["mountName"] = "ref_origin",
				["scale"] = 2.500000,
				["layer"] = 0x0,
				["noFlipX"] = true,
			},
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x127c] = {
		["id"] = 0x127c,
		["effect"] = {
			{
				["type"] = 0x0,
				["prefabPath"] = nil,
				["prefabAnim"] = nil,
				["mountName"] = "ref_head",
				["scale"] = 2.000000,
				["layer"] = 0x0,
				["noFlipX"] = true,
			},
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x1275] = {
		["id"] = 0x1275,
		["effect"] = {
			{
				["type"] = 0x0,
				["prefabPath"] = nil,
				["prefabAnim"] = nil,
				["mountName"] = "ref_origin",
				["scale"] = 2.000000,
				["layer"] = 0x0,
				["noFlipX"] = true,
			},
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x1277] = {
		["id"] = 0x1277,
		["effect"] = {
			{
				["type"] = 0x0,
				["prefabPath"] = nil,
				["prefabAnim"] = nil,
				["mountName"] = "ref_origin",
				["scale"] = 2.500000,
				["layer"] = 0x0,
				["noFlipX"] = true,
			},
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x119f] = {
		["id"] = 0x119f,
		["effect"] = {
			{
				["type"] = 0x0,
				["prefabPath"] = nil,
				["prefabAnim"] = nil,
				["mountName"] = "ref_origin",
				["scale"] = 2.000000,
				["layer"] = 0x0,
				["noFlipX"] = true,
			},
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x1238] = {
		["id"] = 0x1238,
		["effect"] = {
			{
				["type"] = 0x0,
				["prefabPath"] = nil,
				["prefabAnim"] = nil,
				["mountName"] = "ref_origin",
				["scale"] = 2.000000,
				["layer"] = 0x1,
				["noFlipX"] = true,
			},
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x1239] = {
		["id"] = 0x1239,
		["effect"] = nil,
		["layerEffect"] = nil,
		["skillEffect"] = {
			{
				["actionInfo"] = nil,
				["castEffect"] = {
					{
						["prefabPath"] = nil,
						["prefabAnim"] = nil,
						["depth"] = 0x3,
						["offsetX"] = nil,
						["offsetY"] = nil,
						["noOnRole"] = false,
						["mount1Name"] = 0x0,
						["mount2Name"] = nil,
						["delay"] = 0x0,
						["fullScreen"] = false,
						["scale"] = nil,
						["onHurt"] = false,
						["onlyOnce"] = false,
						["noFlipX"] = true,
						["audio"] = 0x0,
						["onFloor"] = false,
						["layerValue"] = 0x0,
					},
				},
				["hurtEffect"] = nil,
				["sceneEffect"] = nil,
				["hurtEffectDelayTime"] = 0x0,
				["hurtAnimation"] = nil,
				["hurtAnimationDelayTime"] = 0x0,
			},
		},
		["playOnAdd"] = false,
	},
	[0x123a] = {
		["id"] = 0x123a,
		["effect"] = {
			{
				["type"] = 0x0,
				["prefabPath"] = nil,
				["prefabAnim"] = nil,
				["mountName"] = "ref_origin",
				["scale"] = 2.000000,
				["layer"] = 0x1,
				["noFlipX"] = true,
			},
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x123b] = {
		["id"] = 0x123b,
		["effect"] = {
			{
				["type"] = 0x0,
				["prefabPath"] = nil,
				["prefabAnim"] = nil,
				["mountName"] = "ref_origin",
				["scale"] = 2.000000,
				["layer"] = 0x1,
				["noFlipX"] = true,
			},
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x123c] = {
		["id"] = 0x123c,
		["effect"] = nil,
		["layerEffect"] = nil,
		["skillEffect"] = {
			{
				["actionInfo"] = nil,
				["castEffect"] = nil,
				["hurtEffect"] = {
					{
						["prefabPath"] = nil,
						["prefabAnim"] = nil,
						["depth"] = 0x1,
						["offsetX"] = nil,
						["offsetY"] = nil,
						["noOnRole"] = false,
						["mount1Name"] = 0x0,
						["mount2Name"] = nil,
						["delay"] = 0x0,
						["fullScreen"] = false,
						["scale"] = nil,
						["onHurt"] = false,
						["onlyOnce"] = false,
						["noFlipX"] = true,
						["audio"] = 0x0,
						["onFloor"] = false,
						["layerValue"] = 0x0,
					},
				},
				["sceneEffect"] = nil,
				["hurtEffectDelayTime"] = 0x0,
				["hurtAnimation"] = nil,
				["hurtAnimationDelayTime"] = 0x0,
			},
		},
		["playOnAdd"] = false,
	},
	[0x1190] = {
		["id"] = 0x1190,
		["effect"] = {
			{
				["type"] = 0x0,
				["prefabPath"] = nil,
				["prefabAnim"] = nil,
				["mountName"] = "ref_origin",
				["scale"] = 2.000000,
				["layer"] = 0x0,
				["noFlipX"] = false,
			},
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x10c5] = {
		["id"] = 0x10c5,
		["effect"] = {
			{
				["type"] = 0x0,
				["prefabPath"] = "Effect/Eff/ef_zmenpai_all/ef_baiyijiao/ef_syshouzha",
				["prefabAnim"] = nil,
				["mountName"] = "ref_origin",
				["scale"] = 2.000000,
				["layer"] = 0x0,
				["noFlipX"] = false,
			},
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0xa5] = {
		["id"] = 0xa5,
		["effect"] = nil,
		["layerEffect"] = nil,
		["skillEffect"] = {
			{
				["actionInfo"] = {
					["oldActionName"] = "prepare",
					["delay"] = nil,
					["action"] = "spell",
					["type"] = nil,
					["num"] = nil,
				},
				["castEffect"] = {
				},
				["hurtEffect"] = {
					{
						["prefabPath"] = "Effect/Eff/com/buff_tiaoxi",
						["prefabAnim"] = "animation",
						["depth"] = nil,
						["offsetX"] = nil,
						["offsetY"] = nil,
						["noOnRole"] = nil,
						["mount1Name"] = nil,
						["mount2Name"] = "ref_waist",
						["delay"] = nil,
						["fullScreen"] = nil,
						["scale"] = 1.000000,
						["onHurt"] = nil,
						["onlyOnce"] = nil,
						["noFlipX"] = nil,
						["audio"] = 0x0,
						["onFloor"] = nil,
						["layerValue"] = 0x0,
					},
				},
				["sceneEffect"] = nil,
				["hurtEffectDelayTime"] = nil,
				["hurtAnimation"] = nil,
				["hurtAnimationDelayTime"] = nil,
			},
		},
		["playOnAdd"] = false,
	},
	[0xd7] = {
		["id"] = 0xd7,
		["effect"] = {
			{
				["type"] = 0x1,
				["prefabPath"] = "Effect/Eff/com/buff_xuli",
				["prefabAnim"] = "animation",
				["mountName"] = "ref_origin",
				["scale"] = 2.000000,
				["layer"] = nil,
				["noFlipX"] = false,
			},
		},
		["layerEffect"] = nil,
		["skillEffect"] = {
			{
				["actionInfo"] = {
					["oldActionName"] = "attack_g_001",
					["delay"] = nil,
					["action"] = "spell",
					["type"] = nil,
					["num"] = nil,
				},
				["castEffect"] = {
					{
						["prefabPath"] = "Effect/Eff/com/fz_xuli001",
						["prefabAnim"] = "animation",
						["depth"] = 0x3,
						["offsetX"] = nil,
						["offsetY"] = nil,
						["noOnRole"] = nil,
						["mount1Name"] = nil,
						["mount2Name"] = "ref_waist",
						["delay"] = nil,
						["fullScreen"] = nil,
						["scale"] = 1.500000,
						["onHurt"] = nil,
						["onlyOnce"] = nil,
						["noFlipX"] = nil,
						["audio"] = 0x0,
						["onFloor"] = nil,
						["layerValue"] = 0x0,
					},
				},
				["hurtEffect"] = nil,
				["sceneEffect"] = nil,
				["hurtEffectDelayTime"] = nil,
				["hurtAnimation"] = nil,
				["hurtAnimationDelayTime"] = nil,
			},
		},
		["playOnAdd"] = false,
	},
	[0x18c] = {
		["id"] = 0x18c,
		["effect"] = {
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x191] = {
		["id"] = 0x191,
		["effect"] = {
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x192] = {
		["id"] = 0x192,
		["effect"] = {
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x19e] = {
		["id"] = 0x19e,
		["effect"] = nil,
		["layerEffect"] = {
			{
				["effect"] = {
					{
						["type"] = 0x1,
						["prefabPath"] = nil,
						["prefabAnim"] = "animation",
						["mountName"] = "ref_origin",
						["scale"] = 0.500000,
						["layer"] = nil,
						["noFlipX"] = false,
					},
				},
				["layer"] = 0x1,
			},
			{
				["effect"] = {
					{
						["type"] = 0x1,
						["prefabPath"] = nil,
						["prefabAnim"] = "animation",
						["mountName"] = "ref_origin",
						["scale"] = 0.550000,
						["layer"] = nil,
						["noFlipX"] = false,
					},
				},
				["layer"] = 0x2,
			},
			{
				["effect"] = {
					{
						["type"] = 0x1,
						["prefabPath"] = nil,
						["prefabAnim"] = "animation",
						["mountName"] = "ref_origin",
						["scale"] = 0.600000,
						["layer"] = nil,
						["noFlipX"] = false,
					},
				},
				["layer"] = 0x3,
			},
			{
				["effect"] = {
					{
						["type"] = 0x1,
						["prefabPath"] = nil,
						["prefabAnim"] = "animation",
						["mountName"] = "ref_origin",
						["scale"] = 0.650000,
						["layer"] = nil,
						["noFlipX"] = false,
					},
				},
				["layer"] = 0x4,
			},
			{
				["effect"] = {
					{
						["type"] = 0x1,
						["prefabPath"] = nil,
						["prefabAnim"] = "animation",
						["mountName"] = "ref_origin",
						["scale"] = 0.700000,
						["layer"] = nil,
						["noFlipX"] = false,
					},
				},
				["layer"] = 0x5,
			},
			{
				["effect"] = {
					{
						["type"] = 0x1,
						["prefabPath"] = nil,
						["prefabAnim"] = "animation",
						["mountName"] = "ref_origin",
						["scale"] = 0.750000,
						["layer"] = nil,
						["noFlipX"] = false,
					},
				},
				["layer"] = 0x6,
			},
			{
				["effect"] = {
					{
						["type"] = 0x1,
						["prefabPath"] = nil,
						["prefabAnim"] = "animation",
						["mountName"] = "ref_origin",
						["scale"] = 0.800000,
						["layer"] = nil,
						["noFlipX"] = false,
					},
				},
				["layer"] = 0x7,
			},
			{
				["effect"] = {
					{
						["type"] = 0x1,
						["prefabPath"] = nil,
						["prefabAnim"] = "animation",
						["mountName"] = "ref_origin",
						["scale"] = 0.850000,
						["layer"] = nil,
						["noFlipX"] = false,
					},
				},
				["layer"] = 0x8,
			},
			{
				["effect"] = {
					{
						["type"] = 0x1,
						["prefabPath"] = nil,
						["prefabAnim"] = "animation",
						["mountName"] = "ref_origin",
						["scale"] = 0.900000,
						["layer"] = nil,
						["noFlipX"] = false,
					},
				},
				["layer"] = 0x9,
			},
			{
				["effect"] = {
					{
						["type"] = 0x1,
						["prefabPath"] = nil,
						["prefabAnim"] = "animation",
						["mountName"] = "ref_origin",
						["scale"] = 0.990000,
						["layer"] = nil,
						["noFlipX"] = false,
					},
				},
				["layer"] = 0xa,
			},
		},
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x10be] = {
		["id"] = 0x10be,
		["effect"] = nil,
		["layerEffect"] = nil,
		["skillEffect"] = {
			{
				["actionInfo"] = nil,
				["castEffect"] = {
					{
						["prefabPath"] = "SkillEffect/spine_eff_chiyou",
						["prefabAnim"] = "animation2",
						["depth"] = 0x1,
						["offsetX"] = nil,
						["offsetY"] = nil,
						["noOnRole"] = false,
						["mount1Name"] = 0x0,
						["mount2Name"] = "ref_origin",
						["delay"] = 0x0,
						["fullScreen"] = false,
						["scale"] = nil,
						["onHurt"] = false,
						["onlyOnce"] = false,
						["noFlipX"] = false,
						["audio"] = 0x0,
						["onFloor"] = false,
						["layerValue"] = 0x0,
					},
					{
						["prefabPath"] = "Effect/Eff/com/ef_buff_chiyou_bd1",
						["prefabAnim"] = nil,
						["depth"] = 0x4,
						["offsetX"] = nil,
						["offsetY"] = nil,
						["noOnRole"] = false,
						["mount1Name"] = 0x0,
						["mount2Name"] = "ref_origin",
						["delay"] = 0x0,
						["fullScreen"] = false,
						["scale"] = nil,
						["onHurt"] = false,
						["onlyOnce"] = false,
						["noFlipX"] = false,
						["audio"] = 0x0,
						["onFloor"] = false,
						["layerValue"] = 0x0,
					},
				},
				["hurtEffect"] = nil,
				["sceneEffect"] = nil,
				["hurtEffectDelayTime"] = 0x0,
				["hurtAnimation"] = nil,
				["hurtAnimationDelayTime"] = 0x0,
			},
		},
		["playOnAdd"] = false,
	},
	[0x1149] = {
		["id"] = 0x1149,
		["effect"] = nil,
		["layerEffect"] = nil,
		["skillEffect"] = {
			{
				["actionInfo"] = nil,
				["castEffect"] = {
					{
						["prefabPath"] = "Effect/Eff/com/ef_fuhuo",
						["prefabAnim"] = "animation2",
						["depth"] = 0x1,
						["offsetX"] = nil,
						["offsetY"] = nil,
						["noOnRole"] = false,
						["mount1Name"] = 0x0,
						["mount2Name"] = "ref_origin",
						["delay"] = 0x0,
						["fullScreen"] = false,
						["scale"] = nil,
						["onHurt"] = false,
						["onlyOnce"] = false,
						["noFlipX"] = false,
						["audio"] = 0x0,
						["onFloor"] = false,
						["layerValue"] = 0x0,
					},
				},
				["hurtEffect"] = nil,
				["sceneEffect"] = nil,
				["hurtEffectDelayTime"] = 0x0,
				["hurtAnimation"] = nil,
				["hurtAnimationDelayTime"] = 0x0,
			},
		},
		["playOnAdd"] = true,
	},
	[0x1131] = {
		["id"] = 0x1131,
		["effect"] = nil,
		["layerEffect"] = nil,
		["skillEffect"] = {
			{
				["actionInfo"] = nil,
				["castEffect"] = {
					{
						["prefabPath"] = "Effect/Eff/ef_zmenpai_all/ef_youchichi/eff_hongchenbao",
						["prefabAnim"] = "animation2",
						["depth"] = 0x1,
						["offsetX"] = nil,
						["offsetY"] = nil,
						["noOnRole"] = false,
						["mount1Name"] = 0x0,
						["mount2Name"] = nil,
						["delay"] = 0x0,
						["fullScreen"] = false,
						["scale"] = nil,
						["onHurt"] = false,
						["onlyOnce"] = false,
						["noFlipX"] = false,
						["audio"] = 0x0,
						["onFloor"] = false,
						["layerValue"] = 0x0,
					},
					{
						["prefabPath"] = "Effect/Eff/com/fz_dilie001",
						["prefabAnim"] = nil,
						["depth"] = 0x4,
						["offsetX"] = nil,
						["offsetY"] = nil,
						["noOnRole"] = false,
						["mount1Name"] = 0x0,
						["mount2Name"] = nil,
						["delay"] = 0x0,
						["fullScreen"] = false,
						["scale"] = nil,
						["onHurt"] = false,
						["onlyOnce"] = false,
						["noFlipX"] = false,
						["audio"] = 0x0,
						["onFloor"] = true,
						["layerValue"] = 0x0,
					},
					{
						["prefabPath"] = "Effect/Eff/com/fz_shikuai04",
						["prefabAnim"] = nil,
						["depth"] = 0x1,
						["offsetX"] = nil,
						["offsetY"] = nil,
						["noOnRole"] = false,
						["mount1Name"] = 0x0,
						["mount2Name"] = nil,
						["delay"] = 0x0,
						["fullScreen"] = false,
						["scale"] = 0.400000,
						["onHurt"] = false,
						["onlyOnce"] = false,
						["noFlipX"] = false,
						["audio"] = 0x0,
						["onFloor"] = false,
						["layerValue"] = 0x0,
					},
				},
				["hurtEffect"] = {
					{
						["prefabPath"] = "Effect/Eff/ef_zmenpai_all/ef_youchichi/eff_hongchenbao_sj",
						["prefabAnim"] = nil,
						["depth"] = 0x1,
						["offsetX"] = nil,
						["offsetY"] = nil,
						["noOnRole"] = false,
						["mount1Name"] = 0x0,
						["mount2Name"] = nil,
						["delay"] = 0x0,
						["fullScreen"] = false,
						["scale"] = nil,
						["onHurt"] = false,
						["onlyOnce"] = false,
						["noFlipX"] = false,
						["audio"] = 0x0,
						["onFloor"] = false,
						["layerValue"] = 0x0,
					},
				},
				["sceneEffect"] = nil,
				["hurtEffectDelayTime"] = 0x0,
				["hurtAnimation"] = nil,
				["hurtAnimationDelayTime"] = 0x0,
			},
		},
		["playOnAdd"] = false,
	},
	[0x10bd] = {
		["id"] = 0x10bd,
		["effect"] = nil,
		["layerEffect"] = nil,
		["skillEffect"] = {
			{
				["actionInfo"] = nil,
				["castEffect"] = {
				},
				["hurtEffect"] = {
					{
						["prefabPath"] = "Effect/Eff/com/ef_buff_chiyou_bd2",
						["prefabAnim"] = nil,
						["depth"] = 0x1,
						["offsetX"] = nil,
						["offsetY"] = nil,
						["noOnRole"] = false,
						["mount1Name"] = 0x0,
						["mount2Name"] = nil,
						["delay"] = 0x0,
						["fullScreen"] = false,
						["scale"] = nil,
						["onHurt"] = false,
						["onlyOnce"] = false,
						["noFlipX"] = false,
						["audio"] = 0x0,
						["onFloor"] = false,
						["layerValue"] = 0x0,
					},
				},
				["sceneEffect"] = nil,
				["hurtEffectDelayTime"] = 0x0,
				["hurtAnimation"] = nil,
				["hurtAnimationDelayTime"] = 0x0,
			},
		},
		["playOnAdd"] = false,
	},
	[0x108e] = {
		["id"] = 0x108e,
		["effect"] = {
			{
				["type"] = 0x0,
				["prefabPath"] = "SkillEffect/spine_eff_chiyou",
				["prefabAnim"] = "animation",
				["mountName"] = "ref_origin",
				["scale"] = 2.000000,
				["layer"] = 0x0,
				["noFlipX"] = false,
			},
			{
				["type"] = nil,
				["prefabPath"] = "Effect/Eff/com/ef_buff_chiyou_n",
				["prefabAnim"] = nil,
				["mountName"] = "ref_origin",
				["scale"] = 2.000000,
				["layer"] = 0x1,
				["noFlipX"] = false,
			},
		},
		["layerEffect"] = nil,
		["skillEffect"] = {
			{
				["actionInfo"] = nil,
				["castEffect"] = nil,
				["hurtEffect"] = nil,
				["sceneEffect"] = nil,
				["hurtEffectDelayTime"] = 0x0,
				["hurtAnimation"] = nil,
				["hurtAnimationDelayTime"] = 0x0,
			},
		},
		["playOnAdd"] = false,
	},
	[0x1a5] = {
		["id"] = 0x1a5,
		["effect"] = {
		},
		["layerEffect"] = nil,
		["skillEffect"] = {
			{
				["actionInfo"] = nil,
				["castEffect"] = {
					{
						["prefabPath"] = "Effect/Eff/com/buff_zhiliao",
						["prefabAnim"] = "animation",
						["depth"] = 0x3,
						["offsetX"] = nil,
						["offsetY"] = nil,
						["noOnRole"] = nil,
						["mount1Name"] = nil,
						["mount2Name"] = "ref_waist",
						["delay"] = nil,
						["fullScreen"] = nil,
						["scale"] = nil,
						["onHurt"] = nil,
						["onlyOnce"] = nil,
						["noFlipX"] = nil,
						["audio"] = 0x0,
						["onFloor"] = nil,
						["layerValue"] = 0x0,
					},
				},
				["hurtEffect"] = nil,
				["sceneEffect"] = nil,
				["hurtEffectDelayTime"] = nil,
				["hurtAnimation"] = nil,
				["hurtAnimationDelayTime"] = nil,
			},
		},
		["playOnAdd"] = false,
	},
	[0xc9] = {
		["id"] = 0xc9,
		["effect"] = nil,
		["layerEffect"] = nil,
		["skillEffect"] = {
			{
				["actionInfo"] = nil,
				["castEffect"] = {
					{
						["prefabPath"] = "Effect/Eff/com/buff_tiaoxi",
						["prefabAnim"] = "animation",
						["depth"] = 0x3,
						["offsetX"] = nil,
						["offsetY"] = nil,
						["noOnRole"] = nil,
						["mount1Name"] = nil,
						["mount2Name"] = "ref_origin",
						["delay"] = nil,
						["fullScreen"] = nil,
						["scale"] = 2.000000,
						["onHurt"] = nil,
						["onlyOnce"] = nil,
						["noFlipX"] = nil,
						["audio"] = 0x0,
						["onFloor"] = nil,
						["layerValue"] = 0x0,
					},
				},
				["hurtEffect"] = nil,
				["sceneEffect"] = nil,
				["hurtEffectDelayTime"] = nil,
				["hurtAnimation"] = nil,
				["hurtAnimationDelayTime"] = nil,
			},
		},
		["playOnAdd"] = false,
	},
	[0x1a6] = {
		["id"] = 0x1a6,
		["effect"] = {
		},
		["layerEffect"] = nil,
		["skillEffect"] = {
			{
				["actionInfo"] = nil,
				["castEffect"] = {
				},
				["hurtEffect"] = nil,
				["sceneEffect"] = nil,
				["hurtEffectDelayTime"] = nil,
				["hurtAnimation"] = nil,
				["hurtAnimationDelayTime"] = nil,
			},
		},
		["playOnAdd"] = false,
	},
	[0x227] = {
		["id"] = 0x227,
		["effect"] = {
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x228] = {
		["id"] = 0x228,
		["effect"] = {
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x1b3] = {
		["id"] = 0x1b3,
		["effect"] = {
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x1c0] = {
		["id"] = 0x1c0,
		["effect"] = {
			{
				["type"] = 0x1,
				["prefabPath"] = "Effect/Eff/com/buff_xuli",
				["prefabAnim"] = "animation",
				["mountName"] = "ref_origin",
				["scale"] = 2.010000,
				["layer"] = nil,
				["noFlipX"] = false,
			},
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x251] = {
		["id"] = 0x251,
		["effect"] = {
			{
				["type"] = 0x1,
				["prefabPath"] = "SkillEffect/ef_ty_neigong",
				["prefabAnim"] = "animation3",
				["mountName"] = "ref_origin",
				["scale"] = 1.500000,
				["layer"] = 0x1,
				["noFlipX"] = false,
			},
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x64] = {
		["id"] = 0x64,
		["effect"] = {
			{
				["type"] = 0x1,
				["prefabPath"] = "Effect/Eff/ef_zmenpai_all/ef_zhujian/ef_zj_buff",
				["prefabAnim"] = "animation",
				["mountName"] = "ref_origin",
				['noFlipX'] = true,
				["scale"] = 2.000000,
				["layer"] = nil,
				["noFlipX"] = true,
			},
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x106d] = {
		["id"] = 0x106d,
		["effect"] = {
			{
				["type"] = 0x1,
				["prefabPath"] = "Effect/Eff/com/buff_xuli",
				["prefabAnim"] = "animation",
				["mountName"] = "ref_origin",
				["scale"] = 2.000000,
				["layer"] = nil,
				["noFlipX"] = false,
			},
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x7a] = {
		["id"] = 0x7a,
		["effect"] = {
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x294] = {
		["id"] = 0x294,
		["effect"] = {
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x7b] = {
		["id"] = 0x7b,
		["effect"] = {
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x265] = {
		["id"] = 0x265,
		["effect"] = {
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x71] = {
		["id"] = 0x71,
		["effect"] = {
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x241] = {
		["id"] = 0x241,
		["effect"] = {
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x7e] = {
		["id"] = 0x7e,
		["effect"] = nil,
		["layerEffect"] = nil,
		["skillEffect"] = {
			{
				["actionInfo"] = nil,
				["castEffect"] = {
					{
						["prefabPath"] = "Effect/Eff/com/buff_qiangzhuang01",
						["prefabAnim"] = "",
						["depth"] = 0x3,
						["offsetX"] = nil,
						["offsetY"] = nil,
						["noOnRole"] = nil,
						["mount1Name"] = nil,
						["mount2Name"] = "ref_overhead",
						["delay"] = nil,
						["fullScreen"] = nil,
						["scale"] = 1.000000,
						["onHurt"] = nil,
						["onlyOnce"] = nil,
						["noFlipX"] = true,
						["audio"] = 0x0,
						["onFloor"] = nil,
						["layerValue"] = 0x0,
					},
				},
				["hurtEffect"] = nil,
				["sceneEffect"] = nil,
				["hurtEffectDelayTime"] = nil,
				["hurtAnimation"] = nil,
				["hurtAnimationDelayTime"] = nil,
			},
		},
		["playOnAdd"] = false,
	},
	[0x7f] = {
		["id"] = 0x7f,
		["effect"] = nil,
		["layerEffect"] = nil,
		["skillEffect"] = {
			{
				["actionInfo"] = nil,
				["castEffect"] = {
					{
						["prefabPath"] = "Effect/Eff/com/buff_jianren01",
						["prefabAnim"] = "",
						["depth"] = 0x3,
						["offsetX"] = nil,
						["offsetY"] = nil,
						["noOnRole"] = nil,
						["mount1Name"] = nil,
						["mount2Name"] = "ref_overhead",
						["delay"] = nil,
						["fullScreen"] = nil,
						["scale"] = 1.000000,
						["onHurt"] = nil,
						["onlyOnce"] = nil,
						["noFlipX"] = true,
						["audio"] = 0x0,
						["onFloor"] = nil,
						["layerValue"] = 0x0,
					},
				},
				["hurtEffect"] = nil,
				["sceneEffect"] = nil,
				["hurtEffectDelayTime"] = nil,
				["hurtAnimation"] = nil,
				["hurtAnimationDelayTime"] = nil,
			},
		},
		["playOnAdd"] = false,
	},
	[0x80] = {
		["id"] = 0x80,
		["effect"] = nil,
		["layerEffect"] = nil,
		["skillEffect"] = {
			{
				["actionInfo"] = nil,
				["castEffect"] = {
					{
						["prefabPath"] = "Effect/Eff/com/buff_zhiliao",
						["prefabAnim"] = "animation",
						["depth"] = 0x2,
						["offsetX"] = nil,
						["offsetY"] = nil,
						["noOnRole"] = nil,
						["mount1Name"] = nil,
						["mount2Name"] = "ref_waist",
						["delay"] = nil,
						["fullScreen"] = nil,
						["scale"] = nil,
						["onHurt"] = nil,
						["onlyOnce"] = nil,
						["noFlipX"] = true,
						["audio"] = 0x0,
						["onFloor"] = nil,
						["layerValue"] = 0x0,
					},
				},
				["hurtEffect"] = nil,
				["sceneEffect"] = nil,
				["hurtEffectDelayTime"] = nil,
				["hurtAnimation"] = nil,
				["hurtAnimationDelayTime"] = nil,
			},
		},
		["playOnAdd"] = false,
	},
	[0x81] = {
		["id"] = 0x81,
		["effect"] = nil,
		["layerEffect"] = nil,
		["skillEffect"] = {
			{
				["actionInfo"] = nil,
				["castEffect"] = {
					{
						["prefabPath"] = "Effect/Eff/com/buff_qingying01",
						["prefabAnim"] = "buff_qingying",
						["depth"] = 0x3,
						["offsetX"] = nil,
						["offsetY"] = nil,
						["noOnRole"] = nil,
						["mount1Name"] = nil,
						["mount2Name"] = "ref_overhead",
						["delay"] = nil,
						["fullScreen"] = nil,
						["scale"] = 1.000000,
						["onHurt"] = nil,
						["onlyOnce"] = nil,
						["noFlipX"] = true,
						["audio"] = 0x0,
						["onFloor"] = nil,
						["layerValue"] = 0x0,
					},
				},
				["hurtEffect"] = nil,
				["sceneEffect"] = nil,
				["hurtEffectDelayTime"] = nil,
				["hurtAnimation"] = nil,
				["hurtAnimationDelayTime"] = nil,
			},
		},
		["playOnAdd"] = false,
	},
	[0x82] = {
		["id"] = 0x82,
		["effect"] = nil,
		["layerEffect"] = nil,
		["skillEffect"] = {
			{
				["actionInfo"] = nil,
				["castEffect"] = {
					{
						["prefabPath"] = "Effect/Eff/com/buff_tiaoxi",
						["prefabAnim"] = "animation",
						["depth"] = 0x2,
						["offsetX"] = nil,
						["offsetY"] = nil,
						["noOnRole"] = nil,
						["mount1Name"] = nil,
						["mount2Name"] = "ref_waist",
						["delay"] = nil,
						["fullScreen"] = nil,
						["scale"] = nil,
						["onHurt"] = nil,
						["onlyOnce"] = nil,
						["noFlipX"] = true,
						["audio"] = 0x0,
						["onFloor"] = nil,
						["layerValue"] = 0x0,
					},
				},
				["hurtEffect"] = nil,
				["sceneEffect"] = nil,
				["hurtEffectDelayTime"] = nil,
				["hurtAnimation"] = nil,
				["hurtAnimationDelayTime"] = nil,
			},
		},
		["playOnAdd"] = false,
	},
	[0x89] = {
		["id"] = 0x89,
		["effect"] = nil,
		["layerEffect"] = nil,
		["skillEffect"] = {
			{
				["actionInfo"] = nil,
				["castEffect"] = {
					{
						["prefabPath"] = "Effect/Eff/com/debuff_pojia01",
						["prefabAnim"] = "debuff_pojia",
						["depth"] = 0x3,
						["offsetX"] = nil,
						["offsetY"] = nil,
						["noOnRole"] = nil,
						["mount1Name"] = nil,
						["mount2Name"] = "ref_overhead",
						["delay"] = nil,
						["fullScreen"] = nil,
						["scale"] = 1.000000,
						["onHurt"] = nil,
						["onlyOnce"] = nil,
						["noFlipX"] = true,
						["audio"] = 0x0,
						["onFloor"] = nil,
						["layerValue"] = 0x0,
					},
				},
				["hurtEffect"] = nil,
				["sceneEffect"] = nil,
				["hurtEffectDelayTime"] = nil,
				["hurtAnimation"] = nil,
				["hurtAnimationDelayTime"] = nil,
			},
		},
		["playOnAdd"] = false,
	},
	[0x8a] = {
		["id"] = 0x8a,
		["effect"] = nil,
		["layerEffect"] = nil,
		["skillEffect"] = {
			{
				["actionInfo"] = nil,
				["castEffect"] = {
					{
						["prefabPath"] = "Effect/Eff/com/debuff_zhongdu",
						["prefabAnim"] = "animation2",
						["depth"] = 0x1,
						["offsetX"] = -0.600000,
						["offsetY"] = nil,
						["noOnRole"] = nil,
						["mount1Name"] = nil,
						["mount2Name"] = "ref_waist",
						["delay"] = nil,
						["fullScreen"] = nil,
						["scale"] = nil,
						["onHurt"] = nil,
						["onlyOnce"] = nil,
						["noFlipX"] = true,
						["audio"] = 0x0,
						["onFloor"] = nil,
						["layerValue"] = 0x0,
					},
				},
				["hurtEffect"] = nil,
				["sceneEffect"] = nil,
				["hurtEffectDelayTime"] = nil,
				["hurtAnimation"] = nil,
				["hurtAnimationDelayTime"] = nil,
			},
		},
		["playOnAdd"] = false,
	},
	[0x8b] = {
		["id"] = 0x8b,
		["effect"] = nil,
		["layerEffect"] = nil,
		["skillEffect"] = {
			{
				["actionInfo"] = nil,
				["castEffect"] = {
					{
						["prefabPath"] = "Effect/Eff/com/debuff_jiansu01",
						["prefabAnim"] = "debuff_jiansu",
						["depth"] = 0x3,
						["offsetX"] = nil,
						["offsetY"] = nil,
						["noOnRole"] = nil,
						["mount1Name"] = nil,
						["mount2Name"] = "ref_overhead",
						["delay"] = nil,
						["fullScreen"] = nil,
						["scale"] = 1.000000,
						["onHurt"] = nil,
						["onlyOnce"] = nil,
						["noFlipX"] = true,
						["audio"] = 0x0,
						["onFloor"] = nil,
						["layerValue"] = 0x0,
					},
				},
				["hurtEffect"] = nil,
				["sceneEffect"] = nil,
				["hurtEffectDelayTime"] = nil,
				["hurtAnimation"] = nil,
				["hurtAnimationDelayTime"] = nil,
			},
		},
		["playOnAdd"] = false,
	},
	[0x8c] = {
		["id"] = 0x8c,
		["effect"] = nil,
		["layerEffect"] = nil,
		["skillEffect"] = {
			{
				["actionInfo"] = nil,
				["castEffect"] = {
					{
						["prefabPath"] = "Effect/Eff/com/debuff_neishang01",
						["prefabAnim"] = "debuff_neishang",
						["depth"] = 0x3,
						["offsetX"] = nil,
						["offsetY"] = nil,
						["noOnRole"] = nil,
						["mount1Name"] = nil,
						["mount2Name"] = "ref_overhead",
						["delay"] = nil,
						["fullScreen"] = nil,
						["scale"] = 1.000000,
						["onHurt"] = nil,
						["onlyOnce"] = nil,
						["noFlipX"] = true,
						["audio"] = 0x0,
						["onFloor"] = nil,
						["layerValue"] = 0x0,
					},
				},
				["hurtEffect"] = nil,
				["sceneEffect"] = nil,
				["hurtEffectDelayTime"] = nil,
				["hurtAnimation"] = nil,
				["hurtAnimationDelayTime"] = nil,
			},
		},
		["playOnAdd"] = false,
	},
	[0x8d] = {
		["id"] = 0x8d,
		["effect"] = nil,
		["layerEffect"] = nil,
		["skillEffect"] = {
			{
				["actionInfo"] = nil,
				["castEffect"] = {
					{
						["prefabPath"] = "Effect/Eff/com/debuff_canfei01",
						["prefabAnim"] = "debuff_canfei",
						["depth"] = 0x3,
						["offsetX"] = nil,
						["offsetY"] = nil,
						["noOnRole"] = nil,
						["mount1Name"] = nil,
						["mount2Name"] = "ref_overhead",
						["delay"] = nil,
						["fullScreen"] = nil,
						["scale"] = 1.000000,
						["onHurt"] = nil,
						["onlyOnce"] = nil,
						["noFlipX"] = true,
						["audio"] = 0x0,
						["onFloor"] = nil,
						["layerValue"] = 0x0,
					},
				},
				["hurtEffect"] = nil,
				["sceneEffect"] = nil,
				["hurtEffectDelayTime"] = nil,
				["hurtAnimation"] = nil,
				["hurtAnimationDelayTime"] = nil,
			},
		},
		["playOnAdd"] = false,
	},
	[0x95] = {
		["id"] = 0x95,
		["effect"] = {
			{
				["type"] = 0x1,
				["prefabPath"] = nil,
				["prefabAnim"] = "animation",
				["mountName"] = "ref_origin",
				["scale"] = 2.000000,
				["layer"] = 0x1,
				["noFlipX"] = true,
			},
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x9a] = {
		["id"] = 0x9a,
		["effect"] = {
			{
				["type"] = 0x1,
				["prefabPath"] = "Effect/Eff/com/debuff_xunyun",
				["prefabAnim"] = "animation",
				["mountName"] = "ref_overhead",
				["scale"] = nil,
				["layer"] = 0x1,
				["noFlipX"] = false,
			},
		},
		["layerEffect"] = nil,
		["skillEffect"] = {
			{
				["actionInfo"] = nil,
				["castEffect"] = {
				},
				["hurtEffect"] = nil,
				["sceneEffect"] = nil,
				["hurtEffectDelayTime"] = nil,
				["hurtAnimation"] = nil,
				["hurtAnimationDelayTime"] = nil,
			},
		},
		["playOnAdd"] = false,
	},
	[0x1ae] = {
		["id"] = 0x1ae,
		["effect"] = {
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x1b0] = {
		["id"] = 0x1b0,
		["effect"] = {
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x1f5] = {
		["id"] = 0x1f5,
		["effect"] = {
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x1af] = {
		["id"] = 0x1af,
		["effect"] = {
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x1c8] = {
		["id"] = 0x1c8,
		["effect"] = {
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x1f6] = {
		["id"] = 0x1f6,
		["effect"] = {
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x1c9] = {
		["id"] = 0x1c9,
		["effect"] = {
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x1f7] = {
		["id"] = 0x1f7,
		["effect"] = {
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x1ca] = {
		["id"] = 0x1ca,
		["effect"] = {
		},
		["layerEffect"] = nil,
		["skillEffect"] = {
			{
				["actionInfo"] = nil,
				["castEffect"] = nil,
				["hurtEffect"] = nil,
				["sceneEffect"] = nil,
				["hurtEffectDelayTime"] = nil,
				["hurtAnimation"] = nil,
				["hurtAnimationDelayTime"] = nil,
			},
		},
		["playOnAdd"] = false,
	},
	[0x5a] = {
		["id"] = 0x5a,
		["effect"] = {
			{
				["type"] = 0x1,
				["prefabPath"] = "Effect/Eff/com/buff_xuli",
				["prefabAnim"] = "animation",
				["mountName"] = "ref_origin",
				["scale"] = 2.000000,
				["layer"] = nil,
				["noFlipX"] = false,
			},
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x5b] = {
		["id"] = 0x5b,
		["effect"] = {
			{
				["type"] = 0x1,
				["prefabPath"] = "Effect/Eff/com/buff_xuli",
				["prefabAnim"] = "animation",
				["mountName"] = "ref_origin",
				["scale"] = 1.000000,
				["layer"] = nil,
				["noFlipX"] = false,
			},
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x1e6] = {
		["id"] = 0x1e6,
		["effect"] = {
			{
				["type"] = 0x1,
				["prefabPath"] = "Effect/Eff/com/buff_xuli",
				["prefabAnim"] = "animation",
				["mountName"] = "ref_origin",
				["scale"] = nil,
				["layer"] = nil,
				["noFlipX"] = false,
			},
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x1e8] = {
		["id"] = 0x1e8,
		["effect"] = {
			{
				["type"] = 0x1,
				["prefabPath"] = "Effect/Eff/com/debuff_xunyun",
				["prefabAnim"] = "animation",
				["mountName"] = "ref_overhead",
				["scale"] = nil,
				["layer"] = nil,
				["noFlipX"] = false,
			},
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x1bf] = {
		["id"] = 0x1bf,
		["effect"] = nil,
		["layerEffect"] = nil,
		["skillEffect"] = {
			{
				["actionInfo"] = nil,
				["castEffect"] = {
					{
						["prefabPath"] = nil,
						["prefabAnim"] = "animation",
						["depth"] = nil,
						["offsetX"] = nil,
						["offsetY"] = nil,
						["noOnRole"] = nil,
						["mount1Name"] = nil,
						["mount2Name"] = "ref_origin",
						["delay"] = nil,
						["fullScreen"] = nil,
						["scale"] = nil,
						["onHurt"] = nil,
						["onlyOnce"] = nil,
						["noFlipX"] = nil,
						["audio"] = 0x0,
						["onFloor"] = nil,
						["layerValue"] = 0x0,
					},
				},
				["hurtEffect"] = nil,
				["sceneEffect"] = nil,
				["hurtEffectDelayTime"] = nil,
				["hurtAnimation"] = nil,
				["hurtAnimationDelayTime"] = nil,
			},
		},
		["playOnAdd"] = false,
	},
	[0x1c1] = {
		["id"] = 0x1c1,
		["effect"] = nil,
		["layerEffect"] = nil,
		["skillEffect"] = {
			{
				["actionInfo"] = nil,
				["castEffect"] = {
					{
						["prefabPath"] = nil,
						["prefabAnim"] = "animation",
						["depth"] = nil,
						["offsetX"] = nil,
						["offsetY"] = nil,
						["noOnRole"] = nil,
						["mount1Name"] = nil,
						["mount2Name"] = "ref_origin",
						["delay"] = nil,
						["fullScreen"] = nil,
						["scale"] = nil,
						["onHurt"] = nil,
						["onlyOnce"] = nil,
						["noFlipX"] = nil,
						["audio"] = 0x0,
						["onFloor"] = nil,
						["layerValue"] = 0x0,
					},
				},
				["hurtEffect"] = nil,
				["sceneEffect"] = nil,
				["hurtEffectDelayTime"] = nil,
				["hurtAnimation"] = nil,
				["hurtAnimationDelayTime"] = nil,
			},
		},
		["playOnAdd"] = false,
	},
	[0x12d] = {
		["id"] = 0x12d,
		["effect"] = nil,
		["layerEffect"] = nil,
		["skillEffect"] = {
			{
				["actionInfo"] = nil,
				["castEffect"] = {
				},
				["hurtEffect"] = nil,
				["sceneEffect"] = nil,
				["hurtEffectDelayTime"] = nil,
				["hurtAnimation"] = nil,
				["hurtAnimationDelayTime"] = nil,
			},
		},
		["playOnAdd"] = false,
	},
	[0xd6] = {
		["id"] = 0xd6,
		["effect"] = nil,
		["layerEffect"] = {
			{
				["effect"] = {
					{
						["type"] = 0x1,
						["prefabPath"] = "Effect/Eff/com/fz_kongcenji",
						["prefabAnim"] = "animation5",
						["mountName"] = "ref_origin",
						["scale"] = 2.600000,
						["layer"] = nil,
						["noFlipX"] = false,
					},
				},
				["layer"] = 0x1,
			},
			{
				["effect"] = {
					{
						["type"] = 0x1,
						["prefabPath"] = "Effect/Eff/com/fz_kongcenji",
						["prefabAnim"] = "animation3",
						["mountName"] = "ref_origin",
						["scale"] = 2.700000,
						["layer"] = nil,
						["noFlipX"] = false,
					},
				},
				["layer"] = 0x2,
			},
			{
				["effect"] = {
					{
						["type"] = 0x1,
						["prefabPath"] = "Effect/Eff/com/fz_kongcenji",
						["prefabAnim"] = "animation",
						["mountName"] = "ref_origin",
						["scale"] = 2.800000,
						["layer"] = nil,
						["noFlipX"] = false,
					},
				},
				["layer"] = 0x3,
			},
		},
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x169] = {
		["id"] = 0x169,
		["effect"] = nil,
		["layerEffect"] = nil,
		["skillEffect"] = {
			{
				["actionInfo"] = nil,
				["castEffect"] = {
				},
				["hurtEffect"] = nil,
				["sceneEffect"] = nil,
				["hurtEffectDelayTime"] = nil,
				["hurtAnimation"] = nil,
				["hurtAnimationDelayTime"] = nil,
			},
		},
		["playOnAdd"] = false,
	},
	[0x2da] = {
		["id"] = 0x2da,
		["effect"] = nil,
		["layerEffect"] = nil,
		["skillEffect"] = {
			{
				["actionInfo"] = nil,
				["castEffect"] = {
				},
				["hurtEffect"] = nil,
				["sceneEffect"] = nil,
				["hurtEffectDelayTime"] = nil,
				["hurtAnimation"] = nil,
				["hurtAnimationDelayTime"] = nil,
			},
		},
		["playOnAdd"] = false,
	},
	[0xf03] = {
		["id"] = 0xf03,
		["effect"] = {
			{
				["type"] = 0x2,
				["prefabPath"] = "Effect/Eff/com/fz_kongcenji",
				["prefabAnim"] = "animation",
				["mountName"] = nil,
				["scale"] = 1.000000,
				["layer"] = 0x0,
				["noFlipX"] = false,
			},
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x23c] = {
		["id"] = 0x23c,
		["effect"] = {
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x281] = {
		["id"] = 0x281,
		["effect"] = {
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x25d] = {
		["id"] = 0x25d,
		["effect"] = {
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x240] = {
		["id"] = 0x240,
		["effect"] = {
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x242] = {
		["id"] = 0x242,
		["effect"] = {
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x248] = {
		["id"] = 0x248,
		["effect"] = {
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x244] = {
		["id"] = 0x244,
		["effect"] = {
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x245] = {
		["id"] = 0x245,
		["effect"] = {
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x246] = {
		["id"] = 0x246,
		["effect"] = {
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x24a] = {
		["id"] = 0x24a,
		["effect"] = {
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
	[0x24b] = {
		["id"] = 0x24b,
		["effect"] = {
		},
		["layerEffect"] = nil,
		["skillEffect"] = nil,
		["playOnAdd"] = false,
	},
}
return t