-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local CallUpConfig= {
  [1]={BaseID=1,OpenTag=120001,LevelTag=130001,CurExpTag=130002,TaiJiYuanWuBuff=1143,MaxLevel=7,LevelExp={0,4,16,32,96,192,512,10000,},RankAddExp={0,1,2,4,8,16,32,64,},RankBattleAddExp={0,3,6,12,32,64,128,256,},RankBattleAddEvil={0,1,2,5,10,20,40,50,},LevelYuanWuGift={0,1790,1791,1793,1792,1796,1795,1794,},LayersAddFanJiLv={0,100,200,300,400,500,600,700,},DifficultBattleAboveGoodEvil=100,NormalBattleAboveGoodEvil=-50,NormalBattlePercent=50,NormalBattleChangeResultPercent=-30,DifficultBattleBuff=361,DifficultBattleBuffLayer=50,BaseResultPercent=70,HighRankChangeResultPercent=0,LowRankChangeResultPercent=-20,GoodEvilChangeResultPercent=25,CurMaxExpShowTag=130020,AddFanJiLvShowTag=130019,BattleWinRankLimit=2,LevelLimit=15,},
}

-- export table: CallUpConfig
return CallUpConfig
