-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Cartoon= {
  [1]={BaseID=1,PicPath="StoryCG/cg_story_yu3wen2zhuangqi2an4",nextCartoon=2,},
  [2]={BaseID=2,PicPath="StoryCG/cg_story_mo2jun1luan4jiang1hu2",nextCartoon=0,},
}

-- export table: Cartoon
return Cartoon
