-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local CityInitialWeather= {
  [1]={BaseID=1,CityID=21,StoryID=2,WeatherID=3,},
  [2]={BaseID=2,CityID=31,StoryID=2,WeatherID=7,},
  [3]={BaseID=3,CityID=35,StoryID=2,WeatherID=5,},
  [4]={BaseID=4,CityID=33,StoryID=2,WeatherID=5,},
  [5]={BaseID=5,CityID=30,StoryID=2,WeatherID=4,},
  [6]={BaseID=6,CityID=39,StoryID=2,WeatherID=4,},
  [7]={BaseID=7,CityID=11,StoryID=2,WeatherID=3,},
  [8]={BaseID=8,CityID=27,StoryID=2,WeatherID=2,},
  [9]={BaseID=9,CityID=15,StoryID=2,WeatherID=3,},
  [10]={BaseID=10,CityID=32,StoryID=2,WeatherID=2,},
}

-- export table: CityInitialWeather
return CityInitialWeather
