-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local CityEventLines= {
  [1]={BaseID=1,FromCity=36,ToCity=30,},
  [2]={BaseID=2,FromCity=19,ToCity=30,},
  [3]={BaseID=3,FromCity=30,ToCity=27,},
  [4]={BaseID=4,FromCity=1,ToCity=27,},
  [5]={BaseID=5,FromCity=4,ToCity=27,},
  [6]={BaseID=6,FromCity=9,ToCity=4,},
  [7]={BaseID=7,FromCity=38,ToCity=33,},
  [8]={BaseID=8,FromCity=5,ToCity=33,},
  [9]={BaseID=9,FromCity=33,ToCity=25,},
  [10]={BaseID=10,FromCity=7,ToCity=25,},
  [11]={BaseID=11,FromCity=34,ToCity=38,},
  [12]={BaseID=12,FromCity=18,ToCity=7,},
  [13]={BaseID=13,FromCity=10,ToCity=31,},
  [14]={BaseID=14,FromCity=39,ToCity=31,},
  [15]={BaseID=15,FromCity=31,ToCity=28,},
  [16]={BaseID=16,FromCity=35,ToCity=10,},
  [17]={BaseID=17,FromCity=15,ToCity=10,},
  [18]={BaseID=18,FromCity=11,ToCity=26,},
  [19]={BaseID=19,FromCity=40,ToCity=26,},
  [20]={BaseID=20,FromCity=37,ToCity=40,},
  [21]={BaseID=21,FromCity=5,ToCity=37,},
  [22]={BaseID=22,FromCity=7,ToCity=11,},
  [23]={BaseID=23,FromCity=2,ToCity=21,},
  [24]={BaseID=24,FromCity=19,ToCity=18,},
  [25]={BaseID=25,FromCity=18,ToCity=21,},
  [26]={BaseID=26,FromCity=9,ToCity=21,},
  [27]={BaseID=27,FromCity=34,ToCity=9,},
  [28]={BaseID=28,FromCity=17,ToCity=18,},
}

-- export table: CityEventLines
return CityEventLines
