-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum RankType
require("common");


local ClanPrestigeRankInfluence= {
  [1]={BaseID=1,Rank=RankType.RT_White,WageRate=80,PrestigeScore=1,PrestigeID=7011,TiGuanLingPaiNum=1,},
  [2]={BaseID=2,Rank=RankType.RT_Green,WageRate=60,PrestigeScore=2,PrestigeID=7012,TiGuanLingPaiNum=2,},
  [3]={BaseID=3,Rank=RankType.RT_Blue,WageRate=25,PrestigeScore=2,PrestigeID=7013,TiGuanLingPaiNum=2,},
  [4]={BaseID=4,Rank=RankType.RT_Purple,WageRate=15,PrestigeScore=3,PrestigeID=7014,TiGuanLingPaiNum=3,},
  [5]={BaseID=5,Rank=RankType.RT_Orange,WageRate=10,PrestigeScore=3,PrestigeID=7015,TiGuanLingPaiNum=3,},
  [6]={BaseID=6,Rank=RankType.RT_Golden,WageRate=5,PrestigeScore=8,PrestigeID=7016,TiGuanLingPaiNum=8,},
  [7]={BaseID=7,Rank=RankType.RT_DarkGolden,WageRate=1,PrestigeScore=10,PrestigeID=7017,TiGuanLingPaiNum=10,},
}

-- export table: ClanPrestigeRankInfluence
return ClanPrestigeRankInfluence
