-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local ClanTaskType= {
  [1]={BaseID=1,Hard=1,ClanTaskTypeID={1,2,3,4,5,6,7,},TaskTypeWeight={0,0,1,0,0,1,0,},},
  [2]={BaseID=2,Hard=2,ClanTaskTypeID={1,2,3,4,5,6,7,},TaskTypeWeight={0,0,1,0,0,1,0,},},
  [3]={BaseID=3,Hard=3,ClanTaskTypeID={1,2,3,4,5,6,7,},TaskTypeWeight={0,0,1,0,0,1,0,},},
  [4]={BaseID=4,Hard=4,ClanTaskTypeID={1,2,3,4,5,6,7,},TaskTypeWeight={1,1,3,1,1,3,1,},},
  [5]={BaseID=5,Hard=5,ClanTaskTypeID={1,2,3,4,5,6,7,},TaskTypeWeight={1,1,3,1,1,3,1,},},
  [6]={BaseID=6,Hard=6,ClanTaskTypeID={1,2,3,4,5,6,7,},TaskTypeWeight={1,1,3,1,1,3,1,},},
  [7]={BaseID=7,Hard=7,ClanTaskTypeID={1,2,3,4,5,6,7,},TaskTypeWeight={1,1,1,1,1,1,1,},},
  [8]={BaseID=8,Hard=8,ClanTaskTypeID={1,2,3,4,5,6,7,},TaskTypeWeight={1,1,1,1,1,1,1,},},
  [9]={BaseID=9,Hard=9,ClanTaskTypeID={1,2,3,4,5,6,7,},TaskTypeWeight={1,1,1,1,1,1,1,},},
}

-- export table: ClanTaskType
return ClanTaskType
