-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum FavorType
require("common");


local ClanItemType= {
  [1]={BaseID=1,ClanItemTypeID=FavorType.FT_Music,},
  [2]={BaseID=2,ClanItemTypeID=FavorType.FT_Game,},
  [3]={BaseID=3,ClanItemTypeID=FavorType.FT_Paint,},
  [4]={BaseID=4,ClanItemTypeID=FavorType.FT_Wine,},
  [5]={BaseID=5,ClanItemTypeID=FavorType.FT_Flower,},
  [6]={BaseID=6,ClanItemTypeID=FavorType.FT_LivingItem,},
  [7]={BaseID=7,ClanItemTypeID=FavorType.FT_Food,},
  [8]={BaseID=8,ClanItemTypeID=FavorType.FT_Cooking,},
  [9]={BaseID=9,ClanItemTypeID=FavorType.FT_Medicinal,},
  [10]={BaseID=10,ClanItemTypeID=FavorType.FT_Ore,},
  [11]={BaseID=11,ClanItemTypeID=FavorType.FT_Maquillage,},
}

-- export table: ClanItemType
return ClanItemType
