-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local ClanTaskGold= {
  [1]={BaseID=1,Gold=800,Reward=0,},
  [2]={BaseID=2,Gold=1300,Reward=0,},
  [3]={BaseID=3,Gold=1800,Reward=0,},
  [4]={BaseID=4,Gold=2300,Reward=0,},
  [5]={BaseID=5,Gold=2800,Reward=0,},
  [6]={BaseID=6,Gold=3300,Reward=0,},
  [7]={BaseID=7,Gold=3800,Reward=0,},
  [8]={BaseID=8,Gold=4300,Reward=0,},
  [9]={BaseID=9,Gold=4800,Reward=0,},
}

-- export table: ClanTaskGold
return ClanTaskGold
