-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local ClanRandomNameDefault = {Ch_Text=0,English_Text=0,}
local ClanRandomName= {
  [2170001]={BaseID=2170001,},
  [2170002]={BaseID=2170002,},
  [2170003]={BaseID=2170003,},
  [2170004]={BaseID=2170004,},
  [2170005]={BaseID=2170005,},
  [2170006]={BaseID=2170006,},
  [2170007]={BaseID=2170007,},
  [2170008]={BaseID=2170008,},
  [2170009]={BaseID=2170009,},
  [2170010]={BaseID=2170010,},
  [2170011]={BaseID=2170011,},
  [2170012]={BaseID=2170012,},
  [2170013]={BaseID=2170013,},
  [2170014]={BaseID=2170014,},
  [2170015]={BaseID=2170015,},
  [2170016]={BaseID=2170016,},
  [2170017]={BaseID=2170017,},
  [2170018]={BaseID=2170018,},
  [2170019]={BaseID=2170019,},
  [2170020]={BaseID=2170020,},
  [2170021]={BaseID=2170021,},
  [2170022]={BaseID=2170022,},
  [2170023]={BaseID=2170023,},
  [2170024]={BaseID=2170024,},
  [2170025]={BaseID=2170025,},
  [2170026]={BaseID=2170026,},
  [2170027]={BaseID=2170027,},
  [2170028]={BaseID=2170028,},
}
for k,v in pairs(ClanRandomName) do
    setmetatable(v, {['__index'] = ClanRandomNameDefault})
end

-- export table: ClanRandomName
return ClanRandomName
