-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local CollectionAchieve= {
  [1]={BaseID=1,AchievePoint=500,},
  [2]={BaseID=2,AchievePoint=1000,},
  [3]={BaseID=3,AchievePoint=2000,},
  [4]={BaseID=4,AchievePoint=5000,},
  [5]={BaseID=5,AchievePoint=10000,},
  [6]={BaseID=6,AchievePoint=15000,},
  [7]={BaseID=7,AchievePoint=25000,},
}

-- export table: CollectionAchieve
return CollectionAchieve
