-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum RankType
require("common");


local CuiLianRankConfig= {
  [1]={Rank=RankType.RT_White,CuilianValue=5,},
  [2]={Rank=RankType.RT_Green,CuilianValue=10,},
  [3]={Rank=RankType.RT_Blue,CuilianValue=20,},
  [4]={Rank=RankType.RT_Purple,CuilianValue=50,},
  [5]={Rank=RankType.RT_Orange,CuilianValue=100,},
  [6]={Rank=RankType.RT_Golden,CuilianValue=200,},
  [7]={Rank=RankType.RT_DarkGolden,CuilianValue=500,},
  [8]={Rank=RankType.RT_MultiColor,CuilianValue=500,},
}

-- export table: CuiLianRankConfig
return CuiLianRankConfig
