-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local CuiLianLvConfig= {
  [1]={BaseID=1,CuilianPresent=100,LvMin=20,},
  [2]={BaseID=2,CuilianPresent=80,LvMin=10,},
  [3]={BaseID=3,CuilianPresent=50,LvMin=0,},
}

-- export table: CuiLianLvConfig
return CuiLianLvConfig
