-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local DifficultDefault = {NameID=0,LifeMax=2500000,ExtraMatrtial=4,DefenseMax=430000,GiftValueMax=6000000,MartialLvMax=10,StorageInItem=8,MartialNumMax=12,RoleLvMax=30,AttrMaxValue=50000,JingtongMax=5000,DamageMax=700000,NumberUp=50000,BattleTeammate=5,DefaultMartialLVMax=10,DefaultGoodOpinion=10,EquipAttrUp=0,WeekEndMeridiansCoef=1,GiftCountMax=12,RoleExp=0,MartialExp=0,MaxSilver=0,MaxCoin=99999999,MaxEnhanceLv=15,MaxRoleCardLv=15,MaxPetLv=15,MarryCountMax=66,EatFoodCountMax=40,MPMax=520000,SpeedMax=5000,MartialAttackMax=500000,}
local Difficult= {
  [1]={BaseID=1,Story={0,},Diff=1,LifeMax=1500000,ExtraMatrtial=0,DefenseMax=210000,StorageInItem=4,MartialNumMax=8,AttrMaxValue=10000,DamageMax=300000,EquipLvMax=5,NumberUp=10000,Wage=4500,GiftCountMax=8,MarryCountMax=1,EatFoodCountMax=10,MPMax=280000,SpeedMax=1000,MartialAttackMax=100000,BagMax=600,},
  [2]={BaseID=2,Story={0,},Diff=2,LifeMax=1800000,ExtraMatrtial=2,DefenseMax=250000,StorageInItem=5,MartialNumMax=10,RoleLvMax=32,AttrMaxValue=20000,DamageMax=400000,EquipLvMax=5,NumberUp=15000,Wage=5000,ExtraMsgs={426,420,424,},GiftCountMax=10,MarryCountMax=3,EatFoodCountMax=20,MPMax=340000,SpeedMax=2000,MartialAttackMax=200000,BagMax=700,},
  [3]={BaseID=3,Story={0,},Diff=3,LifeMax=2000000,ExtraMatrtial=2,DefenseMax=300000,StorageInItem=6,MartialNumMax=10,RoleLvMax=32,AttrMaxValue=28000,DamageMax=500000,EquipLvMax=10,NumberUp=20000,Wage=5500,ExtraMsgs={422,425,434,435,},GiftCountMax=10,MarryCountMax=3,EatFoodCountMax=20,MPMax=400000,SpeedMax=3000,MartialAttackMax=280000,BagMax=800,},
  [4]={BaseID=4,Story={0,},Diff=4,LifeMax=2300000,ExtraMatrtial=3,DefenseMax=360000,StorageInItem=7,RoleLvMax=35,AttrMaxValue=38000,DamageMax=600000,EquipLvMax=10,Wage=6000,ExtraMsgs={427,428,},MarryCountMax=10,EatFoodCountMax=20,MPMax=460000,SpeedMax=4000,MartialAttackMax=380000,BagMax=900,},
  [5]={BaseID=5,Story={0,},Diff=5,RoleLvMax=35,EquipLvMax=15,NumberUp=90000,Wage=6500,ExtraMsgs={430,431,436,},BagMax=1000,},
  [6]={BaseID=6,Story={0,},Diff=6,EquipLvMax=5,Wage=7000,BagMax=1100,},
  [7]={BaseID=7,Story={0,},Diff=7,EquipLvMax=6,Wage=7500,BagMax=1200,},
  [8]={BaseID=8,Story={0,},Diff=8,EquipLvMax=7,Wage=8000,BagMax=1300,},
  [9]={BaseID=9,Story={0,},Diff=9,EquipLvMax=8,Wage=8500,BagMax=1400,},
  [10]={BaseID=10,Story={0,},Diff=10,EquipLvMax=9,Wage=9000,BagMax=1500,},
}
for k,v in pairs(Difficult) do
    setmetatable(v, {['__index'] = DifficultDefault})
end

-- export table: Difficult
return Difficult
