-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum DisguiseType
-- enum TBoolean
require("common");


local DisguiseItemDefault = {NameID=0,Lock=TBoolean.BOOL_NO,}
local DisguiseItem= {
  [1]={BaseID=1,NameID=300001,Model=100,DisguiseTypeList={DisguiseType.DGT_TASK,},Lock=TBoolean.BOOL_YES,},
  [2]={BaseID=2,NameID=300002,Model=887,DisguiseTypeList={DisguiseType.DGT_TASK,},Lock=TBoolean.BOOL_YES,},
  [3]={BaseID=3,NameID=300003,Model=99,DisguiseTypeList={DisguiseType.DGT_TASK,},Lock=TBoolean.BOOL_YES,},
  [4]={BaseID=4,NameID=300004,Model=844,DisguiseTypeList={DisguiseType.DGT_TASK,},Lock=TBoolean.BOOL_YES,},
  [5]={BaseID=5,NameID=300005,Model=362,DisguiseTypeList={DisguiseType.DGT_TASK,},Lock=TBoolean.BOOL_YES,},
  [6]={BaseID=6,NameID=300006,Model=259,DisguiseTypeList={DisguiseType.DGT_TASK,},Lock=TBoolean.BOOL_YES,},
  [7]={BaseID=7,NameID=300007,Model=366,DisguiseTypeList={DisguiseType.DGT_TASK,},Lock=TBoolean.BOOL_YES,},
  [8]={BaseID=8,NameID=300008,Model=365,DisguiseTypeList={DisguiseType.DGT_TASK,},Lock=TBoolean.BOOL_YES,},
  [9]={BaseID=9,NameID=300009,Model=188,DisguiseTypeList={DisguiseType.DGT_TASK,},Lock=TBoolean.BOOL_YES,},
  [10]={BaseID=10,NameID=300010,Model=1133,DisguiseTypeList={DisguiseType.DGT_TASK,},Lock=TBoolean.BOOL_YES,},
  [11]={BaseID=11,NameID=300011,Model=1134,DisguiseTypeList={DisguiseType.DGT_TASK,},Lock=TBoolean.BOOL_YES,},
  [100001]={BaseID=100001,Model=137,DisguiseTypeList={DisguiseType.DGT_POPULACE,DisguiseType.DGT_FEMALE,},},
  [100002]={BaseID=100002,Model=33,DisguiseTypeList={DisguiseType.DGT_POPULACE,DisguiseType.DGT_FEMALE,},},
  [100003]={BaseID=100003,Model=47,DisguiseTypeList={DisguiseType.DGT_POPULACE,DisguiseType.DGT_FEMALE,},},
  [100004]={BaseID=100004,Model=175,DisguiseTypeList={DisguiseType.DGT_POPULACE,},},
  [100005]={BaseID=100005,Model=258,DisguiseTypeList={DisguiseType.DGT_POPULACE,DisguiseType.DGT_FEMALE,},},
  [100006]={BaseID=100006,Model=418,DisguiseTypeList={DisguiseType.DGT_POPULACE,DisguiseType.DGT_FEMALE,},},
  [100007]={BaseID=100007,Model=272,DisguiseTypeList={DisguiseType.DGT_POPULACE,DisguiseType.DGT_FEMALE,},},
  [100008]={BaseID=100008,Model=105,DisguiseTypeList={DisguiseType.DGT_POPULACE,},},
  [100009]={BaseID=100009,Model=237,DisguiseTypeList={DisguiseType.DGT_POPULACE,},},
  [100010]={BaseID=100010,Model=174,DisguiseTypeList={DisguiseType.DGT_POPULACE,},},
  [100011]={BaseID=100011,Model=147,DisguiseTypeList={DisguiseType.DGT_IMPORTANTROLE,},},
  [100012]={BaseID=100012,Model=21,DisguiseTypeList={DisguiseType.DGT_FEMALE,DisguiseType.DGT_IMPORTANTROLE,},},
  [100013]={BaseID=100013,Model=28,DisguiseTypeList={DisguiseType.DGT_FEMALE,DisguiseType.DGT_IMPORTANTROLE,},},
  [100014]={BaseID=100014,Model=604,DisguiseTypeList={DisguiseType.DGT_FEMALE,DisguiseType.DGT_IMPORTANTROLE,},},
  [100015]={BaseID=100015,Model=907,DisguiseTypeList={DisguiseType.DGT_FEMALE,DisguiseType.DGT_IMPORTANTROLE,},},
  [100016]={BaseID=100016,Model=6,DisguiseTypeList={DisguiseType.DGT_FEMALE,DisguiseType.DGT_IMPORTANTROLE,},},
  [100017]={BaseID=100017,Model=41,DisguiseTypeList={DisguiseType.DGT_IMPORTANTROLE,},},
  [100018]={BaseID=100018,Model=890,DisguiseTypeList={DisguiseType.DGT_FEMALE,DisguiseType.DGT_IMPORTANTROLE,},},
  [100019]={BaseID=100019,Model=335,DisguiseTypeList={DisguiseType.DGT_IMPORTANTROLE,},},
  [100020]={BaseID=100020,Model=900,DisguiseTypeList={DisguiseType.DGT_FEMALE,DisguiseType.DGT_IMPORTANTROLE,},},
  [100021]={BaseID=100021,Model=871,DisguiseTypeList={DisguiseType.DGT_BUDDHISM,},},
  [100022]={BaseID=100022,Model=51,DisguiseTypeList={DisguiseType.DGT_BUDDHISM,},},
  [100023]={BaseID=100023,Model=206,DisguiseTypeList={DisguiseType.DGT_BUDDHISM,},},
  [100024]={BaseID=100024,Model=57,DisguiseTypeList={DisguiseType.DGT_BUDDHISM,},},
  [100025]={BaseID=100025,Model=64,DisguiseTypeList={DisguiseType.DGT_BUDDHISM,},},
  [100026]={BaseID=100026,Model=55,DisguiseTypeList={DisguiseType.DGT_BUDDHISM,},},
  [100027]={BaseID=100027,Model=125,DisguiseTypeList={DisguiseType.DGT_BUDDHISM,},},
  [100028]={BaseID=100028,Model=8,DisguiseTypeList={DisguiseType.DGT_BUDDHISM,},},
  [100029]={BaseID=100029,Model=557,DisguiseTypeList={DisguiseType.DGT_FEMALE,DisguiseType.DGT_BUDDHISM,},},
  [100030]={BaseID=100030,Model=225,DisguiseTypeList={DisguiseType.DGT_FEMALE,DisguiseType.DGT_BUDDHISM,},},
  [100031]={BaseID=100031,Model=339,DisguiseTypeList={DisguiseType.DGT_FEMALE,DisguiseType.DGT_SWORDMAN,},},
  [100032]={BaseID=100032,Model=628,DisguiseTypeList={DisguiseType.DGT_FEMALE,DisguiseType.DGT_SWORDMAN,},},
  [100033]={BaseID=100033,Model=677,DisguiseTypeList={DisguiseType.DGT_SWORDMAN,},},
  [100034]={BaseID=100034,Model=177,DisguiseTypeList={DisguiseType.DGT_SWORDMAN,},},
  [100035]={BaseID=100035,Model=892,DisguiseTypeList={DisguiseType.DGT_SWORDMAN,},},
  [100036]={BaseID=100036,Model=34,DisguiseTypeList={DisguiseType.DGT_FEMALE,DisguiseType.DGT_SWORDMAN,},},
  [100037]={BaseID=100037,Model=685,DisguiseTypeList={DisguiseType.DGT_FEMALE,DisguiseType.DGT_SWORDMAN,},},
  [100038]={BaseID=100038,Model=940,DisguiseTypeList={DisguiseType.DGT_SWORDMAN,},},
  [100039]={BaseID=100039,Model=387,DisguiseTypeList={DisguiseType.DGT_SWORDMAN,},},
  [100040]={BaseID=100040,Model=313,DisguiseTypeList={DisguiseType.DGT_SWORDMAN,},},
  [100041]={BaseID=100041,Model=480,DisguiseTypeList={DisguiseType.DGT_FEMALE,DisguiseType.DGT_VILLAIN,},},
  [100042]={BaseID=100042,Model=90,DisguiseTypeList={DisguiseType.DGT_VILLAIN,},},
  [100043]={BaseID=100043,Model=588,DisguiseTypeList={DisguiseType.DGT_VILLAIN,},},
  [100044]={BaseID=100044,Model=319,DisguiseTypeList={DisguiseType.DGT_FEMALE,DisguiseType.DGT_VILLAIN,},},
  [100045]={BaseID=100045,Model=83,DisguiseTypeList={DisguiseType.DGT_FEMALE,DisguiseType.DGT_VILLAIN,},},
  [100046]={BaseID=100046,Model=99,DisguiseTypeList={DisguiseType.DGT_VILLAIN,},},
  [100047]={BaseID=100047,Model=609,DisguiseTypeList={DisguiseType.DGT_VILLAIN,},},
  [100048]={BaseID=100048,Model=483,DisguiseTypeList={DisguiseType.DGT_VILLAIN,},},
  [100049]={BaseID=100049,Model=469,DisguiseTypeList={DisguiseType.DGT_VILLAIN,},},
  [100050]={BaseID=100050,Model=358,DisguiseTypeList={DisguiseType.DGT_FEMALE,DisguiseType.DGT_VILLAIN,},},
}
for k,v in pairs(DisguiseItem) do
    setmetatable(v, {['__index'] = DisguiseItemDefault})
end

-- export table: DisguiseItem
return DisguiseItem
