-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum EmBattleSchemeType
require("common");


local EmbattleScheme= {
  [1]={BaseID=1,NameID=401,EmbattleType=EmBattleSchemeType.EBST_Normal,},
  [2]={BaseID=2,NameID=402,EmbattleType=EmBattleSchemeType.EBST_WheelWar,},
  [3]={BaseID=3,NameID=403,EmbattleType=EmBattleSchemeType.EBST_Help,},
  [4]={BaseID=4,NameID=461,EmbattleType=EmBattleSchemeType.EBST_Sub,},
  [5]={BaseID=5,NameID=481,EmbattleType=EmBattleSchemeType.EBST_Single,},
  [6]={BaseID=6,NameID=482,EmbattleType=EmBattleSchemeType.EBST_Team,},
  [7]={BaseID=7,NameID=483,EmbattleType=EmBattleSchemeType.EBST_ArenaHelp,},
}

-- export table: EmbattleScheme
return EmbattleScheme
