-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local EmojiBig= {
  [1]={BaseID=1,GroupID=2,SortID=1,ExchangeText="[bx]",ResourcePath="Emoji/bx_0001",FramePrefabPath="frames_bixin",},
  [2]={BaseID=2,GroupID=2,SortID=2,ExchangeText="[cgdd]",ResourcePath="Emoji/cgdd_0001",FramePrefabPath="frames_cgdd",},
  [3]={BaseID=3,GroupID=2,SortID=3,ExchangeText="[dx]",ResourcePath="Emoji/dx_0001",FramePrefabPath="frames_dx",},
  [4]={BaseID=4,GroupID=2,SortID=4,ExchangeText="[dlxt]",ResourcePath="Emoji/dlxt_0001",FramePrefabPath="frames_dlxt",},
  [5]={BaseID=5,GroupID=2,SortID=5,ExchangeText="[gg]",ResourcePath="Emoji/gg_0001",FramePrefabPath="frames_gg",},
  [6]={BaseID=6,GroupID=2,SortID=6,ExchangeText="[hen]",ResourcePath="Emoji/hen_0001",FramePrefabPath="frames_hen",},
  [7]={BaseID=7,GroupID=2,SortID=7,ExchangeText="[wh]",ResourcePath="Emoji/wh_0001",FramePrefabPath="frames_wh",},
  [8]={BaseID=8,GroupID=2,SortID=8,ExchangeText="[wddn]",ResourcePath="Emoji/wddn_0001",FramePrefabPath="frames_wddn",},
  [9]={BaseID=9,GroupID=2,SortID=9,ExchangeText="[ye]",ResourcePath="Emoji/ye_0001",FramePrefabPath="frames_ye",},
  [10]={BaseID=10,GroupID=2,SortID=10,ExchangeText="[zal]",ResourcePath="Emoji/zal_0001",FramePrefabPath="frames_zal",},
  [11]={BaseID=11,GroupID=2,SortID=11,ExchangeText="[jy]",ResourcePath="Emoji/jy_0001",FramePrefabPath="frames_jy",},
  [12]={BaseID=12,GroupID=2,SortID=12,ExchangeText="[jt]",ResourcePath="Emoji/jt_0001",FramePrefabPath="frames_jt",},
  [13]={BaseID=13,GroupID=2,SortID=13,ExchangeText="[qd]",ResourcePath="Emoji/qd_0001",FramePrefabPath="frames_qd",},
  [14]={BaseID=14,GroupID=2,SortID=14,ExchangeText="[kj]",ResourcePath="Emoji/kjj_0001",FramePrefabPath="frames_kujiji",},
  [15]={BaseID=15,GroupID=2,SortID=15,ExchangeText="[lue]",ResourcePath="Emoji/lue_0001",FramePrefabPath="frames_lue",},
  [16]={BaseID=16,GroupID=2,SortID=16,ExchangeText="[zyjx]",ResourcePath="Emoji/zyjx_0001",FramePrefabPath="frames_zyjx",},
}

-- export table: EmojiBig
return EmojiBig
