-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum EvoluteActionType
require("common");


local EvoluteActionDefault = {ActionArg1=0,ActionArg2=0,ActionArg3=0,ActionArg4=0,ActionArg5=0,}
local EvoluteAction= {
  [1]={BaseID=1,ActionWeight=350,EvoluteActionType=EvoluteActionType.EAT_Other,},
  [2]={BaseID=2,ActionWeight=50,EvoluteActionType=EvoluteActionType.EAT_Move,RecordIDs={1001,},},
  [3]={BaseID=3,ActionWeight=30,EvoluteActionType=EvoluteActionType.EAT_GetKongFu,RecordIDs={1002,1003,1004,},},
  [4]={BaseID=4,ActionWeight=30,EvoluteActionType=EvoluteActionType.EAT_GetGift,RecordIDs={1005,1006,1007,},},
  [5]={BaseID=5,ActionWeight=100,EvoluteActionType=EvoluteActionType.EAT_GetItem,RecordIDs={1008,1009,1010,1011,},},
  [6]={BaseID=6,ActionWeight=30,EvoluteActionType=EvoluteActionType.EAT_ChangeGoodEvil,RecordIDs={1013,},RecordIDs2={1012,},},
  [7]={BaseID=7,ActionWeight=50,EvoluteActionType=EvoluteActionType.EAT_Conflict,ActionArg1=100,ActionArg2=-45,ActionArg3=-35,RecordIDs={1014,},},
  [8]={BaseID=8,ActionWeight=50,EvoluteActionType=EvoluteActionType.EAT_StealKongFu,RecordIDs={1015,},},
  [9]={BaseID=9,ActionWeight=50,EvoluteActionType=EvoluteActionType.EAT_StealGift,RecordIDs={1016,},},
  [10]={BaseID=10,ActionWeight=75,EvoluteActionType=EvoluteActionType.EAT_StealItem,ActionArg1=-10,ActionArg2=-10,ActionArg3=-45,ActionArg4=-35,RecordIDs={1017,},},
  [11]={BaseID=11,ActionWeight=75,EvoluteActionType=EvoluteActionType.EAT_GiveItem,ActionArg1=35,ActionArg2=45,RecordIDs={1018,},},
  [12]={BaseID=12,ActionWeight=75,EvoluteActionType=EvoluteActionType.EAT_MoveItem,RecordIDs={1019,},},
  [13]={BaseID=13,ActionWeight=500,EvoluteActionType=EvoluteActionType.EAT_Avenger,ActionArg1=-80,RecordIDs={1020,},RecordIDs2={1021,},RecordIDs3={1026,},RecordIDs4={1027,},},
  [14]={BaseID=14,ActionWeight=500,EvoluteActionType=EvoluteActionType.EAT_Marray,RecordIDs={1022,},RecordIDs2={1023,},},
  [15]={BaseID=15,ActionWeight=20,EvoluteActionType=EvoluteActionType.EAT_Assassination,ActionArg1=-20,ActionArg2=-40,RecordIDs={1024,},},
  [16]={BaseID=16,ActionWeight=500,EvoluteActionType=EvoluteActionType.EAT_Born,RecordIDs={1025,},},
}
for k,v in pairs(EvoluteAction) do
    setmetatable(v, {['__index'] = EvoluteActionDefault})
end

-- export table: EvoluteAction
return EvoluteAction
