-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local EvoluteBigMapEvent= {
  [1]={BaseID=1,EvoluteBigMapCondition=0,EventList={3584,3585,},EventWeightList={10,10,},},
  [2]={BaseID=2,EvoluteBigMapCondition=0,EventList={3584,3585,3586,3588,},EventWeightList={10,10,10,10,},},
  [3]={BaseID=3,EvoluteBigMapCondition=0,EventList={3584,3585,3586,3588,4637,},EventWeightList={10,10,10,10,20,},},
  [4]={BaseID=4,EvoluteBigMapCondition=0,EventList={3576,},EventWeightList={10,},},
  [5]={BaseID=5,EvoluteBigMapCondition=0,EventList={3584,3585,3586,3587,3588,4637,},EventWeightList={2,2,2,1,2,5,},},
}

-- export table: EvoluteBigMapEvent
return EvoluteBigMapEvent
