-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local EvoluteStrategy= {
  [1]={BaseID=1,StopEvoluteMonthNum=241,MonthNumList={0,61,241,},RoleEvoluteProbList={100,20,0,},},
  [2]={BaseID=2,StopEvoluteMonthNum=50,MonthNumList={0,50,},RoleEvoluteProbList={100,0,},},
  [3]={BaseID=3,StopEvoluteMonthNum=48,MonthNumList={0,48,},RoleEvoluteProbList={20,0,},},
  [4]={BaseID=4,StopEvoluteMonthNum=50,MonthNumList={0,50,},RoleEvoluteProbList={100,0,},},
}

-- export table: EvoluteStrategy
return EvoluteStrategy
