-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local EvoluteBigMapEventCount= {
  [1]={BaseID=1,EvoluteBigMapCountCondition=120001,MinEvent=1,MaxEvent=1,},
  [2]={BaseID=2,EvoluteBigMapCountCondition=120002,MinEvent=1,MaxEvent=3,},
  [3]={BaseID=3,EvoluteBigMapCountCondition=120007,MinEvent=2,MaxEvent=4,},
  [4]={BaseID=4,EvoluteBigMapCountCondition=120012,MinEvent=2,MaxEvent=3,},
  [5]={BaseID=5,EvoluteBigMapCountCondition=120017,MinEvent=2,MaxEvent=3,},
  [6]={BaseID=6,EvoluteBigMapCountCondition=120018,MinEvent=2,MaxEvent=3,},
}

-- export table: EvoluteBigMapEventCount
return EvoluteBigMapEventCount
