-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum FavorType
require("common");


local FavorLetter= {
  [1]={BaseID=1,FavorLetterID=FavorType.FT_Food,},
  [2]={BaseID=2,FavorLetterID=FavorType.FT_Wine,},
  [3]={BaseID=3,FavorLetterID=FavorType.FT_Cooking,},
  [4]={BaseID=4,FavorLetterID=FavorType.FT_Cloth,},
  [5]={BaseID=5,FavorLetterID=FavorType.FT_Jewelry,},
  [6]={BaseID=6,FavorLetterID=FavorType.FT_Weapon,},
  [7]={BaseID=7,FavorLetterID=FavorType.FT_Ore,},
  [8]={BaseID=8,FavorLetterID=FavorType.FT_Flower,},
  [9]={BaseID=9,FavorLetterID=FavorType.FT_Medicinal,},
  [10]={BaseID=10,FavorLetterID=FavorType.FT_LivingItem,},
  [11]={BaseID=11,FavorLetterID=FavorType.FT_Paint,},
}

-- export table: FavorLetter
return FavorLetter
