-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum TBoolean
require("common");


local FinalBattleFriendDefault = {IsCaptain=TBoolean.BOOL_NO,JoinCondition=0,}
local FinalBattleFriend= {
  [101]={BaseID=101,NameID=3720001,Role=1040101013,JoinCondition=90001,},
  [102]={BaseID=102,NameID=3720002,Role=1040101015,JoinCondition=90002,},
  [103]={BaseID=103,NameID=3720003,Role=1230201003,JoinCondition=90003,},
  [104]={BaseID=104,NameID=3720004,Role=1060301003,JoinCondition=90004,},
  [105]={BaseID=105,NameID=3720005,Role=1080301002,JoinCondition=90005,},
  [106]={BaseID=106,NameID=3720006,Role=1090325010,JoinCondition=90006,},
  [107]={BaseID=107,NameID=3720007,Role=1140314003,IsCaptain=TBoolean.BOOL_YES,JoinCondition=90007,},
  [111]={BaseID=111,NameID=3720030,Role=1000026029,},
  [112]={BaseID=112,NameID=3720031,Role=1000026028,},
  [113]={BaseID=113,NameID=3720032,Role=1000026027,},
  [114]={BaseID=114,NameID=3720033,Role=1000012021,IsCaptain=TBoolean.BOOL_YES,},
  [201]={BaseID=201,NameID=3720008,Role=1020101002,JoinCondition=90008,},
  [202]={BaseID=202,NameID=3720009,Role=1170301005,JoinCondition=90009,},
  [203]={BaseID=203,NameID=3720010,Role=1030114001,JoinCondition=90010,},
  [204]={BaseID=204,NameID=3720011,Role=1150301016,JoinCondition=90011,},
  [205]={BaseID=205,NameID=3720012,Role=1120301004,IsCaptain=TBoolean.BOOL_YES,JoinCondition=90012,},
  [211]={BaseID=211,NameID=3720034,Role=1000026050,},
  [212]={BaseID=212,NameID=3720035,Role=1000026049,},
  [213]={BaseID=213,NameID=3720036,Role=1000026048,},
  [214]={BaseID=214,NameID=3720037,Role=1000012018,IsCaptain=TBoolean.BOOL_YES,},
  [301]={BaseID=301,NameID=3720013,Role=1020101003,JoinCondition=90013,},
  [302]={BaseID=302,NameID=3720014,Role=1050101012,JoinCondition=90014,},
  [303]={BaseID=303,NameID=3720015,Role=1050114005,JoinCondition=90015,},
  [304]={BaseID=304,NameID=3720016,Role=1030101017,JoinCondition=90016,},
  [305]={BaseID=305,NameID=3720017,Role=1120314001,JoinCondition=90017,},
  [306]={BaseID=306,NameID=3720018,Role=1270301001,IsCaptain=TBoolean.BOOL_YES,JoinCondition=90018,},
  [311]={BaseID=311,NameID=3720038,Role=1000026023,},
  [312]={BaseID=312,NameID=3720039,Role=1000026022,},
  [313]={BaseID=313,NameID=3720040,Role=1000026021,},
  [314]={BaseID=314,NameID=3720041,Role=1000012014,IsCaptain=TBoolean.BOOL_YES,},
  [401]={BaseID=401,NameID=3720019,Role=1070101009,JoinCondition=90019,},
  [402]={BaseID=402,NameID=3720020,Role=1070112002,JoinCondition=90020,},
  [403]={BaseID=403,NameID=3720021,Role=1020112002,JoinCondition=90021,},
  [404]={BaseID=404,NameID=3720022,Role=1070112004,JoinCondition=90022,},
  [405]={BaseID=405,NameID=3720023,Role=1250301004,JoinCondition=90023,},
  [406]={BaseID=406,NameID=3720024,Role=1070301001,IsCaptain=TBoolean.BOOL_YES,JoinCondition=90024,},
  [411]={BaseID=411,NameID=3720042,Role=1000026003,},
  [412]={BaseID=412,NameID=3720043,Role=1000026002,},
  [413]={BaseID=413,NameID=3720044,Role=1000026001,},
  [414]={BaseID=414,NameID=3720045,Role=1000012019,IsCaptain=TBoolean.BOOL_YES,},
  [501]={BaseID=501,NameID=3720025,Role=1020112001,JoinCondition=90025,},
  [502]={BaseID=502,NameID=3720026,Role=1060112003,JoinCondition=90026,},
  [503]={BaseID=503,NameID=3720027,Role=1140314002,JoinCondition=90027,},
  [504]={BaseID=504,NameID=3720028,Role=1280301001,JoinCondition=90028,},
  [505]={BaseID=505,NameID=3720029,Role=1030101017,IsCaptain=TBoolean.BOOL_YES,JoinCondition=90029,},
  [511]={BaseID=511,NameID=3720046,Role=1000026017,},
  [512]={BaseID=512,NameID=3720047,Role=1000026016,},
  [513]={BaseID=513,NameID=3720048,Role=1000026015,},
  [514]={BaseID=514,NameID=3720049,Role=1140201002,IsCaptain=TBoolean.BOOL_YES,},
}
for k,v in pairs(FinalBattleFriend) do
    setmetatable(v, {['__index'] = FinalBattleFriendDefault})
end

-- export table: FinalBattleFriend
return FinalBattleFriend
