-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local FiveBoss= {
  [1]={BaseID=1,RoleID=1030412001,GiftsID={1529,1530,1531,1532,},LangID=3501001,TagID=130006,IsStrong=0,},
  [2]={BaseID=2,RoleID=1060212001,GiftsID={1529,1530,1531,1532,},LangID=3501002,TagID=130007,IsStrong=0,},
  [3]={BaseID=3,RoleID=1000012008,GiftsID={1529,1530,1531,1532,},LangID=3501003,TagID=130008,IsStrong=0,},
  [4]={BaseID=4,RoleID=1050112005,GiftsID={1529,1530,1531,1532,},LangID=3501004,TagID=130009,IsStrong=0,},
  [5]={BaseID=5,RoleID=1000012002,GiftsID={1529,1530,1531,1532,},LangID=3501005,TagID=130010,IsStrong=0,},
  [6]={BaseID=6,RoleID=1000001398,GiftsID={1533,1534,1535,1536,},LangID=3501006,TagID=130011,IsStrong=1,},
  [7]={BaseID=7,RoleID=1000001399,GiftsID={1533,1534,1535,1536,},LangID=3501007,TagID=130012,IsStrong=1,},
  [8]={BaseID=8,RoleID=1000001400,GiftsID={1533,1534,1535,1536,},LangID=3501008,TagID=130013,IsStrong=1,},
  [9]={BaseID=9,RoleID=1000001397,GiftsID={1533,1534,1535,1536,},LangID=3501009,TagID=130014,IsStrong=1,},
  [10]={BaseID=10,RoleID=1000001401,GiftsID={1533,1534,1535,1536,},LangID=3501010,TagID=130015,IsStrong=1,},
}

-- export table: FiveBoss
return FiveBoss
