-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local ForgeExAttrbaseDefault = {MinWeekRound=1,MaxWeekRound=30,}
local ForgeExAttrbase= {
  [1]={BaseID=1,Name=1,PromotePercent=50,Weight=1000,MaxWeekRound=4,},
  [2]={BaseID=2,Name=2,PromotePercent=60,Weight=800,MaxWeekRound=7,},
  [3]={BaseID=3,Name=3,PromotePercent=70,Weight=600,MaxWeekRound=10,},
  [4]={BaseID=4,Name=4,PromotePercent=80,Weight=400,},
  [5]={BaseID=5,Name=5,PromotePercent=90,Weight=200,},
  [6]={BaseID=6,Name=6,PromotePercent=100,Weight=100,},
  [7]={BaseID=7,Name=7,PromotePercent=110,Weight=50,MinWeekRound=5,},
  [8]={BaseID=8,Name=8,PromotePercent=120,Weight=10,MinWeekRound=9,},
}
for k,v in pairs(ForgeExAttrbase) do
    setmetatable(v, {['__index'] = ForgeExAttrbaseDefault})
end

-- export table: ForgeExAttrbase
return ForgeExAttrbase
