-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local ForgeLevelExp= {
  [1]={BaseID=1,Name=1,ReForgeExp=10,ForgeExp=10,},
  [2]={BaseID=2,Name=2,ReForgeExp=30,ForgeExp=30,},
  [3]={BaseID=3,Name=3,ReForgeExp=80,ForgeExp=80,},
  [4]={BaseID=4,Name=4,ReForgeExp=180,ForgeExp=180,},
  [5]={BaseID=5,Name=5,ReForgeExp=380,ForgeExp=380,},
  [6]={BaseID=6,Name=6,ReForgeExp=780,ForgeExp=780,},
  [7]={BaseID=7,Name=7,ReForgeExp=1580,ForgeExp=1580,},
  [8]={BaseID=8,Name=8,ReForgeExp=2780,ForgeExp=2780,},
  [9]={BaseID=9,Name=9,ReForgeExp=4380,ForgeExp=4380,},
  [10]={BaseID=10,Name=10,ReForgeExp=6380,ForgeExp=6380,},
  [11]={BaseID=11,Name=11,ReForgeExp=8880,ForgeExp=8880,},
  [12]={BaseID=12,Name=12,ReForgeExp=11880,ForgeExp=11880,},
  [13]={BaseID=13,Name=13,ReForgeExp=15380,ForgeExp=15380,},
  [14]={BaseID=14,Name=14,ReForgeExp=19380,ForgeExp=19380,},
  [15]={BaseID=15,Name=15,ReForgeExp=999999,ForgeExp=999999,},
}

-- export table: ForgeLevelExp
return ForgeLevelExp
