-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local ForgeLevelExpDefault = {ReForgeExp=10,ForgeExp=10,}
local ForgeLevelExp= {
  [1]={BaseID=1,Name=1,},
  [2]={BaseID=2,Name=2,},
  [3]={BaseID=3,Name=3,},
  [4]={BaseID=4,Name=4,},
  [5]={BaseID=5,Name=5,},
  [6]={BaseID=6,Name=6,},
  [7]={BaseID=7,Name=7,},
  [8]={BaseID=8,Name=8,},
  [9]={BaseID=9,Name=9,},
  [10]={BaseID=10,Name=10,},
  [11]={BaseID=11,Name=11,},
  [12]={BaseID=12,Name=12,},
  [13]={BaseID=13,Name=13,},
  [14]={BaseID=14,Name=14,},
  [15]={BaseID=15,Name=15,ReForgeExp=999999,ForgeExp=999999,},
}
for k,v in pairs(ForgeLevelExp) do
    setmetatable(v, {['__index'] = ForgeLevelExpDefault})
end

-- export table: ForgeLevelExp
return ForgeLevelExp
