-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local ForgeRecastPowder= {
  [1]={BaseID=1,Name=1,RankBase={0,0,0,0,0,0,0,0,0,0,},},
  [2]={BaseID=2,Name=2,RankBase={0,0,0,0,0,0,0,0,0,0,},},
  [3]={BaseID=3,Name=3,RankBase={0,0,0,0,0,0,0,0,0,0,},},
  [4]={BaseID=4,Name=4,RankBase={0,0,0,0,0,0,0,0,0,0,},},
  [5]={BaseID=5,Name=5,RankBase={0,0,0,0,0,0,0,0,0,0,},},
  [6]={BaseID=6,Name=6,RankBase={0,0,0,0,0,0,0,0,0,0,},},
  [7]={BaseID=7,Name=7,RankBase={0,0,0,0,0,0,0,0,0,0,},},
  [8]={BaseID=8,Name=8,RankBase={0,0,0,0,0,0,0,0,0,0,},},
}

-- export table: ForgeRecastPowder
return ForgeRecastPowder
