-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local ForgeLevelRecast= {
  [1]={BaseID=1,Name=1,RankBase={0,5,5,5,5,5,4,3,2,},},
  [2]={BaseID=2,Name=2,RankBase={0,5,5,5,5,5,4,3,2,},},
  [3]={BaseID=3,Name=3,RankBase={0,5,5,5,5,5,4,3,2,},},
  [4]={BaseID=4,Name=4,RankBase={0,5,5,5,5,5,4,3,2,},},
  [5]={BaseID=5,Name=5,RankBase={0,5,5,5,5,5,4,3,2,},},
  [6]={BaseID=6,Name=6,RankBase={0,5,5,5,5,5,4,3,2,},},
  [7]={BaseID=7,Name=7,RankBase={0,5,5,5,5,5,4,3,2,},},
  [8]={BaseID=8,Name=8,RankBase={0,5,5,5,5,5,4,3,2,},},
  [9]={BaseID=9,Name=9,RankBase={0,5,5,5,5,5,4,3,2,},},
  [10]={BaseID=10,Name=10,RankBase={0,5,5,5,5,5,4,3,2,},},
  [11]={BaseID=11,Name=11,RankBase={0,5,5,5,5,5,4,3,2,},},
  [12]={BaseID=12,Name=12,RankBase={0,5,5,5,5,5,4,3,2,},},
  [13]={BaseID=13,Name=13,RankBase={0,5,5,5,5,5,4,3,2,},},
  [14]={BaseID=14,Name=14,RankBase={0,5,5,5,5,5,4,3,2,},},
  [15]={BaseID=15,Name=15,RankBase={0,5,5,5,5,5,4,3,2,},},
}

-- export table: ForgeLevelRecast
return ForgeLevelRecast
