-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local ForgeNpc= {
  [1]={BaseID=1,ForgeMakeIDList={29,33,37,25,121,125,129,21,17,13,171,175,},},
  [2]={BaseID=2,ForgeMakeIDList={56,62,61,60,59,58,57,},UseConditionList={80030,80030,80030,80030,80030,80030,80030,},},
  [3]={BaseID=3,ForgeMakeIDList={6,45,44,54,53,52,51,50,49,48,47,46,},},
  [5]={BaseID=5,ForgeMakeIDList={4,},},
  [6]={BaseID=6,ForgeMakeIDList={117,},},
  [7]={BaseID=7,ForgeMakeIDList={133,139,137,136,135,61,},},
  [8]={BaseID=8,ForgeMakeIDList={1,},},
  [9]={BaseID=9,ForgeMakeIDList={2,},},
  [10]={BaseID=10,ForgeMakeIDList={131,45,53,50,47,101,56,61,62,},CondTagList={521,0,0,0,0,507,0,0,0,},},
  [11]={BaseID=11,ForgeMakeIDList={6,54,51,48,},},
  [12]={BaseID=12,ForgeMakeIDList={8,100,},},
  [13]={BaseID=13,ForgeMakeIDList={87,88,},},
  [14]={BaseID=14,ForgeMakeIDList={9,},},
  [15]={BaseID=15,ForgeMakeIDList={10,},},
  [16]={BaseID=16,ForgeMakeIDList={170,},},
  [17]={BaseID=17,ForgeMakeIDList={203,210,211,182,223,224,35,34,33,32,141,151,235,236,},},
  [20]={BaseID=20,ForgeMakeIDList={103,},},
  [21]={BaseID=21,ForgeMakeIDList={5,},},
  [22]={BaseID=22,ForgeMakeIDList={56,62,60,61,59,58,116,},CondTagList={0,0,0,0,0,0,1470,},},
}

-- export table: ForgeNpc
return ForgeNpc
