-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum MallRewardType
require("common");


local GlobalBeg= {
  [1]={BaseID=1,NeedMoney=10000,MallRewardType=MallRewardType.MallRewardType_NULL,value=0,LanguageID=544,},
}

-- export table: GlobalBeg
return GlobalBeg
