-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum TBoolean
require("common");


local GovernmentTaskConfig= {
  [1]={BaseID=1,TaskPublishList={1070114001,1050114001,1060114001,1030301002,1030114001,},ClanRewardTargetList={63,},IsClanDispositionRewardEqualToCity=TBoolean.BOOL_YES,TaskPublishMapList={6,9,2,1758,7,},},
}

-- export table: GovernmentTaskConfig
return GovernmentTaskConfig
