-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum TBoolean
require("common");


local GuideList= {
  [1]={BaseID=1,GuideKey="1",GuideArray={4,},AutoStart=TBoolean.BOOL_NO,},
  [2]={BaseID=2,GuideKey="2",GuideArray={7,9,10,8,},AutoStart=TBoolean.BOOL_YES,},
  [3]={BaseID=3,GuideKey="3",GuideArray={11,13,},AutoStart=TBoolean.BOOL_NO,},
  [4]={BaseID=4,GuideKey="4",GuideArray={14,},AutoStart=TBoolean.BOOL_YES,},
  [5]={BaseID=5,GuideKey="5",GuideArray={17,18,19,},AutoStart=TBoolean.BOOL_YES,},
  [6]={BaseID=6,GuideKey="6",GuideArray={20,21,22,23,},AutoStart=TBoolean.BOOL_YES,},
  [7]={BaseID=7,GuideKey="7",GuideArray={29,30,},AutoStart=TBoolean.BOOL_YES,},
  [8]={BaseID=8,GuideKey="8",GuideArray={25,26,},AutoStart=TBoolean.BOOL_YES,},
  [9]={BaseID=9,GuideKey="9",GuideArray={31,32,33,},AutoStart=TBoolean.BOOL_NO,},
  [10]={BaseID=10,GuideKey="10",GuideArray={5,},AutoStart=TBoolean.BOOL_NO,},
  [11]={BaseID=11,GuideKey="11",GuideArray={4,},AutoStart=TBoolean.BOOL_NO,},
  [12]={BaseID=12,GuideKey="12",GuideArray={34,},AutoStart=TBoolean.BOOL_NO,},
  [13]={BaseID=13,GuideKey="13",GuideArray={35,},AutoStart=TBoolean.BOOL_NO,},
  [14]={BaseID=14,GuideKey="14",GuideArray={36,},AutoStart=TBoolean.BOOL_NO,},
  [15]={BaseID=15,GuideKey="15",GuideArray={37,},AutoStart=TBoolean.BOOL_NO,},
  [16]={BaseID=16,GuideKey="16",GuideArray={38,},AutoStart=TBoolean.BOOL_NO,},
  [17]={BaseID=17,GuideKey="17",GuideArray={39,44,},AutoStart=TBoolean.BOOL_YES,},
  [18]={BaseID=18,GuideKey="18",GuideArray={40,},AutoStart=TBoolean.BOOL_NO,},
  [19]={BaseID=19,GuideKey="19",GuideArray={41,42,43,},AutoStart=TBoolean.BOOL_NO,},
  [23]={BaseID=23,GuideKey="23",GuideArray={55,56,57,},AutoStart=TBoolean.BOOL_NO,},
  [24]={BaseID=24,GuideKey="24",GuideArray={58,59,},AutoStart=TBoolean.BOOL_NO,},
  [27]={BaseID=27,GuideKey="27",GuideArray={62,63,64,149,65,},AutoStart=TBoolean.BOOL_NO,},
  [28]={BaseID=28,GuideKey="28",GuideArray={66,67,},AutoStart=TBoolean.BOOL_NO,},
  [29]={BaseID=29,GuideKey="29",GuideArray={69,70,71,},AutoStart=TBoolean.BOOL_NO,},
  [30]={BaseID=30,GuideKey="30",GuideArray={72,73,},AutoStart=TBoolean.BOOL_NO,},
  [31]={BaseID=31,GuideKey="31",GuideArray={74,},AutoStart=TBoolean.BOOL_NO,},
  [33]={BaseID=33,GuideKey="33",GuideArray={76,},AutoStart=TBoolean.BOOL_NO,},
  [34]={BaseID=34,GuideKey="34",GuideArray={77,},AutoStart=TBoolean.BOOL_NO,},
  [35]={BaseID=35,GuideKey="35",GuideArray={78,},AutoStart=TBoolean.BOOL_NO,},
  [36]={BaseID=36,GuideKey="36",GuideArray={79,},AutoStart=TBoolean.BOOL_NO,},
  [37]={BaseID=37,GuideKey="37",GuideArray={80,},AutoStart=TBoolean.BOOL_NO,},
  [38]={BaseID=38,GuideKey="38",GuideArray={81,82,83,84,},AutoStart=TBoolean.BOOL_NO,},
  [39]={BaseID=39,GuideKey="39",GuideArray={85,86,87,},AutoStart=TBoolean.BOOL_NO,},
  [52]={BaseID=52,GuideKey="52",GuideArray={120,},AutoStart=TBoolean.BOOL_NO,},
  [57]={BaseID=57,GuideKey="57",GuideArray={131,},AutoStart=TBoolean.BOOL_NO,},
  [58]={BaseID=58,GuideKey="58",GuideArray={132,},AutoStart=TBoolean.BOOL_NO,},
  [59]={BaseID=59,GuideKey="59",GuideArray={41,133,},AutoStart=TBoolean.BOOL_NO,},
  [60]={BaseID=60,GuideKey="60",GuideArray={134,},AutoStart=TBoolean.BOOL_NO,},
  [61]={BaseID=61,GuideKey="61",GuideArray={135,},AutoStart=TBoolean.BOOL_NO,},
  [62]={BaseID=62,GuideKey="62",GuideArray={136,},AutoStart=TBoolean.BOOL_NO,},
  [63]={BaseID=63,GuideKey="63",GuideArray={137,138,139,140,142,141,},AutoStart=TBoolean.BOOL_NO,},
  [65]={BaseID=65,GuideKey="65",GuideArray={148,},AutoStart=TBoolean.BOOL_NO,},
  [66]={BaseID=66,GuideKey="66",GuideArray={150,151,152,},AutoStart=TBoolean.BOOL_NO,},
  [67]={BaseID=67,GuideKey="67",GuideArray={153,154,155,},AutoStart=TBoolean.BOOL_NO,},
}

-- export table: GuideList
return GuideList
