-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum TBoolean
require("common");


local HoodleTeach= {
  [1]={BaseID=1,ReplaceReward={2,4,5,},ReplaceItem={35001,35002,35003,},RewardSeq={2,5,4,},},
}

-- export table: HoodleTeach
return HoodleTeach
