-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum RankType
require("common");


local InnerDemonItemDefault = {White=RankType.RT_Blue,Green=RankType.RT_Blue,Blue=RankType.RT_Blue,Purple=RankType.RT_Purple,Orange=RankType.RT_Purple,Golden=RankType.RT_Golden,DarkGolden=RankType.RT_DarkGolden,}
local InnerDemonItem= {
  [0]={BaseID=0,White=RankType.RT_Green,Purple=RankType.RT_Blue,},
  [1]={BaseID=1,White=RankType.RT_Green,Purple=RankType.RT_Blue,},
  [2]={BaseID=2,White=RankType.RT_Green,Purple=RankType.RT_Blue,},
  [3]={BaseID=3,},
  [4]={BaseID=4,},
  [5]={BaseID=5,},
  [6]={BaseID=6,Orange=RankType.RT_Orange,Golden=RankType.RT_DarkGolden,},
  [7]={BaseID=7,Orange=RankType.RT_Orange,Golden=RankType.RT_DarkGolden,},
  [8]={BaseID=8,Orange=RankType.RT_Orange,Golden=RankType.RT_DarkGolden,},
  [9]={BaseID=9,Orange=RankType.RT_Orange,Golden=RankType.RT_DarkGolden,},
  [10]={BaseID=10,Purple=RankType.RT_Golden,Orange=RankType.RT_Orange,Golden=RankType.RT_DarkGolden,},
}
for k,v in pairs(InnerDemonItem) do
    setmetatable(v, {['__index'] = InnerDemonItemDefault})
end

-- export table: InnerDemonItem
return InnerDemonItem
