-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local InquiryReward= {
  [1]={BaseID=1,CityID=21,FoodDrop={8810,8811,8812,8813,},},
  [2]={BaseID=2,CityID=25,FoodDrop={8805,8806,8807,8808,8809,},},
  [3]={BaseID=3,CityID=26,FoodDrop={8814,8815,8816,},},
  [4]={BaseID=4,CityID=27,FoodDrop={8801,8802,8803,8804,},},
  [5]={BaseID=5,CityID=28,FoodDrop={8817,8818,8819,8820,},},
}

-- export table: InquiryReward
return InquiryReward
