-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum TBoolean
require("common");


local InquiryConfig= {
  [1]={BaseID=1,GoodEvilMin=-100,GoodEvilMax=-50,ReviseNullPercent=0,ReviseNull=0,ReviseNullAddition=TBoolean.BOOL_YES,ReviseDoubtPercent=100,ReviseDoubt=125,ReviseDoubtAddition=TBoolean.BOOL_YES,ReviseGuilt=-25,ReviseGuiltAddition=TBoolean.BOOL_NO,RevisePercent=100,},
  [2]={BaseID=2,GoodEvilMin=-50,GoodEvilMax=50,ReviseNullPercent=75,ReviseNull=50,ReviseNullAddition=TBoolean.BOOL_YES,ReviseDoubtPercent=50,ReviseDoubt=100,ReviseDoubtAddition=TBoolean.BOOL_NO,ReviseGuilt=50,ReviseGuiltAddition=TBoolean.BOOL_NO,RevisePercent=25,},
  [3]={BaseID=3,GoodEvilMin=50,GoodEvilMax=100,ReviseNullPercent=50,ReviseNull=100,ReviseNullAddition=TBoolean.BOOL_YES,ReviseDoubtPercent=50,ReviseDoubt=100,ReviseDoubtAddition=TBoolean.BOOL_NO,ReviseGuilt=0,ReviseGuiltAddition=TBoolean.BOOL_YES,RevisePercent=0,},
}

-- export table: InquiryConfig
return InquiryConfig
