-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local InteractLimitConfig= {
  [1]={BaseID=1,RefreshGetCoinMin=1250,RefreshGetCoinMax=2500,},
}

-- export table: InteractLimitConfig
return InteractLimitConfig
