-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum PlayerBehaviorType
require("common");


local InteractLimitDefault = {RefreshTimes=50,Clock=0,BattleID=1163,CostYinDing=50,RefreshAddProbability=0,RefreshAddProbabilityLimit=0,}
local InteractLimit= {
  [1]={BaseID=1,PlayerBehavior=PlayerBehaviorType.PBT_QingJiao,MustGetTimes=10,DesID=180045,RefreshAddTimesTag=130041,},
  [2]={BaseID=2,PlayerBehavior=PlayerBehaviorType.PBT_TouXue,MustGetTimes=5,DesID=180046,RefreshAddTimesTag=130041,},
  [3]={BaseID=3,PlayerBehavior=PlayerBehaviorType.PBT_QieCuo,MustGetTimes=15,DesID=180047,RefreshAddTimesTag=130022,},
  [4]={BaseID=4,PlayerBehavior=PlayerBehaviorType.PBT_GiftRefresh,MustGetTimes=4,RefreshTimes=200,DesID=0,BattleID=0,CostYinDing=10,RefreshAddTimesTag=0,},
  [5]={BaseID=5,PlayerBehavior=PlayerBehaviorType.PBT_QiTao,MustGetTimes=15,DesID=180048,RefreshAddTimesTag=130023,},
  [6]={BaseID=6,PlayerBehavior=PlayerBehaviorType.PBT_WishTaskRewardRefresh,MustGetTimes=0,RefreshTimes=200,DesID=0,BattleID=0,CostYinDing=10,RefreshAddTimesTag=0,},
  [7]={BaseID=7,PlayerBehavior=PlayerBehaviorType.PBT_CallUp,MustGetTimes=10,DesID=180100,RefreshAddTimesTag=130021,RefreshAddProbability=5,RefreshAddProbabilityLimit=20,},
  [8]={BaseID=8,PlayerBehavior=PlayerBehaviorType.PBT_Punish,MustGetTimes=0,DesID=0,RefreshAddTimesTag=0,},
  [9]={BaseID=9,PlayerBehavior=PlayerBehaviorType.PBT_INQUIRY,MustGetTimes=0,DesID=180101,BattleID=0,RefreshAddTimesTag=130040,},
  [10]={BaseID=10,PlayerBehavior=PlayerBehaviorType.PBT_Absorb,MustGetTimes=999,DesID=0,RefreshAddTimesTag=0,},
}
for k,v in pairs(InteractLimit) do
    setmetatable(v, {['__index'] = InteractLimitDefault})
end

-- export table: InteractLimit
return InteractLimit
