-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum RankType
require("common");


local ItemRandomWeight= {
  [1]={BaseID=1,Rank=RankType.RT_White,Weight=100,},
  [2]={BaseID=2,Rank=RankType.RT_Green,Weight=80,},
  [3]={BaseID=3,Rank=RankType.RT_Blue,Weight=50,},
  [4]={BaseID=4,Rank=RankType.RT_Purple,Weight=20,},
  [5]={BaseID=5,Rank=RankType.RT_Orange,Weight=10,},
  [6]={BaseID=6,Rank=RankType.RT_Golden,Weight=5,},
  [7]={BaseID=7,Rank=RankType.RT_DarkGolden,Weight=2,},
  [8]={BaseID=8,Rank=RankType.RT_MultiColor,Weight=2,},
  [9]={BaseID=9,Rank=RankType.RT_ThirdGearDarkGolden,Weight=2,},
}

-- export table: ItemRandomWeight
return ItemRandomWeight
