-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum AttrType
require("common");


local ItemAttrLimitDefault = {Martial=AttrType.ATTR_NULL,WhiteLimit=0,Greenlimit=2590,SumLimit=0,}
local ItemAttrLimit= {
  [1]={BaseID=1,Attribute=AttrType.ATTR_LIDAO,WhiteLimit=5000,SumLimit=13813,},
  [2]={BaseID=2,Attribute=AttrType.ATTR_LINGQIAO,WhiteLimit=5000,SumLimit=13466,},
  [3]={BaseID=3,Attribute=AttrType.ATTR_NEIJIN,WhiteLimit=5000,SumLimit=13466,},
  [4]={BaseID=4,Attribute=AttrType.ATTR_TIZHI,WhiteLimit=10000,Greenlimit=5000,SumLimit=15576,},
  [5]={BaseID=5,Attribute=AttrType.ATTR_JINGLI,WhiteLimit=5000,SumLimit=14157,},
  [6]={BaseID=6,Attribute=AttrType.ATTR_WUXING,WhiteLimit=5000,SumLimit=14157,},
  [7]={BaseID=7,Attribute=AttrType.ATTR_QUANZHANGJINGTONG,SumLimit=6701,},
  [8]={BaseID=8,Attribute=AttrType.ATTR_DAOFAJINGTONG,SumLimit=6701,},
  [9]={BaseID=9,Attribute=AttrType.ATTR_TUIFAJINGTONG,SumLimit=6701,},
  [10]={BaseID=10,Attribute=AttrType.ATTR_JIANFAJINGTONG,SumLimit=6701,},
  [11]={BaseID=11,Attribute=AttrType.ATTR_NEIGONGJINGTONG,SumLimit=6701,},
  [12]={BaseID=12,Attribute=AttrType.ATTR_YISHUJINGTONG,SumLimit=6701,},
  [13]={BaseID=13,Attribute=AttrType.ATTR_QIMENJINGTONG,SumLimit=6701,},
  [14]={BaseID=14,Attribute=AttrType.ATTR_ANQIJINGTONG,SumLimit=6701,},
  [15]={BaseID=15,Attribute=AttrType.ATTR_MAXHP,Greenlimit=259200,SumLimit=5000000,},
  [16]={BaseID=16,Attribute=AttrType.ATTR_QUANZHANGATK,Greenlimit=25920,SumLimit=150000,},
  [17]={BaseID=17,Attribute=AttrType.ATTR_DAOFAATK,Greenlimit=25920,SumLimit=150000,},
  [18]={BaseID=18,Attribute=AttrType.ATTR_TUIFAATK,Greenlimit=25920,SumLimit=150000,},
  [19]={BaseID=19,Attribute=AttrType.ATTR_JIANFAATK,Greenlimit=25920,SumLimit=150000,},
  [20]={BaseID=20,Attribute=AttrType.ATTR_NEIGONGATK,Greenlimit=25920,SumLimit=150000,},
  [21]={BaseID=21,Attribute=AttrType.ATTR_YISHUATK,Greenlimit=25920,SumLimit=150000,},
  [22]={BaseID=22,Attribute=AttrType.ATTR_QIMENATK,Greenlimit=25920,SumLimit=150000,},
  [23]={BaseID=23,Attribute=AttrType.ATTR_ANQIATK,Greenlimit=25920,SumLimit=150000,},
  [24]={BaseID=24,Attribute=AttrType.ATTR_DEF,Greenlimit=7780,SumLimit=150000,},
  [25]={BaseID=25,Attribute=AttrType.ATTR_MAXMP,Greenlimit=226560,SumLimit=1500000,},
  [26]={BaseID=26,Attribute=AttrType.ATTR_HITATK,Greenlimit=3890,},
  [27]={BaseID=27,Attribute=AttrType.ATTR_SHANBI,Greenlimit=4540,},
  [28]={BaseID=28,Attribute=AttrType.ATTR_CRITATK,Greenlimit=3890,},
  [29]={BaseID=29,Attribute=AttrType.ATTR_BAOJIDIKANGZHI,Greenlimit=3240,},
  [30]={BaseID=30,Attribute=AttrType.ATTR_CONTINUATK,Greenlimit=3240,},
  [31]={BaseID=31,Attribute=AttrType.ATTR_KANGLIANJI,},
  [32]={BaseID=32,Attribute=AttrType.ATTR_ROUNDHP,Greenlimit=24690,},
  [33]={BaseID=33,Attribute=AttrType.ATTR_ROUNDMP,Greenlimit=44950,},
  [34]={BaseID=34,Attribute=AttrType.ATTR_SUDUZHI,Greenlimit=1300,SumLimit=5000,},
  [35]={BaseID=35,Attribute=AttrType.ATTR_NULL,Martial=AttrType.MP_ZUIZHONGSHANGHAIFUJIAZHI,Greenlimit=19160,},
  [36]={BaseID=36,Attribute=AttrType.ATTR_NULL,Martial=AttrType.MP_ZUIZHONGSHANGHAIJIANMIANZHI,Greenlimit=19160,},
  [37]={BaseID=37,Attribute=AttrType.ATTR_NULL,Martial=AttrType.MP_MartialLV,Greenlimit=3,},
  [38]={BaseID=38,Attribute=AttrType.ATTR_LIANZHAOLV,Greenlimit=1,SumLimit=5,},
  [39]={BaseID=39,Attribute=AttrType.ATTR_FANJILV,Greenlimit=1,SumLimit=5,},
  [40]={BaseID=40,Attribute=AttrType.ATTR_HEJILV,Greenlimit=1,SumLimit=5,},
  [41]={BaseID=41,Attribute=AttrType.ATTR_YUANHULV,Greenlimit=1,SumLimit=5,},
  [42]={BaseID=42,Attribute=AttrType.ATTR_JUEZHAOLV,Greenlimit=1,SumLimit=5,},
  [43]={BaseID=43,Attribute=AttrType.ATTR_IGNOREDEFPER,Greenlimit=1,SumLimit=8,},
  [44]={BaseID=44,Attribute=AttrType.ATTR_SUCKHP,Greenlimit=1,SumLimit=5,},
  [45]={BaseID=45,Attribute=AttrType.ATTR_POZHAOLV,Greenlimit=1,SumLimit=5,},
  [46]={BaseID=46,Attribute=AttrType.ATTR_NULL,Martial=AttrType.MP_WEILI,Greenlimit=1,SumLimit=10,},
  [47]={BaseID=47,Attribute=AttrType.ATTR_FANTANLV,Greenlimit=1,SumLimit=5,},
  [48]={BaseID=48,Attribute=AttrType.ATTR_FANTANBEISHU,Greenlimit=1,SumLimit=5,},
}
for k,v in pairs(ItemAttrLimit) do
    setmetatable(v, {['__index'] = ItemAttrLimitDefault})
end

-- export table: ItemAttrLimit
return ItemAttrLimit
