-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum RankType
require("common");


local ItemCrackBase= {
  [1]={BaseID=1,Rank=RankType.RT_White,CrackCountWeightMap={{Value=0,Weight=5000,},{Value=1,Weight=5000,},{Value=2,Weight=0,},{Value=3,Weight=0,},{Value=4,Weight=0,},{Value=5,Weight=0,},{Value=6,Weight=0,},{Value=7,Weight=0,},{Value=8,Weight=0,},},EquipAttrCountUp=1,},
  [2]={BaseID=2,Rank=RankType.RT_Green,CrackCountWeightMap={{Value=0,Weight=4000,},{Value=1,Weight=5000,},{Value=2,Weight=1000,},{Value=3,Weight=0,},{Value=4,Weight=0,},{Value=5,Weight=0,},{Value=6,Weight=0,},{Value=7,Weight=0,},{Value=8,Weight=0,},},EquipAttrCountUp=2,},
  [3]={BaseID=3,Rank=RankType.RT_Blue,CrackCountWeightMap={{Value=0,Weight=3000,},{Value=1,Weight=3500,},{Value=2,Weight=3500,},{Value=3,Weight=0,},{Value=4,Weight=0,},{Value=5,Weight=0,},{Value=6,Weight=0,},{Value=7,Weight=0,},{Value=8,Weight=0,},},EquipAttrCountUp=3,},
  [4]={BaseID=4,Rank=RankType.RT_Purple,CrackCountWeightMap={{Value=0,Weight=1500,},{Value=1,Weight=2500,},{Value=2,Weight=3000,},{Value=3,Weight=3000,},{Value=4,Weight=0,},{Value=5,Weight=0,},{Value=6,Weight=0,},{Value=7,Weight=0,},{Value=8,Weight=0,},},EquipAttrCountUp=4,},
  [5]={BaseID=5,Rank=RankType.RT_Orange,CrackCountWeightMap={{Value=0,Weight=700,},{Value=1,Weight=1500,},{Value=2,Weight=2300,},{Value=3,Weight=3000,},{Value=4,Weight=2500,},{Value=5,Weight=0,},{Value=6,Weight=0,},{Value=7,Weight=0,},{Value=8,Weight=0,},},EquipAttrCountUp=5,},
  [6]={BaseID=6,Rank=RankType.RT_Golden,CrackCountWeightMap={{Value=0,Weight=300,},{Value=1,Weight=1500,},{Value=2,Weight=1700,},{Value=3,Weight=2500,},{Value=4,Weight=2500,},{Value=5,Weight=1500,},{Value=6,Weight=0,},{Value=7,Weight=0,},{Value=8,Weight=0,},},EquipAttrCountUp=6,},
  [7]={BaseID=7,Rank=RankType.RT_DarkGolden,CrackCountWeightMap={{Value=0,Weight=50,},{Value=1,Weight=850,},{Value=2,Weight=1500,},{Value=3,Weight=2000,},{Value=4,Weight=2000,},{Value=5,Weight=2000,},{Value=6,Weight=1600,},{Value=7,Weight=0,},{Value=8,Weight=0,},},EquipAttrCountUp=7,},
  [8]={BaseID=8,Rank=RankType.RT_MultiColor,CrackCountWeightMap={{Value=0,Weight=50,},{Value=1,Weight=850,},{Value=2,Weight=1500,},{Value=3,Weight=2000,},{Value=4,Weight=2000,},{Value=5,Weight=2000,},{Value=6,Weight=1600,},{Value=7,Weight=0,},{Value=8,Weight=0,},},EquipAttrCountUp=7,},
  [9]={BaseID=9,Rank=RankType.RT_ThirdGearDarkGolden,CrackCountWeightMap={{Value=0,Weight=50,},{Value=1,Weight=850,},{Value=2,Weight=1500,},{Value=3,Weight=2000,},{Value=4,Weight=2000,},{Value=5,Weight=2000,},{Value=6,Weight=1600,},{Value=7,Weight=0,},{Value=8,Weight=0,},},EquipAttrCountUp=7,},
}

-- export table: ItemCrackBase
return ItemCrackBase
