-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local ItemStrengthenConfig= {
  [1]={BaseID=1,StrengthenLevel=1,LevelCondUpValue=0,},
  [2]={BaseID=2,StrengthenLevel=2,LevelCondUpValue=0,},
  [3]={BaseID=3,StrengthenLevel=3,LevelCondUpValue=0,},
  [4]={BaseID=4,StrengthenLevel=4,LevelCondUpValue=0,},
  [5]={BaseID=5,StrengthenLevel=5,LevelCondUpValue=0,},
  [6]={BaseID=6,StrengthenLevel=6,LevelCondUpValue=0,},
  [7]={BaseID=7,StrengthenLevel=7,LevelCondUpValue=0,},
  [8]={BaseID=8,StrengthenLevel=8,LevelCondUpValue=0,},
  [9]={BaseID=9,StrengthenLevel=9,LevelCondUpValue=0,},
  [10]={BaseID=10,StrengthenLevel=10,LevelCondUpValue=0,},
  [11]={BaseID=11,StrengthenLevel=11,LevelCondUpValue=0,},
  [12]={BaseID=12,StrengthenLevel=12,LevelCondUpValue=0,},
  [13]={BaseID=13,StrengthenLevel=13,LevelCondUpValue=0,},
  [14]={BaseID=14,StrengthenLevel=14,LevelCondUpValue=0,},
  [15]={BaseID=15,StrengthenLevel=15,LevelCondUpValue=0,},
  [16]={BaseID=16,StrengthenLevel=16,LevelCondUpValue=0,},
  [17]={BaseID=17,StrengthenLevel=17,LevelCondUpValue=0,},
  [18]={BaseID=18,StrengthenLevel=18,LevelCondUpValue=0,},
  [19]={BaseID=19,StrengthenLevel=19,LevelCondUpValue=0,},
  [20]={BaseID=20,StrengthenLevel=20,LevelCondUpValue=0,},
}

-- export table: ItemStrengthenConfig
return ItemStrengthenConfig
