-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [1005041001]="你帮助{发布角色(Language)[Role.NameID]}教训了他的仇人一顿",
  [1005041002]="由于你偷袭成功，本场战斗敌人变弱了。",
  [1005041003]="唔——！好痛！",
  [1005041004]="为了养伤，消耗了3日时间。",
  [1005041005]="是哪个小贼打算偷袭我！",
  [1005041006]="偷袭失败，敌人拿出了更强的实力。",
  [1005041007]="<IF-门派-SHOW-【{门派(Language)[Clan.NameID]}】><IF-委托城市-SHOW-【{委托城市(Language)[City.NameID]}】>{发布角色(Language)[Role.NameID]}拜托你去教训{仇人ID(Language)[Role.NameID]}一顿",
  [1005041008]="你帮助{发布角色(Language)[Role.NameID]}教训了他的仇人一顿",
  [1005047001]="简单",
  [1005047002]="普通",
  [1005047003]="困难",
  [1005047004]="【角色挑战】{发布角色(Language)[Role.NameID]}",
}

-- export table: Language
return Language
