-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [1005291001]="开局奖励-武器",
  [1005291002]="要选择哪件武器呢？",
  [1005291003]="刀",
  [1005291004]="剑",
  [1005291005]="拳套",
  [1005291006]="护腿",
  [1005291007]="棍",
  [1005291008]="针匣",
  [1005291009]="扇",
}

-- export table: Language
return Language
