-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [2830001]="徐超渊",
  [2830002]="薛铖",
  [2830003]="本杰明（BENJAMIN）",
  [2830004]="沈欣彦",
  [2830005]="兰家江",
  [2830006]="任志诚",
  [2830007]="余远奎",
}

-- export table: Language
return Language
