-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [1104299001]="<IF-门派-SHOW-【{门派(Language)[Clan.NameID]}】><IF-委托城市-SHOW-【六扇门】>委托任务",
  [1104299002]="{材料1数量},{材料2数量},{材料3数量},{材料4数量}",
  [1104299003]="{发布角色(Language)[Role.NameID]}不妨直说。",
  [1104299004]="近来，我对<color=#dd0f0f>{目标物品(Language)[Item.ItemName]}</color>极度需求，想要劳烦[少侠]你前去帮我寻找，也可带回材料由我自行制作。",
  [1104299005]="不知道需要什么材料？",
  [1104299006]="不知道需要什么材料？",
  [1104299007]="需要<color=#dd0f0f>{材料1(Language)[Item.ItemName]}{材料1数量(Int)}份</color>（产出方式有{材料1[Item.ItemSource]}），如果你找到后，请尽快回来交予我。",
  [1104299008]="需要<color=#dd0f0f>{材料1(Language)[Item.ItemName]}{材料1数量(Int)}份</color>（产出方式有{材料1[Item.ItemSource]}），<color=#dd0f0f>{材料2(Language)[Item.ItemName]}{材料2数量(Int)}份</color>（产出方式有{材料2[Item.ItemSource]}），如果你找到后，请尽快回来交予我。",
  [1104299009]="需要<color=#dd0f0f>{材料1(Language)[Item.ItemName]}{材料1数量(Int)}份</color>（产出方式有{材料1[Item.ItemSource]}），<color=#dd0f0f>{材料2(Language)[Item.ItemName]}{材料2数量(Int)}份</color>（产出方式有{材料2[Item.ItemSource]}），<color=#dd0f0f>{材料3(Language)[Item.ItemName]}{材料3数量(Int)}份</color>（产出方式有{材料3[Item.ItemSource]}），如果你找到后，请尽快回来交予我。",
  [1104299010]="需要<color=#dd0f0f>{材料1(Language)[Item.ItemName]}{材料1数量(Int)}份</color>（产出方式有{材料1[Item.ItemSource]}），<color=#dd0f0f>{材料2(Language)[Item.ItemName]}{材料2数量(Int)}份</color>（产出方式有{材料2[Item.ItemSource]}），<color=#dd0f0f>{材料3(Language)[Item.ItemName]}{材料3数量(Int)}份</color>（产出方式有{材料3[Item.ItemSource]}），<color=#dd0f0f>{材料4(Language)[Item.ItemName]}{材料4数量(Int)}份</color>（产出方式有{材料4[Item.ItemSource]}），如果你找到后，请尽快回来交予我。",
  [1104299011]="<IF-门派-SHOW-【{门派(Language)[Clan.NameID]}】><IF-委托城市-SHOW-【六扇门】>委托任务",
  [1104299012]="[少侠]你将东西带来了吗？",
  [1104299013]="我该怎么做......?",
  [1104299014]="提交{目标物品(Language)[Item.ItemName]}",
  [1104299015]="提交材料",
  [1104299016]="再想想",
  [1104299017]="太感谢[少侠]了，解了我燃眉之急！",
  [1104299018]="太感谢[少侠]了，如此一来，我就可以生产了！",
  [1104299019]="需要<color=#dd0f0f>{材料1[Item.ItemName]}{材料1数量(Int)}份</color>，如果你找到后，请尽快回来交予我。",
  [1104299020]="需要<color=#dd0f0f>{材料1[Item.ItemName]}{材料1数量(Int)}份</color>，<color=#dd0f0f>{材料2[Item.ItemName]}{材料2数量(Int)}份</color>，如果你找到后，请尽快回来交予我。",
  [1104299021]="需要<color=#dd0f0f>{材料1[Item.ItemName]}{材料1数量(Int)}份</color>，<color=#dd0f0f>{材料2[Item.ItemName]}{材料2数量(Int)}份</color>，<color=#dd0f0f>{材料3[Item.ItemName]}{材料3数量(Int)}份</color>，如果你找到后，请尽快回来交予我。",
  [1104299022]="需要<color=#dd0f0f>{材料1[Item.ItemName]}{材料1数量(Int)}份</color>，<color=#dd0f0f>{材料2[Item.ItemName]}{材料2数量(Int)}份</color>，<color=#dd0f0f>{材料3[Item.ItemName]}{材料3数量(Int)}份</color>，<color=#dd0f0f>{材料4[Item.ItemName]}{材料4数量(Int)}份</color>，如果你找到后，请尽快回来交予我。",
  [1104299023]="需要<color=#dd0f0f>{材料1[Item.ItemName]}{材料1数量(Int)}份</color>，如果你找到后，请尽快回来交予我。",
  [1104299024]="需要<color=#dd0f0f>{材料1[Item.ItemName]}{材料1数量(Int)}份</color>，<color=#dd0f0f>{材料2[Item.ItemName]}{材料2数量(Int)}份</color>，如果你找到后，请尽快回来交予我。",
  [1104299025]="需要<color=#dd0f0f>{材料1[Item.ItemName]}{材料1数量(Int)}份</color>，<color=#dd0f0f>{材料2[Item.ItemName]}{材料2数量(Int)}份</color>，<color=#dd0f0f>{材料3[Item.ItemName]}{材料3数量(Int)}份</color>，如果你找到后，请尽快回来交予我。",
  [1104299026]="需要<color=#dd0f0f>{材料1[Item.ItemName]}{材料1数量(Int)}份</color>，<color=#dd0f0f>{材料2[Item.ItemName]}{材料2数量(Int)}份</color>，<color=#dd0f0f>{材料3[Item.ItemName]}{材料3数量(Int)}份</color>，<color=#dd0f0f>{材料4[Item.ItemName]}{材料4数量(Int)}份</color>，如果你找到后，请尽快回来交予我。",
  [1104299027]="[少侠]你将东西带来了吗？",
  [1104299028]="MAINROLE[少侠]请留步，我有一事相求。",
  [1104299030]="<IF-门派-SHOW-【{门派(Language)[Clan.NameID]}】><IF-委托城市-SHOW-【{委托城市(Language)[City.NameID]}】>{发布角色(Language)[Role.NameID]}托你去寻找@prc1@（产出方式有{目标物品[Item.ItemSource]}）或对应的原料@prc2@（产出方式有{材料1[Item.ItemSource]}）找到后尽快回去交予他",
  [1104299031]="<IF-门派-SHOW-【{门派(Language)[Clan.NameID]}】><IF-委托城市-SHOW-【{委托城市(Language)[City.NameID]}】>{发布角色(Language)[Role.NameID]}托你去寻找@prc1@（产出方式有{目标物品[Item.ItemSource]}）或对应的原料@prc2@（产出方式有{材料1[Item.ItemSource]}），@prc3@（产出方式有{材料2[Item.ItemSource]}）找到后尽快回去交予他",
  [1104299032]="<IF-门派-SHOW-【{门派(Language)[Clan.NameID]}】><IF-委托城市-SHOW-【{委托城市(Language)[City.NameID]}】>{发布角色(Language)[Role.NameID]}托你去寻找@prc1@（产出方式有{目标物品[Item.ItemSource]}）或对应的原料@prc2@（产出方式有{材料1[Item.ItemSource]}），@prc3@（产出方式有{材料2[Item.ItemSource]}），@prc4@（产出方式有{材料3[Item.ItemSource]}）找到后尽快回去交予他",
  [1104299033]="<IF-门派-SHOW-【{门派(Language)[Clan.NameID]}】><IF-委托城市-SHOW-【{委托城市(Language)[City.NameID]}】>{发布角色(Language)[Role.NameID]}托你去寻找@prc1@（产出方式有{目标物品[Item.ItemSource]}）或对应的原料@prc2@（产出方式有{材料1[Item.ItemSource]}），@prc3@（产出方式有{材料2[Item.ItemSource]}），@prc4@（产出方式有{材料3[Item.ItemSource]}），@prc5@（产出方式有{材料4[Item.ItemSource]}）找到后尽快回去交予他",
}

-- export table: Language
return Language
