-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [1005442001]="采矿等级不足",
  [1005442002]="采药等级不足",
  [1005442003]="食材搜刮等级不足",
  [1005442004]="矿山",
  [1005442005]="药田",
  [1005442006]="粮仓",
  [1005442007]="{等级要求(Int)}级粮仓",
  [1005442008]="{等级要求(Int)}级药田",
  [1005442009]="{等级要求(Int)}级矿山",
  [1005442010]="花丛",
}

-- export table: Language
return Language
