-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [2710001]="通常",
  [2710002]="烈日",
  [2710003]="刮风",
  [2710004]="起雾",
  [2710005]="降雨",
  [2710006]="雷雨",
  [2710007]="降雪",
}

-- export table: Language
return Language
