-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [3810001]="在你周岁之时，父母让你抓周，你选择了……",
  [3810002]="当你读着武侠小人书，幻想自己成为怎样的“大侠”……",
  [3810003]="父亲带着你上街，你看到有人在偷钱，你会……",
  [3810004]="你爱的姑娘劝你不要闯荡江湖，与她过平凡安逸的日子，你会……",
  [3810005]="在投身江湖前夜，你最后做的事是……",
}

-- export table: Language
return Language
