-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [1104730001]="开启后续任务",
  [1104736001]="再遇南宫世家",
  [1104736002]="在广州遇到了南宫世家",
  [1104736003]="由于我带了石开山，所以与南宫世家发生了一些故事。",
  [1104736004]="由于我不认识什么南宫世家主的弟弟，与他们擦肩而过了。",
}

-- export table: Language
return Language
