-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [1104110001]="邢安阳普通战斗监听",
  [1104110004]="邢安阳，你还在被仇恨驱使吗？",
  [1104117001]="【无】任务占位1185！去表格占了再用",
  [1104117002]="你瞧瞧，你都做了什么！！",
  [1104117003]="我，我做什么，你管得着吗！？",
  [1104118001]="【无】任务占位1186！去表格占了再用",
}

-- export table: Language
return Language
