-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [2010001]="魔君乱江湖",
  [2010002]="宇文庄奇案",
  [2010003]="破天逆命传",
  [2010004]="测试入口",
}

-- export table: Language
return Language
