-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [3710001]="京城",
  [3710002]="开封",
  [3710003]="杭州",
  [3710004]="大理",
  [3710005]="广州",
}

-- export table: Language
return Language
