-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [810001]="测试活动：买三送二",
  [810002]="双十一活动：买五送五",
  [810003]="周年活动：买十送十一",
}

-- export table: Language
return Language
