-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [1104560001]="【无】刷怪迷宫_珍惜物品动态任务",
  [1104560002]="绕道而行",
  [1104560003]="离开",
}

-- export table: Language
return Language
