-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [631001]="拯救阿月",
  [631002]="弹珠池名2",
  [631003]="白衣探宝",
  [632001]="%s天降洪福，获得了%s",
  [632002]="%s幸运地夺得了%s",
  [632003]="%s幸运地夺得了稀有奖励%s",
  [632004]="击败恶霸，参加夺宝！",
}

-- export table: Language
return Language
