-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [1004342001]="[少侠]，我需要{物品品质(RankType)}及以上的{物品类型(FavorType)}类型物品2个。",
  [1004342002]="【{心愿角色ID[Role.NameID]}】寻物探宝",
  [1004342003]="[少侠]，我需要{物品品质(RankType)}及以上的{物品类型(FavorType)}类型物品2个。",
  [1004344001]="兑换山贼讨伐奖励",
  [1004344002]="大地图上有许多山贼在游荡。讨伐他们获得山贼头巾后可以来我这里兑换奖励。",
}

-- export table: Language
return Language
