-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [1104160001]="【无】任务占位1228！去表格占了再用",
  [1104161001]="【无】任务占位1229！去表格占了再用",
  [1104162001]="【无】任务占位1230！去表格占了再用",
}

-- export table: Language
return Language
