-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [360001]="经历一番品尝,你吃到了肉味包子",
  [360002]="经历一番品尝,你吃到了芝麻味包子",
  [360003]="经历一番品尝,你吃到了蛋黄味包子",
}

-- export table: Language
return Language
