-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [1104630001]="【无】系统_大地图界面监听",
  [1104631001]="【无】系统_大地图系统",
  [1104635001]="【无】系统任务_大地图事件_劫镖",
  [1104636001]="【无】系统任务_大地图事件_剧情",
  [1104637001]="【无】系统任务_大地图事件_商队",
  [1104639001]="下山",
}

-- export table: Language
return Language
