-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [1104560001]="【无】刷怪迷宫_珍惜物品动态任务",
  [1104560002]="绕道而行",
  [1104560003]="离开",
  [1104561001]="【无】嵩山线索1",
  [1104562001]="【无】嵩山线索2",
  [1104563001]="【无】嵩山线索3",
  [1104564001]="【无】嵩山线索4",
}

-- export table: Language
return Language
