-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [1005579001]="自从郭鹏举来到大理已经过去了不少日子，去<color=#dd0f0f>大理府</color>看看他的近况吧。",
}

-- export table: Language
return Language
