-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [2030001]="10~50小时",
  [2030002]="5~10分钟",
  [2030003]="2小时",
  [2030004]="2~3年",
}

-- export table: Language
return Language
