-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [1104021001]="门派挑战_六扇门3",
  [1104022001]="门派挑战_峨嵋1_扶叶_拳",
  [1104023001]="门派挑战_峨嵋2_扶叶_剑",
  [1104024001]="九黎人秘藏",
  [1104024002]="开宝箱",
  [1104028001]="【系统】开启通用系统",
  [1104029001]="【无】大决战-宇文柯低难度常驻战斗监听",
}

-- export table: Language
return Language
