-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [1005451001]="曾是心中第一，现在已心有所属",
  [1005453001]="而你不同，你年纪轻轻就习得一身好武艺，出门闯荡江湖……",
  [1005456001]="从此你们一起行走江湖，成为人人称颂的神仙眷侣。",
  [1005456002]="就是那了知兄弟最后也没来参加你们的婚礼……",
  [1005459001]="所以她虽是喜欢他，但不敢贸然接近表白心意。",
}

-- export table: Language
return Language
