-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [1004596001]="【兴奋】吼呜呜!吼呜呜！",
  [1004596002]="包子因为和你的感情递增而似乎变得兴奋了...",
  [1004596003]="酒逢知己千杯少，话不投机半句多，没想到我和MAINROLE[少侠]你已经成为了知己，真是难得",
  [1004596004]="确实，我也十分欣慰有你的陪伴!",
}

-- export table: Language
return Language
