-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [2720001]="近日烈日炎炎，药草和毒虫枯死了不少",
  [2720002]="近日微风拂面，山贼草寇似乎比平日更多",
  [2720003]="近日大雾蒙蒙，不少草寇打起了寻找毒虫的侠客的主意",
  [2720004]="近日阴雨绵绵，野草毒虫增多，商人却抱怨不迭",
  [2720005]="近日雷雨交加，雨天路滑，众人都不愿出门",
  [2720006]="近日雪花飘飘，野外见不到什么东西，商店也早早关门",
}

-- export table: Language
return Language
