-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local Language= {
  [118486001]="战斗监听已生效",
  [118486002]="接下来等待1000",
  [118486003]="等待正常结束",
}

-- export table: Language
return Language
