-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum RankType
require("common");


local LotteryLimit= {
  [1]={BaseID=1,Rank=RankType.RT_White,CompareGetTime=1,BegGetTime=1,PunishGetTime=1,Weight=10,Probable=100,},
  [2]={BaseID=2,Rank=RankType.RT_Green,CompareGetTime=1,BegGetTime=1,PunishGetTime=1,Weight=9,Probable=100,},
  [3]={BaseID=3,Rank=RankType.RT_Blue,CompareGetTime=2,BegGetTime=2,PunishGetTime=2,Weight=8,Probable=80,},
  [4]={BaseID=4,Rank=RankType.RT_Purple,CompareGetTime=3,BegGetTime=3,PunishGetTime=2,Weight=7,Probable=60,},
  [5]={BaseID=5,Rank=RankType.RT_Orange,CompareGetTime=5,BegGetTime=5,PunishGetTime=4,Weight=6,Probable=40,},
  [6]={BaseID=6,Rank=RankType.RT_Golden,CompareGetTime=8,BegGetTime=8,PunishGetTime=6,Weight=5,Probable=20,},
  [7]={BaseID=7,Rank=RankType.RT_DarkGolden,CompareGetTime=10,BegGetTime=10,PunishGetTime=10,Weight=4,Probable=5,},
  [8]={BaseID=8,Rank=RankType.RT_MultiColor,CompareGetTime=10,BegGetTime=10,PunishGetTime=10,Weight=4,Probable=3,},
  [9]={BaseID=9,Rank=RankType.RT_ThirdGearDarkGolden,CompareGetTime=10,BegGetTime=10,PunishGetTime=10,Weight=4,Probable=2,},
}

-- export table: LotteryLimit
return LotteryLimit
