-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local LuckyReward= {
  [1]={BaseID=1,LuckyValueMin=0,LuckyValueMax=10,Items={250601741,},ItemsNum={1,},},
  [2]={BaseID=2,LuckyValueMin=11,LuckyValueMax=20,Items={250601741,},ItemsNum={2,},},
  [3]={BaseID=3,LuckyValueMin=21,LuckyValueMax=30,Items={250601741,},ItemsNum={3,},},
  [4]={BaseID=4,LuckyValueMin=31,LuckyValueMax=40,Items={250601741,},ItemsNum={4,},},
  [5]={BaseID=5,LuckyValueMin=41,LuckyValueMax=50,Items={250601741,},ItemsNum={5,},},
  [6]={BaseID=6,LuckyValueMin=51,LuckyValueMax=60,Items={250601741,},ItemsNum={6,},},
  [7]={BaseID=7,LuckyValueMin=61,LuckyValueMax=70,Items={250601741,},ItemsNum={7,},},
  [8]={BaseID=8,LuckyValueMin=71,LuckyValueMax=80,Items={250601741,},ItemsNum={8,},},
  [9]={BaseID=9,LuckyValueMin=81,LuckyValueMax=90,Items={250601741,},ItemsNum={9,},},
  [10]={BaseID=10,LuckyValueMin=91,LuckyValueMax=999,Items={250601741,},ItemsNum={10,},},
}

-- export table: LuckyReward
return LuckyReward
