-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum MainRoleData
-- enum TBoolean
require("common");


local MainRoleDataIsPercentDefault = {PerMyriad=TBoolean.BOOL_YES,ShowAsPercent=TBoolean.BOOL_YES,}
local MainRoleDataIsPercent= {
  [14]={BaseID=MainRoleData.MRD_EXTRA_GOOD,},
  [15]={BaseID=MainRoleData.MRD_EXTRA_MARITAL,},
  [16]={BaseID=MainRoleData.MRD_EXTRA_ROLEEXP,},
  [17]={BaseID=MainRoleData.MRD_EXTRA_ROLESELLITEM,},
  [18]={BaseID=MainRoleData.MRD_ENMEY_DIFFUP,},
  [19]={BaseID=MainRoleData.MRD_EQUIP_ATTRUP,},
  [20]={BaseID=MainRoleData.MRD_DIFF,PerMyriad=TBoolean.BOOL_NO,ShowAsPercent=TBoolean.BOOL_NO,},
  [21]={BaseID=MainRoleData.MRD_MARTIALLVMAX,PerMyriad=TBoolean.BOOL_NO,ShowAsPercent=TBoolean.BOOL_NO,},
  [22]={BaseID=MainRoleData.MRD_ROLELEVELMAX,PerMyriad=TBoolean.BOOL_NO,ShowAsPercent=TBoolean.BOOL_NO,},
  [23]={BaseID=MainRoleData.MRD_DEFAULT_GOOD,PerMyriad=TBoolean.BOOL_NO,ShowAsPercent=TBoolean.BOOL_NO,},
  [24]={BaseID=MainRoleData.MRD_BATTLE_TEAMNUMS,PerMyriad=TBoolean.BOOL_NO,ShowAsPercent=TBoolean.BOOL_NO,},
  [25]={BaseID=MainRoleData.MRD_MARTIAL_NUM_MAX,PerMyriad=TBoolean.BOOL_NO,ShowAsPercent=TBoolean.BOOL_NO,},
}
for k,v in pairs(MainRoleDataIsPercent) do
    setmetatable(v, {['__index'] = MainRoleDataIsPercentDefault})
end

-- export table: MainRoleDataIsPercent
return MainRoleDataIsPercent
