-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local MapAttrChangeDefault = {MapName="",MapType=0,MapPic="BuildingBG/sc_bt_fei4xu1_01",SceneImg="",}
local MapAttrChange= {
  [1]={BaseID=1,TagID=10003,MapID=69,MapName="月牙村测试",MapPic="MapBG/sc_bg_guan1fu3",},
  [2]={BaseID=2,TagID=432,MapID=1465,MapPic="BuildingBG/sc_bt_qing1liang2si4",},
  [3]={BaseID=3,TagID=1588,MapID=524,},
  [4]={BaseID=4,TagID=1589,MapID=541,},
  [5]={BaseID=5,TagID=1590,MapID=564,},
  [6]={BaseID=6,TagID=1591,MapID=596,},
  [7]={BaseID=7,TagID=1592,MapID=674,},
  [8]={BaseID=8,TagID=1593,MapID=703,},
  [9]={BaseID=9,TagID=1594,MapID=783,},
  [10]={BaseID=10,TagID=1595,MapID=800,},
  [11]={BaseID=11,TagID=1597,MapID=866,},
  [12]={BaseID=12,TagID=1598,MapID=884,},
  [13]={BaseID=13,TagID=1599,MapID=899,},
  [14]={BaseID=14,TagID=1600,MapID=926,},
  [15]={BaseID=15,TagID=1601,MapID=944,},
  [16]={BaseID=16,TagID=1602,MapID=960,},
  [17]={BaseID=17,TagID=1603,MapID=1236,},
  [18]={BaseID=18,TagID=1604,MapID=1493,},
  [19]={BaseID=19,TagID=1606,MapID=323,},
  [20]={BaseID=20,TagID=1607,MapID=1070,},
  [21]={BaseID=21,TagID=1608,MapID=1078,},
  [22]={BaseID=22,TagID=1609,MapID=1072,},
  [23]={BaseID=23,TagID=1610,MapID=1084,},
  [24]={BaseID=24,TagID=1611,MapID=1168,},
  [25]={BaseID=25,TagID=1612,MapID=1917,},
  [26]={BaseID=26,TagID=1613,MapID=1176,},
  [27]={BaseID=27,TagID=1614,MapID=118,},
  [28]={BaseID=28,TagID=1615,MapID=1223,},
  [29]={BaseID=29,TagID=1616,MapID=1207,},
  [30]={BaseID=30,TagID=1617,MapID=1201,},
  [31]={BaseID=31,TagID=1618,MapID=1363,},
  [32]={BaseID=32,TagID=1619,MapID=486,},
  [33]={BaseID=33,TagID=1620,MapID=1374,},
  [34]={BaseID=34,TagID=1621,MapID=97,},
  [35]={BaseID=35,TagID=1622,MapID=1422,},
  [36]={BaseID=36,TagID=1623,MapID=1195,},
  [37]={BaseID=37,TagID=1624,MapID=1188,},
  [38]={BaseID=38,TagID=1625,MapID=1261,},
  [39]={BaseID=39,TagID=1626,MapID=1249,},
  [40]={BaseID=40,TagID=1627,MapID=1404,},
  [41]={BaseID=41,TagID=1628,MapID=1373,},
  [42]={BaseID=42,TagID=1629,MapID=1856,},
  [43]={BaseID=43,TagID=1794,MapID=1338,MapName="倒塌的城墙",MapPic="BuildingBG/sc_bt_dao3ta1de0cheng2qiang2",},
  [44]={BaseID=44,TagID=1898,MapID=63,MapName="废墟",},
  [45]={BaseID=45,TagID=1899,MapID=75,MapName="废墟",},
  [46]={BaseID=46,TagID=1900,MapID=63,MapName="民居",MapPic="BuildingBG/sc_bt_min2ju102",},
  [47]={BaseID=47,TagID=1901,MapID=75,MapName="民居",MapPic="BuildingBG/sc_bt_min2ju106",},
}
for k,v in pairs(MapAttrChange) do
    setmetatable(v, {['__index'] = MapAttrChangeDefault})
end

-- export table: MapAttrChange
return MapAttrChange
