-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local MartialExtExpAppDefault = {AttrLimit1=2800,AttrLimit2=175,AttrLimit3=500,RoleLevel=250000,RoleOverlayLevel=0,}
local MartialExtExpApp= {
  [1]={BaseID=1,MartialLevel=1,AttrLimit1=0,AttrLimit2=0,AttrLimit3=0,RoleLevel=0,},
  [2]={BaseID=2,MartialLevel=2,AttrLimit1=0,AttrLimit2=0,AttrLimit3=0,RoleLevel=0,},
  [3]={BaseID=3,MartialLevel=3,AttrLimit1=0,AttrLimit2=0,AttrLimit3=0,RoleLevel=0,},
  [4]={BaseID=4,MartialLevel=4,AttrLimit1=0,AttrLimit2=0,AttrLimit3=0,RoleLevel=0,},
  [5]={BaseID=5,MartialLevel=5,AttrLimit1=100,AttrLimit2=10,AttrLimit3=100,RoleLevel=50000,},
  [6]={BaseID=6,MartialLevel=6,AttrLimit1=100,AttrLimit2=10,AttrLimit3=100,RoleLevel=50000,},
  [7]={BaseID=7,MartialLevel=7,AttrLimit1=100,AttrLimit2=10,AttrLimit3=100,RoleLevel=50000,},
  [8]={BaseID=8,MartialLevel=8,AttrLimit1=100,AttrLimit2=10,AttrLimit3=100,RoleLevel=50000,},
  [9]={BaseID=9,MartialLevel=9,AttrLimit1=100,AttrLimit2=10,AttrLimit3=100,RoleLevel=50000,},
  [10]={BaseID=10,MartialLevel=10,AttrLimit1=300,AttrLimit2=50,AttrLimit3=150,RoleLevel=100000,},
  [11]={BaseID=11,MartialLevel=11,AttrLimit1=300,AttrLimit2=50,AttrLimit3=150,RoleLevel=100000,},
  [12]={BaseID=12,MartialLevel=12,AttrLimit1=300,AttrLimit2=50,AttrLimit3=150,RoleLevel=100000,},
  [13]={BaseID=13,MartialLevel=13,AttrLimit1=300,AttrLimit2=50,AttrLimit3=150,RoleLevel=100000,},
  [14]={BaseID=14,MartialLevel=14,AttrLimit1=300,AttrLimit2=50,AttrLimit3=150,RoleLevel=100000,},
  [15]={BaseID=15,MartialLevel=15,AttrLimit1=800,AttrLimit2=100,AttrLimit3=300,RoleLevel=150000,},
  [16]={BaseID=16,MartialLevel=16,AttrLimit1=800,AttrLimit2=100,AttrLimit3=300,RoleLevel=150000,},
  [17]={BaseID=17,MartialLevel=17,AttrLimit1=800,AttrLimit2=100,AttrLimit3=300,RoleLevel=150000,},
  [18]={BaseID=18,MartialLevel=18,AttrLimit1=800,AttrLimit2=100,AttrLimit3=300,RoleLevel=150000,},
  [19]={BaseID=19,MartialLevel=19,AttrLimit1=800,AttrLimit2=100,AttrLimit3=300,RoleLevel=150000,},
  [20]={BaseID=20,MartialLevel=20,AttrLimit1=1200,AttrLimit2=120,AttrLimit3=350,RoleLevel=155000,},
  [21]={BaseID=21,MartialLevel=21,AttrLimit1=1300,AttrLimit2=125,AttrLimit3=360,RoleLevel=160000,},
  [22]={BaseID=22,MartialLevel=22,AttrLimit1=1400,AttrLimit2=130,AttrLimit3=370,RoleLevel=165000,RoleOverlayLevel=5000,},
  [23]={BaseID=23,MartialLevel=23,AttrLimit1=1500,AttrLimit2=135,AttrLimit3=380,RoleLevel=170000,RoleOverlayLevel=6000,},
  [24]={BaseID=24,MartialLevel=24,AttrLimit1=1600,AttrLimit2=140,AttrLimit3=390,RoleLevel=175000,RoleOverlayLevel=7000,},
  [25]={BaseID=25,MartialLevel=25,AttrLimit1=1800,AttrLimit2=150,AttrLimit3=400,RoleLevel=185000,RoleOverlayLevel=8000,},
  [26]={BaseID=26,MartialLevel=26,AttrLimit1=2000,AttrLimit2=155,AttrLimit3=420,RoleLevel=195000,RoleOverlayLevel=9000,},
  [27]={BaseID=27,MartialLevel=27,AttrLimit1=2200,AttrLimit2=160,AttrLimit3=440,RoleLevel=205000,RoleOverlayLevel=10000,},
  [28]={BaseID=28,MartialLevel=28,AttrLimit1=2400,AttrLimit2=165,AttrLimit3=460,RoleLevel=215000,RoleOverlayLevel=12000,},
  [29]={BaseID=29,MartialLevel=29,AttrLimit1=2600,AttrLimit2=170,AttrLimit3=480,RoleLevel=230000,RoleOverlayLevel=14000,},
  [30]={BaseID=30,MartialLevel=30,RoleOverlayLevel=16000,},
  [31]={BaseID=31,MartialLevel=31,RoleOverlayLevel=16000,},
  [32]={BaseID=32,MartialLevel=32,RoleOverlayLevel=16000,},
  [33]={BaseID=33,MartialLevel=33,RoleOverlayLevel=16000,},
  [34]={BaseID=34,MartialLevel=34,RoleOverlayLevel=16000,},
  [35]={BaseID=35,MartialLevel=35,RoleOverlayLevel=16000,},
  [36]={BaseID=36,MartialLevel=36,RoleOverlayLevel=16000,},
  [37]={BaseID=37,MartialLevel=37,RoleOverlayLevel=16000,},
  [38]={BaseID=38,MartialLevel=38,RoleOverlayLevel=16000,},
  [39]={BaseID=39,MartialLevel=39,RoleOverlayLevel=16000,},
  [40]={BaseID=40,MartialLevel=40,RoleOverlayLevel=16000,},
  [41]={BaseID=41,MartialLevel=41,RoleOverlayLevel=16000,},
  [42]={BaseID=42,MartialLevel=42,RoleOverlayLevel=16000,},
  [43]={BaseID=43,MartialLevel=43,RoleOverlayLevel=16000,},
  [44]={BaseID=44,MartialLevel=44,RoleOverlayLevel=16000,},
  [45]={BaseID=45,MartialLevel=45,RoleOverlayLevel=16000,},
  [46]={BaseID=46,MartialLevel=46,RoleOverlayLevel=16000,},
  [47]={BaseID=47,MartialLevel=47,RoleOverlayLevel=16000,},
  [48]={BaseID=48,MartialLevel=48,RoleOverlayLevel=16000,},
  [49]={BaseID=49,MartialLevel=49,RoleOverlayLevel=16000,},
  [50]={BaseID=50,MartialLevel=50,RoleOverlayLevel=16000,},
}
for k,v in pairs(MartialExtExpApp) do
    setmetatable(v, {['__index'] = MartialExtExpAppDefault})
end

-- export table: MartialExtExpApp
return MartialExtExpApp
