-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum RankType
require("common");


local MartialAtkDamageLimitFactor= {
  [1]={BaseID=1,MartialRank=RankType.RT_White,UpperLimitFactor=40000,LowerLimitFactor=50,},
  [2]={BaseID=2,MartialRank=RankType.RT_Green,UpperLimitFactor=60000,LowerLimitFactor=80,},
  [3]={BaseID=3,MartialRank=RankType.RT_Blue,UpperLimitFactor=90000,LowerLimitFactor=100,},
  [4]={BaseID=4,MartialRank=RankType.RT_Purple,UpperLimitFactor=120000,LowerLimitFactor=200,},
  [5]={BaseID=5,MartialRank=RankType.RT_Orange,UpperLimitFactor=180000,LowerLimitFactor=400,},
  [6]={BaseID=6,MartialRank=RankType.RT_Golden,UpperLimitFactor=250000,LowerLimitFactor=600,},
  [7]={BaseID=7,MartialRank=RankType.RT_DarkGolden,UpperLimitFactor=350000,LowerLimitFactor=1000,},
}

-- export table: MartialAtkDamageLimitFactor
return MartialAtkDamageLimitFactor
