-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum TBoolean
require("common");


local MartialRange= {
  [1]={BaseID=1,Name="拳掌",CasterRangeIDs={6,},AttackRangeIDs={1,5,},IsOnlyShowCasterRange=TBoolean.BOOL_NO,},
  [2]={BaseID=2,Name="剑",CasterRangeIDs={56,},AttackRangeIDs={23,60,},IsOnlyShowCasterRange=TBoolean.BOOL_NO,CasterRangeIDs2={17,},AttackRangeIDs2={24,61,},},
  [3]={BaseID=3,Name="刀",CasterRangeIDs={56,},AttackRangeIDs={16,26,},IsOnlyShowCasterRange=TBoolean.BOOL_NO,CasterRangeIDs2={17,},AttackRangeIDs2={19,26,},},
  [4]={BaseID=4,Name="奇门",CasterRangeIDs={6,},AttackRangeIDs={3,},IsOnlyShowCasterRange=TBoolean.BOOL_YES,},
  [5]={BaseID=5,Name="暗器",CasterRangeIDs={22,},AttackRangeIDs={1,8,},IsOnlyShowCasterRange=TBoolean.BOOL_NO,CasterRangeIDs2={31,},AttackRangeIDs2={1,13,},},
  [6]={BaseID=6,Name="腿",CasterRangeIDs={1,},AttackRangeIDs={41,},IsOnlyShowCasterRange=TBoolean.BOOL_NO,},
  [7]={BaseID=7,Name="内功",CasterRangeIDs={6,},AttackRangeIDs={1,5,},IsOnlyShowCasterRange=TBoolean.BOOL_NO,},
  [8]={BaseID=8,Name="拳掌奥义",CasterRangeIDs={3,},AttackRangeIDs={2,},IsOnlyShowCasterRange=TBoolean.BOOL_NO,},
  [9]={BaseID=9,Name="剑法奥义",CasterRangeIDs={56,},AttackRangeIDs={18,},IsOnlyShowCasterRange=TBoolean.BOOL_NO,CasterRangeIDs2={17,},AttackRangeIDs2={27,},},
  [10]={BaseID=10,Name="刀法奥义",CasterRangeIDs={56,},AttackRangeIDs={53,26,},IsOnlyShowCasterRange=TBoolean.BOOL_NO,CasterRangeIDs2={17,},AttackRangeIDs2={20,26,},},
  [11]={BaseID=11,Name="腿法绝招奥义",CasterRangeIDs={1,},AttackRangeIDs={30,},IsOnlyShowCasterRange=TBoolean.BOOL_NO,},
  [12]={BaseID=12,Name="拳掌绝招",CasterRangeIDs={3,},AttackRangeIDs={2,5,},IsOnlyShowCasterRange=TBoolean.BOOL_NO,},
  [13]={BaseID=13,Name="剑法绝招",CasterRangeIDs={56,},AttackRangeIDs={18,},IsOnlyShowCasterRange=TBoolean.BOOL_NO,CasterRangeIDs2={17,},AttackRangeIDs2={27,},},
  [14]={BaseID=14,Name="奇门绝招",CasterRangeIDs={22,},AttackRangeIDs={6,},IsOnlyShowCasterRange=TBoolean.BOOL_YES,},
  [15]={BaseID=15,Name="刀法绝招",CasterRangeIDs={56,},AttackRangeIDs={53,26,},IsOnlyShowCasterRange=TBoolean.BOOL_NO,CasterRangeIDs2={17,},AttackRangeIDs2={20,26,},},
  [16]={BaseID=16,Name="全屏",CasterRangeIDs={26,},AttackRangeIDs={1,},IsOnlyShowCasterRange=TBoolean.BOOL_NO,},
  [17]={BaseID=17,Name="北冥真气奥义",CasterRangeIDs={1,},AttackRangeIDs={5,},IsOnlyShowCasterRange=TBoolean.BOOL_NO,},
  [18]={BaseID=18,Name="蝌蚪文洗脑奥义",CasterRangeIDs={25,},AttackRangeIDs={25,},IsOnlyShowCasterRange=TBoolean.BOOL_NO,},
  [19]={BaseID=19,Name="颠倒乾坤奥义",CasterRangeIDs={25,},AttackRangeIDs={5,},IsOnlyShowCasterRange=TBoolean.BOOL_NO,},
  [20]={BaseID=20,Name="大吃罗汉腿绝招",CasterRangeIDs={1,},AttackRangeIDs={25,},IsOnlyShowCasterRange=TBoolean.BOOL_NO,},
  [21]={BaseID=21,Name="双掌怒炎绝招",CasterRangeIDs={1,},AttackRangeIDs={5,},IsOnlyShowCasterRange=TBoolean.BOOL_NO,},
  [22]={BaseID=22,Name="医术（周围3*3）",CasterRangeIDs={1,},AttackRangeIDs={5,},IsOnlyShowCasterRange=TBoolean.BOOL_NO,},
  [23]={BaseID=23,Name="医术（对自身）",CasterRangeIDs={1,},AttackRangeIDs={1,},IsOnlyShowCasterRange=TBoolean.BOOL_NO,},
  [24]={BaseID=24,Name="医术",CasterRangeIDs={29,},AttackRangeIDs={1,},IsOnlyShowCasterRange=TBoolean.BOOL_NO,},
  [25]={BaseID=25,Name="撒石灰_临时",CasterRangeIDs={1,},AttackRangeIDs={41,},IsOnlyShowCasterRange=TBoolean.BOOL_NO,},
  [26]={BaseID=26,Name="轻功",CasterRangeIDs={1,},AttackRangeIDs={1,},IsOnlyShowCasterRange=TBoolean.BOOL_NO,},
  [27]={BaseID=27,Name="暴雨梨花针奥义",CasterRangeIDs={1,},AttackRangeIDs={26,},IsOnlyShowCasterRange=TBoolean.BOOL_NO,},
  [28]={BaseID=28,Name="赤刀神功奥义",CasterRangeIDs={1,},AttackRangeIDs={26,},IsOnlyShowCasterRange=TBoolean.BOOL_NO,},
  [29]={BaseID=29,Name="剑法-单体",CasterRangeIDs={21,},AttackRangeIDs={1,},IsOnlyShowCasterRange=TBoolean.BOOL_NO,},
  [30]={BaseID=30,Name="拳掌单体",CasterRangeIDs={3,},AttackRangeIDs={1,5,},IsOnlyShowCasterRange=TBoolean.BOOL_NO,},
  [31]={BaseID=31,Name="火星冲日",CasterRangeIDs={11,},AttackRangeIDs={1,13,},IsOnlyShowCasterRange=TBoolean.BOOL_NO,},
  [32]={BaseID=32,Name="黑云绝招",CasterRangeIDs={22,},AttackRangeIDs={5,},IsOnlyShowCasterRange=TBoolean.BOOL_NO,},
  [33]={BaseID=33,Name="乾坤一掷",CasterRangeIDs={44,},AttackRangeIDs={1,},IsOnlyShowCasterRange=TBoolean.BOOL_NO,},
  [34]={BaseID=34,Name="逐日元气掌",CasterRangeIDs={2,1,},AttackRangeIDs={1,52,},IsOnlyShowCasterRange=TBoolean.BOOL_NO,},
  [35]={BaseID=35,Name="单体",CasterRangeIDs={6,},AttackRangeIDs={1,},IsOnlyShowCasterRange=TBoolean.BOOL_NO,},
  [36]={BaseID=36,Name="单体_小范围",CasterRangeIDs={25,},AttackRangeIDs={1,},IsOnlyShowCasterRange=TBoolean.BOOL_NO,},
  [37]={BaseID=37,Name="万佛朝宗掌",CasterRangeIDs={2,},AttackRangeIDs={5,},IsOnlyShowCasterRange=TBoolean.BOOL_NO,},
  [38]={BaseID=38,Name="天长掌法专用",CasterRangeIDs={58,},AttackRangeIDs={1,2,},IsOnlyShowCasterRange=TBoolean.BOOL_YES,},
  [39]={BaseID=39,Name="狮吼功",CasterRangeIDs={25,26,},AttackRangeIDs={5,26,},IsOnlyShowCasterRange=TBoolean.BOOL_NO,},
  [40]={BaseID=40,Name="江陵路专用-7*7十字",CasterRangeIDs={4,},AttackRangeIDs={1,},IsOnlyShowCasterRange=TBoolean.BOOL_NO,},
  [41]={BaseID=41,Name="杨家枪",CasterRangeIDs={6,},AttackRangeIDs={3,},IsOnlyShowCasterRange=TBoolean.BOOL_NO,},
}

-- export table: MartialRange
return MartialRange
