-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum RankType
require("common");


local MartialExtExpRank= {
  [1]={BaseID=1,Rank=RankType.RT_White,AttrCoef=10000,LevelCoef=10000,RoleCoef=8000,},
  [2]={BaseID=2,Rank=RankType.RT_Green,AttrCoef=10000,LevelCoef=10000,RoleCoef=9000,},
  [3]={BaseID=3,Rank=RankType.RT_Blue,AttrCoef=10000,LevelCoef=10000,RoleCoef=10000,},
  [4]={BaseID=4,Rank=RankType.RT_Purple,AttrCoef=12000,LevelCoef=12000,RoleCoef=12000,},
  [5]={BaseID=5,Rank=RankType.RT_Orange,AttrCoef=14000,LevelCoef=14000,RoleCoef=14000,},
  [6]={BaseID=6,Rank=RankType.RT_Golden,AttrCoef=16000,LevelCoef=16000,RoleCoef=16000,},
  [7]={BaseID=7,Rank=RankType.RT_DarkGolden,AttrCoef=20000,LevelCoef=20000,RoleCoef=20000,},
}

-- export table: MartialExtExpRank
return MartialExtExpRank
