-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum Grade
require("common");


local MatGrowUPAttrGrade= {
  [1]={BaseID=1,Grade=Grade.GA_Low,Factor=10000,GrowFactor=10000,},
  [2]={BaseID=2,Grade=Grade.GA_Medium,Factor=10000,GrowFactor=10000,},
  [3]={BaseID=3,Grade=Grade.GA_High,Factor=10000,GrowFactor=10000,},
  [4]={BaseID=4,Grade=Grade.GA_AOYI2_Low,Factor=18000,GrowFactor=18000,},
  [5]={BaseID=5,Grade=Grade.GA_AOYI2_Medium,Factor=18000,GrowFactor=18000,},
  [6]={BaseID=6,Grade=Grade.GA_AOYI2_High,Factor=18000,GrowFactor=18000,},
  [7]={BaseID=7,Grade=Grade.GA_AOYI3_Low,Factor=22000,GrowFactor=22000,},
  [8]={BaseID=8,Grade=Grade.GA_AOYI3_Medium,Factor=22000,GrowFactor=22000,},
  [9]={BaseID=9,Grade=Grade.GA_AOYI3_High,Factor=22000,GrowFactor=22000,},
  [10]={BaseID=10,Grade=Grade.GA_MedicalSingle,Factor=10000,GrowFactor=10000,},
  [11]={BaseID=11,Grade=Grade.GA_MedicalGroup,Factor=6500,GrowFactor=6500,},
}

-- export table: MatGrowUPAttrGrade
return MatGrowUPAttrGrade
