-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum MazeCardFirstType
-- enum TBoolean
require("common");


local MazeCommonConfig= {
  [1]={BaseID=1,FatigueBuffID=4092,CardTypeAutoMoveSettingList={{FirstType=MazeCardFirstType.MCFT_ROAD,CanAutoMove=TBoolean.BOOL_YES,},{FirstType=MazeCardFirstType.MCFT_BATTLE,CanAutoMove=TBoolean.BOOL_NO,},{FirstType=MazeCardFirstType.MCFT_TREASURE,CanAutoMove=TBoolean.BOOL_NO,},{FirstType=MazeCardFirstType.MCFT_BUFF,CanAutoMove=TBoolean.BOOL_YES,},{FirstType=MazeCardFirstType.MCFT_TRAP,CanAutoMove=TBoolean.BOOL_YES,},{FirstType=MazeCardFirstType.MCFT_STAIR,CanAutoMove=TBoolean.BOOL_NO,},{FirstType=MazeCardFirstType.MCFT_TASK,CanAutoMove=TBoolean.BOOL_NO,},},},
}

-- export table: MazeCommonConfig
return MazeCommonConfig
