-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local MoneyTaskConfig= {
  [1]={BaseID=1,MoneyTaskStartTaskID=4337,},
}

-- export table: MoneyTaskConfig
return MoneyTaskConfig
