-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum SkillEffectDescription
require("common");


local Multistage= {
  [1]={BaseID=1,EffectDescription=SkillEffectDescription.SED_SkillLogic_RemoteMultisegmentAnQiSkill,MultistagePosition=3,},
  [2]={BaseID=2,EffectDescription=SkillEffectDescription.SED_SkillLogic_MultisegmentAttackSkill,MultistagePosition=3,},
  [3]={BaseID=3,EffectDescription=SkillEffectDescription.SED_SpecificSkillLogic_XiaJiBaKan,MultistagePosition=3,},
}

-- export table: Multistage
return Multistage
