-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local NpcBigMapMoveConfig= {
  [1]={BaseID=1,MainRoleMoveDeltaTime=100,MoveNpcCountMin=0,MoveNpcCountMax=1,},
  [2]={BaseID=2,MainRoleMoveDeltaTime=200,MoveNpcCountMin=1,MoveNpcCountMax=1,},
  [3]={BaseID=3,MainRoleMoveDeltaTime=300,MoveNpcCountMin=1,MoveNpcCountMax=1,},
  [4]={BaseID=4,MainRoleMoveDeltaTime=400,MoveNpcCountMin=2,MoveNpcCountMax=2,},
  [5]={BaseID=5,MainRoleMoveDeltaTime=500,MoveNpcCountMin=2,MoveNpcCountMax=2,},
  [6]={BaseID=6,MainRoleMoveDeltaTime=600,MoveNpcCountMin=2,MoveNpcCountMax=2,},
  [7]={BaseID=7,MainRoleMoveDeltaTime=700,MoveNpcCountMin=3,MoveNpcCountMax=3,},
  [8]={BaseID=8,MainRoleMoveDeltaTime=800,MoveNpcCountMin=3,MoveNpcCountMax=3,},
  [9]={BaseID=9,MainRoleMoveDeltaTime=900,MoveNpcCountMin=3,MoveNpcCountMax=3,},
  [10]={BaseID=10,MainRoleMoveDeltaTime=1000,MoveNpcCountMin=3,MoveNpcCountMax=3,},
}

-- export table: NpcBigMapMoveConfig
return NpcBigMapMoveConfig
