-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local PlusEditionConfig= {
  [1]={BaseID=1,LockStorys={10,},DifficultLimit=999,UnlockAchieves={368,},FreeOpenDay=0,GiveItems={1603,},GiveItemNums={2,},MidPrice=180,HighPrice=680,Discount={50,25,},DiscountCondition={98,100,},FullBuyMailTitle="原价购买完整版奖励",FullBuyMailContent="感谢您对《我的侠客》完整版的支持，赠送暗金掌门自选卡1个。祝您游戏愉快。",FullBuyMailItems={250601740,},FullBuyMailItemsNum={1,},GiveTreasureBookVIPMonth=2,FreeLockText=564,},
}

-- export table: PlusEditionConfig
return PlusEditionConfig
