-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local PunishConfig= {
  [1]={BaseID=1,OpenTag=120002,LevelTag=130003,Task=5065,AboveGoodEvil=20,LiQiBuff=1054,LiQiMaxLevel=100,LayersNum={0,1,10,25,50,100,},LayersAddHitAtkPer={0,-200,-400,-600,-800,-1000,},LayersAddCritAtkTime={0,500,1000,1500,2000,2500,},PunishDeterrence={80,70,60,40,20,0,0,},AddLiQiA=2,AddDispositionA=-2,AddLiQiB=5,AddDispositionB=-5,MainRoleAddGoodEvilLow=1,MainRoleAddGoodEvilHigh=5,TargetAddGoodEvilLow=10,TargetAddGoodEvilHigh=20,AddLiQiC=10,BaoShangShowTag=130017,MingZhongShowTag=130018,LayersAddGift={2090,2088,2094,2093,2092,2091,},},
}

-- export table: PunishConfig
return PunishConfig
