-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local QbExp= {
  [1]={BaseID=1,RangeA=0,RangeB=18,ExpLimit=40000,Price=10,BuyNum=1,ExpAllLimit=4000000,},
  [2]={BaseID=2,RangeA=19,RangeB=42,ExpLimit=60000,Price=15,BuyNum=2,ExpAllLimit=4000000,},
  [3]={BaseID=3,RangeA=43,RangeB=81,ExpLimit=80000,Price=20,BuyNum=3,ExpAllLimit=4000000,},
  [4]={BaseID=4,RangeA=82,RangeB=123,ExpLimit=100000,Price=25,BuyNum=4,ExpAllLimit=4000000,},
  [5]={BaseID=5,RangeA=124,RangeB=165,ExpLimit=120000,Price=30,BuyNum=5,ExpAllLimit=4000000,},
}

-- export table: QbExp
return QbExp
