-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum RackItemType
-- enum RackItemOpenType
-- enum RackItemProperty
-- enum RackItemMoneyType
-- enum ShopBuyLimitResetType
-- enum ShopItemBuyLimitType
require("common");


local Rack= {
}

-- export table: Rack
return Rack
