-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum RankType
require("common");


local RankMartialAddition= {
  [1]={BaseID=1,MartialRank=RankType.RT_White,MartialAddition=5000,},
  [2]={BaseID=2,MartialRank=RankType.RT_Green,MartialAddition=5000,},
  [3]={BaseID=3,MartialRank=RankType.RT_Blue,MartialAddition=5000,},
  [4]={BaseID=4,MartialRank=RankType.RT_Purple,MartialAddition=5000,},
  [5]={BaseID=5,MartialRank=RankType.RT_Orange,MartialAddition=6000,},
  [6]={BaseID=6,MartialRank=RankType.RT_Golden,MartialAddition=7500,},
  [7]={BaseID=7,MartialRank=RankType.RT_DarkGolden,MartialAddition=10000,},
}

-- export table: RankMartialAddition
return RankMartialAddition
