-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local RevengeTaskConfig= {
  [1]={BaseID=1,RevengeTaskStartTaskID=5089,},
}

-- export table: RevengeTaskConfig
return RevengeTaskConfig
