-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum RankType
-- enum TBoolean
-- enum SexType
require("common");


local RoleFaceModelDefault = {CreateRoleID=1,ModelName="天命之人",ModelRank=RankType.RT_Purple,InitUnlock=TBoolean.BOOL_NO,UnlockDLC=0,UnlockCostSilver=0,UnlockAchieve=0,Open=TBoolean.BOOL_YES,Show=TBoolean.BOOL_NO,SexLimit=SexType.ST_Male,UnlockDescription="",SpineScale=80,}
local RoleFaceModel= {
  [1]={BaseID=1,InitUnlock=TBoolean.BOOL_YES,},
  [5]={BaseID=5,CreateRoleID=50,ModelName="狂放不羁",ModelRank=RankType.RT_DarkGolden,UnlockAchieve=73,Show=TBoolean.BOOL_YES,SexLimit=SexType.ST_Female,UnlockDescription="完成成就“海外神仙”后解锁",},
  [10]={BaseID=10,ModelName="气运之子",InitUnlock=TBoolean.BOOL_YES,Show=TBoolean.BOOL_YES,},
  [31]={BaseID=31,CreateRoleID=9,ModelName="魅影神行",ModelRank=RankType.RT_DarkGolden,UnlockAchieve=53,Show=TBoolean.BOOL_YES,UnlockDescription="完成成就“神州霸主”后解锁",SpineScale=65,},
  [32]={BaseID=32,CreateRoleID=17,ModelName="徒弟",InitUnlock=TBoolean.BOOL_YES,Show=TBoolean.BOOL_YES,},
  [33]={BaseID=33,CreateRoleID=18,ModelName="女徒弟",InitUnlock=TBoolean.BOOL_YES,Show=TBoolean.BOOL_YES,SexLimit=SexType.ST_Female,SpineScale=70,},
  [38]={BaseID=38,CreateRoleID=12,ModelName="孤独剑客",InitUnlock=TBoolean.BOOL_YES,Show=TBoolean.BOOL_YES,},
  [39]={BaseID=39,CreateRoleID=7,ModelName="大隐于市",ModelRank=RankType.RT_DarkGolden,Open=TBoolean.BOOL_NO,},
  [65]={BaseID=65,CreateRoleID=12,ModelName="任侠之人",InitUnlock=TBoolean.BOOL_YES,},
  [146]={BaseID=146,CreateRoleID=13,ModelName="小家碧玉",InitUnlock=TBoolean.BOOL_YES,Show=TBoolean.BOOL_YES,SexLimit=SexType.ST_Female,},
  [147]={BaseID=147,CreateRoleID=10,ModelName="独眼豪杰",ModelRank=RankType.RT_Orange,UnlockAchieve=349,Show=TBoolean.BOOL_YES,UnlockDescription="完成成就“江湖不再”后解锁",},
  [148]={BaseID=148,CreateRoleID=3,ModelName="温文尔雅",ModelRank=RankType.RT_Orange,Open=TBoolean.BOOL_NO,},
  [151]={BaseID=151,CreateRoleID=14,ModelName="狂放不羁",InitUnlock=TBoolean.BOOL_YES,UnlockAchieve=73,Show=TBoolean.BOOL_YES,UnlockDescription="完成成就“海外神仙”后解锁",},
  [158]={BaseID=158,CreateRoleID=2,ModelName="弯弓射雕",ModelRank=RankType.RT_Orange,InitUnlock=TBoolean.BOOL_YES,Show=TBoolean.BOOL_YES,},
  [161]={BaseID=161,CreateRoleID=8,ModelName="清心玉女",ModelRank=RankType.RT_DarkGolden,UnlockAchieve=458,Show=TBoolean.BOOL_YES,SexLimit=SexType.ST_Female,UnlockDescription="完成成就“行遍四海”后解锁",},
  [189]={BaseID=189,CreateRoleID=15,ModelName="邪道巨头",ModelRank=RankType.RT_DarkGolden,UnlockAchieve=459,Show=TBoolean.BOOL_YES,UnlockDescription="完成成就“村霸”后解锁",SpineScale=70,},
  [191]={BaseID=191,CreateRoleID=49,ModelName="魅影神行",ModelRank=RankType.RT_DarkGolden,UnlockAchieve=53,Show=TBoolean.BOOL_YES,SexLimit=SexType.ST_Female,UnlockDescription="完成成就“神州霸主”后解锁",SpineScale=65,},
  [258]={BaseID=258,CreateRoleID=52,ModelName="武媚之人",ModelRank=RankType.RT_DarkGolden,UnlockDLC=1,Show=TBoolean.BOOL_YES,SexLimit=SexType.ST_Female,UnlockDescription="拥有豪华版",},
  [590]={BaseID=590,CreateRoleID=13,ModelName="玲珑之人",InitUnlock=TBoolean.BOOL_YES,SexLimit=SexType.ST_Female,},
  [664]={BaseID=664,CreateRoleID=8,ModelName="素心玉女",ModelRank=RankType.RT_Golden,SexLimit=SexType.ST_Female,},
  [673]={BaseID=673,CreateRoleID=8,ModelName="素心玉女",ModelRank=RankType.RT_Golden,SexLimit=SexType.ST_Female,},
  [704]={BaseID=704,InitUnlock=TBoolean.BOOL_YES,},
  [705]={BaseID=705,InitUnlock=TBoolean.BOOL_YES,},
  [706]={BaseID=706,InitUnlock=TBoolean.BOOL_YES,},
  [707]={BaseID=707,InitUnlock=TBoolean.BOOL_YES,},
  [708]={BaseID=708,CreateRoleID=14,ModelName="不羁之人",InitUnlock=TBoolean.BOOL_YES,},
  [709]={BaseID=709,CreateRoleID=12,ModelName="任侠之人",InitUnlock=TBoolean.BOOL_YES,},
  [710]={BaseID=710,CreateRoleID=13,ModelName="玲珑之人",InitUnlock=TBoolean.BOOL_YES,SexLimit=SexType.ST_Female,},
  [711]={BaseID=711,CreateRoleID=2,ModelName="狂进之士",ModelRank=RankType.RT_Orange,InitUnlock=TBoolean.BOOL_YES,},
  [712]={BaseID=712,CreateRoleID=2,ModelName="狂进之士",ModelRank=RankType.RT_Orange,InitUnlock=TBoolean.BOOL_YES,},
  [713]={BaseID=713,CreateRoleID=3,ModelName="秉节之士",ModelRank=RankType.RT_Orange,InitUnlock=TBoolean.BOOL_YES,},
  [714]={BaseID=714,CreateRoleID=3,ModelName="秉节之士",ModelRank=RankType.RT_Orange,InitUnlock=TBoolean.BOOL_YES,},
  [715]={BaseID=715,CreateRoleID=3,ModelName="秉节之士",ModelRank=RankType.RT_Orange,InitUnlock=TBoolean.BOOL_YES,},
  [716]={BaseID=716,CreateRoleID=5,ModelName="豪气冲天",ModelRank=RankType.RT_Orange,UnlockAchieve=89,Show=TBoolean.BOOL_YES,UnlockDescription="完成成就“木兰花凋”后解锁",},
  [717]={BaseID=717,CreateRoleID=7,ModelName="世外剑圣",ModelRank=RankType.RT_Orange,},
  [718]={BaseID=718,CreateRoleID=9,ModelName="辟邪不败",ModelRank=RankType.RT_Golden,SpineScale=65,},
  [719]={BaseID=719,CreateRoleID=9,ModelName="辟邪不败",ModelRank=RankType.RT_Golden,SpineScale=65,},
  [720]={BaseID=720,CreateRoleID=9,ModelName="辟邪不败",ModelRank=RankType.RT_Golden,SpineScale=65,},
  [721]={BaseID=721,CreateRoleID=8,ModelName="素心玉女",ModelRank=RankType.RT_Golden,SexLimit=SexType.ST_Female,},
  [722]={BaseID=722,CreateRoleID=8,ModelName="素心玉女",ModelRank=RankType.RT_Golden,SexLimit=SexType.ST_Female,},
  [723]={BaseID=723,CreateRoleID=4,ModelName="异域美女",ModelRank=RankType.RT_Orange,InitUnlock=TBoolean.BOOL_YES,Show=TBoolean.BOOL_YES,SexLimit=SexType.ST_Female,},
  [893]={BaseID=893,CreateRoleID=46,ModelName="金刚女徒弟",ModelRank=RankType.RT_DarkGolden,SexLimit=SexType.ST_Female,},
  [894]={BaseID=894,CreateRoleID=47,ModelName="金刚男徒弟",ModelRank=RankType.RT_DarkGolden,},
  [895]={BaseID=895,CreateRoleID=44,ModelName="福娃女徒弟",ModelRank=RankType.RT_Orange,SexLimit=SexType.ST_Female,},
  [896]={BaseID=896,CreateRoleID=45,ModelName="福娃男徒弟",ModelRank=RankType.RT_Orange,},
  [900]={BaseID=900,CreateRoleID=51,ModelName="云鬓销魂",ModelRank=RankType.RT_DarkGolden,UnlockDLC=1,Show=TBoolean.BOOL_YES,SexLimit=SexType.ST_Female,UnlockDescription="拥有豪华版",},
  [909]={BaseID=909,CreateRoleID=6,ModelName="腰缠万贯",ModelRank=RankType.RT_Golden,UnlockAchieve=467,Show=TBoolean.BOOL_YES,UnlockDescription="完成成就“神秘财团黑名单”后解锁",},
  [978]={BaseID=978,CreateRoleID=26,ModelName="出家之人",ModelRank=RankType.RT_Orange,},
  [982]={BaseID=982,CreateRoleID=22,ModelName="寂寞如雪",ModelRank=RankType.RT_DarkGolden,Open=TBoolean.BOOL_NO,},
  [983]={BaseID=983,CreateRoleID=20,ModelName="霸道圣子",ModelRank=RankType.RT_DarkGolden,Open=TBoolean.BOOL_NO,},
  [988]={BaseID=988,CreateRoleID=23,ModelName="寂寞如雪",ModelRank=RankType.RT_DarkGolden,Open=TBoolean.BOOL_NO,},
  [989]={BaseID=989,CreateRoleID=27,ModelName="出家信女",ModelRank=RankType.RT_Orange,SexLimit=SexType.ST_Female,},
  [990]={BaseID=990,CreateRoleID=29,ModelName="修道之女",ModelRank=RankType.RT_Orange,SexLimit=SexType.ST_Female,},
  [991]={BaseID=991,CreateRoleID=25,ModelName="武林盟圣女",ModelRank=RankType.RT_DarkGolden,},
  [992]={BaseID=992,CreateRoleID=28,ModelName="修道之人",ModelRank=RankType.RT_Orange,},
  [993]={BaseID=993,CreateRoleID=24,ModelName="武林盟主",ModelRank=RankType.RT_DarkGolden,},
  [999]={BaseID=999,CreateRoleID=21,ModelName="霸道圣女",ModelRank=RankType.RT_DarkGolden,Open=TBoolean.BOOL_NO,},
  [1005]={BaseID=1005,CreateRoleID=11,ModelName="逆天改命",ModelRank=RankType.RT_Golden,UnlockAchieve=72,Show=TBoolean.BOOL_YES,UnlockDescription="完成成就“武侠小说看多了”后解锁",},
  [1024]={BaseID=1024,CreateRoleID=53,ModelName="如意之人",ModelRank=RankType.RT_DarkGolden,UnlockDLC=1,Show=TBoolean.BOOL_YES,SexLimit=SexType.ST_Female,UnlockDescription="拥有豪华版",},
  [1028]={BaseID=1028,CreateRoleID=41,ModelName="美丽徒弟",ModelRank=RankType.RT_Golden,Open=TBoolean.BOOL_NO,SexLimit=SexType.ST_Female,},
  [1029]={BaseID=1029,CreateRoleID=43,ModelName="强壮徒弟",Open=TBoolean.BOOL_NO,},
  [1030]={BaseID=1030,CreateRoleID=42,ModelName="嗜睡徒弟",Open=TBoolean.BOOL_NO,},
  [1031]={BaseID=1031,CreateRoleID=39,ModelName="活泼徒弟",Open=TBoolean.BOOL_NO,},
  [1057]={BaseID=1057,CreateRoleID=40,ModelName="聪明徒弟",ModelRank=RankType.RT_Orange,Open=TBoolean.BOOL_NO,},
  [1080]={BaseID=1080,CreateRoleID=48,ModelName="武炼之人",ModelRank=RankType.RT_Green,},
}
for k,v in pairs(RoleFaceModel) do
    setmetatable(v, {['__index'] = RoleFaceModelDefault})
end

-- export table: RoleFaceModel
return RoleFaceModel
