-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local RolePiece= {
  [1]={BaseID=1,Level=1,Piece=1,AttrAdd=2000,},
  [2]={BaseID=2,Level=2,Piece=2,AttrAdd=4000,},
  [3]={BaseID=3,Level=3,Piece=4,AttrAdd=6000,},
  [4]={BaseID=4,Level=4,Piece=6,AttrAdd=8000,},
  [5]={BaseID=5,Level=5,Piece=8,AttrAdd=10000,},
  [6]={BaseID=6,Level=6,Piece=12,AttrAdd=12000,},
  [7]={BaseID=7,Level=7,Piece=16,AttrAdd=14000,},
  [8]={BaseID=8,Level=8,Piece=24,AttrAdd=16000,},
  [9]={BaseID=9,Level=9,Piece=32,AttrAdd=18000,},
  [10]={BaseID=10,Level=10,Piece=50,AttrAdd=20000,},
}

-- export table: RolePiece
return RolePiece
