-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum SexType
require("common");


local RoleFaceJudge= {
  [1]={BaseID=1,Sex=SexType.ST_Male,Param1=1,Param2=2010,Param3=0,Param4=0,Param5=0,Param6=0,Param7=4001,Param8=0,Description="观自在菩萨，行深般若波罗蜜多时，照见五蕴皆空，度一切苦厄。",},
  [2]={BaseID=2,Sex=SexType.ST_SexNull,Param1=0,Param2=0,Param3=0,Param4=0,Param5=0,Param6=0,Param7=0,Param8=0,Description="",},
  [3]={BaseID=3,Sex=SexType.ST_SexNull,Param1=0,Param2=0,Param3=0,Param4=0,Param5=0,Param6=0,Param7=0,Param8=0,Description="",},
}

-- export table: RoleFaceJudge
return RoleFaceJudge
