-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum StatusType
-- enum RankType
require("common");


local RoleImpressionConfig= {
  [1]={BaseID=1,SexDesc={650015,650016,650017,650018,},ClanDescNoStatusDesc={650019,},ClanDescHasStatusDesc={650020,},StatusList={StatusType.STT_Chengshigaoshou,StatusType.STT_Yinshigaoshou,StatusType.STT_JiangHuGaoShou,StatusType.STT_Menpaizhangmen,StatusType.STT_Menpaizhanglao,StatusType.STT_Menpaihufa,StatusType.STT_Menpaidizi,},StatusDescList={650001,650002,650003,650004,650005,650006,650007,},RankList={RankType.RT_White,RankType.RT_Green,RankType.RT_Blue,RankType.RT_Purple,RankType.RT_Orange,RankType.RT_Golden,RankType.RT_DarkGolden,},RankDescList={650008,650009,650010,650011,650012,650013,650013,},NoGoodMartialDesc={650021,},HasGoodMartialDesc={650022,},HasTreasureDesc={650023,},NoTreasureDesc={650024,},PowerList={-11,-6,5,10,99,},PowerDescList={650025,650026,650027,650028,650029,},LevelToPower=1,RankToPower=2,},
}

-- export table: RoleImpressionConfig
return RoleImpressionConfig
