-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum RankType
-- enum TBoolean
-- enum StatusType
require("common");


local RoleAddLevelDefault = {CharacterLine=TBoolean.BOOL_NO,Status=StatusType.STT_StatusTypeNull,}
local RoleAddLevel= {
  [1]={BaseID=1,Priority=4,Rank={RankType.RT_White,RankType.RT_Green,},AddLevel={1,2,3,5,7,10,},DescID={190001,190002,190003,190004,190005,190006,},},
  [2]={BaseID=2,Priority=4,Rank={RankType.RT_Blue,RankType.RT_Purple,},AddLevel={1,2,3,5,7,10,},DescID={190007,190008,190009,190010,190011,190012,},},
  [3]={BaseID=3,Priority=4,Rank={RankType.RT_Orange,RankType.RT_Golden,RankType.RT_DarkGolden,},AddLevel={1,2,3,4,5,7,8,10,},DescID={190013,190014,190015,190016,190017,190018,190019,190020,},},
  [4]={BaseID=4,Priority=10,CharacterLine=TBoolean.BOOL_YES,AddLevel={1,1,2,2,2,3,4,5,6,6,7,7,8,9,10,10,},DescID={190021,190022,190023,190024,190025,190026,859779897,190029,190030,190031,190032,190033,190034,190035,190036,},},
  [5]={BaseID=5,Priority=5,Status=StatusType.STT_Menpaizhangmen,AddLevel={1,1,1,2,2,3,4,5,6,7,8,10,},DescID={190037,190038,190039,190040,190041,190042,190043,190044,190045,190046,190047,190048,},},
  [6]={BaseID=6,Priority=5,Status=StatusType.STT_Yinshigaoshou,AddLevel={2,2,2,3,4,5,6,7,8,10,},DescID={190049,190050,190051,190052,190053,190054,190055,190056,190057,190058,},},
  [7]={BaseID=7,Priority=0,AddLevel={1,1,2,3,},DescID={190059,190060,190061,190062,},},
}
for k,v in pairs(RoleAddLevel) do
    setmetatable(v, {['__index'] = RoleAddLevelDefault})
end

-- export table: RoleAddLevel
return RoleAddLevel
