-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local RoleExtraLevelAttr= {
  [1]={BaseID=1,Level=1,White=300,Green=300,Blue=300,Purple=400,Orange=400,Golden=500,DarkGolden=500,JingliangDarkGolden=500,YouxiuDarkGolden=500,},
  [2]={BaseID=2,Level=2,White=400,Green=400,Blue=400,Purple=500,Orange=500,Golden=600,DarkGolden=600,JingliangDarkGolden=600,YouxiuDarkGolden=600,},
  [3]={BaseID=3,Level=3,White=500,Green=500,Blue=500,Purple=600,Orange=600,Golden=700,DarkGolden=700,JingliangDarkGolden=700,YouxiuDarkGolden=700,},
  [4]={BaseID=4,Level=4,White=600,Green=600,Blue=600,Purple=700,Orange=700,Golden=800,DarkGolden=800,JingliangDarkGolden=800,YouxiuDarkGolden=800,},
  [5]={BaseID=5,Level=5,White=700,Green=700,Blue=700,Purple=800,Orange=800,Golden=900,DarkGolden=900,JingliangDarkGolden=900,YouxiuDarkGolden=900,},
  [6]={BaseID=6,Level=6,White=800,Green=800,Blue=800,Purple=900,Orange=900,Golden=1000,DarkGolden=1000,JingliangDarkGolden=1000,YouxiuDarkGolden=1000,},
  [7]={BaseID=7,Level=7,White=900,Green=900,Blue=900,Purple=1000,Orange=1000,Golden=1100,DarkGolden=1100,JingliangDarkGolden=1100,YouxiuDarkGolden=1100,},
  [8]={BaseID=8,Level=8,White=1000,Green=1000,Blue=1000,Purple=1100,Orange=1100,Golden=1200,DarkGolden=1200,JingliangDarkGolden=1200,YouxiuDarkGolden=1200,},
  [9]={BaseID=9,Level=9,White=1100,Green=1100,Blue=1100,Purple=1200,Orange=1200,Golden=1300,DarkGolden=1300,JingliangDarkGolden=1300,YouxiuDarkGolden=1300,},
  [10]={BaseID=10,Level=10,White=1200,Green=1200,Blue=1200,Purple=1300,Orange=1300,Golden=1400,DarkGolden=1400,JingliangDarkGolden=1400,YouxiuDarkGolden=1400,},
}

-- export table: RoleExtraLevelAttr
return RoleExtraLevelAttr
