-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum SexType
require("common");


local RoleFaceJudgeDefault= {
  [1]={BaseID=1,Sex=SexType.ST_Male,Description="海到无边天作岸，山登绝顶我为峰。",},
  [2]={BaseID=2,Sex=SexType.ST_Male,Description="千淘万漉虽辛苦，吹尽狂沙始到金。",},
  [3]={BaseID=3,Sex=SexType.ST_Male,Description="有花堪折直须折，莫待无花空折枝。",},
  [4]={BaseID=4,Sex=SexType.ST_Male,Description="宝剑锋从磨砺出，梅花香自苦寒来。",},
  [5]={BaseID=5,Sex=SexType.ST_Male,Description="长风破浪会有时，直挂云帆济沧海。",},
  [6]={BaseID=6,Sex=SexType.ST_Female,Description="绝代有佳人，幽居在空谷。",},
  [7]={BaseID=7,Sex=SexType.ST_Female,Description="云想衣裳花想容，春风拂槛露华浓。",},
  [8]={BaseID=8,Sex=SexType.ST_Female,Description="仿佛兮若轻云之蔽月，飘摇兮若流风之回雪。",},
  [9]={BaseID=9,Sex=SexType.ST_Female,Description="北方有佳人，绝世而独立。一顾倾人城，再顾倾人国。",},
  [10]={BaseID=10,Sex=SexType.ST_Female,Description="螓首蛾眉，巧笑倩兮，美目盼兮。",},
}

-- export table: RoleFaceJudgeDefault
return RoleFaceJudgeDefault
