-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local RoleAdventureGift= {
  [1]={BaseID=1,level=10,White=1,Green=1,Blue=2,Purple=2,Orange=3,Golden=3,DarkGolden=3,JingliangDarkGolden=3,YouxiuDarkGolden=3,},
  [2]={BaseID=2,level=15,White=1,Green=2,Blue=2,Purple=3,Orange=3,Golden=4,DarkGolden=4,JingliangDarkGolden=4,YouxiuDarkGolden=4,},
  [3]={BaseID=3,level=20,White=2,Green=3,Blue=3,Purple=4,Orange=4,Golden=4,DarkGolden=4,JingliangDarkGolden=4,YouxiuDarkGolden=4,},
  [4]={BaseID=4,level=25,White=2,Green=3,Blue=4,Purple=4,Orange=5,Golden=6,DarkGolden=6,JingliangDarkGolden=6,YouxiuDarkGolden=6,},
  [5]={BaseID=5,level=30,White=3,Green=4,Blue=5,Purple=5,Orange=6,Golden=7,DarkGolden=7,JingliangDarkGolden=7,YouxiuDarkGolden=7,},
  [6]={BaseID=6,level=999,White=4,Green=4,Blue=5,Purple=5,Orange=6,Golden=7,DarkGolden=7,JingliangDarkGolden=7,YouxiuDarkGolden=7,},
}

-- export table: RoleAdventureGift
return RoleAdventureGift
