-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum RoleCardEffect
require("common");


local RoleCard= {
}

-- export table: RoleCard
return RoleCard
