-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local RoleWishConfig_ChiZiZhiXin= {
  [1]={BaseID=1,ClanList={15,8,16,},OutRoleList={1000013050,1000013051,1000013052,},CityList={32,39,35,13,},},
}

-- export table: RoleWishConfig_ChiZiZhiXin
return RoleWishConfig_ChiZiZhiXin
