-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local SecretShopDefault = {Money=48000000,DropID=8008,}
local SecretShop= {
  [1]={BaseID=1,Diff=1,Money=10000000,DropID=8001,},
  [2]={BaseID=2,Diff=2,Money=12000000,DropID=8002,},
  [3]={BaseID=3,Diff=3,Money=14000000,DropID=8002,},
  [4]={BaseID=4,Diff=4,Money=16000000,DropID=8002,},
  [5]={BaseID=5,Diff=5,Money=18000000,DropID=8003,},
  [6]={BaseID=6,Diff=6,Money=20000000,DropID=8003,},
  [7]={BaseID=7,Diff=7,Money=22000000,DropID=8003,},
  [8]={BaseID=8,Diff=8,Money=24000000,DropID=8004,},
  [9]={BaseID=9,Diff=9,Money=26000000,DropID=8004,},
  [10]={BaseID=10,Diff=10,Money=28000000,DropID=8004,},
  [11]={BaseID=11,Diff=11,Money=30000000,DropID=8005,},
  [12]={BaseID=12,Diff=12,Money=32000000,DropID=8005,},
  [13]={BaseID=13,Diff=13,Money=34000000,DropID=8005,},
  [14]={BaseID=14,Diff=14,Money=36000000,DropID=8006,},
  [15]={BaseID=15,Diff=15,Money=38000000,DropID=8006,},
  [16]={BaseID=16,Diff=16,Money=40000000,DropID=8006,},
  [17]={BaseID=17,Diff=17,Money=42000000,DropID=8007,},
  [18]={BaseID=18,Diff=18,Money=44000000,DropID=8007,},
  [19]={BaseID=19,Diff=19,Money=46000000,DropID=8007,},
  [20]={BaseID=20,Diff=20,},
  [21]={BaseID=21,Diff=21,},
  [22]={BaseID=22,Diff=22,},
  [23]={BaseID=23,Diff=23,},
  [24]={BaseID=24,Diff=24,},
  [25]={BaseID=25,Diff=25,},
  [26]={BaseID=26,Diff=26,},
  [27]={BaseID=27,Diff=27,},
  [28]={BaseID=28,Diff=28,},
  [29]={BaseID=29,Diff=29,},
  [30]={BaseID=30,Diff=30,},
}
for k,v in pairs(SecretShop) do
    setmetatable(v, {['__index'] = SecretShopDefault})
end

-- export table: SecretShop
return SecretShop
