-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local ShotData= {
  [1]={BaseID=1,bgPath="UI/UISprite/TencentIcon/share_fight",textPath="UI/UISprite/TencentIcon/share_text",},
  [2]={BaseID=2,bgPath="UI/UISprite/TencentIcon/share_clan",textPath="UI/UISprite/TencentIcon/share_word3",},
  [3]={BaseID=3,bgPath="UI/UISprite/TencentIcon/share_invite",textPath="UI/UISprite/TencentIcon/share_text",},
  [4]={BaseID=4,bgPath="UI/UISprite/TencentIcon/share_student",textPath="UI/UISprite/TencentIcon/share_word4",},
  [5]={BaseID=5,bgPath="",textPath="UI/UISprite/TencentIcon/share_word2",},
  [6]={BaseID=6,bgPath="UI/UISprite/TencentIcon/share_treasure",textPath="UI/UISprite/TencentIcon/share_word5",},
  [7]={BaseID=7,bgPath="",textPath="UI/UISprite/TencentIcon/share_text",},
  [8]={BaseID=8,bgPath="UI/UISprite/TencentIcon/share_create",textPath="UI/UISprite/TencentIcon/share_text",},
  [9]={BaseID=9,bgPath="UI/UISprite/TencentIcon/share_arena",textPath="UI/UISprite/TencentIcon/share_word6",},
  [10]={BaseID=10,bgPath="UI/UISprite/TencentIcon/share_set",textPath="UI/UISprite/TencentIcon/share_word7",},
}

-- export table: ShotData
return ShotData
