-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- ShotAdd.ShotImageEnum
ShotImageEnum = {
  IMG_NULL = 0; -- 空
  IMG_PIC = 1; -- 图片
  IMG_SHOT = 2; -- 截图
}

ShotImageEnum_Revert = {
  ["空"] = ShotImageEnum.IMG_NULL;
  ["图片"] = ShotImageEnum.IMG_PIC;
  ["截图"] = ShotImageEnum.IMG_SHOT;
}


local ShotAdd= {
  [1]={BaseID=1,picType={ShotImageEnum.IMG_SHOT,},picPath={"/",},shotPosX={39,},shotPosY={152,},shotWidth={850,},shotHeight={460,},},
  [2]={BaseID=2,picType={ShotImageEnum.IMG_SHOT,},picPath={"/",},shotPosX={39,},shotPosY={152,},shotWidth={850,},shotHeight={460,},},
  [3]={BaseID=3,picType={ShotImageEnum.IMG_SHOT,},picPath={"/",},shotPosX={39,},shotPosY={152,},shotWidth={850,},shotHeight={460,},},
  [4]={BaseID=4,picType={ShotImageEnum.IMG_SHOT,},picPath={"/",},shotPosX={39,},shotPosY={152,},shotWidth={850,},shotHeight={460,},},
  [5]={BaseID=5,picType={ShotImageEnum.IMG_SHOT,},picPath={"/",},shotPosX={0,},shotPosY={0,},shotWidth={1280,},shotHeight={720,},},
  [6]={BaseID=6,picType={ShotImageEnum.IMG_SHOT,},picPath={"/",},shotPosX={39,},shotPosY={152,},shotWidth={850,},shotHeight={460,},},
  [7]={BaseID=7,picType={ShotImageEnum.IMG_SHOT,},picPath={"/",},shotPosX={0,},shotPosY={0,},shotWidth={1280,},shotHeight={720,},},
  [8]={BaseID=8,picType={ShotImageEnum.IMG_SHOT,},picPath={"/",},shotPosX={39,},shotPosY={152,},shotWidth={850,},shotHeight={460,},},
  [9]={BaseID=9,picType={ShotImageEnum.IMG_SHOT,},picPath={"/",},shotPosX={39,},shotPosY={152,},shotWidth={850,},shotHeight={460,},},
  [10]={BaseID=10,picType={ShotImageEnum.IMG_SHOT,},picPath={"/",},shotPosX={39,},shotPosY={152,},shotWidth={850,},shotHeight={460,},},
}

-- export table: ShotAdd
return ShotAdd
