-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local SpecialMapRoleAnimation= {
  [1]={BaseID=1,Role=1020114002,Map=0,AnimationName="disappear",Tag=881,},
  [2]={BaseID=2,Role=1020114001,Map=0,AnimationName="disappear",Tag=894,},
}

-- export table: SpecialMapRoleAnimation
return SpecialMapRoleAnimation
