-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum StoryDiffDropRewardType
require("common");


local SpecialGiftDefault = {NeedItemType=StoryDiffDropRewardType.SDDRT_Item,ExtraFavor=15,RewardItemType=StoryDiffDropRewardType.SDDRT_Item,ExecuteTime=1,}
local SpecialGift= {
  [1]={BaseID=1,RoleID=1020112001,NeedItemID=30922,Conversation={680003,680004,680005,},RewardItemID={30521,},RewardItemNum={5,},},
  [2]={BaseID=2,RoleID=1020112001,NeedItemID=30722,ExtraFavor=20,Conversation={680006,680007,},RewardItemID={70404,},RewardItemNum={1,},},
  [3]={BaseID=3,RoleID=1020101003,NeedItemID=440103,Conversation={680008,680009,680010,},RewardItemType=StoryDiffDropRewardType.SDDRT_Tianshu,RewardItemID={800,},RewardItemNum={1,},},
  [4]={BaseID=4,RoleID=1020101003,NeedItemID=440302,Conversation={680011,680012,680013,},RewardItemType=StoryDiffDropRewardType.SDDRT_Tianshu,RewardItemID={30053,},RewardItemNum={1,},},
  [5]={BaseID=5,RoleID=1020112002,NeedItemID=70404,ExtraFavor=25,Conversation={680014,680015,},RewardItemID={70302,},RewardItemNum={1,},},
  [6]={BaseID=6,RoleID=1020112002,NeedItemID=30911,Conversation={680016,680017,680018,},RewardItemType=StoryDiffDropRewardType.SDDRT_Miji,RewardItemID={12110,},RewardItemNum={1,},},
  [7]={BaseID=7,RoleID=1020112002,NeedItemID=412102,ExtraFavor=25,Conversation={680019,680020,680021,680022,},RewardItemType=StoryDiffDropRewardType.SDDRT_Miji,RewardItemID={12111,},RewardItemNum={1,},},
  [8]={BaseID=8,RoleID=1020101002,NeedItemID=31013,Conversation={680023,680024,680025,680026,},RewardItemID={1301,},RewardItemNum={300,},},
  [9]={BaseID=9,RoleID=1020101002,NeedItemID=440206,ExtraFavor=30,Conversation={680029,680030,680031,},RewardItemType=StoryDiffDropRewardType.SDDRT_Tianshu,RewardItemID={860,},RewardItemNum={1,},},
  [10]={BaseID=10,RoleID=1020101001,NeedItemID=30922,Conversation={680032,680033,},RewardItemID={1301,},RewardItemNum={400,},},
  [11]={BaseID=11,RoleID=1020101001,NeedItemID=440206,ExtraFavor=30,Conversation={680036,680037,680038,680039,},RewardItemType=StoryDiffDropRewardType.SDDRT_Tianshu,RewardItemID={30047,},RewardItemNum={1,},},
  [12]={BaseID=12,RoleID=1020112003,NeedItemID=31513,Conversation={680040,680041,},RewardItemID={1001,},RewardItemNum={1,},},
  [13]={BaseID=13,RoleID=1020112003,NeedItemID=31521,Conversation={680042,},RewardItemID={1101,},RewardItemNum={1,},},
  [14]={BaseID=14,RoleID=1020101004,NeedItemID=30822,Conversation={680043,680044,},RewardItemID={30832,},RewardItemNum={1,},},
  [15]={BaseID=15,RoleID=1020101004,NeedItemID=30823,ExtraFavor=10,Conversation={680045,680046,},RewardItemID={30833,},RewardItemNum={1,},},
  [16]={BaseID=16,RoleID=1020112003,NeedItemID=412102,ExtraFavor=10,Conversation={680047,680048,},RewardItemType=StoryDiffDropRewardType.SDDRT_Null,},
}
for k,v in pairs(SpecialGift) do
    setmetatable(v, {['__index'] = SpecialGiftDefault})
end

-- export table: SpecialGift
return SpecialGift
