-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local StoryItemBring= {
  [1]={BaseID=1,SilverIgnot=200,},
  [2]={BaseID=2,SilverIgnot=400,},
  [3]={BaseID=3,SilverIgnot=600,},
  [4]={BaseID=4,SilverIgnot=800,},
  [5]={BaseID=5,SilverIgnot=1000,},
  [6]={BaseID=6,SilverIgnot=1500,},
  [7]={BaseID=7,SilverIgnot=2000,},
  [8]={BaseID=8,SilverIgnot=2500,},
  [9]={BaseID=9,SilverIgnot=3000,},
  [10]={BaseID=10,SilverIgnot=3500,},
}

-- export table: StoryItemBring
return StoryItemBring
