-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local SystemOpenLanguage= {
  [1]={BaseID=1,LanguageID=710001,},
  [8]={BaseID=8,LanguageID=710002,},
  [16]={BaseID=16,LanguageID=710003,},
  [31]={BaseID=31,LanguageID=710004,},
}

-- export table: SystemOpenLanguage
return SystemOpenLanguage
