-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum TaskEventCallbackType
require("common");


local TaskEventCallbackDefault = {Arg2="",Arg3="",Arg4="",Arg5="",}
local TaskEventCallback= {
  [1]={BaseID=1,CallBackType=TaskEventCallbackType.TECT_ChangeMap,Arg1="",},
  [2]={BaseID=2,CallBackType=TaskEventCallbackType.TECT_FireEventCustomize,Arg1="3",},
  [3]={BaseID=3,CallBackType=TaskEventCallbackType.TECT_RunDrop,Arg1="124",},
  [4]={BaseID=4,CallBackType=TaskEventCallbackType.TECT_MAZE_ENTER,Arg1="1",},
  [5]={BaseID=5,CallBackType=TaskEventCallbackType.TECT_MAZE_QUIT,Arg1="",},
  [6]={BaseID=6,CallBackType=TaskEventCallbackType.TECT_MAZE_MOVE_TO_CLICK,Arg1="",},
  [7]={BaseID=7,CallBackType=TaskEventCallbackType.TECT_ROLE_MODIFY_SHOWNAME,Arg1="MAINROLE",Arg2="张三丰",},
  [8]={BaseID=8,CallBackType=TaskEventCallbackType.TECT_MAP_MOVE_MAINROLE,Arg1="60",},
}
for k,v in pairs(TaskEventCallback) do
    setmetatable(v, {['__index'] = TaskEventCallbackDefault})
end

-- export table: TaskEventCallback
return TaskEventCallback
