-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local TimeLimitGiftDefault = {Grade=1,IsMultiChoice=0,HadGoldMax=0,NextGrade=0,NextPer=0,LastGrade=1,LastPer=0,}
local TimeLimitGift= {
  [101]={BaseID=101,TypeID=1,NameID=800101,Price=60,ItemId={1006,1106,},ItemNum={1,1,},NextGrade=1,NextPer=10000,LastGrade=0,},
  [102]={BaseID=102,TypeID=1,Grade=2,NameID=800102,Price=120,ItemId={1006,1106,},ItemNum={2,2,},HadGoldMax=200,NextGrade=2,NextPer=8000,LastPer=8000,},
  [103]={BaseID=103,TypeID=1,Grade=3,NameID=800103,Price=180,ItemId={1006,1106,},ItemNum={3,3,},HadGoldMax=500,NextGrade=3,NextPer=6000,LastPer=9000,},
  [104]={BaseID=104,TypeID=1,Grade=4,NameID=800104,Price=600,ItemId={1006,1106,},ItemNum={4,4,},HadGoldMax=1000,LastPer=10000,},
  [201]={BaseID=201,TypeID=2,NameID=800201,Price=60,ItemId={30951,30941,},ItemNum={3,3,},NextGrade=1,NextPer=10000,LastGrade=0,},
  [202]={BaseID=202,TypeID=2,Grade=2,NameID=800202,Price=120,ItemId={30951,30941,},ItemNum={5,5,},HadGoldMax=200,NextGrade=2,NextPer=8000,LastPer=8000,},
  [203]={BaseID=203,TypeID=2,Grade=3,NameID=800203,Price=200,ItemId={30951,30941,},ItemNum={8,8,},HadGoldMax=500,NextGrade=3,NextPer=6000,LastPer=9000,},
  [204]={BaseID=204,TypeID=2,Grade=4,NameID=800204,Price=600,ItemId={30951,30941,},ItemNum={10,10,},HadGoldMax=1000,LastPer=10000,},
  [301]={BaseID=301,TypeID=3,NameID=800301,IsMultiChoice=1,Price=60,ItemId={335001,335002,336001,},ItemNum={1,1,1,},NextGrade=1,NextPer=10000,LastGrade=0,},
  [302]={BaseID=302,TypeID=3,Grade=2,NameID=800302,IsMultiChoice=1,Price=120,ItemId={335001,335002,336001,},ItemNum={2,2,2,},HadGoldMax=200,NextGrade=2,NextPer=8000,LastPer=8000,},
  [303]={BaseID=303,TypeID=3,Grade=3,NameID=800303,IsMultiChoice=1,Price=200,ItemId={335001,335002,336001,},ItemNum={3,3,3,},HadGoldMax=500,NextGrade=3,NextPer=6000,LastPer=9000,},
  [304]={BaseID=304,TypeID=3,Grade=4,NameID=800304,IsMultiChoice=1,Price=600,ItemId={335001,335002,336001,},ItemNum={4,4,4,},HadGoldMax=1000,LastPer=10000,},
  [401]={BaseID=401,TypeID=4,NameID=800401,IsMultiChoice=1,Price=60,ItemId={35001,35002,35003,35004,35005,35006,35007,35008,35009,},ItemNum={1,1,1,1,1,1,1,1,1,},NextGrade=1,NextPer=10000,LastGrade=0,},
  [402]={BaseID=402,TypeID=4,Grade=2,NameID=800402,IsMultiChoice=1,Price=120,ItemId={35001,35002,35003,35004,35005,35006,35007,35008,35009,},ItemNum={2,2,2,2,2,2,2,2,2,},HadGoldMax=200,NextGrade=2,NextPer=8000,LastPer=8000,},
  [403]={BaseID=403,TypeID=4,Grade=3,NameID=800403,IsMultiChoice=1,Price=220,ItemId={35001,35002,35003,35004,35005,35006,35007,35008,35009,},ItemNum={3,3,3,3,3,3,3,3,3,},HadGoldMax=500,NextGrade=3,NextPer=6000,LastPer=9000,},
  [404]={BaseID=404,TypeID=4,Grade=4,NameID=800404,IsMultiChoice=1,Price=600,ItemId={35001,35002,35003,35004,35005,35006,35007,35008,35009,},ItemNum={4,4,4,4,4,4,4,4,4,},HadGoldMax=1000,LastPer=10000,},
  [8801]={BaseID=8801,TypeID=88,NameID=808801,Price=0,ItemId={1301,},ItemNum={5000,},LastGrade=0,},
}
for k,v in pairs(TimeLimitGift) do
    setmetatable(v, {['__index'] = TimeLimitGiftDefault})
end

-- export table: TimeLimitGift
return TimeLimitGift
