-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local TimeLimitConfig= {
  [1]={BaseID=1,DayLimitCanZhang=2,DayLimitForge=5,DayLimitRoleCard=1,NumMax=2,GapTime=180,CoinPer=3000,OtherGiftPer=5000,BigCoinCovGlod=180,TriggerLv=24,CountDown=30,RequireNum=15,CutGoldNum=170,ActivityTime=120,CoinGiftNum=7,HighGradeRule={TimeLimitGiftGradeCondNum=2,TimeLimitGiftGradeCond=3,TimeLimitGiftCount=1,TimeLimitGiftGrade=1,},DiscountEfcTime=24,MustGiftNum=2,TimeLimitGiftFirstPush={{FirstPushGiftType=1,FirstPushGiftGrade=3,},{FirstPushGiftType=3,FirstPushGiftGrade=1,},{FirstPushGiftType=4,FirstPushGiftGrade=2,},},TimeLimitGiftDonateKnifeId=1702,TimeLimitEnableScripts={2,6,7,},},
}

-- export table: TimeLimitConfig
return TimeLimitConfig
