-- Auto generated by TableTool, Copyright ElectronicSoul@2017


local TimeLimitPriorityGrade= {
  [200]={Discount=200,PriorityGrade=4,},
  [300]={Discount=300,PriorityGrade=3,},
}

-- export table: TimeLimitPriorityGrade
return TimeLimitPriorityGrade
