-- Auto generated by TableTool, Copyright ElectronicSoul@2017

-- import for enum types:
-- enum EffectSubType
-- enum TBoolean
require("common");


local TreasureMazeDefault = {Type=EffectSubType.EST_Advanced,Maze=5,MazeArea=1,EntryCardTypeID=601,ShareFriend=TBoolean.BOOL_NO,MaxShareNums=0,TreasureItemTypeID=80601,TriggerTask=5353,}
local TreasureMaze= {
  [101]={BaseID=101,Type=EffectSubType.EST_Ordinary,Maze=21,TreasureMazeID={35,36,37,71,},TreasureMazeWeight={10,10,10,3,},TreasureItemTypeID=80501,},
  [102]={BaseID=102,Type=EffectSubType.EST_Ordinary,Maze=25,TreasureMazeID={35,36,37,71,},TreasureMazeWeight={10,10,10,3,},TreasureItemTypeID=80501,},
  [103]={BaseID=103,Type=EffectSubType.EST_Ordinary,Maze=26,TreasureMazeID={35,36,37,71,},TreasureMazeWeight={10,10,10,3,},TreasureItemTypeID=80501,},
  [104]={BaseID=104,Type=EffectSubType.EST_Ordinary,Maze=27,TreasureMazeID={35,36,37,71,},TreasureMazeWeight={10,10,10,3,},TreasureItemTypeID=80501,},
  [105]={BaseID=105,Type=EffectSubType.EST_Ordinary,Maze=28,TreasureMazeID={35,36,37,71,},TreasureMazeWeight={10,10,10,3,},TreasureItemTypeID=80501,},
  [201]={BaseID=201,Maze=1,TreasureMazeID={38,72,},TreasureMazeWeight={10,1,},},
  [202]={BaseID=202,Maze=4,TreasureMazeID={38,72,},TreasureMazeWeight={10,1,},},
  [203]={BaseID=203,TreasureMazeID={38,72,},TreasureMazeWeight={10,1,},},
  [204]={BaseID=204,Maze=7,TreasureMazeID={38,72,},TreasureMazeWeight={10,1,},},
  [205]={BaseID=205,Maze=9,TreasureMazeID={38,72,},TreasureMazeWeight={10,1,},},
  [206]={BaseID=206,Maze=10,TreasureMazeID={38,72,},TreasureMazeWeight={10,1,},},
  [207]={BaseID=207,Maze=11,TreasureMazeID={38,72,},TreasureMazeWeight={10,1,},},
  [208]={BaseID=208,Maze=15,TreasureMazeID={38,72,},TreasureMazeWeight={10,1,},},
  [209]={BaseID=209,Maze=17,TreasureMazeID={38,72,},TreasureMazeWeight={10,1,},},
  [210]={BaseID=210,Maze=18,TreasureMazeID={38,72,},TreasureMazeWeight={10,1,},},
  [211]={BaseID=211,Maze=19,TreasureMazeID={38,72,},TreasureMazeWeight={10,1,},},
  [212]={BaseID=212,Maze=30,TreasureMazeID={38,72,},TreasureMazeWeight={10,1,},},
  [213]={BaseID=213,Maze=31,TreasureMazeID={38,72,},TreasureMazeWeight={10,1,},},
  [214]={BaseID=214,Maze=33,TreasureMazeID={38,72,},TreasureMazeWeight={10,1,},},
  [301]={BaseID=301,Type=EffectSubType.EST_Magical,Maze=13,TreasureMazeID={42,73,},TreasureMazeWeight={10,1,},TreasureItemTypeID=80702,},
  [302]={BaseID=302,Type=EffectSubType.EST_Magical,Maze=32,TreasureMazeID={42,73,},TreasureMazeWeight={10,1,},TreasureItemTypeID=80702,},
  [303]={BaseID=303,Type=EffectSubType.EST_Magical,Maze=34,TreasureMazeID={42,73,},TreasureMazeWeight={10,1,},TreasureItemTypeID=80702,},
  [304]={BaseID=304,Type=EffectSubType.EST_Magical,Maze=35,TreasureMazeID={42,73,},TreasureMazeWeight={10,1,},TreasureItemTypeID=80702,},
  [305]={BaseID=305,Type=EffectSubType.EST_Magical,Maze=36,TreasureMazeID={42,73,},TreasureMazeWeight={10,1,},TreasureItemTypeID=80702,},
  [306]={BaseID=306,Type=EffectSubType.EST_Magical,Maze=37,TreasureMazeID={42,73,},TreasureMazeWeight={10,1,},TreasureItemTypeID=80702,},
  [307]={BaseID=307,Type=EffectSubType.EST_Magical,Maze=38,TreasureMazeID={42,73,},TreasureMazeWeight={10,1,},TreasureItemTypeID=80702,},
  [308]={BaseID=308,Type=EffectSubType.EST_Magical,Maze=39,TreasureMazeID={42,73,},TreasureMazeWeight={10,1,},TreasureItemTypeID=80702,},
  [309]={BaseID=309,Type=EffectSubType.EST_Magical,Maze=40,TreasureMazeID={42,73,},TreasureMazeWeight={10,1,},TreasureItemTypeID=80702,},
  [315]={BaseID=315,Type=EffectSubType.EST_ShaoLin,Maze=19,TreasureMazeID={42,},TreasureMazeWeight={10,},TreasureItemTypeID=80702,},
  [401]={BaseID=401,Type=EffectSubType.EST_YuWang,TreasureMazeID={59,},TreasureMazeWeight={1,},TreasureItemTypeID=80710,TriggerTask=5354,},
  [402]={BaseID=402,Type=EffectSubType.EST_YuWang,Maze=34,TreasureMazeID={59,},TreasureMazeWeight={1,},TreasureItemTypeID=80710,TriggerTask=5354,},
  [403]={BaseID=403,Type=EffectSubType.EST_YuWang,Maze=37,TreasureMazeID={59,},TreasureMazeWeight={1,},TreasureItemTypeID=80710,TriggerTask=5354,},
  [404]={BaseID=404,Type=EffectSubType.EST_YuWang,Maze=38,TreasureMazeID={59,},TreasureMazeWeight={1,},TreasureItemTypeID=80710,TriggerTask=5354,},
  [405]={BaseID=405,Type=EffectSubType.EST_YuWang,Maze=40,TreasureMazeID={59,},TreasureMazeWeight={1,},TreasureItemTypeID=80710,TriggerTask=5354,},
  [501]={BaseID=501,Type=EffectSubType.EST_ShareTreasure,Maze=2,TreasureMazeID={71,},TreasureMazeWeight={1,},TreasureItemTypeID=80501,},
  [601]={BaseID=601,Type=EffectSubType.EST_YuWenBaoTu1,Maze=21,TreasureMazeID={103,},TreasureMazeWeight={1,},TreasureItemTypeID=805006,},
  [602]={BaseID=602,Type=EffectSubType.EST_YuWenBaoTu1,Maze=25,TreasureMazeID={103,},TreasureMazeWeight={1,},TreasureItemTypeID=805006,},
  [603]={BaseID=603,Type=EffectSubType.EST_YuWenBaoTu1,Maze=26,TreasureMazeID={103,},TreasureMazeWeight={1,},TreasureItemTypeID=805006,},
  [604]={BaseID=604,Type=EffectSubType.EST_YuWenBaoTu1,Maze=27,TreasureMazeID={103,},TreasureMazeWeight={1,},TreasureItemTypeID=805006,},
  [605]={BaseID=605,Type=EffectSubType.EST_YuWenBaoTu1,Maze=28,TreasureMazeID={103,},TreasureMazeWeight={1,},TreasureItemTypeID=805006,},
  [701]={BaseID=701,Type=EffectSubType.EST_YuWenBaoTu2,Maze=1,TreasureMazeID={104,},TreasureMazeWeight={1,},TreasureItemTypeID=806005,},
  [702]={BaseID=702,Type=EffectSubType.EST_YuWenBaoTu2,Maze=4,TreasureMazeID={104,},TreasureMazeWeight={1,},TreasureItemTypeID=806005,},
  [703]={BaseID=703,Type=EffectSubType.EST_YuWenBaoTu2,TreasureMazeID={104,},TreasureMazeWeight={1,},TreasureItemTypeID=806005,},
  [704]={BaseID=704,Type=EffectSubType.EST_YuWenBaoTu2,Maze=7,TreasureMazeID={104,},TreasureMazeWeight={1,},TreasureItemTypeID=806005,},
  [705]={BaseID=705,Type=EffectSubType.EST_YuWenBaoTu2,Maze=9,TreasureMazeID={104,},TreasureMazeWeight={1,},TreasureItemTypeID=806005,},
  [706]={BaseID=706,Type=EffectSubType.EST_YuWenBaoTu2,Maze=10,TreasureMazeID={104,},TreasureMazeWeight={1,},TreasureItemTypeID=806005,},
  [707]={BaseID=707,Type=EffectSubType.EST_YuWenBaoTu2,Maze=11,TreasureMazeID={104,},TreasureMazeWeight={1,},TreasureItemTypeID=806005,},
  [708]={BaseID=708,Type=EffectSubType.EST_YuWenBaoTu2,Maze=15,TreasureMazeID={104,},TreasureMazeWeight={1,},TreasureItemTypeID=806005,},
  [709]={BaseID=709,Type=EffectSubType.EST_YuWenBaoTu2,Maze=17,TreasureMazeID={104,},TreasureMazeWeight={1,},TreasureItemTypeID=806005,},
  [710]={BaseID=710,Type=EffectSubType.EST_YuWenBaoTu2,Maze=18,TreasureMazeID={104,},TreasureMazeWeight={1,},TreasureItemTypeID=806005,},
  [711]={BaseID=711,Type=EffectSubType.EST_YuWenBaoTu2,Maze=19,TreasureMazeID={104,},TreasureMazeWeight={1,},TreasureItemTypeID=806005,},
  [712]={BaseID=712,Type=EffectSubType.EST_YuWenBaoTu2,Maze=30,TreasureMazeID={104,},TreasureMazeWeight={1,},TreasureItemTypeID=806005,},
  [713]={BaseID=713,Type=EffectSubType.EST_YuWenBaoTu2,Maze=31,TreasureMazeID={104,},TreasureMazeWeight={1,},TreasureItemTypeID=806005,},
  [714]={BaseID=714,Type=EffectSubType.EST_YuWenBaoTu2,Maze=33,TreasureMazeID={104,},TreasureMazeWeight={1,},TreasureItemTypeID=806005,},
  [801]={BaseID=801,Type=EffectSubType.EST_YuWenBaoTu3,TreasureMazeID={105,},TreasureMazeWeight={1,},TreasureItemTypeID=807005,},
  [802]={BaseID=802,Type=EffectSubType.EST_YuWenBaoTu3,Maze=34,TreasureMazeID={105,},TreasureMazeWeight={1,},TreasureItemTypeID=807005,},
  [803]={BaseID=803,Type=EffectSubType.EST_YuWenBaoTu3,Maze=37,TreasureMazeID={105,},TreasureMazeWeight={1,},TreasureItemTypeID=807005,},
  [804]={BaseID=804,Type=EffectSubType.EST_YuWenBaoTu3,Maze=38,TreasureMazeID={105,},TreasureMazeWeight={1,},TreasureItemTypeID=807005,},
  [805]={BaseID=805,Type=EffectSubType.EST_YuWenBaoTu3,Maze=40,TreasureMazeID={105,},TreasureMazeWeight={1,},TreasureItemTypeID=807005,},
  [901]={BaseID=901,Type=EffectSubType.EST_WaTieBaoTu,TreasureMazeID={100,},TreasureMazeWeight={1,},TreasureItemTypeID=805008,},
  [902]={BaseID=902,Type=EffectSubType.EST_WaTieBaoTu,Maze=34,TreasureMazeID={100,},TreasureMazeWeight={1,},TreasureItemTypeID=805008,},
  [903]={BaseID=903,Type=EffectSubType.EST_WaTieBaoTu,Maze=37,TreasureMazeID={100,},TreasureMazeWeight={1,},TreasureItemTypeID=805008,},
  [904]={BaseID=904,Type=EffectSubType.EST_WaTieBaoTu,Maze=38,TreasureMazeID={100,},TreasureMazeWeight={1,},TreasureItemTypeID=805008,},
  [905]={BaseID=905,Type=EffectSubType.EST_WaTieBaoTu,Maze=40,TreasureMazeID={100,},TreasureMazeWeight={1,},TreasureItemTypeID=805008,},
}
for k,v in pairs(TreasureMaze) do
    setmetatable(v, {['__index'] = TreasureMazeDefault})
end

-- export table: TreasureMaze
return TreasureMaze
